/* TaskManager.c generated by valac 0.50.3, the Vala compiler
 * generated from TaskManager.vala, do not modify */

/*
* Copyright (C) 2017-2021 Lains
*
* This program is free software; you can redistribute it &&/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 3 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*/

#include <glib-object.h>
#include <handy.h>
#include <json-glib/json-glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>
#include <glib/gstdio.h>
#include <gtk/gtk.h>
#include <webkit2/webkit2.h>
#include <gobject/gvaluecollector.h>

#define NOTEJOT_TYPE_TASK_MANAGER (notejot_task_manager_get_type ())
#define NOTEJOT_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManager))
#define NOTEJOT_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManagerClass))
#define NOTEJOT_IS_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_TYPE_TASK_MANAGER))
#define NOTEJOT_IS_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_TYPE_TASK_MANAGER))
#define NOTEJOT_TASK_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManagerClass))

typedef struct _NotejotTaskManager NotejotTaskManager;
typedef struct _NotejotTaskManagerClass NotejotTaskManagerClass;
typedef struct _NotejotTaskManagerPrivate NotejotTaskManagerPrivate;

#define NOTEJOT_TYPE_MAIN_WINDOW (notejot_main_window_get_type ())
#define NOTEJOT_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindow))
#define NOTEJOT_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindowClass))
#define NOTEJOT_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_TYPE_MAIN_WINDOW))
#define NOTEJOT_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_TYPE_MAIN_WINDOW))
#define NOTEJOT_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindowClass))

typedef struct _NotejotMainWindow NotejotMainWindow;
typedef struct _NotejotMainWindowClass NotejotMainWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _notejot_task_manager_unref0(var) ((var == NULL) ? NULL : (var = (notejot_task_manager_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _NotejotTaskManagerSaveNotesData NotejotTaskManagerSaveNotesData;
typedef struct _NotejotMainWindowPrivate NotejotMainWindowPrivate;

#define NOTEJOT_WIDGETS_TYPE_DIALOG (notejot_widgets_dialog_get_type ())
#define NOTEJOT_WIDGETS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialog))
#define NOTEJOT_WIDGETS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialogClass))
#define NOTEJOT_WIDGETS_IS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG))
#define NOTEJOT_WIDGETS_IS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_DIALOG))
#define NOTEJOT_WIDGETS_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialogClass))

typedef struct _NotejotWidgetsDialog NotejotWidgetsDialog;
typedef struct _NotejotWidgetsDialogClass NotejotWidgetsDialogClass;

#define NOTEJOT_WIDGETS_TYPE_SETTING_MENU (notejot_widgets_setting_menu_get_type ())
#define NOTEJOT_WIDGETS_SETTING_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenu))
#define NOTEJOT_WIDGETS_SETTING_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenuClass))
#define NOTEJOT_WIDGETS_IS_SETTING_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU))
#define NOTEJOT_WIDGETS_IS_SETTING_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_SETTING_MENU))
#define NOTEJOT_WIDGETS_SETTING_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenuClass))

typedef struct _NotejotWidgetsSettingMenu NotejotWidgetsSettingMenu;
typedef struct _NotejotWidgetsSettingMenuClass NotejotWidgetsSettingMenuClass;

#define NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON (notejot_widgets_header_bar_button_get_type ())
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButton))
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButtonClass))
#define NOTEJOT_WIDGETS_IS_HEADER_BAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON))
#define NOTEJOT_WIDGETS_IS_HEADER_BAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON))
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButtonClass))

typedef struct _NotejotWidgetsHeaderBarButton NotejotWidgetsHeaderBarButton;
typedef struct _NotejotWidgetsHeaderBarButtonClass NotejotWidgetsHeaderBarButtonClass;

#define NOTEJOT_VIEWS_TYPE_LIST_VIEW (notejot_views_list_view_get_type ())
#define NOTEJOT_VIEWS_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListView))
#define NOTEJOT_VIEWS_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListViewClass))
#define NOTEJOT_VIEWS_IS_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW))
#define NOTEJOT_VIEWS_IS_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_VIEWS_TYPE_LIST_VIEW))
#define NOTEJOT_VIEWS_LIST_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListViewClass))

typedef struct _NotejotViewsListView NotejotViewsListView;
typedef struct _NotejotViewsListViewClass NotejotViewsListViewClass;

#define NOTEJOT_VIEWS_TYPE_TRASH_VIEW (notejot_views_trash_view_get_type ())
#define NOTEJOT_VIEWS_TRASH_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashView))
#define NOTEJOT_VIEWS_TRASH_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashViewClass))
#define NOTEJOT_VIEWS_IS_TRASH_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW))
#define NOTEJOT_VIEWS_IS_TRASH_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_VIEWS_TYPE_TRASH_VIEW))
#define NOTEJOT_VIEWS_TRASH_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashViewClass))

typedef struct _NotejotViewsTrashView NotejotViewsTrashView;
typedef struct _NotejotViewsTrashViewClass NotejotViewsTrashViewClass;
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))

#define NOTEJOT_WIDGETS_TYPE_NOTE (notejot_widgets_note_get_type ())
#define NOTEJOT_WIDGETS_NOTE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote))
#define NOTEJOT_WIDGETS_NOTE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNoteClass))
#define NOTEJOT_WIDGETS_IS_NOTE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_NOTE))
#define NOTEJOT_WIDGETS_IS_NOTE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_NOTE))
#define NOTEJOT_WIDGETS_NOTE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNoteClass))

typedef struct _NotejotWidgetsNote NotejotWidgetsNote;
typedef struct _NotejotWidgetsNoteClass NotejotWidgetsNoteClass;
typedef struct _NotejotWidgetsNotePrivate NotejotWidgetsNotePrivate;

#define NOTEJOT_WIDGETS_TYPE_TEXT_FIELD (notejot_widgets_text_field_get_type ())
#define NOTEJOT_WIDGETS_TEXT_FIELD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD, NotejotWidgetsTextField))
#define NOTEJOT_WIDGETS_TEXT_FIELD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD, NotejotWidgetsTextFieldClass))
#define NOTEJOT_WIDGETS_IS_TEXT_FIELD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD))
#define NOTEJOT_WIDGETS_IS_TEXT_FIELD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD))
#define NOTEJOT_WIDGETS_TEXT_FIELD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD, NotejotWidgetsTextFieldClass))

typedef struct _NotejotWidgetsTextField NotejotWidgetsTextField;
typedef struct _NotejotWidgetsTextFieldClass NotejotWidgetsTextFieldClass;

#define NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL (notejot_widgets_editable_label_get_type ())
#define NOTEJOT_WIDGETS_EDITABLE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabel))
#define NOTEJOT_WIDGETS_EDITABLE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabelClass))
#define NOTEJOT_WIDGETS_IS_EDITABLE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL))
#define NOTEJOT_WIDGETS_IS_EDITABLE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL))
#define NOTEJOT_WIDGETS_EDITABLE_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabelClass))

typedef struct _NotejotWidgetsEditableLabel NotejotWidgetsEditableLabel;
typedef struct _NotejotWidgetsEditableLabelClass NotejotWidgetsEditableLabelClass;
typedef struct _NotejotTaskManagerSaveColumnData NotejotTaskManagerSaveColumnData;
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))
typedef struct _NotejotTaskManagerLoadFromFileData NotejotTaskManagerLoadFromFileData;
typedef struct _NotejotParamSpecTaskManager NotejotParamSpecTaskManager;

struct _NotejotTaskManager {
	GTypeInstance parent_instance;
	volatile int ref_count;
	NotejotTaskManagerPrivate * priv;
	NotejotMainWindow* win;
	JsonBuilder* builder;
};

struct _NotejotTaskManagerClass {
	GTypeClass parent_class;
	void (*finalize) (NotejotTaskManager *self);
};

struct _NotejotTaskManagerPrivate {
	gchar* app_dir;
	gchar* file_name;
};

struct _NotejotTaskManagerSaveNotesData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	NotejotTaskManager* self;
	gchar* json_string;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GFile* dir;
	const gchar* _tmp6_;
	GFile* _tmp7_;
	GFile* file;
	const gchar* _tmp8_;
	GFile* _tmp9_;
	GFile* _tmp10_;
	GFile* _tmp11_;
	GFile* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	const gchar* _tmp15_;
	GError* e;
	GError* _tmp16_;
	const gchar* _tmp17_;
	GError* _inner_error0_;
};

struct _NotejotMainWindow {
	HdyApplicationWindow parent_instance;
	NotejotMainWindowPrivate * priv;
	GtkButton* new_button;
	GtkButton* back_button;
	GtkButton* welcome_new_button;
	GtkMenuButton* menu_button;
	GtkBox* grid;
	GtkBox* sgrid;
	GtkBox* welcome_view;
	GtkBox* empty_state;
	HdyLeaflet* leaflet;
	GtkStack* main_stack;
	GtkStack* sidebar_stack;
	GtkStack* titlebar_stack;
	HdyHeaderBar* titlebar;
	HdyHeaderBar* stitlebar;
	HdyHeaderBar* welcome_titlebar;
	HdyHeaderGroup* titlegroup;
	GtkScrolledWindow* trash_scroller;
	GtkScrolledWindow* list_scroller;
	NotejotWidgetsDialog* dialog;
	NotejotWidgetsSettingMenu* settingmenu;
	NotejotWidgetsHeaderBarButton* sidebar_title_button;
	NotejotViewsListView* listview;
	NotejotViewsTrashView* trashview;
	NotejotTaskManager* tm;
	gboolean pinned;
};

struct _NotejotMainWindowClass {
	HdyApplicationWindowClass parent_class;
};

struct _NotejotWidgetsNote {
	HdyActionRow parent_instance;
	NotejotWidgetsNotePrivate * priv;
	NotejotWidgetsTextField* textfield;
	NotejotWidgetsEditableLabel* titlelabel;
	gint uid;
	gchar* title;
	gchar* subtitle;
	gchar* text;
	gchar* color;
};

struct _NotejotWidgetsNoteClass {
	HdyActionRowClass parent_class;
};

struct _NotejotTaskManagerSaveColumnData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	NotejotTaskManager* self;
	JsonBuilder* builder;
	NotejotViewsListView* listview;
	GList* _tmp0_;
	GList* _tmp1_;
	gboolean _tmp2_;
	GList* _tmp3_;
	GList* item_collection;
	GList* item_it;
	NotejotWidgetsNote* _tmp4_;
	NotejotWidgetsNote* item;
	NotejotWidgetsNote* _tmp5_;
	const gchar* _tmp6_;
	NotejotWidgetsNote* _tmp7_;
	const gchar* _tmp8_;
	NotejotWidgetsNote* _tmp9_;
	const gchar* _tmp10_;
	NotejotWidgetsNote* _tmp11_;
	const gchar* _tmp12_;
};

struct _NotejotTaskManagerLoadFromFileData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	NotejotTaskManager* self;
	GFile* file;
	const gchar* _tmp0_;
	GFile* _tmp1_;
	GFile* _tmp2_;
	gchar* line;
	GFile* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	JsonParser* parser;
	JsonParser* _tmp7_;
	JsonParser* _tmp8_;
	const gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	JsonNode* root;
	JsonParser* _tmp14_;
	JsonNode* _tmp15_;
	JsonNode* _tmp16_;
	JsonArray* array;
	JsonNode* _tmp17_;
	JsonArray* _tmp18_;
	JsonArray* _tmp19_;
	JsonArray* columns;
	JsonArray* _tmp20_;
	JsonArray* _tmp21_;
	JsonArray* _tmp22_;
	JsonArray* _tmp23_;
	GList* _tmp24_;
	GList* tasks_collection;
	GList* tasks_it;
	JsonNode* tasks;
	JsonArray* task;
	JsonNode* _tmp25_;
	JsonArray* _tmp26_;
	JsonArray* _tmp27_;
	gchar* title;
	JsonArray* _tmp28_;
	const gchar* _tmp29_;
	gchar* _tmp30_;
	gchar* subtitle;
	JsonArray* _tmp31_;
	const gchar* _tmp32_;
	gchar* _tmp33_;
	gchar* text;
	JsonArray* _tmp34_;
	const gchar* _tmp35_;
	gchar* _tmp36_;
	gchar* color;
	JsonArray* _tmp37_;
	const gchar* _tmp38_;
	gchar* _tmp39_;
	NotejotMainWindow* _tmp40_;
	NotejotViewsListView* _tmp41_;
	NotejotMainWindow* _tmp42_;
	const gchar* _tmp43_;
	const gchar* _tmp44_;
	const gchar* _tmp45_;
	const gchar* _tmp46_;
	GError* e;
	GError* _tmp47_;
	const gchar* _tmp48_;
	GError* _inner_error0_;
};

struct _NotejotParamSpecTaskManager {
	GParamSpec parent_instance;
};

static gint NotejotTaskManager_private_offset;
static gpointer notejot_task_manager_parent_class = NULL;

gpointer notejot_task_manager_ref (gpointer instance);
void notejot_task_manager_unref (gpointer instance);
GParamSpec* notejot_param_spec_task_manager (const gchar* name,
                                             const gchar* nick,
                                             const gchar* blurb,
                                             GType object_type,
                                             GParamFlags flags);
void notejot_value_set_task_manager (GValue* value,
                                     gpointer v_object);
void notejot_value_take_task_manager (GValue* value,
                                      gpointer v_object);
gpointer notejot_value_get_task_manager (const GValue* value);
GType notejot_task_manager_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotTaskManager, notejot_task_manager_unref)
GType notejot_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotMainWindow, g_object_unref)
NotejotTaskManager* notejot_task_manager_new (NotejotMainWindow* win);
NotejotTaskManager* notejot_task_manager_construct (GType object_type,
                                                    NotejotMainWindow* win);
static void notejot_task_manager_save_notes_data_free (gpointer _data);
void notejot_task_manager_save_notes (NotejotTaskManager* self,
                                      GAsyncReadyCallback _callback_,
                                      gpointer _user_data_);
void notejot_task_manager_save_notes_finish (NotejotTaskManager* self,
                                             GAsyncResult* _res_);
static gboolean notejot_task_manager_save_notes_co (NotejotTaskManagerSaveNotesData* _data_);
static gchar* notejot_task_manager_prepare_json_from_notes (NotejotTaskManager* self);
GType notejot_widgets_dialog_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsDialog, g_object_unref)
GType notejot_widgets_setting_menu_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsSettingMenu, g_object_unref)
GType notejot_widgets_header_bar_button_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsHeaderBarButton, g_object_unref)
GType notejot_views_list_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotViewsListView, g_object_unref)
GType notejot_views_trash_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotViewsTrashView, g_object_unref)
static void notejot_task_manager_save_column (NotejotTaskManager* self,
                                       JsonBuilder* builder,
                                       NotejotViewsListView* listview,
                                       GAsyncReadyCallback _callback_,
                                       gpointer _user_data_);
static void notejot_task_manager_save_column_finish (NotejotTaskManager* self,
                                              GAsyncResult* _res_);
static void _vala_JsonNode_free (JsonNode* self);
static void notejot_task_manager_save_column_data_free (gpointer _data);
static gboolean notejot_task_manager_save_column_co (NotejotTaskManagerSaveColumnData* _data_);
GType notejot_widgets_note_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsNote, g_object_unref)
GList* notejot_views_list_view_get_rows (NotejotViewsListView* self);
GType notejot_widgets_text_field_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsTextField, g_object_unref)
GType notejot_widgets_editable_label_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsEditableLabel, g_object_unref)
static void notejot_task_manager_load_from_file_data_free (gpointer _data);
void notejot_task_manager_load_from_file (NotejotTaskManager* self,
                                          GAsyncReadyCallback _callback_,
                                          gpointer _user_data_);
void notejot_task_manager_load_from_file_finish (NotejotTaskManager* self,
                                                 GAsyncResult* _res_);
static gboolean notejot_task_manager_load_from_file_co (NotejotTaskManagerLoadFromFileData* _data_);
static JsonNode* _vala_JsonNode_copy (JsonNode* self);
void notejot_views_list_view_new_taskbox (NotejotViewsListView* self,
                                          NotejotMainWindow* win,
                                          const gchar* title,
                                          const gchar* contents,
                                          const gchar* text,
                                          const gchar* color,
                                          GAsyncReadyCallback _callback_,
                                          gpointer _user_data_);
void notejot_views_list_view_new_taskbox_finish (NotejotViewsListView* self,
                                                 GAsyncResult* _res_);
static void notejot_task_manager_finalize (NotejotTaskManager * obj);
static GType notejot_task_manager_get_type_once (void);

static inline gpointer
notejot_task_manager_get_instance_private (NotejotTaskManager* self)
{
	return G_STRUCT_MEMBER_P (self, NotejotTaskManager_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 28 "../src/Services/TaskManager.vala"
	return self ? g_object_ref (self) : NULL;
#line 441 "TaskManager.c"
}

NotejotTaskManager*
notejot_task_manager_construct (GType object_type,
                                NotejotMainWindow* win)
{
	NotejotTaskManager* self = NULL;
	NotejotMainWindow* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
#line 27 "../src/Services/TaskManager.vala"
	g_return_val_if_fail (win != NULL, NULL);
#line 27 "../src/Services/TaskManager.vala"
	self = (NotejotTaskManager*) g_type_create_instance (object_type);
#line 28 "../src/Services/TaskManager.vala"
	_tmp0_ = _g_object_ref0 (win);
#line 28 "../src/Services/TaskManager.vala"
	_g_object_unref0 (self->win);
#line 28 "../src/Services/TaskManager.vala"
	self->win = _tmp0_;
#line 29 "../src/Services/TaskManager.vala"
	_tmp1_ = self->priv->app_dir;
#line 29 "../src/Services/TaskManager.vala"
	_tmp2_ = g_strconcat (_tmp1_, "/saved_notes.json", NULL);
#line 29 "../src/Services/TaskManager.vala"
	_g_free0 (self->priv->file_name);
#line 29 "../src/Services/TaskManager.vala"
	self->priv->file_name = _tmp2_;
#line 27 "../src/Services/TaskManager.vala"
	return self;
#line 472 "TaskManager.c"
}

NotejotTaskManager*
notejot_task_manager_new (NotejotMainWindow* win)
{
#line 27 "../src/Services/TaskManager.vala"
	return notejot_task_manager_construct (NOTEJOT_TYPE_TASK_MANAGER, win);
#line 480 "TaskManager.c"
}

static void
notejot_task_manager_save_notes_data_free (gpointer _data)
{
	NotejotTaskManagerSaveNotesData* _data_;
	_data_ = _data;
#line 20 "../src/Services/TaskManager.vala"
	_notejot_task_manager_unref0 (_data_->self);
#line 20 "../src/Services/TaskManager.vala"
	g_slice_free (NotejotTaskManagerSaveNotesData, _data_);
#line 492 "TaskManager.c"
}

static gpointer
_notejot_task_manager_ref0 (gpointer self)
{
#line 20 "../src/Services/TaskManager.vala"
	return self ? notejot_task_manager_ref (self) : NULL;
#line 500 "TaskManager.c"
}

void
notejot_task_manager_save_notes (NotejotTaskManager* self,
                                 GAsyncReadyCallback _callback_,
                                 gpointer _user_data_)
{
	NotejotTaskManagerSaveNotesData* _data_;
	NotejotTaskManager* _tmp0_;
#line 20 "../src/Services/TaskManager.vala"
	g_return_if_fail (self != NULL);
#line 20 "../src/Services/TaskManager.vala"
	_data_ = g_slice_new0 (NotejotTaskManagerSaveNotesData);
#line 20 "../src/Services/TaskManager.vala"
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
#line 20 "../src/Services/TaskManager.vala"
	g_task_set_task_data (_data_->_async_result, _data_, notejot_task_manager_save_notes_data_free);
#line 20 "../src/Services/TaskManager.vala"
	_tmp0_ = _notejot_task_manager_ref0 (self);
#line 20 "../src/Services/TaskManager.vala"
	_data_->self = _tmp0_;
#line 20 "../src/Services/TaskManager.vala"
	notejot_task_manager_save_notes_co (_data_);
#line 524 "TaskManager.c"
}

void
notejot_task_manager_save_notes_finish (NotejotTaskManager* self,
                                        GAsyncResult* _res_)
{
	NotejotTaskManagerSaveNotesData* _data_;
#line 20 "../src/Services/TaskManager.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 534 "TaskManager.c"
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	gchar* result = NULL;
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (old != NULL, NULL);
#line 1534 "glib-2.0.vapi"
	g_return_val_if_fail (replacement != NULL, NULL);
#line 1535 "glib-2.0.vapi"
	if ((*((gchar*) self)) == '\0') {
#line 1535 "glib-2.0.vapi"
		_tmp1_ = TRUE;
#line 556 "TaskManager.c"
	} else {
#line 1535 "glib-2.0.vapi"
		_tmp1_ = (*((gchar*) old)) == '\0';
#line 560 "TaskManager.c"
	}
#line 1535 "glib-2.0.vapi"
	if (_tmp1_) {
#line 1535 "glib-2.0.vapi"
		_tmp0_ = TRUE;
#line 566 "TaskManager.c"
	} else {
#line 1535 "glib-2.0.vapi"
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
#line 570 "TaskManager.c"
	}
#line 1535 "glib-2.0.vapi"
	if (_tmp0_) {
#line 574 "TaskManager.c"
		gchar* _tmp2_;
#line 1536 "glib-2.0.vapi"
		_tmp2_ = g_strdup (self);
#line 1536 "glib-2.0.vapi"
		result = _tmp2_;
#line 1536 "glib-2.0.vapi"
		return result;
#line 582 "TaskManager.c"
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
#line 1539 "glib-2.0.vapi"
		_tmp3_ = g_regex_escape_string (old, -1);
#line 1539 "glib-2.0.vapi"
		_tmp4_ = _tmp3_;
#line 1539 "glib-2.0.vapi"
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
#line 1539 "glib-2.0.vapi"
		_tmp6_ = _tmp5_;
#line 1539 "glib-2.0.vapi"
		_g_free0 (_tmp4_);
#line 1539 "glib-2.0.vapi"
		regex = _tmp6_;
#line 1539 "glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1539 "glib-2.0.vapi"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 610 "TaskManager.c"
				goto __catch0_g_regex_error;
			}
#line 1539 "glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1539 "glib-2.0.vapi"
			g_clear_error (&_inner_error0_);
#line 1539 "glib-2.0.vapi"
			return NULL;
#line 619 "TaskManager.c"
		}
#line 1540 "glib-2.0.vapi"
		_tmp8_ = regex;
#line 1540 "glib-2.0.vapi"
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
#line 1540 "glib-2.0.vapi"
		_tmp7_ = _tmp9_;
#line 1540 "glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1540 "glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1540 "glib-2.0.vapi"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 633 "TaskManager.c"
				goto __catch0_g_regex_error;
			}
#line 1540 "glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1540 "glib-2.0.vapi"
			g_clear_error (&_inner_error0_);
#line 1540 "glib-2.0.vapi"
			return NULL;
#line 642 "TaskManager.c"
		}
#line 1540 "glib-2.0.vapi"
		_tmp10_ = _tmp7_;
#line 1540 "glib-2.0.vapi"
		_tmp7_ = NULL;
#line 1540 "glib-2.0.vapi"
		result = _tmp10_;
#line 1540 "glib-2.0.vapi"
		_g_free0 (_tmp7_);
#line 1540 "glib-2.0.vapi"
		_g_regex_unref0 (regex);
#line 1540 "glib-2.0.vapi"
		return result;
#line 656 "TaskManager.c"
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
#line 1538 "glib-2.0.vapi"
		g_clear_error (&_inner_error0_);
#line 1542 "glib-2.0.vapi"
		g_assert_not_reached ();
#line 665 "TaskManager.c"
	}
	__finally0:
#line 1538 "glib-2.0.vapi"
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1538 "glib-2.0.vapi"
	g_clear_error (&_inner_error0_);
#line 1538 "glib-2.0.vapi"
	return NULL;
#line 674 "TaskManager.c"
}

static gboolean
notejot_task_manager_save_notes_co (NotejotTaskManagerSaveNotesData* _data_)
{
#line 32 "../src/Services/TaskManager.vala"
	switch (_data_->_state_) {
#line 32 "../src/Services/TaskManager.vala"
		case 0:
#line 684 "TaskManager.c"
		goto _state_0;
		default:
#line 32 "../src/Services/TaskManager.vala"
		g_assert_not_reached ();
#line 689 "TaskManager.c"
	}
	_state_0:
	{
#line 34 "../src/Services/TaskManager.vala"
		_data_->_tmp0_ = notejot_task_manager_prepare_json_from_notes (_data_->self);
#line 34 "../src/Services/TaskManager.vala"
		_data_->_tmp1_ = _data_->_tmp0_;
#line 34 "../src/Services/TaskManager.vala"
		_data_->_tmp2_ = string_replace (_data_->_tmp1_, "\"", "\\\"");
#line 34 "../src/Services/TaskManager.vala"
		_data_->_tmp3_ = _data_->_tmp2_;
#line 34 "../src/Services/TaskManager.vala"
		_data_->_tmp4_ = string_replace (_data_->_tmp3_, "/", "\\/");
#line 34 "../src/Services/TaskManager.vala"
		_data_->_tmp5_ = _data_->_tmp4_;
#line 34 "../src/Services/TaskManager.vala"
		_g_free0 (_data_->_tmp3_);
#line 34 "../src/Services/TaskManager.vala"
		_g_free0 (_data_->_tmp1_);
#line 34 "../src/Services/TaskManager.vala"
		_data_->json_string = _data_->_tmp5_;
#line 35 "../src/Services/TaskManager.vala"
		_data_->_tmp6_ = _data_->self->priv->app_dir;
#line 35 "../src/Services/TaskManager.vala"
		_data_->_tmp7_ = g_file_new_for_path (_data_->_tmp6_);
#line 35 "../src/Services/TaskManager.vala"
		_data_->dir = _data_->_tmp7_;
#line 36 "../src/Services/TaskManager.vala"
		_data_->_tmp8_ = _data_->self->priv->file_name;
#line 36 "../src/Services/TaskManager.vala"
		_data_->_tmp9_ = g_file_new_for_path (_data_->_tmp8_);
#line 36 "../src/Services/TaskManager.vala"
		_data_->file = _data_->_tmp9_;
#line 37 "../src/Services/TaskManager.vala"
		_data_->_tmp10_ = _data_->dir;
#line 37 "../src/Services/TaskManager.vala"
		if (!g_file_query_exists (_data_->_tmp10_, NULL)) {
#line 38 "../src/Services/TaskManager.vala"
			_data_->_tmp11_ = _data_->dir;
#line 38 "../src/Services/TaskManager.vala"
			g_file_make_directory (_data_->_tmp11_, NULL, &_data_->_inner_error0_);
#line 38 "../src/Services/TaskManager.vala"
			if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 38 "../src/Services/TaskManager.vala"
				_g_object_unref0 (_data_->file);
#line 38 "../src/Services/TaskManager.vala"
				_g_object_unref0 (_data_->dir);
#line 38 "../src/Services/TaskManager.vala"
				_g_free0 (_data_->json_string);
#line 739 "TaskManager.c"
				goto __catch0_g_error;
			}
		}
#line 40 "../src/Services/TaskManager.vala"
		_data_->_tmp12_ = _data_->file;
#line 40 "../src/Services/TaskManager.vala"
		_data_->_tmp13_ = g_file_get_path (_data_->_tmp12_);
#line 40 "../src/Services/TaskManager.vala"
		_data_->_tmp14_ = _data_->_tmp13_;
#line 40 "../src/Services/TaskManager.vala"
		_data_->_tmp15_ = _data_->json_string;
#line 40 "../src/Services/TaskManager.vala"
		g_file_set_contents (_data_->_tmp14_, _data_->_tmp15_, (gssize) -1, &_data_->_inner_error0_);
#line 40 "../src/Services/TaskManager.vala"
		_g_free0 (_data_->_tmp14_);
#line 40 "../src/Services/TaskManager.vala"
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 40 "../src/Services/TaskManager.vala"
			_g_object_unref0 (_data_->file);
#line 40 "../src/Services/TaskManager.vala"
			_g_object_unref0 (_data_->dir);
#line 40 "../src/Services/TaskManager.vala"
			_g_free0 (_data_->json_string);
#line 763 "TaskManager.c"
			goto __catch0_g_error;
		}
#line 33 "../src/Services/TaskManager.vala"
		_g_object_unref0 (_data_->file);
#line 33 "../src/Services/TaskManager.vala"
		_g_object_unref0 (_data_->dir);
#line 33 "../src/Services/TaskManager.vala"
		_g_free0 (_data_->json_string);
#line 772 "TaskManager.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
#line 33 "../src/Services/TaskManager.vala"
		_data_->e = _data_->_inner_error0_;
#line 33 "../src/Services/TaskManager.vala"
		_data_->_inner_error0_ = NULL;
#line 42 "../src/Services/TaskManager.vala"
		_data_->_tmp16_ = _data_->e;
#line 42 "../src/Services/TaskManager.vala"
		_data_->_tmp17_ = _data_->_tmp16_->message;
#line 42 "../src/Services/TaskManager.vala"
		g_warning ("TaskManager.vala:42: Failed to save: %s\n", _data_->_tmp17_);
#line 33 "../src/Services/TaskManager.vala"
		_g_error_free0 (_data_->e);
#line 789 "TaskManager.c"
	}
	__finally0:
#line 33 "../src/Services/TaskManager.vala"
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 33 "../src/Services/TaskManager.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
#line 33 "../src/Services/TaskManager.vala"
		g_clear_error (&_data_->_inner_error0_);
#line 33 "../src/Services/TaskManager.vala"
		g_object_unref (_data_->_async_result);
#line 33 "../src/Services/TaskManager.vala"
		return FALSE;
#line 802 "TaskManager.c"
	}
#line 32 "../src/Services/TaskManager.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 32 "../src/Services/TaskManager.vala"
	if (_data_->_state_ != 0) {
#line 32 "../src/Services/TaskManager.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 32 "../src/Services/TaskManager.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 812 "TaskManager.c"
		}
	}
#line 32 "../src/Services/TaskManager.vala"
	g_object_unref (_data_->_async_result);
#line 32 "../src/Services/TaskManager.vala"
	return FALSE;
#line 819 "TaskManager.c"
}

static void
_vala_JsonNode_free (JsonNode* self)
{
#line 60 "../src/Services/TaskManager.vala"
	g_boxed_free (json_node_get_type (), self);
#line 827 "TaskManager.c"
}

static gchar*
notejot_task_manager_prepare_json_from_notes (NotejotTaskManager* self)
{
	JsonBuilder* _tmp0_;
	JsonBuilder* _tmp1_;
	NotejotMainWindow* _tmp2_;
	NotejotViewsListView* _tmp3_;
	JsonBuilder* _tmp7_;
	JsonGenerator* generator = NULL;
	JsonGenerator* _tmp8_;
	JsonNode* root = NULL;
	JsonBuilder* _tmp9_;
	JsonNode* _tmp10_;
	gchar* str = NULL;
	gchar* _tmp11_;
	gchar* result = NULL;
#line 47 "../src/Services/TaskManager.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 48 "../src/Services/TaskManager.vala"
	_tmp0_ = json_builder_new ();
#line 48 "../src/Services/TaskManager.vala"
	_g_object_unref0 (self->builder);
#line 48 "../src/Services/TaskManager.vala"
	self->builder = _tmp0_;
#line 50 "../src/Services/TaskManager.vala"
	_tmp1_ = self->builder;
#line 50 "../src/Services/TaskManager.vala"
	json_builder_begin_array (_tmp1_);
#line 51 "../src/Services/TaskManager.vala"
	_tmp2_ = self->win;
#line 51 "../src/Services/TaskManager.vala"
	_tmp3_ = _tmp2_->listview;
#line 51 "../src/Services/TaskManager.vala"
	if (_tmp3_ != NULL) {
#line 864 "TaskManager.c"
		JsonBuilder* _tmp4_;
		NotejotMainWindow* _tmp5_;
		NotejotViewsListView* _tmp6_;
#line 52 "../src/Services/TaskManager.vala"
		_tmp4_ = self->builder;
#line 52 "../src/Services/TaskManager.vala"
		_tmp5_ = self->win;
#line 52 "../src/Services/TaskManager.vala"
		_tmp6_ = _tmp5_->listview;
#line 52 "../src/Services/TaskManager.vala"
		notejot_task_manager_save_column (self, _tmp4_, _tmp6_, NULL, NULL);
#line 876 "TaskManager.c"
	}
#line 54 "../src/Services/TaskManager.vala"
	_tmp7_ = self->builder;
#line 54 "../src/Services/TaskManager.vala"
	json_builder_end_array (_tmp7_);
#line 56 "../src/Services/TaskManager.vala"
	_tmp8_ = json_generator_new ();
#line 56 "../src/Services/TaskManager.vala"
	generator = _tmp8_;
#line 57 "../src/Services/TaskManager.vala"
	_tmp9_ = self->builder;
#line 57 "../src/Services/TaskManager.vala"
	_tmp10_ = json_builder_get_root (_tmp9_);
#line 57 "../src/Services/TaskManager.vala"
	root = _tmp10_;
#line 58 "../src/Services/TaskManager.vala"
	json_generator_set_root (generator, root);
#line 59 "../src/Services/TaskManager.vala"
	_tmp11_ = json_generator_to_data (generator, NULL);
#line 59 "../src/Services/TaskManager.vala"
	str = _tmp11_;
#line 60 "../src/Services/TaskManager.vala"
	result = str;
#line 60 "../src/Services/TaskManager.vala"
	__vala_JsonNode_free0 (root);
#line 60 "../src/Services/TaskManager.vala"
	_g_object_unref0 (generator);
#line 60 "../src/Services/TaskManager.vala"
	return result;
#line 906 "TaskManager.c"
}

static void
notejot_task_manager_save_column_data_free (gpointer _data)
{
	NotejotTaskManagerSaveColumnData* _data_;
	_data_ = _data;
#line 20 "../src/Services/TaskManager.vala"
	_g_object_unref0 (_data_->builder);
#line 20 "../src/Services/TaskManager.vala"
	_g_object_unref0 (_data_->listview);
#line 20 "../src/Services/TaskManager.vala"
	_notejot_task_manager_unref0 (_data_->self);
#line 20 "../src/Services/TaskManager.vala"
	g_slice_free (NotejotTaskManagerSaveColumnData, _data_);
#line 922 "TaskManager.c"
}

static void
notejot_task_manager_save_column (NotejotTaskManager* self,
                                  JsonBuilder* builder,
                                  NotejotViewsListView* listview,
                                  GAsyncReadyCallback _callback_,
                                  gpointer _user_data_)
{
	NotejotTaskManagerSaveColumnData* _data_;
	NotejotTaskManager* _tmp0_;
	JsonBuilder* _tmp1_;
	NotejotViewsListView* _tmp2_;
#line 20 "../src/Services/TaskManager.vala"
	g_return_if_fail (self != NULL);
#line 20 "../src/Services/TaskManager.vala"
	g_return_if_fail (builder != NULL);
#line 20 "../src/Services/TaskManager.vala"
	g_return_if_fail (listview != NULL);
#line 20 "../src/Services/TaskManager.vala"
	_data_ = g_slice_new0 (NotejotTaskManagerSaveColumnData);
#line 20 "../src/Services/TaskManager.vala"
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
#line 20 "../src/Services/TaskManager.vala"
	g_task_set_task_data (_data_->_async_result, _data_, notejot_task_manager_save_column_data_free);
#line 20 "../src/Services/TaskManager.vala"
	_tmp0_ = _notejot_task_manager_ref0 (self);
#line 20 "../src/Services/TaskManager.vala"
	_data_->self = _tmp0_;
#line 20 "../src/Services/TaskManager.vala"
	_tmp1_ = _g_object_ref0 (builder);
#line 20 "../src/Services/TaskManager.vala"
	_g_object_unref0 (_data_->builder);
#line 20 "../src/Services/TaskManager.vala"
	_data_->builder = _tmp1_;
#line 20 "../src/Services/TaskManager.vala"
	_tmp2_ = _g_object_ref0 (listview);
#line 20 "../src/Services/TaskManager.vala"
	_g_object_unref0 (_data_->listview);
#line 20 "../src/Services/TaskManager.vala"
	_data_->listview = _tmp2_;
#line 20 "../src/Services/TaskManager.vala"
	notejot_task_manager_save_column_co (_data_);
#line 966 "TaskManager.c"
}

static void
notejot_task_manager_save_column_finish (NotejotTaskManager* self,
                                         GAsyncResult* _res_)
{
	NotejotTaskManagerSaveColumnData* _data_;
#line 20 "../src/Services/TaskManager.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 976 "TaskManager.c"
}

static gboolean
notejot_task_manager_save_column_co (NotejotTaskManagerSaveColumnData* _data_)
{
#line 63 "../src/Services/TaskManager.vala"
	switch (_data_->_state_) {
#line 63 "../src/Services/TaskManager.vala"
		case 0:
#line 986 "TaskManager.c"
		goto _state_0;
		default:
#line 63 "../src/Services/TaskManager.vala"
		g_assert_not_reached ();
#line 991 "TaskManager.c"
	}
	_state_0:
#line 65 "../src/Services/TaskManager.vala"
	json_builder_begin_array (_data_->builder);
#line 66 "../src/Services/TaskManager.vala"
	_data_->_tmp0_ = gtk_container_get_children ((GtkContainer*) _data_->listview);
#line 66 "../src/Services/TaskManager.vala"
	_data_->_tmp1_ = _data_->_tmp0_;
#line 66 "../src/Services/TaskManager.vala"
	_data_->_tmp2_ = _data_->_tmp1_ != NULL;
#line 66 "../src/Services/TaskManager.vala"
	(_data_->_tmp1_ == NULL) ? NULL : (_data_->_tmp1_ = (g_list_free (_data_->_tmp1_), NULL));
#line 66 "../src/Services/TaskManager.vala"
	if (_data_->_tmp2_) {
#line 67 "../src/Services/TaskManager.vala"
		_data_->_tmp3_ = notejot_views_list_view_get_rows (_data_->listview);
#line 1008 "TaskManager.c"
		{
#line 67 "../src/Services/TaskManager.vala"
			_data_->item_collection = _data_->_tmp3_;
#line 67 "../src/Services/TaskManager.vala"
			for (_data_->item_it = _data_->item_collection; _data_->item_it != NULL; _data_->item_it = _data_->item_it->next) {
#line 67 "../src/Services/TaskManager.vala"
				_data_->_tmp4_ = _g_object_ref0 ((NotejotWidgetsNote*) _data_->item_it->data);
#line 67 "../src/Services/TaskManager.vala"
				_data_->item = _data_->_tmp4_;
#line 1018 "TaskManager.c"
				{
#line 68 "../src/Services/TaskManager.vala"
					json_builder_begin_array (_data_->builder);
#line 69 "../src/Services/TaskManager.vala"
					_data_->_tmp5_ = _data_->item;
#line 69 "../src/Services/TaskManager.vala"
					_data_->_tmp6_ = _data_->_tmp5_->title;
#line 69 "../src/Services/TaskManager.vala"
					json_builder_add_string_value (_data_->builder, _data_->_tmp6_);
#line 70 "../src/Services/TaskManager.vala"
					_data_->_tmp7_ = _data_->item;
#line 70 "../src/Services/TaskManager.vala"
					_data_->_tmp8_ = _data_->_tmp7_->subtitle;
#line 70 "../src/Services/TaskManager.vala"
					json_builder_add_string_value (_data_->builder, _data_->_tmp8_);
#line 71 "../src/Services/TaskManager.vala"
					_data_->_tmp9_ = _data_->item;
#line 71 "../src/Services/TaskManager.vala"
					_data_->_tmp10_ = _data_->_tmp9_->text;
#line 71 "../src/Services/TaskManager.vala"
					json_builder_add_string_value (_data_->builder, _data_->_tmp10_);
#line 72 "../src/Services/TaskManager.vala"
					_data_->_tmp11_ = _data_->item;
#line 72 "../src/Services/TaskManager.vala"
					_data_->_tmp12_ = _data_->_tmp11_->color;
#line 72 "../src/Services/TaskManager.vala"
					json_builder_add_string_value (_data_->builder, _data_->_tmp12_);
#line 73 "../src/Services/TaskManager.vala"
					json_builder_end_array (_data_->builder);
#line 67 "../src/Services/TaskManager.vala"
					_g_object_unref0 (_data_->item);
#line 1050 "TaskManager.c"
				}
			}
#line 67 "../src/Services/TaskManager.vala"
			(_data_->item_collection == NULL) ? NULL : (_data_->item_collection = (g_list_free (_data_->item_collection), NULL));
#line 1055 "TaskManager.c"
		}
	}
#line 76 "../src/Services/TaskManager.vala"
	json_builder_end_array (_data_->builder);
#line 63 "../src/Services/TaskManager.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 63 "../src/Services/TaskManager.vala"
	if (_data_->_state_ != 0) {
#line 63 "../src/Services/TaskManager.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 63 "../src/Services/TaskManager.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 1068 "TaskManager.c"
		}
	}
#line 63 "../src/Services/TaskManager.vala"
	g_object_unref (_data_->_async_result);
#line 63 "../src/Services/TaskManager.vala"
	return FALSE;
#line 1075 "TaskManager.c"
}

static void
notejot_task_manager_load_from_file_data_free (gpointer _data)
{
	NotejotTaskManagerLoadFromFileData* _data_;
	_data_ = _data;
#line 20 "../src/Services/TaskManager.vala"
	_notejot_task_manager_unref0 (_data_->self);
#line 20 "../src/Services/TaskManager.vala"
	g_slice_free (NotejotTaskManagerLoadFromFileData, _data_);
#line 1087 "TaskManager.c"
}

void
notejot_task_manager_load_from_file (NotejotTaskManager* self,
                                     GAsyncReadyCallback _callback_,
                                     gpointer _user_data_)
{
	NotejotTaskManagerLoadFromFileData* _data_;
	NotejotTaskManager* _tmp0_;
#line 20 "../src/Services/TaskManager.vala"
	g_return_if_fail (self != NULL);
#line 20 "../src/Services/TaskManager.vala"
	_data_ = g_slice_new0 (NotejotTaskManagerLoadFromFileData);
#line 20 "../src/Services/TaskManager.vala"
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
#line 20 "../src/Services/TaskManager.vala"
	g_task_set_task_data (_data_->_async_result, _data_, notejot_task_manager_load_from_file_data_free);
#line 20 "../src/Services/TaskManager.vala"
	_tmp0_ = _notejot_task_manager_ref0 (self);
#line 20 "../src/Services/TaskManager.vala"
	_data_->self = _tmp0_;
#line 20 "../src/Services/TaskManager.vala"
	notejot_task_manager_load_from_file_co (_data_);
#line 1111 "TaskManager.c"
}

void
notejot_task_manager_load_from_file_finish (NotejotTaskManager* self,
                                            GAsyncResult* _res_)
{
	NotejotTaskManagerLoadFromFileData* _data_;
#line 20 "../src/Services/TaskManager.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 1121 "TaskManager.c"
}

static JsonNode*
_vala_JsonNode_copy (JsonNode* self)
{
#line 88 "../src/Services/TaskManager.vala"
	return g_boxed_copy (json_node_get_type (), self);
#line 1129 "TaskManager.c"
}

static gpointer
__vala_JsonNode_copy0 (gpointer self)
{
#line 88 "../src/Services/TaskManager.vala"
	return self ? _vala_JsonNode_copy (self) : NULL;
#line 1137 "TaskManager.c"
}

static gpointer
_json_array_ref0 (gpointer self)
{
#line 89 "../src/Services/TaskManager.vala"
	return self ? json_array_ref (self) : NULL;
#line 1145 "TaskManager.c"
}

static gboolean
notejot_task_manager_load_from_file_co (NotejotTaskManagerLoadFromFileData* _data_)
{
#line 79 "../src/Services/TaskManager.vala"
	switch (_data_->_state_) {
#line 79 "../src/Services/TaskManager.vala"
		case 0:
#line 1155 "TaskManager.c"
		goto _state_0;
		default:
#line 79 "../src/Services/TaskManager.vala"
		g_assert_not_reached ();
#line 1160 "TaskManager.c"
	}
	_state_0:
	{
#line 81 "../src/Services/TaskManager.vala"
		_data_->_tmp0_ = _data_->self->priv->file_name;
#line 81 "../src/Services/TaskManager.vala"
		_data_->_tmp1_ = g_file_new_for_path (_data_->_tmp0_);
#line 81 "../src/Services/TaskManager.vala"
		_data_->file = _data_->_tmp1_;
#line 83 "../src/Services/TaskManager.vala"
		_data_->_tmp2_ = _data_->file;
#line 83 "../src/Services/TaskManager.vala"
		if (g_file_query_exists (_data_->_tmp2_, NULL)) {
#line 85 "../src/Services/TaskManager.vala"
			_data_->_tmp3_ = _data_->file;
#line 85 "../src/Services/TaskManager.vala"
			_data_->_tmp4_ = g_file_get_path (_data_->_tmp3_);
#line 85 "../src/Services/TaskManager.vala"
			_data_->_tmp5_ = _data_->_tmp4_;
#line 85 "../src/Services/TaskManager.vala"
			_data_->_tmp6_ = NULL;
#line 85 "../src/Services/TaskManager.vala"
			g_file_get_contents (_data_->_tmp5_, &_data_->_tmp6_, NULL, &_data_->_inner_error0_);
#line 85 "../src/Services/TaskManager.vala"
			_g_free0 (_data_->line);
#line 85 "../src/Services/TaskManager.vala"
			_data_->line = _data_->_tmp6_;
#line 85 "../src/Services/TaskManager.vala"
			_g_free0 (_data_->_tmp5_);
#line 85 "../src/Services/TaskManager.vala"
			if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 85 "../src/Services/TaskManager.vala"
				_g_free0 (_data_->line);
#line 85 "../src/Services/TaskManager.vala"
				_g_object_unref0 (_data_->file);
#line 1196 "TaskManager.c"
				goto __catch0_g_error;
			}
#line 86 "../src/Services/TaskManager.vala"
			_data_->_tmp7_ = json_parser_new ();
#line 86 "../src/Services/TaskManager.vala"
			_data_->parser = _data_->_tmp7_;
#line 87 "../src/Services/TaskManager.vala"
			_data_->_tmp8_ = _data_->parser;
#line 87 "../src/Services/TaskManager.vala"
			_data_->_tmp9_ = _data_->line;
#line 87 "../src/Services/TaskManager.vala"
			_data_->_tmp10_ = string_replace (_data_->_tmp9_, "\\/", "/");
#line 87 "../src/Services/TaskManager.vala"
			_data_->_tmp11_ = _data_->_tmp10_;
#line 87 "../src/Services/TaskManager.vala"
			_data_->_tmp12_ = string_replace (_data_->_tmp11_, "\\\"", "\"");
#line 87 "../src/Services/TaskManager.vala"
			_data_->_tmp13_ = _data_->_tmp12_;
#line 87 "../src/Services/TaskManager.vala"
			json_parser_load_from_data (_data_->_tmp8_, _data_->_tmp13_, (gssize) -1, &_data_->_inner_error0_);
#line 87 "../src/Services/TaskManager.vala"
			_g_free0 (_data_->_tmp13_);
#line 87 "../src/Services/TaskManager.vala"
			_g_free0 (_data_->_tmp11_);
#line 87 "../src/Services/TaskManager.vala"
			if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 87 "../src/Services/TaskManager.vala"
				_g_object_unref0 (_data_->parser);
#line 87 "../src/Services/TaskManager.vala"
				_g_free0 (_data_->line);
#line 87 "../src/Services/TaskManager.vala"
				_g_object_unref0 (_data_->file);
#line 1229 "TaskManager.c"
				goto __catch0_g_error;
			}
#line 88 "../src/Services/TaskManager.vala"
			_data_->_tmp14_ = _data_->parser;
#line 88 "../src/Services/TaskManager.vala"
			_data_->_tmp15_ = json_parser_get_root (_data_->_tmp14_);
#line 88 "../src/Services/TaskManager.vala"
			_data_->_tmp16_ = __vala_JsonNode_copy0 (_data_->_tmp15_);
#line 88 "../src/Services/TaskManager.vala"
			_data_->root = _data_->_tmp16_;
#line 89 "../src/Services/TaskManager.vala"
			_data_->_tmp17_ = _data_->root;
#line 89 "../src/Services/TaskManager.vala"
			_data_->_tmp18_ = json_node_get_array (_data_->_tmp17_);
#line 89 "../src/Services/TaskManager.vala"
			_data_->_tmp19_ = _json_array_ref0 (_data_->_tmp18_);
#line 89 "../src/Services/TaskManager.vala"
			_data_->array = _data_->_tmp19_;
#line 90 "../src/Services/TaskManager.vala"
			_data_->_tmp20_ = _data_->array;
#line 90 "../src/Services/TaskManager.vala"
			_data_->_tmp21_ = json_array_get_array_element (_data_->_tmp20_, (guint) 0);
#line 90 "../src/Services/TaskManager.vala"
			_data_->_tmp22_ = _json_array_ref0 (_data_->_tmp21_);
#line 90 "../src/Services/TaskManager.vala"
			_data_->columns = _data_->_tmp22_;
#line 91 "../src/Services/TaskManager.vala"
			_data_->_tmp23_ = _data_->columns;
#line 91 "../src/Services/TaskManager.vala"
			_data_->_tmp24_ = json_array_get_elements (_data_->_tmp23_);
#line 1260 "TaskManager.c"
			{
#line 91 "../src/Services/TaskManager.vala"
				_data_->tasks_collection = _data_->_tmp24_;
#line 91 "../src/Services/TaskManager.vala"
				for (_data_->tasks_it = _data_->tasks_collection; _data_->tasks_it != NULL; _data_->tasks_it = _data_->tasks_it->next) {
#line 91 "../src/Services/TaskManager.vala"
					_data_->tasks = (JsonNode*) _data_->tasks_it->data;
#line 1268 "TaskManager.c"
					{
#line 92 "../src/Services/TaskManager.vala"
						_data_->_tmp25_ = _data_->tasks;
#line 92 "../src/Services/TaskManager.vala"
						_data_->_tmp26_ = json_node_get_array (_data_->_tmp25_);
#line 92 "../src/Services/TaskManager.vala"
						_data_->_tmp27_ = _json_array_ref0 (_data_->_tmp26_);
#line 92 "../src/Services/TaskManager.vala"
						_data_->task = _data_->_tmp27_;
#line 93 "../src/Services/TaskManager.vala"
						_data_->_tmp28_ = _data_->task;
#line 93 "../src/Services/TaskManager.vala"
						_data_->_tmp29_ = json_array_get_string_element (_data_->_tmp28_, (guint) 0);
#line 93 "../src/Services/TaskManager.vala"
						_data_->_tmp30_ = g_strdup (_data_->_tmp29_);
#line 93 "../src/Services/TaskManager.vala"
						_data_->title = _data_->_tmp30_;
#line 94 "../src/Services/TaskManager.vala"
						_data_->_tmp31_ = _data_->task;
#line 94 "../src/Services/TaskManager.vala"
						_data_->_tmp32_ = json_array_get_string_element (_data_->_tmp31_, (guint) 1);
#line 94 "../src/Services/TaskManager.vala"
						_data_->_tmp33_ = g_strdup (_data_->_tmp32_);
#line 94 "../src/Services/TaskManager.vala"
						_data_->subtitle = _data_->_tmp33_;
#line 95 "../src/Services/TaskManager.vala"
						_data_->_tmp34_ = _data_->task;
#line 95 "../src/Services/TaskManager.vala"
						_data_->_tmp35_ = json_array_get_string_element (_data_->_tmp34_, (guint) 2);
#line 95 "../src/Services/TaskManager.vala"
						_data_->_tmp36_ = g_strdup (_data_->_tmp35_);
#line 95 "../src/Services/TaskManager.vala"
						_data_->text = _data_->_tmp36_;
#line 96 "../src/Services/TaskManager.vala"
						_data_->_tmp37_ = _data_->task;
#line 96 "../src/Services/TaskManager.vala"
						_data_->_tmp38_ = json_array_get_string_element (_data_->_tmp37_, (guint) 3);
#line 96 "../src/Services/TaskManager.vala"
						_data_->_tmp39_ = g_strdup (_data_->_tmp38_);
#line 96 "../src/Services/TaskManager.vala"
						_data_->color = _data_->_tmp39_;
#line 98 "../src/Services/TaskManager.vala"
						_data_->_tmp40_ = _data_->self->win;
#line 98 "../src/Services/TaskManager.vala"
						_data_->_tmp41_ = _data_->_tmp40_->listview;
#line 98 "../src/Services/TaskManager.vala"
						_data_->_tmp42_ = _data_->self->win;
#line 98 "../src/Services/TaskManager.vala"
						_data_->_tmp43_ = _data_->title;
#line 98 "../src/Services/TaskManager.vala"
						_data_->_tmp44_ = _data_->subtitle;
#line 98 "../src/Services/TaskManager.vala"
						_data_->_tmp45_ = _data_->text;
#line 98 "../src/Services/TaskManager.vala"
						_data_->_tmp46_ = _data_->color;
#line 98 "../src/Services/TaskManager.vala"
						notejot_views_list_view_new_taskbox (_data_->_tmp41_, _data_->_tmp42_, _data_->_tmp43_, _data_->_tmp44_, _data_->_tmp45_, _data_->_tmp46_, NULL, NULL);
#line 91 "../src/Services/TaskManager.vala"
						_g_free0 (_data_->color);
#line 91 "../src/Services/TaskManager.vala"
						_g_free0 (_data_->text);
#line 91 "../src/Services/TaskManager.vala"
						_g_free0 (_data_->subtitle);
#line 91 "../src/Services/TaskManager.vala"
						_g_free0 (_data_->title);
#line 91 "../src/Services/TaskManager.vala"
						_json_array_unref0 (_data_->task);
#line 1336 "TaskManager.c"
					}
				}
#line 91 "../src/Services/TaskManager.vala"
				(_data_->tasks_collection == NULL) ? NULL : (_data_->tasks_collection = (g_list_free (_data_->tasks_collection), NULL));
#line 1341 "TaskManager.c"
			}
#line 83 "../src/Services/TaskManager.vala"
			_json_array_unref0 (_data_->columns);
#line 83 "../src/Services/TaskManager.vala"
			_json_array_unref0 (_data_->array);
#line 83 "../src/Services/TaskManager.vala"
			__vala_JsonNode_free0 (_data_->root);
#line 83 "../src/Services/TaskManager.vala"
			_g_object_unref0 (_data_->parser);
#line 83 "../src/Services/TaskManager.vala"
			_g_free0 (_data_->line);
#line 1353 "TaskManager.c"
		}
#line 80 "../src/Services/TaskManager.vala"
		_g_object_unref0 (_data_->file);
#line 1357 "TaskManager.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
#line 80 "../src/Services/TaskManager.vala"
		_data_->e = _data_->_inner_error0_;
#line 80 "../src/Services/TaskManager.vala"
		_data_->_inner_error0_ = NULL;
#line 102 "../src/Services/TaskManager.vala"
		_data_->_tmp47_ = _data_->e;
#line 102 "../src/Services/TaskManager.vala"
		_data_->_tmp48_ = _data_->_tmp47_->message;
#line 102 "../src/Services/TaskManager.vala"
		g_warning ("TaskManager.vala:102: Failed to load file: %s\n", _data_->_tmp48_);
#line 80 "../src/Services/TaskManager.vala"
		_g_error_free0 (_data_->e);
#line 1374 "TaskManager.c"
	}
	__finally0:
#line 80 "../src/Services/TaskManager.vala"
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 80 "../src/Services/TaskManager.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
#line 80 "../src/Services/TaskManager.vala"
		g_clear_error (&_data_->_inner_error0_);
#line 80 "../src/Services/TaskManager.vala"
		g_object_unref (_data_->_async_result);
#line 80 "../src/Services/TaskManager.vala"
		return FALSE;
#line 1387 "TaskManager.c"
	}
#line 79 "../src/Services/TaskManager.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 79 "../src/Services/TaskManager.vala"
	if (_data_->_state_ != 0) {
#line 79 "../src/Services/TaskManager.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 79 "../src/Services/TaskManager.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 1397 "TaskManager.c"
		}
	}
#line 79 "../src/Services/TaskManager.vala"
	g_object_unref (_data_->_async_result);
#line 79 "../src/Services/TaskManager.vala"
	return FALSE;
#line 1404 "TaskManager.c"
}

static void
notejot_value_task_manager_init (GValue* value)
{
#line 20 "../src/Services/TaskManager.vala"
	value->data[0].v_pointer = NULL;
#line 1412 "TaskManager.c"
}

static void
notejot_value_task_manager_free_value (GValue* value)
{
#line 20 "../src/Services/TaskManager.vala"
	if (value->data[0].v_pointer) {
#line 20 "../src/Services/TaskManager.vala"
		notejot_task_manager_unref (value->data[0].v_pointer);
#line 1422 "TaskManager.c"
	}
}

static void
notejot_value_task_manager_copy_value (const GValue* src_value,
                                       GValue* dest_value)
{
#line 20 "../src/Services/TaskManager.vala"
	if (src_value->data[0].v_pointer) {
#line 20 "../src/Services/TaskManager.vala"
		dest_value->data[0].v_pointer = notejot_task_manager_ref (src_value->data[0].v_pointer);
#line 1434 "TaskManager.c"
	} else {
#line 20 "../src/Services/TaskManager.vala"
		dest_value->data[0].v_pointer = NULL;
#line 1438 "TaskManager.c"
	}
}

static gpointer
notejot_value_task_manager_peek_pointer (const GValue* value)
{
#line 20 "../src/Services/TaskManager.vala"
	return value->data[0].v_pointer;
#line 1447 "TaskManager.c"
}

static gchar*
notejot_value_task_manager_collect_value (GValue* value,
                                          guint n_collect_values,
                                          GTypeCValue* collect_values,
                                          guint collect_flags)
{
#line 20 "../src/Services/TaskManager.vala"
	if (collect_values[0].v_pointer) {
#line 1458 "TaskManager.c"
		NotejotTaskManager * object;
		object = collect_values[0].v_pointer;
#line 20 "../src/Services/TaskManager.vala"
		if (object->parent_instance.g_class == NULL) {
#line 20 "../src/Services/TaskManager.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1465 "TaskManager.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 20 "../src/Services/TaskManager.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 1469 "TaskManager.c"
		}
#line 20 "../src/Services/TaskManager.vala"
		value->data[0].v_pointer = notejot_task_manager_ref (object);
#line 1473 "TaskManager.c"
	} else {
#line 20 "../src/Services/TaskManager.vala"
		value->data[0].v_pointer = NULL;
#line 1477 "TaskManager.c"
	}
#line 20 "../src/Services/TaskManager.vala"
	return NULL;
#line 1481 "TaskManager.c"
}

static gchar*
notejot_value_task_manager_lcopy_value (const GValue* value,
                                        guint n_collect_values,
                                        GTypeCValue* collect_values,
                                        guint collect_flags)
{
	NotejotTaskManager ** object_p;
	object_p = collect_values[0].v_pointer;
#line 20 "../src/Services/TaskManager.vala"
	if (!object_p) {
#line 20 "../src/Services/TaskManager.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 1496 "TaskManager.c"
	}
#line 20 "../src/Services/TaskManager.vala"
	if (!value->data[0].v_pointer) {
#line 20 "../src/Services/TaskManager.vala"
		*object_p = NULL;
#line 1502 "TaskManager.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 20 "../src/Services/TaskManager.vala"
		*object_p = value->data[0].v_pointer;
#line 1506 "TaskManager.c"
	} else {
#line 20 "../src/Services/TaskManager.vala"
		*object_p = notejot_task_manager_ref (value->data[0].v_pointer);
#line 1510 "TaskManager.c"
	}
#line 20 "../src/Services/TaskManager.vala"
	return NULL;
#line 1514 "TaskManager.c"
}

GParamSpec*
notejot_param_spec_task_manager (const gchar* name,
                                 const gchar* nick,
                                 const gchar* blurb,
                                 GType object_type,
                                 GParamFlags flags)
{
	NotejotParamSpecTaskManager* spec;
#line 20 "../src/Services/TaskManager.vala"
	g_return_val_if_fail (g_type_is_a (object_type, NOTEJOT_TYPE_TASK_MANAGER), NULL);
#line 20 "../src/Services/TaskManager.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 20 "../src/Services/TaskManager.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 20 "../src/Services/TaskManager.vala"
	return G_PARAM_SPEC (spec);
#line 1533 "TaskManager.c"
}

gpointer
notejot_value_get_task_manager (const GValue* value)
{
#line 20 "../src/Services/TaskManager.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, NOTEJOT_TYPE_TASK_MANAGER), NULL);
#line 20 "../src/Services/TaskManager.vala"
	return value->data[0].v_pointer;
#line 1543 "TaskManager.c"
}

void
notejot_value_set_task_manager (GValue* value,
                                gpointer v_object)
{
	NotejotTaskManager * old;
#line 20 "../src/Services/TaskManager.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, NOTEJOT_TYPE_TASK_MANAGER));
#line 20 "../src/Services/TaskManager.vala"
	old = value->data[0].v_pointer;
#line 20 "../src/Services/TaskManager.vala"
	if (v_object) {
#line 20 "../src/Services/TaskManager.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, NOTEJOT_TYPE_TASK_MANAGER));
#line 20 "../src/Services/TaskManager.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 20 "../src/Services/TaskManager.vala"
		value->data[0].v_pointer = v_object;
#line 20 "../src/Services/TaskManager.vala"
		notejot_task_manager_ref (value->data[0].v_pointer);
#line 1565 "TaskManager.c"
	} else {
#line 20 "../src/Services/TaskManager.vala"
		value->data[0].v_pointer = NULL;
#line 1569 "TaskManager.c"
	}
#line 20 "../src/Services/TaskManager.vala"
	if (old) {
#line 20 "../src/Services/TaskManager.vala"
		notejot_task_manager_unref (old);
#line 1575 "TaskManager.c"
	}
}

void
notejot_value_take_task_manager (GValue* value,
                                 gpointer v_object)
{
	NotejotTaskManager * old;
#line 20 "../src/Services/TaskManager.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, NOTEJOT_TYPE_TASK_MANAGER));
#line 20 "../src/Services/TaskManager.vala"
	old = value->data[0].v_pointer;
#line 20 "../src/Services/TaskManager.vala"
	if (v_object) {
#line 20 "../src/Services/TaskManager.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, NOTEJOT_TYPE_TASK_MANAGER));
#line 20 "../src/Services/TaskManager.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 20 "../src/Services/TaskManager.vala"
		value->data[0].v_pointer = v_object;
#line 1596 "TaskManager.c"
	} else {
#line 20 "../src/Services/TaskManager.vala"
		value->data[0].v_pointer = NULL;
#line 1600 "TaskManager.c"
	}
#line 20 "../src/Services/TaskManager.vala"
	if (old) {
#line 20 "../src/Services/TaskManager.vala"
		notejot_task_manager_unref (old);
#line 1606 "TaskManager.c"
	}
}

static void
notejot_task_manager_class_init (NotejotTaskManagerClass * klass,
                                 gpointer klass_data)
{
#line 20 "../src/Services/TaskManager.vala"
	notejot_task_manager_parent_class = g_type_class_peek_parent (klass);
#line 20 "../src/Services/TaskManager.vala"
	((NotejotTaskManagerClass *) klass)->finalize = notejot_task_manager_finalize;
#line 20 "../src/Services/TaskManager.vala"
	g_type_class_adjust_private_offset (klass, &NotejotTaskManager_private_offset);
#line 1620 "TaskManager.c"
}

static void
notejot_task_manager_instance_init (NotejotTaskManager * self,
                                    gpointer klass)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
#line 20 "../src/Services/TaskManager.vala"
	self->priv = notejot_task_manager_get_instance_private (self);
#line 23 "../src/Services/TaskManager.vala"
	_tmp0_ = g_get_user_data_dir ();
#line 23 "../src/Services/TaskManager.vala"
	_tmp1_ = g_strconcat (_tmp0_, "/io.github.lainsce.Notejot", NULL);
#line 23 "../src/Services/TaskManager.vala"
	self->priv->app_dir = _tmp1_;
#line 20 "../src/Services/TaskManager.vala"
	self->ref_count = 1;
#line 1639 "TaskManager.c"
}

static void
notejot_task_manager_finalize (NotejotTaskManager * obj)
{
	NotejotTaskManager * self;
#line 20 "../src/Services/TaskManager.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManager);
#line 20 "../src/Services/TaskManager.vala"
	g_signal_handlers_destroy (self);
#line 21 "../src/Services/TaskManager.vala"
	_g_object_unref0 (self->win);
#line 22 "../src/Services/TaskManager.vala"
	_g_object_unref0 (self->builder);
#line 23 "../src/Services/TaskManager.vala"
	_g_free0 (self->priv->app_dir);
#line 25 "../src/Services/TaskManager.vala"
	_g_free0 (self->priv->file_name);
#line 1658 "TaskManager.c"
}

static GType
notejot_task_manager_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { notejot_value_task_manager_init, notejot_value_task_manager_free_value, notejot_value_task_manager_copy_value, notejot_value_task_manager_peek_pointer, "p", notejot_value_task_manager_collect_value, "p", notejot_value_task_manager_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (NotejotTaskManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) notejot_task_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NotejotTaskManager), 0, (GInstanceInitFunc) notejot_task_manager_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType notejot_task_manager_type_id;
	notejot_task_manager_type_id = g_type_register_fundamental (g_type_fundamental_next (), "NotejotTaskManager", &g_define_type_info, &g_define_type_fundamental_info, 0);
	NotejotTaskManager_private_offset = g_type_add_instance_private (notejot_task_manager_type_id, sizeof (NotejotTaskManagerPrivate));
	return notejot_task_manager_type_id;
}

GType
notejot_task_manager_get_type (void)
{
	static volatile gsize notejot_task_manager_type_id__volatile = 0;
	if (g_once_init_enter (&notejot_task_manager_type_id__volatile)) {
		GType notejot_task_manager_type_id;
		notejot_task_manager_type_id = notejot_task_manager_get_type_once ();
		g_once_init_leave (&notejot_task_manager_type_id__volatile, notejot_task_manager_type_id);
	}
	return notejot_task_manager_type_id__volatile;
}

gpointer
notejot_task_manager_ref (gpointer instance)
{
	NotejotTaskManager * self;
	self = instance;
#line 20 "../src/Services/TaskManager.vala"
	g_atomic_int_inc (&self->ref_count);
#line 20 "../src/Services/TaskManager.vala"
	return instance;
#line 1694 "TaskManager.c"
}

void
notejot_task_manager_unref (gpointer instance)
{
	NotejotTaskManager * self;
	self = instance;
#line 20 "../src/Services/TaskManager.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 20 "../src/Services/TaskManager.vala"
		NOTEJOT_TASK_MANAGER_GET_CLASS (self)->finalize (self);
#line 20 "../src/Services/TaskManager.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 1708 "TaskManager.c"
	}
}

