/* Utils.c generated by valac 0.50.3, the Vala compiler
 * generated from Utils.vala, do not modify */

#include <glib-object.h>
#include <glib.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <math.h>
#include <float.h>
#include <gobject/gvaluecollector.h>

#define NOTEJOT_TYPE_UTILS (notejot_utils_get_type ())
#define NOTEJOT_UTILS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_TYPE_UTILS, NotejotUtils))
#define NOTEJOT_UTILS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_TYPE_UTILS, NotejotUtilsClass))
#define NOTEJOT_IS_UTILS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_TYPE_UTILS))
#define NOTEJOT_IS_UTILS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_TYPE_UTILS))
#define NOTEJOT_UTILS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_TYPE_UTILS, NotejotUtilsClass))

typedef struct _NotejotUtils NotejotUtils;
typedef struct _NotejotUtilsClass NotejotUtilsClass;
typedef struct _NotejotUtilsPrivate NotejotUtilsPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
typedef struct _NotejotParamSpecUtils NotejotParamSpecUtils;

struct _NotejotUtils {
	GTypeInstance parent_instance;
	volatile int ref_count;
	NotejotUtilsPrivate * priv;
};

struct _NotejotUtilsClass {
	GTypeClass parent_class;
	void (*finalize) (NotejotUtils *self);
};

struct _NotejotParamSpecUtils {
	GParamSpec parent_instance;
};

static gpointer notejot_utils_parent_class = NULL;

gpointer notejot_utils_ref (gpointer instance);
void notejot_utils_unref (gpointer instance);
GParamSpec* notejot_param_spec_utils (const gchar* name,
                                      const gchar* nick,
                                      const gchar* blurb,
                                      GType object_type,
                                      GParamFlags flags);
void notejot_value_set_utils (GValue* value,
                              gpointer v_object);
void notejot_value_take_utils (GValue* value,
                               gpointer v_object);
gpointer notejot_value_get_utils (const GValue* value);
GType notejot_utils_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotUtils, notejot_utils_unref)
gboolean notejot_utils_is_same_day (GDateTime* day1,
                                    GDateTime* day2);
static gboolean notejot_utils_is_clock_format_12h (void);
gchar* notejot_utils_get_default_date_format (gboolean with_weekday,
                                              gboolean with_day,
                                              gboolean with_year);
gchar* notejot_utils_get_default_time_format (gboolean is_12h,
                                              gboolean with_second);
gchar* notejot_utils_get_relative_datetime (GDateTime* date_time);
NotejotUtils* notejot_utils_new (void);
NotejotUtils* notejot_utils_construct (GType object_type);
static void notejot_utils_finalize (NotejotUtils * obj);
static GType notejot_utils_get_type_once (void);

gboolean
notejot_utils_is_same_day (GDateTime* day1,
                           GDateTime* day2)
{
	gboolean _tmp0_ = FALSE;
	gboolean result = FALSE;
#line 3 "../src/Services/Utils.vala"
	g_return_val_if_fail (day1 != NULL, FALSE);
#line 3 "../src/Services/Utils.vala"
	g_return_val_if_fail (day2 != NULL, FALSE);
#line 4 "../src/Services/Utils.vala"
	if (g_date_time_get_day_of_year (day1) == g_date_time_get_day_of_year (day2)) {
#line 4 "../src/Services/Utils.vala"
		_tmp0_ = g_date_time_get_year (day1) == g_date_time_get_year (day2);
#line 89 "Utils.c"
	} else {
#line 4 "../src/Services/Utils.vala"
		_tmp0_ = FALSE;
#line 93 "Utils.c"
	}
#line 4 "../src/Services/Utils.vala"
	result = _tmp0_;
#line 4 "../src/Services/Utils.vala"
	return result;
#line 99 "Utils.c"
}

static gboolean
string_contains (const gchar* self,
                 const gchar* needle)
{
	gchar* _tmp0_;
	gboolean result = FALSE;
#line 1530 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, FALSE);
#line 1530 "glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, FALSE);
#line 1531 "glib-2.0.vapi"
	_tmp0_ = strstr ((gchar*) self, (gchar*) needle);
#line 1531 "glib-2.0.vapi"
	result = _tmp0_ != NULL;
#line 1531 "glib-2.0.vapi"
	return result;
#line 118 "Utils.c"
}

static gboolean
notejot_utils_is_clock_format_12h (void)
{
	GSettings* h24_settings = NULL;
	GSettings* _tmp0_;
	gchar* format = NULL;
	gchar* _tmp1_;
	gboolean result = FALSE;
#line 8 "../src/Services/Utils.vala"
	_tmp0_ = g_settings_new ("org.gnome.desktop.interface");
#line 8 "../src/Services/Utils.vala"
	h24_settings = _tmp0_;
#line 9 "../src/Services/Utils.vala"
	_tmp1_ = g_settings_get_string (h24_settings, "clock-format");
#line 9 "../src/Services/Utils.vala"
	format = _tmp1_;
#line 10 "../src/Services/Utils.vala"
	result = string_contains (format, "12h");
#line 10 "../src/Services/Utils.vala"
	_g_free0 (format);
#line 10 "../src/Services/Utils.vala"
	_g_object_unref0 (h24_settings);
#line 10 "../src/Services/Utils.vala"
	return result;
#line 145 "Utils.c"
}

gchar*
notejot_utils_get_default_date_format (gboolean with_weekday,
                                       gboolean with_day,
                                       gboolean with_year)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gchar* _tmp24_;
	gchar* result = NULL;
#line 14 "../src/Services/Utils.vala"
	if (with_weekday == TRUE) {
#line 14 "../src/Services/Utils.vala"
		_tmp1_ = with_day == TRUE;
#line 161 "Utils.c"
	} else {
#line 14 "../src/Services/Utils.vala"
		_tmp1_ = FALSE;
#line 165 "Utils.c"
	}
#line 14 "../src/Services/Utils.vala"
	if (_tmp1_) {
#line 14 "../src/Services/Utils.vala"
		_tmp0_ = with_year == TRUE;
#line 171 "Utils.c"
	} else {
#line 14 "../src/Services/Utils.vala"
		_tmp0_ = FALSE;
#line 175 "Utils.c"
	}
#line 14 "../src/Services/Utils.vala"
	if (_tmp0_) {
#line 179 "Utils.c"
		gchar* _tmp2_;
#line 16 "../src/Services/Utils.vala"
		_tmp2_ = g_strdup (_ ("%a, %b %e, %Y"));
#line 16 "../src/Services/Utils.vala"
		result = _tmp2_;
#line 16 "../src/Services/Utils.vala"
		return result;
#line 187 "Utils.c"
	} else {
		gboolean _tmp3_ = FALSE;
		gboolean _tmp4_ = FALSE;
#line 17 "../src/Services/Utils.vala"
		if (with_weekday == FALSE) {
#line 17 "../src/Services/Utils.vala"
			_tmp4_ = with_day == TRUE;
#line 195 "Utils.c"
		} else {
#line 17 "../src/Services/Utils.vala"
			_tmp4_ = FALSE;
#line 199 "Utils.c"
		}
#line 17 "../src/Services/Utils.vala"
		if (_tmp4_) {
#line 17 "../src/Services/Utils.vala"
			_tmp3_ = with_year == TRUE;
#line 205 "Utils.c"
		} else {
#line 17 "../src/Services/Utils.vala"
			_tmp3_ = FALSE;
#line 209 "Utils.c"
		}
#line 17 "../src/Services/Utils.vala"
		if (_tmp3_) {
#line 213 "Utils.c"
			gchar* _tmp5_;
#line 19 "../src/Services/Utils.vala"
			_tmp5_ = g_strdup (_ ("%b %e %Y"));
#line 19 "../src/Services/Utils.vala"
			result = _tmp5_;
#line 19 "../src/Services/Utils.vala"
			return result;
#line 221 "Utils.c"
		} else {
			gboolean _tmp6_ = FALSE;
			gboolean _tmp7_ = FALSE;
#line 20 "../src/Services/Utils.vala"
			if (with_weekday == FALSE) {
#line 20 "../src/Services/Utils.vala"
				_tmp7_ = with_day == FALSE;
#line 229 "Utils.c"
			} else {
#line 20 "../src/Services/Utils.vala"
				_tmp7_ = FALSE;
#line 233 "Utils.c"
			}
#line 20 "../src/Services/Utils.vala"
			if (_tmp7_) {
#line 20 "../src/Services/Utils.vala"
				_tmp6_ = with_year == TRUE;
#line 239 "Utils.c"
			} else {
#line 20 "../src/Services/Utils.vala"
				_tmp6_ = FALSE;
#line 243 "Utils.c"
			}
#line 20 "../src/Services/Utils.vala"
			if (_tmp6_) {
#line 247 "Utils.c"
				gchar* _tmp8_;
#line 22 "../src/Services/Utils.vala"
				_tmp8_ = g_strdup (_ ("%Y"));
#line 22 "../src/Services/Utils.vala"
				result = _tmp8_;
#line 22 "../src/Services/Utils.vala"
				return result;
#line 255 "Utils.c"
			} else {
				gboolean _tmp9_ = FALSE;
				gboolean _tmp10_ = FALSE;
#line 23 "../src/Services/Utils.vala"
				if (with_weekday == FALSE) {
#line 23 "../src/Services/Utils.vala"
					_tmp10_ = with_day == TRUE;
#line 263 "Utils.c"
				} else {
#line 23 "../src/Services/Utils.vala"
					_tmp10_ = FALSE;
#line 267 "Utils.c"
				}
#line 23 "../src/Services/Utils.vala"
				if (_tmp10_) {
#line 23 "../src/Services/Utils.vala"
					_tmp9_ = with_year == FALSE;
#line 273 "Utils.c"
				} else {
#line 23 "../src/Services/Utils.vala"
					_tmp9_ = FALSE;
#line 277 "Utils.c"
				}
#line 23 "../src/Services/Utils.vala"
				if (_tmp9_) {
#line 281 "Utils.c"
					gchar* _tmp11_;
#line 25 "../src/Services/Utils.vala"
					_tmp11_ = g_strdup (_ ("%b %e"));
#line 25 "../src/Services/Utils.vala"
					result = _tmp11_;
#line 25 "../src/Services/Utils.vala"
					return result;
#line 289 "Utils.c"
				} else {
					gboolean _tmp12_ = FALSE;
					gboolean _tmp13_ = FALSE;
#line 26 "../src/Services/Utils.vala"
					if (with_weekday == TRUE) {
#line 26 "../src/Services/Utils.vala"
						_tmp13_ = with_day == FALSE;
#line 297 "Utils.c"
					} else {
#line 26 "../src/Services/Utils.vala"
						_tmp13_ = FALSE;
#line 301 "Utils.c"
					}
#line 26 "../src/Services/Utils.vala"
					if (_tmp13_) {
#line 26 "../src/Services/Utils.vala"
						_tmp12_ = with_year == TRUE;
#line 307 "Utils.c"
					} else {
#line 26 "../src/Services/Utils.vala"
						_tmp12_ = FALSE;
#line 311 "Utils.c"
					}
#line 26 "../src/Services/Utils.vala"
					if (_tmp12_) {
#line 315 "Utils.c"
						gchar* _tmp14_;
#line 28 "../src/Services/Utils.vala"
						_tmp14_ = g_strdup (_ ("%a %Y"));
#line 28 "../src/Services/Utils.vala"
						result = _tmp14_;
#line 28 "../src/Services/Utils.vala"
						return result;
#line 323 "Utils.c"
					} else {
						gboolean _tmp15_ = FALSE;
						gboolean _tmp16_ = FALSE;
#line 29 "../src/Services/Utils.vala"
						if (with_weekday == TRUE) {
#line 29 "../src/Services/Utils.vala"
							_tmp16_ = with_day == FALSE;
#line 331 "Utils.c"
						} else {
#line 29 "../src/Services/Utils.vala"
							_tmp16_ = FALSE;
#line 335 "Utils.c"
						}
#line 29 "../src/Services/Utils.vala"
						if (_tmp16_) {
#line 29 "../src/Services/Utils.vala"
							_tmp15_ = with_year == FALSE;
#line 341 "Utils.c"
						} else {
#line 29 "../src/Services/Utils.vala"
							_tmp15_ = FALSE;
#line 345 "Utils.c"
						}
#line 29 "../src/Services/Utils.vala"
						if (_tmp15_) {
#line 349 "Utils.c"
							gchar* _tmp17_;
#line 31 "../src/Services/Utils.vala"
							_tmp17_ = g_strdup (_ ("%a"));
#line 31 "../src/Services/Utils.vala"
							result = _tmp17_;
#line 31 "../src/Services/Utils.vala"
							return result;
#line 357 "Utils.c"
						} else {
							gboolean _tmp18_ = FALSE;
							gboolean _tmp19_ = FALSE;
#line 32 "../src/Services/Utils.vala"
							if (with_weekday == TRUE) {
#line 32 "../src/Services/Utils.vala"
								_tmp19_ = with_day == TRUE;
#line 365 "Utils.c"
							} else {
#line 32 "../src/Services/Utils.vala"
								_tmp19_ = FALSE;
#line 369 "Utils.c"
							}
#line 32 "../src/Services/Utils.vala"
							if (_tmp19_) {
#line 32 "../src/Services/Utils.vala"
								_tmp18_ = with_year == FALSE;
#line 375 "Utils.c"
							} else {
#line 32 "../src/Services/Utils.vala"
								_tmp18_ = FALSE;
#line 379 "Utils.c"
							}
#line 32 "../src/Services/Utils.vala"
							if (_tmp18_) {
#line 383 "Utils.c"
								gchar* _tmp20_;
#line 34 "../src/Services/Utils.vala"
								_tmp20_ = g_strdup (_ ("%a, %b %e"));
#line 34 "../src/Services/Utils.vala"
								result = _tmp20_;
#line 34 "../src/Services/Utils.vala"
								return result;
#line 391 "Utils.c"
							} else {
								gboolean _tmp21_ = FALSE;
								gboolean _tmp22_ = FALSE;
#line 35 "../src/Services/Utils.vala"
								if (with_weekday == FALSE) {
#line 35 "../src/Services/Utils.vala"
									_tmp22_ = with_day == FALSE;
#line 399 "Utils.c"
								} else {
#line 35 "../src/Services/Utils.vala"
									_tmp22_ = FALSE;
#line 403 "Utils.c"
								}
#line 35 "../src/Services/Utils.vala"
								if (_tmp22_) {
#line 35 "../src/Services/Utils.vala"
									_tmp21_ = with_year == FALSE;
#line 409 "Utils.c"
								} else {
#line 35 "../src/Services/Utils.vala"
									_tmp21_ = FALSE;
#line 413 "Utils.c"
								}
#line 35 "../src/Services/Utils.vala"
								if (_tmp21_) {
#line 417 "Utils.c"
									gchar* _tmp23_;
#line 37 "../src/Services/Utils.vala"
									_tmp23_ = g_strdup (_ ("%b"));
#line 37 "../src/Services/Utils.vala"
									result = _tmp23_;
#line 37 "../src/Services/Utils.vala"
									return result;
#line 425 "Utils.c"
								}
							}
						}
					}
				}
			}
		}
	}
#line 40 "../src/Services/Utils.vala"
	_tmp24_ = g_strdup ("");
#line 40 "../src/Services/Utils.vala"
	result = _tmp24_;
#line 40 "../src/Services/Utils.vala"
	return result;
#line 440 "Utils.c"
}

gchar*
notejot_utils_get_default_time_format (gboolean is_12h,
                                       gboolean with_second)
{
	gchar* result = NULL;
#line 44 "../src/Services/Utils.vala"
	if (is_12h == TRUE) {
#line 45 "../src/Services/Utils.vala"
		if (with_second == TRUE) {
#line 452 "Utils.c"
			gchar* _tmp0_;
#line 47 "../src/Services/Utils.vala"
			_tmp0_ = g_strdup (_ ("%-l:%M:%S %p"));
#line 47 "../src/Services/Utils.vala"
			result = _tmp0_;
#line 47 "../src/Services/Utils.vala"
			return result;
#line 460 "Utils.c"
		} else {
			gchar* _tmp1_;
#line 50 "../src/Services/Utils.vala"
			_tmp1_ = g_strdup (_ ("%-l:%M %p"));
#line 50 "../src/Services/Utils.vala"
			result = _tmp1_;
#line 50 "../src/Services/Utils.vala"
			return result;
#line 469 "Utils.c"
		}
	} else {
#line 53 "../src/Services/Utils.vala"
		if (with_second == TRUE) {
#line 474 "Utils.c"
			gchar* _tmp2_;
#line 55 "../src/Services/Utils.vala"
			_tmp2_ = g_strdup (_ ("%H:%M:%S"));
#line 55 "../src/Services/Utils.vala"
			result = _tmp2_;
#line 55 "../src/Services/Utils.vala"
			return result;
#line 482 "Utils.c"
		} else {
			gchar* _tmp3_;
#line 58 "../src/Services/Utils.vala"
			_tmp3_ = g_strdup (_ ("%H:%M"));
#line 58 "../src/Services/Utils.vala"
			result = _tmp3_;
#line 58 "../src/Services/Utils.vala"
			return result;
#line 491 "Utils.c"
		}
	}
}

gchar*
notejot_utils_get_relative_datetime (GDateTime* date_time)
{
	GDateTime* now = NULL;
	GDateTime* _tmp0_;
	GTimeSpan diff = 0LL;
	GDateTime* _tmp1_;
	GDateTime* _tmp2_;
	gchar* result = NULL;
#line 63 "../src/Services/Utils.vala"
	g_return_val_if_fail (date_time != NULL, NULL);
#line 64 "../src/Services/Utils.vala"
	_tmp0_ = g_date_time_new_now_local ();
#line 64 "../src/Services/Utils.vala"
	now = _tmp0_;
#line 65 "../src/Services/Utils.vala"
	_tmp1_ = now;
#line 65 "../src/Services/Utils.vala"
	diff = g_date_time_difference (_tmp1_, date_time);
#line 67 "../src/Services/Utils.vala"
	_tmp2_ = now;
#line 67 "../src/Services/Utils.vala"
	if (notejot_utils_is_same_day (date_time, _tmp2_)) {
#line 519 "Utils.c"
		gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
#line 68 "../src/Services/Utils.vala"
		if (diff > ((GTimeSpan) 0)) {
#line 69 "../src/Services/Utils.vala"
			if (diff < G_TIME_SPAN_MINUTE) {
#line 528 "Utils.c"
				gchar* _tmp3_;
#line 70 "../src/Services/Utils.vala"
				_tmp3_ = g_strdup (_ ("Now"));
#line 70 "../src/Services/Utils.vala"
				result = _tmp3_;
#line 70 "../src/Services/Utils.vala"
				_g_date_time_unref0 (now);
#line 70 "../src/Services/Utils.vala"
				return result;
#line 538 "Utils.c"
			} else {
#line 71 "../src/Services/Utils.vala"
				if (diff < G_TIME_SPAN_HOUR) {
#line 542 "Utils.c"
					GTimeSpan minutes = 0LL;
					gchar* _tmp4_;
#line 72 "../src/Services/Utils.vala"
					minutes = diff / G_TIME_SPAN_MINUTE;
#line 73 "../src/Services/Utils.vala"
					_tmp4_ = g_strdup_printf (ngettext ("%d minute ago", "%d minutes ago", (gulong) minutes), (gint) minutes);
#line 73 "../src/Services/Utils.vala"
					result = _tmp4_;
#line 73 "../src/Services/Utils.vala"
					_g_date_time_unref0 (now);
#line 73 "../src/Services/Utils.vala"
					return result;
#line 555 "Utils.c"
				} else {
#line 74 "../src/Services/Utils.vala"
					if (diff < (12 * G_TIME_SPAN_HOUR)) {
#line 559 "Utils.c"
						gint rounded = 0;
						gchar* _tmp5_;
#line 75 "../src/Services/Utils.vala"
						rounded = (gint) round (((gdouble) diff) / G_TIME_SPAN_HOUR);
#line 76 "../src/Services/Utils.vala"
						_tmp5_ = g_strdup_printf (ngettext ("%d hour ago", "%d hours ago", (gulong) rounded), rounded);
#line 76 "../src/Services/Utils.vala"
						result = _tmp5_;
#line 76 "../src/Services/Utils.vala"
						_g_date_time_unref0 (now);
#line 76 "../src/Services/Utils.vala"
						return result;
#line 572 "Utils.c"
					}
				}
			}
		} else {
#line 79 "../src/Services/Utils.vala"
			diff = -1 * diff;
#line 80 "../src/Services/Utils.vala"
			if (diff < G_TIME_SPAN_HOUR) {
#line 581 "Utils.c"
				GTimeSpan minutes = 0LL;
				gchar* _tmp6_;
#line 81 "../src/Services/Utils.vala"
				minutes = diff / G_TIME_SPAN_MINUTE;
#line 82 "../src/Services/Utils.vala"
				_tmp6_ = g_strdup_printf (ngettext ("in %d minute", "in %d minutes", (gulong) minutes), (gint) minutes);
#line 82 "../src/Services/Utils.vala"
				result = _tmp6_;
#line 82 "../src/Services/Utils.vala"
				_g_date_time_unref0 (now);
#line 82 "../src/Services/Utils.vala"
				return result;
#line 594 "Utils.c"
			} else {
#line 83 "../src/Services/Utils.vala"
				if (diff < (12 * G_TIME_SPAN_HOUR)) {
#line 598 "Utils.c"
					gint rounded = 0;
					gchar* _tmp7_;
#line 84 "../src/Services/Utils.vala"
					rounded = (gint) round (((gdouble) diff) / G_TIME_SPAN_HOUR);
#line 85 "../src/Services/Utils.vala"
					_tmp7_ = g_strdup_printf (ngettext ("in %d hour", "in %d hours", (gulong) rounded), rounded);
#line 85 "../src/Services/Utils.vala"
					result = _tmp7_;
#line 85 "../src/Services/Utils.vala"
					_g_date_time_unref0 (now);
#line 85 "../src/Services/Utils.vala"
					return result;
#line 611 "Utils.c"
				}
			}
		}
#line 89 "../src/Services/Utils.vala"
		_tmp8_ = notejot_utils_get_default_time_format (notejot_utils_is_clock_format_12h (), FALSE);
#line 89 "../src/Services/Utils.vala"
		_tmp9_ = _tmp8_;
#line 89 "../src/Services/Utils.vala"
		_tmp10_ = g_date_time_format (date_time, _tmp9_);
#line 89 "../src/Services/Utils.vala"
		_tmp11_ = _tmp10_;
#line 89 "../src/Services/Utils.vala"
		_g_free0 (_tmp9_);
#line 89 "../src/Services/Utils.vala"
		result = _tmp11_;
#line 89 "../src/Services/Utils.vala"
		_g_date_time_unref0 (now);
#line 89 "../src/Services/Utils.vala"
		return result;
#line 631 "Utils.c"
	} else {
		GDateTime* _tmp12_;
		GDateTime* _tmp13_;
		GDateTime* _tmp14_;
		gboolean _tmp15_;
#line 90 "../src/Services/Utils.vala"
		_tmp12_ = g_date_time_add_days (date_time, 1);
#line 90 "../src/Services/Utils.vala"
		_tmp13_ = _tmp12_;
#line 90 "../src/Services/Utils.vala"
		_tmp14_ = now;
#line 90 "../src/Services/Utils.vala"
		_tmp15_ = notejot_utils_is_same_day (_tmp13_, _tmp14_);
#line 90 "../src/Services/Utils.vala"
		_g_date_time_unref0 (_tmp13_);
#line 90 "../src/Services/Utils.vala"
		if (_tmp15_) {
#line 649 "Utils.c"
			gchar* _tmp16_;
#line 91 "../src/Services/Utils.vala"
			_tmp16_ = g_strdup (_ ("Yesterday"));
#line 91 "../src/Services/Utils.vala"
			result = _tmp16_;
#line 91 "../src/Services/Utils.vala"
			_g_date_time_unref0 (now);
#line 91 "../src/Services/Utils.vala"
			return result;
#line 659 "Utils.c"
		} else {
			GDateTime* _tmp17_;
			GDateTime* _tmp18_;
			GDateTime* _tmp19_;
			gboolean _tmp20_;
#line 92 "../src/Services/Utils.vala"
			_tmp17_ = g_date_time_add_days (date_time, -1);
#line 92 "../src/Services/Utils.vala"
			_tmp18_ = _tmp17_;
#line 92 "../src/Services/Utils.vala"
			_tmp19_ = now;
#line 92 "../src/Services/Utils.vala"
			_tmp20_ = notejot_utils_is_same_day (_tmp18_, _tmp19_);
#line 92 "../src/Services/Utils.vala"
			_g_date_time_unref0 (_tmp18_);
#line 92 "../src/Services/Utils.vala"
			if (_tmp20_) {
#line 677 "Utils.c"
				gchar* _tmp21_;
#line 93 "../src/Services/Utils.vala"
				_tmp21_ = g_strdup (_ ("Tomorrow"));
#line 93 "../src/Services/Utils.vala"
				result = _tmp21_;
#line 93 "../src/Services/Utils.vala"
				_g_date_time_unref0 (now);
#line 93 "../src/Services/Utils.vala"
				return result;
#line 687 "Utils.c"
			} else {
				gboolean _tmp22_ = FALSE;
#line 94 "../src/Services/Utils.vala"
				if (diff < (6 * G_TIME_SPAN_DAY)) {
#line 94 "../src/Services/Utils.vala"
					_tmp22_ = diff > (-6 * G_TIME_SPAN_DAY);
#line 694 "Utils.c"
				} else {
#line 94 "../src/Services/Utils.vala"
					_tmp22_ = FALSE;
#line 698 "Utils.c"
				}
#line 94 "../src/Services/Utils.vala"
				if (_tmp22_) {
#line 702 "Utils.c"
					gchar* _tmp23_;
					gchar* _tmp24_;
					gchar* _tmp25_;
					gchar* _tmp26_;
#line 95 "../src/Services/Utils.vala"
					_tmp23_ = notejot_utils_get_default_date_format (TRUE, FALSE, FALSE);
#line 95 "../src/Services/Utils.vala"
					_tmp24_ = _tmp23_;
#line 95 "../src/Services/Utils.vala"
					_tmp25_ = g_date_time_format (date_time, _tmp24_);
#line 95 "../src/Services/Utils.vala"
					_tmp26_ = _tmp25_;
#line 95 "../src/Services/Utils.vala"
					_g_free0 (_tmp24_);
#line 95 "../src/Services/Utils.vala"
					result = _tmp26_;
#line 95 "../src/Services/Utils.vala"
					_g_date_time_unref0 (now);
#line 95 "../src/Services/Utils.vala"
					return result;
#line 723 "Utils.c"
				} else {
					GDateTime* _tmp27_;
#line 96 "../src/Services/Utils.vala"
					_tmp27_ = now;
#line 96 "../src/Services/Utils.vala"
					if (g_date_time_get_year (date_time) == g_date_time_get_year (_tmp27_)) {
#line 730 "Utils.c"
						gchar* _tmp28_;
						gchar* _tmp29_;
						gchar* _tmp30_;
						gchar* _tmp31_;
#line 97 "../src/Services/Utils.vala"
						_tmp28_ = notejot_utils_get_default_date_format (FALSE, TRUE, FALSE);
#line 97 "../src/Services/Utils.vala"
						_tmp29_ = _tmp28_;
#line 97 "../src/Services/Utils.vala"
						_tmp30_ = g_date_time_format (date_time, _tmp29_);
#line 97 "../src/Services/Utils.vala"
						_tmp31_ = _tmp30_;
#line 97 "../src/Services/Utils.vala"
						_g_free0 (_tmp29_);
#line 97 "../src/Services/Utils.vala"
						result = _tmp31_;
#line 97 "../src/Services/Utils.vala"
						_g_date_time_unref0 (now);
#line 97 "../src/Services/Utils.vala"
						return result;
#line 751 "Utils.c"
					} else {
						gchar* _tmp32_;
#line 99 "../src/Services/Utils.vala"
						_tmp32_ = g_date_time_format (date_time, "%x");
#line 99 "../src/Services/Utils.vala"
						result = _tmp32_;
#line 99 "../src/Services/Utils.vala"
						_g_date_time_unref0 (now);
#line 99 "../src/Services/Utils.vala"
						return result;
#line 762 "Utils.c"
					}
				}
			}
		}
	}
#line 63 "../src/Services/Utils.vala"
	_g_date_time_unref0 (now);
#line 770 "Utils.c"
}

NotejotUtils*
notejot_utils_construct (GType object_type)
{
	NotejotUtils* self = NULL;
#line 2 "../src/Services/Utils.vala"
	self = (NotejotUtils*) g_type_create_instance (object_type);
#line 2 "../src/Services/Utils.vala"
	return self;
#line 781 "Utils.c"
}

NotejotUtils*
notejot_utils_new (void)
{
#line 2 "../src/Services/Utils.vala"
	return notejot_utils_construct (NOTEJOT_TYPE_UTILS);
#line 789 "Utils.c"
}

static void
notejot_value_utils_init (GValue* value)
{
#line 2 "../src/Services/Utils.vala"
	value->data[0].v_pointer = NULL;
#line 797 "Utils.c"
}

static void
notejot_value_utils_free_value (GValue* value)
{
#line 2 "../src/Services/Utils.vala"
	if (value->data[0].v_pointer) {
#line 2 "../src/Services/Utils.vala"
		notejot_utils_unref (value->data[0].v_pointer);
#line 807 "Utils.c"
	}
}

static void
notejot_value_utils_copy_value (const GValue* src_value,
                                GValue* dest_value)
{
#line 2 "../src/Services/Utils.vala"
	if (src_value->data[0].v_pointer) {
#line 2 "../src/Services/Utils.vala"
		dest_value->data[0].v_pointer = notejot_utils_ref (src_value->data[0].v_pointer);
#line 819 "Utils.c"
	} else {
#line 2 "../src/Services/Utils.vala"
		dest_value->data[0].v_pointer = NULL;
#line 823 "Utils.c"
	}
}

static gpointer
notejot_value_utils_peek_pointer (const GValue* value)
{
#line 2 "../src/Services/Utils.vala"
	return value->data[0].v_pointer;
#line 832 "Utils.c"
}

static gchar*
notejot_value_utils_collect_value (GValue* value,
                                   guint n_collect_values,
                                   GTypeCValue* collect_values,
                                   guint collect_flags)
{
#line 2 "../src/Services/Utils.vala"
	if (collect_values[0].v_pointer) {
#line 843 "Utils.c"
		NotejotUtils * object;
		object = collect_values[0].v_pointer;
#line 2 "../src/Services/Utils.vala"
		if (object->parent_instance.g_class == NULL) {
#line 2 "../src/Services/Utils.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 850 "Utils.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 2 "../src/Services/Utils.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 854 "Utils.c"
		}
#line 2 "../src/Services/Utils.vala"
		value->data[0].v_pointer = notejot_utils_ref (object);
#line 858 "Utils.c"
	} else {
#line 2 "../src/Services/Utils.vala"
		value->data[0].v_pointer = NULL;
#line 862 "Utils.c"
	}
#line 2 "../src/Services/Utils.vala"
	return NULL;
#line 866 "Utils.c"
}

static gchar*
notejot_value_utils_lcopy_value (const GValue* value,
                                 guint n_collect_values,
                                 GTypeCValue* collect_values,
                                 guint collect_flags)
{
	NotejotUtils ** object_p;
	object_p = collect_values[0].v_pointer;
#line 2 "../src/Services/Utils.vala"
	if (!object_p) {
#line 2 "../src/Services/Utils.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 881 "Utils.c"
	}
#line 2 "../src/Services/Utils.vala"
	if (!value->data[0].v_pointer) {
#line 2 "../src/Services/Utils.vala"
		*object_p = NULL;
#line 887 "Utils.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 2 "../src/Services/Utils.vala"
		*object_p = value->data[0].v_pointer;
#line 891 "Utils.c"
	} else {
#line 2 "../src/Services/Utils.vala"
		*object_p = notejot_utils_ref (value->data[0].v_pointer);
#line 895 "Utils.c"
	}
#line 2 "../src/Services/Utils.vala"
	return NULL;
#line 899 "Utils.c"
}

GParamSpec*
notejot_param_spec_utils (const gchar* name,
                          const gchar* nick,
                          const gchar* blurb,
                          GType object_type,
                          GParamFlags flags)
{
	NotejotParamSpecUtils* spec;
#line 2 "../src/Services/Utils.vala"
	g_return_val_if_fail (g_type_is_a (object_type, NOTEJOT_TYPE_UTILS), NULL);
#line 2 "../src/Services/Utils.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 2 "../src/Services/Utils.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 2 "../src/Services/Utils.vala"
	return G_PARAM_SPEC (spec);
#line 918 "Utils.c"
}

gpointer
notejot_value_get_utils (const GValue* value)
{
#line 2 "../src/Services/Utils.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, NOTEJOT_TYPE_UTILS), NULL);
#line 2 "../src/Services/Utils.vala"
	return value->data[0].v_pointer;
#line 928 "Utils.c"
}

void
notejot_value_set_utils (GValue* value,
                         gpointer v_object)
{
	NotejotUtils * old;
#line 2 "../src/Services/Utils.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, NOTEJOT_TYPE_UTILS));
#line 2 "../src/Services/Utils.vala"
	old = value->data[0].v_pointer;
#line 2 "../src/Services/Utils.vala"
	if (v_object) {
#line 2 "../src/Services/Utils.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, NOTEJOT_TYPE_UTILS));
#line 2 "../src/Services/Utils.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 2 "../src/Services/Utils.vala"
		value->data[0].v_pointer = v_object;
#line 2 "../src/Services/Utils.vala"
		notejot_utils_ref (value->data[0].v_pointer);
#line 950 "Utils.c"
	} else {
#line 2 "../src/Services/Utils.vala"
		value->data[0].v_pointer = NULL;
#line 954 "Utils.c"
	}
#line 2 "../src/Services/Utils.vala"
	if (old) {
#line 2 "../src/Services/Utils.vala"
		notejot_utils_unref (old);
#line 960 "Utils.c"
	}
}

void
notejot_value_take_utils (GValue* value,
                          gpointer v_object)
{
	NotejotUtils * old;
#line 2 "../src/Services/Utils.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, NOTEJOT_TYPE_UTILS));
#line 2 "../src/Services/Utils.vala"
	old = value->data[0].v_pointer;
#line 2 "../src/Services/Utils.vala"
	if (v_object) {
#line 2 "../src/Services/Utils.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, NOTEJOT_TYPE_UTILS));
#line 2 "../src/Services/Utils.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 2 "../src/Services/Utils.vala"
		value->data[0].v_pointer = v_object;
#line 981 "Utils.c"
	} else {
#line 2 "../src/Services/Utils.vala"
		value->data[0].v_pointer = NULL;
#line 985 "Utils.c"
	}
#line 2 "../src/Services/Utils.vala"
	if (old) {
#line 2 "../src/Services/Utils.vala"
		notejot_utils_unref (old);
#line 991 "Utils.c"
	}
}

static void
notejot_utils_class_init (NotejotUtilsClass * klass,
                          gpointer klass_data)
{
#line 2 "../src/Services/Utils.vala"
	notejot_utils_parent_class = g_type_class_peek_parent (klass);
#line 2 "../src/Services/Utils.vala"
	((NotejotUtilsClass *) klass)->finalize = notejot_utils_finalize;
#line 1003 "Utils.c"
}

static void
notejot_utils_instance_init (NotejotUtils * self,
                             gpointer klass)
{
#line 2 "../src/Services/Utils.vala"
	self->ref_count = 1;
#line 1012 "Utils.c"
}

static void
notejot_utils_finalize (NotejotUtils * obj)
{
	NotejotUtils * self;
#line 2 "../src/Services/Utils.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, NOTEJOT_TYPE_UTILS, NotejotUtils);
#line 2 "../src/Services/Utils.vala"
	g_signal_handlers_destroy (self);
#line 1023 "Utils.c"
}

static GType
notejot_utils_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { notejot_value_utils_init, notejot_value_utils_free_value, notejot_value_utils_copy_value, notejot_value_utils_peek_pointer, "p", notejot_value_utils_collect_value, "p", notejot_value_utils_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (NotejotUtilsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) notejot_utils_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NotejotUtils), 0, (GInstanceInitFunc) notejot_utils_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType notejot_utils_type_id;
	notejot_utils_type_id = g_type_register_fundamental (g_type_fundamental_next (), "NotejotUtils", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return notejot_utils_type_id;
}

GType
notejot_utils_get_type (void)
{
	static volatile gsize notejot_utils_type_id__volatile = 0;
	if (g_once_init_enter (&notejot_utils_type_id__volatile)) {
		GType notejot_utils_type_id;
		notejot_utils_type_id = notejot_utils_get_type_once ();
		g_once_init_leave (&notejot_utils_type_id__volatile, notejot_utils_type_id);
	}
	return notejot_utils_type_id__volatile;
}

gpointer
notejot_utils_ref (gpointer instance)
{
	NotejotUtils * self;
	self = instance;
#line 2 "../src/Services/Utils.vala"
	g_atomic_int_inc (&self->ref_count);
#line 2 "../src/Services/Utils.vala"
	return instance;
#line 1058 "Utils.c"
}

void
notejot_utils_unref (gpointer instance)
{
	NotejotUtils * self;
	self = instance;
#line 2 "../src/Services/Utils.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 2 "../src/Services/Utils.vala"
		NOTEJOT_UTILS_GET_CLASS (self)->finalize (self);
#line 2 "../src/Services/Utils.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 1072 "Utils.c"
	}
}

