/* EditableLabel.c generated by valac 0.50.3, the Vala compiler
 * generated from EditableLabel.vala, do not modify */

/*
* Copyright (c) 2017-2021 Lains
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 3 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*
* Co-authored by: Corentin Noël <corentin@elementary.io>
*
*/

#include <gtk/gtk.h>
#include <glib-object.h>
#include <handy.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gdk/gdk.h>

#define NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL (notejot_widgets_editable_label_get_type ())
#define NOTEJOT_WIDGETS_EDITABLE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabel))
#define NOTEJOT_WIDGETS_EDITABLE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabelClass))
#define NOTEJOT_WIDGETS_IS_EDITABLE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL))
#define NOTEJOT_WIDGETS_IS_EDITABLE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL))
#define NOTEJOT_WIDGETS_EDITABLE_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabelClass))

typedef struct _NotejotWidgetsEditableLabel NotejotWidgetsEditableLabel;
typedef struct _NotejotWidgetsEditableLabelClass NotejotWidgetsEditableLabelClass;
typedef struct _NotejotWidgetsEditableLabelPrivate NotejotWidgetsEditableLabelPrivate;

#define NOTEJOT_TYPE_MAIN_WINDOW (notejot_main_window_get_type ())
#define NOTEJOT_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindow))
#define NOTEJOT_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindowClass))
#define NOTEJOT_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_TYPE_MAIN_WINDOW))
#define NOTEJOT_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_TYPE_MAIN_WINDOW))
#define NOTEJOT_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindowClass))

typedef struct _NotejotMainWindow NotejotMainWindow;
typedef struct _NotejotMainWindowClass NotejotMainWindowClass;
enum  {
	NOTEJOT_WIDGETS_EDITABLE_LABEL_0_PROPERTY,
	NOTEJOT_WIDGETS_EDITABLE_LABEL_TEXT_PROPERTY,
	NOTEJOT_WIDGETS_EDITABLE_LABEL_NUM_PROPERTIES
};
static GParamSpec* notejot_widgets_editable_label_properties[NOTEJOT_WIDGETS_EDITABLE_LABEL_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
enum  {
	NOTEJOT_WIDGETS_EDITABLE_LABEL_CHANGED_SIGNAL,
	NOTEJOT_WIDGETS_EDITABLE_LABEL_NUM_SIGNALS
};
static guint notejot_widgets_editable_label_signals[NOTEJOT_WIDGETS_EDITABLE_LABEL_NUM_SIGNALS] = {0};

struct _NotejotWidgetsEditableLabel {
	GtkEventBox parent_instance;
	NotejotWidgetsEditableLabelPrivate * priv;
	GtkLabel* title;
	GtkEntry* entry;
};

struct _NotejotWidgetsEditableLabelClass {
	GtkEventBoxClass parent_class;
};

struct _NotejotWidgetsEditableLabelPrivate {
	NotejotMainWindow* win;
	GtkStack* stack;
	GtkBox* grid;
	GtkButton* edit_button;
	GtkRevealer* button_revealer;
};

static gint NotejotWidgetsEditableLabel_private_offset;
static gpointer notejot_widgets_editable_label_parent_class = NULL;

GType notejot_widgets_editable_label_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsEditableLabel, g_object_unref)
GType notejot_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotMainWindow, g_object_unref)
NotejotWidgetsEditableLabel* notejot_widgets_editable_label_new (NotejotMainWindow* win,
                                                                 const gchar* title_name);
NotejotWidgetsEditableLabel* notejot_widgets_editable_label_construct (GType object_type,
                                                                       NotejotMainWindow* win,
                                                                       const gchar* title_name);
static gboolean __lambda9_ (NotejotWidgetsEditableLabel* self,
                     GdkEventCrossing* event);
static gboolean ___lambda9__gtk_widget_enter_notify_event (GtkWidget* _sender,
                                                    GdkEventCrossing* event,
                                                    gpointer self);
static gboolean __lambda10_ (NotejotWidgetsEditableLabel* self,
                      GdkEventCrossing* event);
static gboolean ___lambda10__gtk_widget_leave_notify_event (GtkWidget* _sender,
                                                     GdkEventCrossing* event,
                                                     gpointer self);
static gboolean __lambda11_ (NotejotWidgetsEditableLabel* self,
                      GdkEventButton* event);
static void notejot_widgets_editable_label_set_editing (NotejotWidgetsEditableLabel* self,
                                                 gboolean value);
static gboolean ___lambda11__gtk_widget_button_release_event (GtkWidget* _sender,
                                                       GdkEventButton* event,
                                                       gpointer self);
static void __lambda12_ (NotejotWidgetsEditableLabel* self);
static void ___lambda12__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda13_ (NotejotWidgetsEditableLabel* self);
static void ___lambda13__gtk_entry_activate (GtkEntry* _sender,
                                      gpointer self);
static gboolean __lambda14_ (NotejotWidgetsEditableLabel* self,
                      GdkEventFocus* event);
static gboolean ___lambda14__gtk_widget_focus_out_event (GtkWidget* _sender,
                                                  GdkEventFocus* event,
                                                  gpointer self);
static void __lambda15_ (NotejotWidgetsEditableLabel* self,
                  GtkEntryIconPosition p0,
                  GdkEvent* p1);
static void ___lambda15__gtk_entry_icon_release (GtkEntry* _sender,
                                          GtkEntryIconPosition icon_pos,
                                          GdkEvent* event,
                                          gpointer self);
const gchar* notejot_widgets_editable_label_get_text (NotejotWidgetsEditableLabel* self);
void notejot_widgets_editable_label_set_text (NotejotWidgetsEditableLabel* self,
                                              const gchar* value);
static void notejot_widgets_editable_label_finalize (GObject * obj);
static GType notejot_widgets_editable_label_get_type_once (void);
static void _vala_notejot_widgets_editable_label_get_property (GObject * object,
                                                        guint property_id,
                                                        GValue * value,
                                                        GParamSpec * pspec);
static void _vala_notejot_widgets_editable_label_set_property (GObject * object,
                                                        guint property_id,
                                                        const GValue * value,
                                                        GParamSpec * pspec);

static inline gpointer
notejot_widgets_editable_label_get_instance_private (NotejotWidgetsEditableLabel* self)
{
	return G_STRUCT_MEMBER_P (self, NotejotWidgetsEditableLabel_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 74 "../src/Widgets/EditableLabel.vala"
	return self ? g_object_ref (self) : NULL;
#line 160 "EditableLabel.c"
}

static gboolean
__lambda9_ (NotejotWidgetsEditableLabel* self,
            GdkEventCrossing* event)
{
	GdkNotifyType _tmp0_;
	gboolean result = FALSE;
#line 83 "../src/Widgets/EditableLabel.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 84 "../src/Widgets/EditableLabel.vala"
	_tmp0_ = event->detail;
#line 84 "../src/Widgets/EditableLabel.vala"
	if (_tmp0_ != GDK_NOTIFY_INFERIOR) {
#line 175 "EditableLabel.c"
		GtkRevealer* _tmp1_;
		GdkWindow* _tmp2_;
		GdkDisplay* _tmp3_;
		GdkCursor* _tmp4_;
		GdkCursor* _tmp5_;
#line 85 "../src/Widgets/EditableLabel.vala"
		_tmp1_ = self->priv->button_revealer;
#line 85 "../src/Widgets/EditableLabel.vala"
		gtk_revealer_set_reveal_child (_tmp1_, TRUE);
#line 86 "../src/Widgets/EditableLabel.vala"
		_tmp2_ = event->window;
#line 86 "../src/Widgets/EditableLabel.vala"
		_tmp3_ = gdk_display_get_default ();
#line 86 "../src/Widgets/EditableLabel.vala"
		_tmp4_ = gdk_cursor_new_from_name (_tmp3_, "text");
#line 86 "../src/Widgets/EditableLabel.vala"
		_tmp5_ = _tmp4_;
#line 86 "../src/Widgets/EditableLabel.vala"
		gdk_window_set_cursor (_tmp2_, _tmp5_);
#line 86 "../src/Widgets/EditableLabel.vala"
		_g_object_unref0 (_tmp5_);
#line 197 "EditableLabel.c"
	}
#line 89 "../src/Widgets/EditableLabel.vala"
	result = FALSE;
#line 89 "../src/Widgets/EditableLabel.vala"
	return result;
#line 203 "EditableLabel.c"
}

static gboolean
___lambda9__gtk_widget_enter_notify_event (GtkWidget* _sender,
                                           GdkEventCrossing* event,
                                           gpointer self)
{
	gboolean result;
	result = __lambda9_ ((NotejotWidgetsEditableLabel*) self, event);
#line 83 "../src/Widgets/EditableLabel.vala"
	return result;
#line 215 "EditableLabel.c"
}

static gboolean
__lambda10_ (NotejotWidgetsEditableLabel* self,
             GdkEventCrossing* event)
{
	GdkNotifyType _tmp0_;
	GdkWindow* _tmp2_;
	GdkDisplay* _tmp3_;
	GdkCursor* _tmp4_;
	GdkCursor* _tmp5_;
	gboolean result = FALSE;
#line 92 "../src/Widgets/EditableLabel.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 93 "../src/Widgets/EditableLabel.vala"
	_tmp0_ = event->detail;
#line 93 "../src/Widgets/EditableLabel.vala"
	if (_tmp0_ != GDK_NOTIFY_INFERIOR) {
#line 234 "EditableLabel.c"
		GtkRevealer* _tmp1_;
#line 94 "../src/Widgets/EditableLabel.vala"
		_tmp1_ = self->priv->button_revealer;
#line 94 "../src/Widgets/EditableLabel.vala"
		gtk_revealer_set_reveal_child (_tmp1_, FALSE);
#line 240 "EditableLabel.c"
	}
#line 96 "../src/Widgets/EditableLabel.vala"
	_tmp2_ = event->window;
#line 96 "../src/Widgets/EditableLabel.vala"
	_tmp3_ = gdk_display_get_default ();
#line 96 "../src/Widgets/EditableLabel.vala"
	_tmp4_ = gdk_cursor_new_from_name (_tmp3_, "default");
#line 96 "../src/Widgets/EditableLabel.vala"
	_tmp5_ = _tmp4_;
#line 96 "../src/Widgets/EditableLabel.vala"
	gdk_window_set_cursor (_tmp2_, _tmp5_);
#line 96 "../src/Widgets/EditableLabel.vala"
	_g_object_unref0 (_tmp5_);
#line 98 "../src/Widgets/EditableLabel.vala"
	result = FALSE;
#line 98 "../src/Widgets/EditableLabel.vala"
	return result;
#line 258 "EditableLabel.c"
}

static gboolean
___lambda10__gtk_widget_leave_notify_event (GtkWidget* _sender,
                                            GdkEventCrossing* event,
                                            gpointer self)
{
	gboolean result;
	result = __lambda10_ ((NotejotWidgetsEditableLabel*) self, event);
#line 92 "../src/Widgets/EditableLabel.vala"
	return result;
#line 270 "EditableLabel.c"
}

static gboolean
__lambda11_ (NotejotWidgetsEditableLabel* self,
             GdkEventButton* event)
{
	gboolean result = FALSE;
#line 101 "../src/Widgets/EditableLabel.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 102 "../src/Widgets/EditableLabel.vala"
	notejot_widgets_editable_label_set_editing (self, TRUE);
#line 103 "../src/Widgets/EditableLabel.vala"
	result = FALSE;
#line 103 "../src/Widgets/EditableLabel.vala"
	return result;
#line 286 "EditableLabel.c"
}

static gboolean
___lambda11__gtk_widget_button_release_event (GtkWidget* _sender,
                                              GdkEventButton* event,
                                              gpointer self)
{
	gboolean result;
	result = __lambda11_ ((NotejotWidgetsEditableLabel*) self, event);
#line 101 "../src/Widgets/EditableLabel.vala"
	return result;
#line 298 "EditableLabel.c"
}

static void
__lambda12_ (NotejotWidgetsEditableLabel* self)
{
#line 107 "../src/Widgets/EditableLabel.vala"
	notejot_widgets_editable_label_set_editing (self, TRUE);
#line 306 "EditableLabel.c"
}

static void
___lambda12__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 106 "../src/Widgets/EditableLabel.vala"
	__lambda12_ ((NotejotWidgetsEditableLabel*) self);
#line 315 "EditableLabel.c"
}

static void
__lambda13_ (NotejotWidgetsEditableLabel* self)
{
#line 111 "../src/Widgets/EditableLabel.vala"
	notejot_widgets_editable_label_set_editing (self, FALSE);
#line 323 "EditableLabel.c"
}

static void
___lambda13__gtk_entry_activate (GtkEntry* _sender,
                                 gpointer self)
{
#line 110 "../src/Widgets/EditableLabel.vala"
	__lambda13_ ((NotejotWidgetsEditableLabel*) self);
#line 332 "EditableLabel.c"
}

static gboolean
__lambda14_ (NotejotWidgetsEditableLabel* self,
             GdkEventFocus* event)
{
	gboolean result = FALSE;
#line 114 "../src/Widgets/EditableLabel.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 115 "../src/Widgets/EditableLabel.vala"
	notejot_widgets_editable_label_set_editing (self, FALSE);
#line 116 "../src/Widgets/EditableLabel.vala"
	result = FALSE;
#line 116 "../src/Widgets/EditableLabel.vala"
	return result;
#line 348 "EditableLabel.c"
}

static gboolean
___lambda14__gtk_widget_focus_out_event (GtkWidget* _sender,
                                         GdkEventFocus* event,
                                         gpointer self)
{
	gboolean result;
	result = __lambda14_ ((NotejotWidgetsEditableLabel*) self, event);
#line 114 "../src/Widgets/EditableLabel.vala"
	return result;
#line 360 "EditableLabel.c"
}

static void
__lambda15_ (NotejotWidgetsEditableLabel* self,
             GtkEntryIconPosition p0,
             GdkEvent* p1)
{
#line 119 "../src/Widgets/EditableLabel.vala"
	g_return_if_fail (p1 != NULL);
#line 120 "../src/Widgets/EditableLabel.vala"
	if (p0 == GTK_ENTRY_ICON_SECONDARY) {
#line 121 "../src/Widgets/EditableLabel.vala"
		notejot_widgets_editable_label_set_editing (self, FALSE);
#line 374 "EditableLabel.c"
	}
}

static void
___lambda15__gtk_entry_icon_release (GtkEntry* _sender,
                                     GtkEntryIconPosition icon_pos,
                                     GdkEvent* event,
                                     gpointer self)
{
#line 119 "../src/Widgets/EditableLabel.vala"
	__lambda15_ ((NotejotWidgetsEditableLabel*) self, icon_pos, event);
#line 386 "EditableLabel.c"
}

NotejotWidgetsEditableLabel*
notejot_widgets_editable_label_construct (GType object_type,
                                          NotejotMainWindow* win,
                                          const gchar* title_name)
{
	NotejotWidgetsEditableLabel * self = NULL;
	NotejotMainWindow* _tmp0_;
	GdkEventMask _tmp1_;
	GdkEventMask _tmp2_;
	GdkEventMask _tmp3_;
	GdkEventMask _tmp4_;
	GdkEventMask _tmp5_;
	GdkEventMask _tmp6_;
	GtkLabel* _tmp7_;
	GtkButton* _tmp8_;
	GtkEntry* _tmp9_;
	GtkEntry* _tmp10_;
	GtkEntry* _tmp11_;
#line 73 "../src/Widgets/EditableLabel.vala"
	g_return_val_if_fail (win != NULL, NULL);
#line 73 "../src/Widgets/EditableLabel.vala"
	self = (NotejotWidgetsEditableLabel*) g_object_new (object_type, NULL);
#line 74 "../src/Widgets/EditableLabel.vala"
	_tmp0_ = _g_object_ref0 (win);
#line 74 "../src/Widgets/EditableLabel.vala"
	_g_object_unref0 (self->priv->win);
#line 74 "../src/Widgets/EditableLabel.vala"
	self->priv->win = _tmp0_;
#line 75 "../src/Widgets/EditableLabel.vala"
	_tmp1_ = gtk_widget_get_events ((GtkWidget*) self);
#line 75 "../src/Widgets/EditableLabel.vala"
	_tmp2_ = _tmp1_;
#line 75 "../src/Widgets/EditableLabel.vala"
	gtk_widget_set_events ((GtkWidget*) self, _tmp2_ | GDK_ENTER_NOTIFY_MASK);
#line 76 "../src/Widgets/EditableLabel.vala"
	_tmp3_ = gtk_widget_get_events ((GtkWidget*) self);
#line 76 "../src/Widgets/EditableLabel.vala"
	_tmp4_ = _tmp3_;
#line 76 "../src/Widgets/EditableLabel.vala"
	gtk_widget_set_events ((GtkWidget*) self, _tmp4_ | GDK_LEAVE_NOTIFY_MASK);
#line 77 "../src/Widgets/EditableLabel.vala"
	_tmp5_ = gtk_widget_get_events ((GtkWidget*) self);
#line 77 "../src/Widgets/EditableLabel.vala"
	_tmp6_ = _tmp5_;
#line 77 "../src/Widgets/EditableLabel.vala"
	gtk_widget_set_events ((GtkWidget*) self, _tmp6_ | GDK_BUTTON_PRESS_MASK);
#line 79 "../src/Widgets/EditableLabel.vala"
	_tmp7_ = self->title;
#line 79 "../src/Widgets/EditableLabel.vala"
	gtk_label_set_label (_tmp7_, title_name);
#line 81 "../src/Widgets/EditableLabel.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 83 "../src/Widgets/EditableLabel.vala"
	g_signal_connect_object ((GtkWidget*) self, "enter-notify-event", (GCallback) ___lambda9__gtk_widget_enter_notify_event, self, 0);
#line 92 "../src/Widgets/EditableLabel.vala"
	g_signal_connect_object ((GtkWidget*) self, "leave-notify-event", (GCallback) ___lambda10__gtk_widget_leave_notify_event, self, 0);
#line 101 "../src/Widgets/EditableLabel.vala"
	g_signal_connect_object ((GtkWidget*) self, "button-release-event", (GCallback) ___lambda11__gtk_widget_button_release_event, self, 0);
#line 106 "../src/Widgets/EditableLabel.vala"
	_tmp8_ = self->priv->edit_button;
#line 106 "../src/Widgets/EditableLabel.vala"
	g_signal_connect_object (_tmp8_, "clicked", (GCallback) ___lambda12__gtk_button_clicked, self, 0);
#line 110 "../src/Widgets/EditableLabel.vala"
	_tmp9_ = self->entry;
#line 110 "../src/Widgets/EditableLabel.vala"
	g_signal_connect_object (_tmp9_, "activate", (GCallback) ___lambda13__gtk_entry_activate, self, 0);
#line 114 "../src/Widgets/EditableLabel.vala"
	_tmp10_ = self->entry;
#line 114 "../src/Widgets/EditableLabel.vala"
	g_signal_connect_object ((GtkWidget*) _tmp10_, "focus-out-event", (GCallback) ___lambda14__gtk_widget_focus_out_event, self, 0);
#line 119 "../src/Widgets/EditableLabel.vala"
	_tmp11_ = self->entry;
#line 119 "../src/Widgets/EditableLabel.vala"
	g_signal_connect_object (_tmp11_, "icon-release", (GCallback) ___lambda15__gtk_entry_icon_release, self, 0);
#line 73 "../src/Widgets/EditableLabel.vala"
	return self;
#line 465 "EditableLabel.c"
}

NotejotWidgetsEditableLabel*
notejot_widgets_editable_label_new (NotejotMainWindow* win,
                                    const gchar* title_name)
{
#line 73 "../src/Widgets/EditableLabel.vala"
	return notejot_widgets_editable_label_construct (NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, win, title_name);
#line 474 "EditableLabel.c"
}

const gchar*
notejot_widgets_editable_label_get_text (NotejotWidgetsEditableLabel* self)
{
	const gchar* result;
	GtkLabel* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
#line 47 "../src/Widgets/EditableLabel.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 48 "../src/Widgets/EditableLabel.vala"
	_tmp0_ = self->title;
#line 48 "../src/Widgets/EditableLabel.vala"
	_tmp1_ = gtk_label_get_label (_tmp0_);
#line 48 "../src/Widgets/EditableLabel.vala"
	_tmp2_ = _tmp1_;
#line 48 "../src/Widgets/EditableLabel.vala"
	result = _tmp2_;
#line 48 "../src/Widgets/EditableLabel.vala"
	return result;
#line 496 "EditableLabel.c"
}

void
notejot_widgets_editable_label_set_text (NotejotWidgetsEditableLabel* self,
                                         const gchar* value)
{
	GtkLabel* _tmp0_;
#line 51 "../src/Widgets/EditableLabel.vala"
	g_return_if_fail (self != NULL);
#line 52 "../src/Widgets/EditableLabel.vala"
	_tmp0_ = self->title;
#line 52 "../src/Widgets/EditableLabel.vala"
	gtk_label_set_label (_tmp0_, value);
#line 51 "../src/Widgets/EditableLabel.vala"
	g_object_notify_by_pspec ((GObject *) self, notejot_widgets_editable_label_properties[NOTEJOT_WIDGETS_EDITABLE_LABEL_TEXT_PROPERTY]);
#line 512 "EditableLabel.c"
}

static gchar*
string_strip (const gchar* self)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* result = NULL;
#line 1359 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1360 "glib-2.0.vapi"
	_tmp0_ = g_strdup (self);
#line 1360 "glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1361 "glib-2.0.vapi"
	g_strstrip (_result_);
#line 1362 "glib-2.0.vapi"
	result = _result_;
#line 1362 "glib-2.0.vapi"
	return result;
#line 533 "EditableLabel.c"
}

static void
notejot_widgets_editable_label_set_editing (NotejotWidgetsEditableLabel* self,
                                            gboolean value)
{
#line 57 "../src/Widgets/EditableLabel.vala"
	g_return_if_fail (self != NULL);
#line 58 "../src/Widgets/EditableLabel.vala"
	if (value) {
#line 544 "EditableLabel.c"
		GtkEntry* _tmp0_;
		GtkLabel* _tmp1_;
		const gchar* _tmp2_;
		const gchar* _tmp3_;
		GtkStack* _tmp4_;
		GtkEntry* _tmp5_;
		GtkEntry* _tmp6_;
#line 59 "../src/Widgets/EditableLabel.vala"
		_tmp0_ = self->entry;
#line 59 "../src/Widgets/EditableLabel.vala"
		_tmp1_ = self->title;
#line 59 "../src/Widgets/EditableLabel.vala"
		_tmp2_ = gtk_label_get_label (_tmp1_);
#line 59 "../src/Widgets/EditableLabel.vala"
		_tmp3_ = _tmp2_;
#line 59 "../src/Widgets/EditableLabel.vala"
		gtk_entry_set_text (_tmp0_, _tmp3_);
#line 60 "../src/Widgets/EditableLabel.vala"
		_tmp4_ = self->priv->stack;
#line 60 "../src/Widgets/EditableLabel.vala"
		_tmp5_ = self->entry;
#line 60 "../src/Widgets/EditableLabel.vala"
		gtk_stack_set_visible_child (_tmp4_, (GtkWidget*) _tmp5_);
#line 61 "../src/Widgets/EditableLabel.vala"
		_tmp6_ = self->entry;
#line 61 "../src/Widgets/EditableLabel.vala"
		gtk_widget_grab_focus ((GtkWidget*) _tmp6_);
#line 572 "EditableLabel.c"
	} else {
		gboolean _tmp7_ = FALSE;
		GtkEntry* _tmp8_;
		const gchar* _tmp9_;
		const gchar* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		gboolean _tmp13_;
		GtkStack* _tmp27_;
		GtkBox* _tmp28_;
#line 63 "../src/Widgets/EditableLabel.vala"
		_tmp8_ = self->entry;
#line 63 "../src/Widgets/EditableLabel.vala"
		_tmp9_ = gtk_entry_get_text (_tmp8_);
#line 63 "../src/Widgets/EditableLabel.vala"
		_tmp10_ = _tmp9_;
#line 63 "../src/Widgets/EditableLabel.vala"
		_tmp11_ = string_strip (_tmp10_);
#line 63 "../src/Widgets/EditableLabel.vala"
		_tmp12_ = _tmp11_;
#line 63 "../src/Widgets/EditableLabel.vala"
		_tmp13_ = g_strcmp0 (_tmp12_, "") != 0;
#line 63 "../src/Widgets/EditableLabel.vala"
		_g_free0 (_tmp12_);
#line 63 "../src/Widgets/EditableLabel.vala"
		if (_tmp13_) {
#line 599 "EditableLabel.c"
			GtkLabel* _tmp14_;
			const gchar* _tmp15_;
			const gchar* _tmp16_;
			GtkEntry* _tmp17_;
			const gchar* _tmp18_;
			const gchar* _tmp19_;
#line 63 "../src/Widgets/EditableLabel.vala"
			_tmp14_ = self->title;
#line 63 "../src/Widgets/EditableLabel.vala"
			_tmp15_ = gtk_label_get_label (_tmp14_);
#line 63 "../src/Widgets/EditableLabel.vala"
			_tmp16_ = _tmp15_;
#line 63 "../src/Widgets/EditableLabel.vala"
			_tmp17_ = self->entry;
#line 63 "../src/Widgets/EditableLabel.vala"
			_tmp18_ = gtk_entry_get_text (_tmp17_);
#line 63 "../src/Widgets/EditableLabel.vala"
			_tmp19_ = _tmp18_;
#line 63 "../src/Widgets/EditableLabel.vala"
			_tmp7_ = g_strcmp0 (_tmp16_, _tmp19_) != 0;
#line 620 "EditableLabel.c"
		} else {
#line 63 "../src/Widgets/EditableLabel.vala"
			_tmp7_ = FALSE;
#line 624 "EditableLabel.c"
		}
#line 63 "../src/Widgets/EditableLabel.vala"
		if (_tmp7_) {
#line 628 "EditableLabel.c"
			GtkLabel* _tmp20_;
			GtkEntry* _tmp21_;
			const gchar* _tmp22_;
			const gchar* _tmp23_;
			GtkEntry* _tmp24_;
			const gchar* _tmp25_;
			const gchar* _tmp26_;
#line 64 "../src/Widgets/EditableLabel.vala"
			_tmp20_ = self->title;
#line 64 "../src/Widgets/EditableLabel.vala"
			_tmp21_ = self->entry;
#line 64 "../src/Widgets/EditableLabel.vala"
			_tmp22_ = gtk_entry_get_text (_tmp21_);
#line 64 "../src/Widgets/EditableLabel.vala"
			_tmp23_ = _tmp22_;
#line 64 "../src/Widgets/EditableLabel.vala"
			gtk_label_set_label (_tmp20_, _tmp23_);
#line 65 "../src/Widgets/EditableLabel.vala"
			_tmp24_ = self->entry;
#line 65 "../src/Widgets/EditableLabel.vala"
			_tmp25_ = gtk_entry_get_text (_tmp24_);
#line 65 "../src/Widgets/EditableLabel.vala"
			_tmp26_ = _tmp25_;
#line 65 "../src/Widgets/EditableLabel.vala"
			g_signal_emit (self, notejot_widgets_editable_label_signals[NOTEJOT_WIDGETS_EDITABLE_LABEL_CHANGED_SIGNAL], 0, _tmp26_);
#line 654 "EditableLabel.c"
		}
#line 68 "../src/Widgets/EditableLabel.vala"
		_tmp27_ = self->priv->stack;
#line 68 "../src/Widgets/EditableLabel.vala"
		_tmp28_ = self->priv->grid;
#line 68 "../src/Widgets/EditableLabel.vala"
		gtk_stack_set_visible_child (_tmp27_, (GtkWidget*) _tmp28_);
#line 662 "EditableLabel.c"
	}
}

static void
notejot_widgets_editable_label_class_init (NotejotWidgetsEditableLabelClass * klass,
                                           gpointer klass_data)
{
#line 24 "../src/Widgets/EditableLabel.vala"
	notejot_widgets_editable_label_parent_class = g_type_class_peek_parent (klass);
#line 24 "../src/Widgets/EditableLabel.vala"
	g_type_class_adjust_private_offset (klass, &NotejotWidgetsEditableLabel_private_offset);
#line 24 "../src/Widgets/EditableLabel.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_notejot_widgets_editable_label_get_property;
#line 24 "../src/Widgets/EditableLabel.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_notejot_widgets_editable_label_set_property;
#line 24 "../src/Widgets/EditableLabel.vala"
	G_OBJECT_CLASS (klass)->finalize = notejot_widgets_editable_label_finalize;
#line 24 "../src/Widgets/EditableLabel.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), NOTEJOT_WIDGETS_EDITABLE_LABEL_TEXT_PROPERTY, notejot_widgets_editable_label_properties[NOTEJOT_WIDGETS_EDITABLE_LABEL_TEXT_PROPERTY] = g_param_spec_string ("text", "text", "text", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 24 "../src/Widgets/EditableLabel.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/io/github/lainsce/Notejot/editable_label.ui");
#line 24 "../src/Widgets/EditableLabel.vala"
	notejot_widgets_editable_label_signals[NOTEJOT_WIDGETS_EDITABLE_LABEL_CHANGED_SIGNAL] = g_signal_new ("changed", NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
#line 24 "../src/Widgets/EditableLabel.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "title", FALSE, G_STRUCT_OFFSET (NotejotWidgetsEditableLabel, title));
#line 24 "../src/Widgets/EditableLabel.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "entry", FALSE, G_STRUCT_OFFSET (NotejotWidgetsEditableLabel, entry));
#line 24 "../src/Widgets/EditableLabel.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "stack", FALSE, NotejotWidgetsEditableLabel_private_offset + G_STRUCT_OFFSET (NotejotWidgetsEditableLabelPrivate, stack));
#line 24 "../src/Widgets/EditableLabel.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "grid", FALSE, NotejotWidgetsEditableLabel_private_offset + G_STRUCT_OFFSET (NotejotWidgetsEditableLabelPrivate, grid));
#line 24 "../src/Widgets/EditableLabel.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "edit_button", FALSE, NotejotWidgetsEditableLabel_private_offset + G_STRUCT_OFFSET (NotejotWidgetsEditableLabelPrivate, edit_button));
#line 24 "../src/Widgets/EditableLabel.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "button_revealer", FALSE, NotejotWidgetsEditableLabel_private_offset + G_STRUCT_OFFSET (NotejotWidgetsEditableLabelPrivate, button_revealer));
#line 698 "EditableLabel.c"
}

static void
notejot_widgets_editable_label_instance_init (NotejotWidgetsEditableLabel * self,
                                              gpointer klass)
{
#line 24 "../src/Widgets/EditableLabel.vala"
	self->priv = notejot_widgets_editable_label_get_instance_private (self);
#line 24 "../src/Widgets/EditableLabel.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 709 "EditableLabel.c"
}

static void
notejot_widgets_editable_label_finalize (GObject * obj)
{
	NotejotWidgetsEditableLabel * self;
#line 24 "../src/Widgets/EditableLabel.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabel);
#line 25 "../src/Widgets/EditableLabel.vala"
	_g_object_unref0 (self->priv->win);
#line 29 "../src/Widgets/EditableLabel.vala"
	_g_object_unref0 (self->title);
#line 32 "../src/Widgets/EditableLabel.vala"
	_g_object_unref0 (self->entry);
#line 35 "../src/Widgets/EditableLabel.vala"
	_g_object_unref0 (self->priv->stack);
#line 38 "../src/Widgets/EditableLabel.vala"
	_g_object_unref0 (self->priv->grid);
#line 41 "../src/Widgets/EditableLabel.vala"
	_g_object_unref0 (self->priv->edit_button);
#line 44 "../src/Widgets/EditableLabel.vala"
	_g_object_unref0 (self->priv->button_revealer);
#line 24 "../src/Widgets/EditableLabel.vala"
	G_OBJECT_CLASS (notejot_widgets_editable_label_parent_class)->finalize (obj);
#line 734 "EditableLabel.c"
}

static GType
notejot_widgets_editable_label_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (NotejotWidgetsEditableLabelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) notejot_widgets_editable_label_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NotejotWidgetsEditableLabel), 0, (GInstanceInitFunc) notejot_widgets_editable_label_instance_init, NULL };
	GType notejot_widgets_editable_label_type_id;
	notejot_widgets_editable_label_type_id = g_type_register_static (gtk_event_box_get_type (), "NotejotWidgetsEditableLabel", &g_define_type_info, 0);
	NotejotWidgetsEditableLabel_private_offset = g_type_add_instance_private (notejot_widgets_editable_label_type_id, sizeof (NotejotWidgetsEditableLabelPrivate));
	return notejot_widgets_editable_label_type_id;
}

GType
notejot_widgets_editable_label_get_type (void)
{
	static volatile gsize notejot_widgets_editable_label_type_id__volatile = 0;
	if (g_once_init_enter (&notejot_widgets_editable_label_type_id__volatile)) {
		GType notejot_widgets_editable_label_type_id;
		notejot_widgets_editable_label_type_id = notejot_widgets_editable_label_get_type_once ();
		g_once_init_leave (&notejot_widgets_editable_label_type_id__volatile, notejot_widgets_editable_label_type_id);
	}
	return notejot_widgets_editable_label_type_id__volatile;
}

static void
_vala_notejot_widgets_editable_label_get_property (GObject * object,
                                                   guint property_id,
                                                   GValue * value,
                                                   GParamSpec * pspec)
{
	NotejotWidgetsEditableLabel * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabel);
#line 24 "../src/Widgets/EditableLabel.vala"
	switch (property_id) {
#line 24 "../src/Widgets/EditableLabel.vala"
		case NOTEJOT_WIDGETS_EDITABLE_LABEL_TEXT_PROPERTY:
#line 24 "../src/Widgets/EditableLabel.vala"
		g_value_set_string (value, notejot_widgets_editable_label_get_text (self));
#line 24 "../src/Widgets/EditableLabel.vala"
		break;
#line 775 "EditableLabel.c"
		default:
#line 24 "../src/Widgets/EditableLabel.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "../src/Widgets/EditableLabel.vala"
		break;
#line 781 "EditableLabel.c"
	}
}

static void
_vala_notejot_widgets_editable_label_set_property (GObject * object,
                                                   guint property_id,
                                                   const GValue * value,
                                                   GParamSpec * pspec)
{
	NotejotWidgetsEditableLabel * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabel);
#line 24 "../src/Widgets/EditableLabel.vala"
	switch (property_id) {
#line 24 "../src/Widgets/EditableLabel.vala"
		case NOTEJOT_WIDGETS_EDITABLE_LABEL_TEXT_PROPERTY:
#line 24 "../src/Widgets/EditableLabel.vala"
		notejot_widgets_editable_label_set_text (self, g_value_get_string (value));
#line 24 "../src/Widgets/EditableLabel.vala"
		break;
#line 801 "EditableLabel.c"
		default:
#line 24 "../src/Widgets/EditableLabel.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "../src/Widgets/EditableLabel.vala"
		break;
#line 807 "EditableLabel.c"
	}
}

