/* Note.c generated by valac 0.50.3, the Vala compiler
 * generated from Note.vala, do not modify */

/*
* Copyright (C) 2017-2021 Lains
*
* This program is free software; you can redistribute it &&/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 3 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*/

#include <handy.h>
#include <glib-object.h>
#include <webkit2/webkit2.h>
#include <gtk/gtk.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <float.h>
#include <math.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>

#define NOTEJOT_WIDGETS_TYPE_NOTE (notejot_widgets_note_get_type ())
#define NOTEJOT_WIDGETS_NOTE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote))
#define NOTEJOT_WIDGETS_NOTE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNoteClass))
#define NOTEJOT_WIDGETS_IS_NOTE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_NOTE))
#define NOTEJOT_WIDGETS_IS_NOTE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_NOTE))
#define NOTEJOT_WIDGETS_NOTE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNoteClass))

typedef struct _NotejotWidgetsNote NotejotWidgetsNote;
typedef struct _NotejotWidgetsNoteClass NotejotWidgetsNoteClass;
typedef struct _NotejotWidgetsNotePrivate NotejotWidgetsNotePrivate;

#define NOTEJOT_WIDGETS_TYPE_TEXT_FIELD (notejot_widgets_text_field_get_type ())
#define NOTEJOT_WIDGETS_TEXT_FIELD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD, NotejotWidgetsTextField))
#define NOTEJOT_WIDGETS_TEXT_FIELD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD, NotejotWidgetsTextFieldClass))
#define NOTEJOT_WIDGETS_IS_TEXT_FIELD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD))
#define NOTEJOT_WIDGETS_IS_TEXT_FIELD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD))
#define NOTEJOT_WIDGETS_TEXT_FIELD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD, NotejotWidgetsTextFieldClass))

typedef struct _NotejotWidgetsTextField NotejotWidgetsTextField;
typedef struct _NotejotWidgetsTextFieldClass NotejotWidgetsTextFieldClass;

#define NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL (notejot_widgets_editable_label_get_type ())
#define NOTEJOT_WIDGETS_EDITABLE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabel))
#define NOTEJOT_WIDGETS_EDITABLE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabelClass))
#define NOTEJOT_WIDGETS_IS_EDITABLE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL))
#define NOTEJOT_WIDGETS_IS_EDITABLE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL))
#define NOTEJOT_WIDGETS_EDITABLE_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabelClass))

typedef struct _NotejotWidgetsEditableLabel NotejotWidgetsEditableLabel;
typedef struct _NotejotWidgetsEditableLabelClass NotejotWidgetsEditableLabelClass;

#define NOTEJOT_TYPE_MAIN_WINDOW (notejot_main_window_get_type ())
#define NOTEJOT_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindow))
#define NOTEJOT_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindowClass))
#define NOTEJOT_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_TYPE_MAIN_WINDOW))
#define NOTEJOT_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_TYPE_MAIN_WINDOW))
#define NOTEJOT_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindowClass))

typedef struct _NotejotMainWindow NotejotMainWindow;
typedef struct _NotejotMainWindowClass NotejotMainWindowClass;
enum  {
	NOTEJOT_WIDGETS_NOTE_0_PROPERTY,
	NOTEJOT_WIDGETS_NOTE_NUM_PROPERTIES
};
static GParamSpec* notejot_widgets_note_properties[NOTEJOT_WIDGETS_NOTE_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block5Data Block5Data;
typedef struct _NotejotWidgetsTextFieldPrivate NotejotWidgetsTextFieldPrivate;
typedef struct _NotejotWidgetsEditableLabelPrivate NotejotWidgetsEditableLabelPrivate;

#define NOTEJOT_WIDGETS_TYPE_FORMAT_BAR (notejot_widgets_format_bar_get_type ())
#define NOTEJOT_WIDGETS_FORMAT_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_FORMAT_BAR, NotejotWidgetsFormatBar))
#define NOTEJOT_WIDGETS_FORMAT_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_FORMAT_BAR, NotejotWidgetsFormatBarClass))
#define NOTEJOT_WIDGETS_IS_FORMAT_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_FORMAT_BAR))
#define NOTEJOT_WIDGETS_IS_FORMAT_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_FORMAT_BAR))
#define NOTEJOT_WIDGETS_FORMAT_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_FORMAT_BAR, NotejotWidgetsFormatBarClass))

typedef struct _NotejotWidgetsFormatBar NotejotWidgetsFormatBar;
typedef struct _NotejotWidgetsFormatBarClass NotejotWidgetsFormatBarClass;
typedef struct _NotejotWidgetsFormatBarPrivate NotejotWidgetsFormatBarPrivate;
typedef struct _NotejotMainWindowPrivate NotejotMainWindowPrivate;

#define NOTEJOT_WIDGETS_TYPE_DIALOG (notejot_widgets_dialog_get_type ())
#define NOTEJOT_WIDGETS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialog))
#define NOTEJOT_WIDGETS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialogClass))
#define NOTEJOT_WIDGETS_IS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG))
#define NOTEJOT_WIDGETS_IS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_DIALOG))
#define NOTEJOT_WIDGETS_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialogClass))

typedef struct _NotejotWidgetsDialog NotejotWidgetsDialog;
typedef struct _NotejotWidgetsDialogClass NotejotWidgetsDialogClass;

#define NOTEJOT_WIDGETS_TYPE_SETTING_MENU (notejot_widgets_setting_menu_get_type ())
#define NOTEJOT_WIDGETS_SETTING_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenu))
#define NOTEJOT_WIDGETS_SETTING_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenuClass))
#define NOTEJOT_WIDGETS_IS_SETTING_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU))
#define NOTEJOT_WIDGETS_IS_SETTING_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_SETTING_MENU))
#define NOTEJOT_WIDGETS_SETTING_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenuClass))

typedef struct _NotejotWidgetsSettingMenu NotejotWidgetsSettingMenu;
typedef struct _NotejotWidgetsSettingMenuClass NotejotWidgetsSettingMenuClass;

#define NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON (notejot_widgets_header_bar_button_get_type ())
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButton))
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButtonClass))
#define NOTEJOT_WIDGETS_IS_HEADER_BAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON))
#define NOTEJOT_WIDGETS_IS_HEADER_BAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON))
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButtonClass))

typedef struct _NotejotWidgetsHeaderBarButton NotejotWidgetsHeaderBarButton;
typedef struct _NotejotWidgetsHeaderBarButtonClass NotejotWidgetsHeaderBarButtonClass;

#define NOTEJOT_VIEWS_TYPE_LIST_VIEW (notejot_views_list_view_get_type ())
#define NOTEJOT_VIEWS_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListView))
#define NOTEJOT_VIEWS_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListViewClass))
#define NOTEJOT_VIEWS_IS_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW))
#define NOTEJOT_VIEWS_IS_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_VIEWS_TYPE_LIST_VIEW))
#define NOTEJOT_VIEWS_LIST_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListViewClass))

typedef struct _NotejotViewsListView NotejotViewsListView;
typedef struct _NotejotViewsListViewClass NotejotViewsListViewClass;

#define NOTEJOT_VIEWS_TYPE_TRASH_VIEW (notejot_views_trash_view_get_type ())
#define NOTEJOT_VIEWS_TRASH_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashView))
#define NOTEJOT_VIEWS_TRASH_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashViewClass))
#define NOTEJOT_VIEWS_IS_TRASH_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW))
#define NOTEJOT_VIEWS_IS_TRASH_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_VIEWS_TYPE_TRASH_VIEW))
#define NOTEJOT_VIEWS_TRASH_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashViewClass))

typedef struct _NotejotViewsTrashView NotejotViewsTrashView;
typedef struct _NotejotViewsTrashViewClass NotejotViewsTrashViewClass;

#define NOTEJOT_TYPE_TASK_MANAGER (notejot_task_manager_get_type ())
#define NOTEJOT_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManager))
#define NOTEJOT_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManagerClass))
#define NOTEJOT_IS_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_TYPE_TASK_MANAGER))
#define NOTEJOT_IS_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_TYPE_TASK_MANAGER))
#define NOTEJOT_TASK_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManagerClass))

typedef struct _NotejotTaskManager NotejotTaskManager;
typedef struct _NotejotTaskManagerClass NotejotTaskManagerClass;
#define _g_match_info_unref0(var) ((var == NULL) ? NULL : (var = (g_match_info_unref (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER (notejot_widgets_note_menu_popover_get_type ())
#define NOTEJOT_WIDGETS_NOTE_MENU_POPOVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER, NotejotWidgetsNoteMenuPopover))
#define NOTEJOT_WIDGETS_NOTE_MENU_POPOVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER, NotejotWidgetsNoteMenuPopoverClass))
#define NOTEJOT_WIDGETS_IS_NOTE_MENU_POPOVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER))
#define NOTEJOT_WIDGETS_IS_NOTE_MENU_POPOVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER))
#define NOTEJOT_WIDGETS_NOTE_MENU_POPOVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER, NotejotWidgetsNoteMenuPopoverClass))

typedef struct _NotejotWidgetsNoteMenuPopover NotejotWidgetsNoteMenuPopover;
typedef struct _NotejotWidgetsNoteMenuPopoverClass NotejotWidgetsNoteMenuPopoverClass;
typedef struct _NotejotWidgetsNoteMenuPopoverPrivate NotejotWidgetsNoteMenuPopoverPrivate;

struct _NotejotWidgetsNote {
	HdyActionRow parent_instance;
	NotejotWidgetsNotePrivate * priv;
	NotejotWidgetsTextField* textfield;
	NotejotWidgetsEditableLabel* titlelabel;
	gint uid;
	gchar* title;
	gchar* subtitle;
	gchar* text;
	gchar* color;
};

struct _NotejotWidgetsNoteClass {
	HdyActionRowClass parent_class;
};

struct _NotejotWidgetsNotePrivate {
	NotejotMainWindow* win;
	GtkCssProvider* css_provider;
};

struct _Block5Data {
	int _ref_count_;
	NotejotWidgetsNote* self;
	GtkImage* icon;
	GtkLabel* subtitlelabel;
	GtkGrid* note_grid;
	NotejotMainWindow* win;
};

struct _NotejotWidgetsTextField {
	WebKitWebView parent_instance;
	NotejotWidgetsTextFieldPrivate * priv;
	NotejotMainWindow* win;
	gchar* text;
	NotejotWidgetsNote* controller;
};

struct _NotejotWidgetsTextFieldClass {
	WebKitWebViewClass parent_class;
};

struct _NotejotWidgetsEditableLabel {
	GtkEventBox parent_instance;
	NotejotWidgetsEditableLabelPrivate * priv;
	GtkLabel* title;
	GtkEntry* entry;
};

struct _NotejotWidgetsEditableLabelClass {
	GtkEventBoxClass parent_class;
};

struct _NotejotWidgetsFormatBar {
	GtkActionBar parent_instance;
	NotejotWidgetsFormatBarPrivate * priv;
	NotejotWidgetsTextField* controller;
};

struct _NotejotWidgetsFormatBarClass {
	GtkActionBarClass parent_class;
};

struct _NotejotMainWindow {
	HdyApplicationWindow parent_instance;
	NotejotMainWindowPrivate * priv;
	GtkButton* new_button;
	GtkButton* back_button;
	GtkButton* welcome_new_button;
	GtkMenuButton* menu_button;
	GtkBox* grid;
	GtkBox* sgrid;
	GtkBox* welcome_view;
	GtkBox* empty_state;
	HdyLeaflet* leaflet;
	GtkStack* main_stack;
	GtkStack* sidebar_stack;
	GtkStack* titlebar_stack;
	HdyHeaderBar* titlebar;
	HdyHeaderBar* stitlebar;
	HdyHeaderBar* welcome_titlebar;
	HdyHeaderGroup* titlegroup;
	GtkScrolledWindow* trash_scroller;
	GtkScrolledWindow* list_scroller;
	NotejotWidgetsDialog* dialog;
	NotejotWidgetsSettingMenu* settingmenu;
	NotejotWidgetsHeaderBarButton* sidebar_title_button;
	NotejotViewsListView* listview;
	NotejotViewsTrashView* trashview;
	NotejotTaskManager* tm;
	gboolean pinned;
};

struct _NotejotMainWindowClass {
	HdyApplicationWindowClass parent_class;
};

struct _NotejotWidgetsNoteMenuPopover {
	GtkPopover parent_instance;
	NotejotWidgetsNoteMenuPopoverPrivate * priv;
	GtkModelButton* delete_note_button;
	GtkRadioButton* color_button_red;
	GtkRadioButton* color_button_orange;
	GtkRadioButton* color_button_yellow;
	GtkRadioButton* color_button_green;
	GtkRadioButton* color_button_blue;
	GtkRadioButton* color_button_purple;
	GtkRadioButton* color_button_brown;
	GtkRadioButton* color_button_reset;
};

struct _NotejotWidgetsNoteMenuPopoverClass {
	GtkPopoverClass parent_class;
};

static gint NotejotWidgetsNote_private_offset;
static gpointer notejot_widgets_note_parent_class = NULL;
static gint notejot_widgets_note_uid_counter;
static gint notejot_widgets_note_uid_counter = 0;
extern GSettings* notejot_application_gsettings;

GType notejot_widgets_note_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsNote, g_object_unref)
GType notejot_widgets_text_field_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsTextField, g_object_unref)
GType notejot_widgets_editable_label_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsEditableLabel, g_object_unref)
GType notejot_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotMainWindow, g_object_unref)
NotejotWidgetsNote* notejot_widgets_note_new (NotejotMainWindow* win,
                                              const gchar* title,
                                              const gchar* subtitle,
                                              const gchar* text,
                                              const gchar* color);
NotejotWidgetsNote* notejot_widgets_note_construct (GType object_type,
                                                    NotejotMainWindow* win,
                                                    const gchar* title,
                                                    const gchar* subtitle,
                                                    const gchar* text,
                                                    const gchar* color);
static Block5Data* block5_data_ref (Block5Data* _data5_);
static void block5_data_unref (void * _userdata_);
void notejot_widgets_note_update_theme (NotejotWidgetsNote* self,
                                        const gchar* color);
NotejotWidgetsTextField* notejot_widgets_text_field_new (NotejotMainWindow* win);
NotejotWidgetsTextField* notejot_widgets_text_field_construct (GType object_type,
                                                               NotejotMainWindow* win);
void notejot_widgets_text_field_update_html_view (NotejotWidgetsTextField* self,
                                                  GAsyncReadyCallback _callback_,
                                                  gpointer _user_data_);
void notejot_widgets_text_field_update_html_view_finish (NotejotWidgetsTextField* self,
                                                         GAsyncResult* _res_);
NotejotWidgetsEditableLabel* notejot_widgets_editable_label_new (NotejotMainWindow* win,
                                                                 const gchar* title_name);
NotejotWidgetsEditableLabel* notejot_widgets_editable_label_construct (GType object_type,
                                                                       NotejotMainWindow* win,
                                                                       const gchar* title_name);
GType notejot_widgets_format_bar_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsFormatBar, g_object_unref)
NotejotWidgetsFormatBar* notejot_widgets_format_bar_new (NotejotMainWindow* win);
NotejotWidgetsFormatBar* notejot_widgets_format_bar_construct (GType object_type,
                                                               NotejotMainWindow* win);
GType notejot_widgets_dialog_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsDialog, g_object_unref)
GType notejot_widgets_setting_menu_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsSettingMenu, g_object_unref)
GType notejot_widgets_header_bar_button_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsHeaderBarButton, g_object_unref)
GType notejot_views_list_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotViewsListView, g_object_unref)
GType notejot_views_trash_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotViewsTrashView, g_object_unref)
gpointer notejot_task_manager_ref (gpointer instance);
void notejot_task_manager_unref (gpointer instance);
GParamSpec* notejot_param_spec_task_manager (const gchar* name,
                                             const gchar* nick,
                                             const gchar* blurb,
                                             GType object_type,
                                             GParamFlags flags);
void notejot_value_set_task_manager (GValue* value,
                                     gpointer v_object);
void notejot_value_take_task_manager (GValue* value,
                                      gpointer v_object);
gpointer notejot_value_get_task_manager (const GValue* value);
GType notejot_task_manager_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotTaskManager, notejot_task_manager_unref)
static void __lambda44_ (Block5Data* _data5_);
const gchar* notejot_widgets_editable_label_get_text (NotejotWidgetsEditableLabel* self);
void notejot_task_manager_save_notes (NotejotTaskManager* self,
                                      GAsyncReadyCallback _callback_,
                                      gpointer _user_data_);
void notejot_task_manager_save_notes_finish (NotejotTaskManager* self,
                                             GAsyncResult* _res_);
static void ___lambda44__notejot_widgets_editable_label_changed (NotejotWidgetsEditableLabel* _sender,
                                                          const gchar* new_title,
                                                          gpointer self);
static gboolean __lambda45_ (Block5Data* _data5_);
gchar* notejot_utils_get_relative_datetime (GDateTime* date_time);
static gboolean ___lambda45__gsource_func (gpointer self);
static void __lambda46_ (Block5Data* _data5_);
static void ___lambda46__g_object_notify (GObject* _sender,
                                   GParamSpec* pspec,
                                   gpointer self);
static void __lambda47_ (Block5Data* _data5_);
static void ___lambda47__g_settings_changed (GSettings* _sender,
                                      const gchar* key,
                                      gpointer self);
void notejot_widgets_note_destroy_item (NotejotWidgetsNote* self);
void notejot_widgets_note_select_item (NotejotWidgetsNote* self);
GType notejot_widgets_note_menu_popover_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsNoteMenuPopover, g_object_unref)
void notejot_widgets_note_popover_listener (NotejotWidgetsNote* self,
                                            NotejotWidgetsNoteMenuPopover* popover);
static void __lambda25_ (NotejotWidgetsNote* self);
void notejot_views_trash_view_new_taskbox (NotejotViewsTrashView* self,
                                           NotejotMainWindow* win,
                                           const gchar* title,
                                           const gchar* contents,
                                           const gchar* text,
                                           const gchar* color,
                                           GAsyncReadyCallback _callback_,
                                           gpointer _user_data_);
void notejot_views_trash_view_new_taskbox_finish (NotejotViewsTrashView* self,
                                                  GAsyncResult* _res_);
static void ___lambda25__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda26_ (NotejotWidgetsNote* self);
static void ___lambda26__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda27_ (NotejotWidgetsNote* self);
static void ___lambda27__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda28_ (NotejotWidgetsNote* self);
static void ___lambda28__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda29_ (NotejotWidgetsNote* self);
static void ___lambda29__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda30_ (NotejotWidgetsNote* self);
static void ___lambda30__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda31_ (NotejotWidgetsNote* self);
static void ___lambda31__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda32_ (NotejotWidgetsNote* self);
static void ___lambda32__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda33_ (NotejotWidgetsNote* self);
static void ___lambda33__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void notejot_widgets_note_finalize (GObject * obj);
static GType notejot_widgets_note_get_type_once (void);

static inline gpointer
notejot_widgets_note_get_instance_private (NotejotWidgetsNote* self)
{
	return G_STRUCT_MEMBER_P (self, NotejotWidgetsNote_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 32 "../src/Widgets/Note.vala"
	return self ? g_object_ref (self) : NULL;
#line 439 "Note.c"
}

static Block5Data*
block5_data_ref (Block5Data* _data5_)
{
#line 32 "../src/Widgets/Note.vala"
	g_atomic_int_inc (&_data5_->_ref_count_);
#line 32 "../src/Widgets/Note.vala"
	return _data5_;
#line 449 "Note.c"
}

static void
block5_data_unref (void * _userdata_)
{
	Block5Data* _data5_;
	_data5_ = (Block5Data*) _userdata_;
#line 32 "../src/Widgets/Note.vala"
	if (g_atomic_int_dec_and_test (&_data5_->_ref_count_)) {
#line 459 "Note.c"
		NotejotWidgetsNote* self;
#line 32 "../src/Widgets/Note.vala"
		self = _data5_->self;
#line 32 "../src/Widgets/Note.vala"
		_g_object_unref0 (_data5_->note_grid);
#line 32 "../src/Widgets/Note.vala"
		_g_object_unref0 (_data5_->subtitlelabel);
#line 32 "../src/Widgets/Note.vala"
		_g_object_unref0 (_data5_->icon);
#line 32 "../src/Widgets/Note.vala"
		_g_object_unref0 (_data5_->win);
#line 32 "../src/Widgets/Note.vala"
		_g_object_unref0 (self);
#line 32 "../src/Widgets/Note.vala"
		g_slice_free (Block5Data, _data5_);
#line 475 "Note.c"
	}
}

static void
__lambda44_ (Block5Data* _data5_)
{
	NotejotWidgetsNote* self;
	NotejotWidgetsEditableLabel* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	NotejotWidgetsEditableLabel* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	NotejotTaskManager* _tmp7_;
#line 99 "../src/Widgets/Note.vala"
	self = _data5_->self;
#line 100 "../src/Widgets/Note.vala"
	_tmp0_ = self->titlelabel;
#line 100 "../src/Widgets/Note.vala"
	_tmp1_ = notejot_widgets_editable_label_get_text (_tmp0_);
#line 100 "../src/Widgets/Note.vala"
	_tmp2_ = _tmp1_;
#line 100 "../src/Widgets/Note.vala"
	hdy_preferences_row_set_title ((HdyPreferencesRow*) self, _tmp2_);
#line 101 "../src/Widgets/Note.vala"
	_tmp3_ = self->titlelabel;
#line 101 "../src/Widgets/Note.vala"
	_tmp4_ = notejot_widgets_editable_label_get_text (_tmp3_);
#line 101 "../src/Widgets/Note.vala"
	_tmp5_ = _tmp4_;
#line 101 "../src/Widgets/Note.vala"
	_tmp6_ = g_strdup (_tmp5_);
#line 101 "../src/Widgets/Note.vala"
	_g_free0 (self->title);
#line 101 "../src/Widgets/Note.vala"
	self->title = _tmp6_;
#line 102 "../src/Widgets/Note.vala"
	_tmp7_ = _data5_->win->tm;
#line 102 "../src/Widgets/Note.vala"
	notejot_task_manager_save_notes (_tmp7_, NULL, NULL);
#line 517 "Note.c"
}

static void
___lambda44__notejot_widgets_editable_label_changed (NotejotWidgetsEditableLabel* _sender,
                                                     const gchar* new_title,
                                                     gpointer self)
{
#line 99 "../src/Widgets/Note.vala"
	__lambda44_ (self);
#line 527 "Note.c"
}

static gboolean
__lambda45_ (Block5Data* _data5_)
{
	NotejotWidgetsNote* self;
	GtkLabel* _tmp34_;
	const gchar* _tmp35_;
	gchar* _tmp36_;
	gchar* _tmp37_;
	GError* _inner_error0_ = NULL;
	gboolean result = FALSE;
#line 105 "../src/Widgets/Note.vala"
	self = _data5_->self;
#line 542 "Note.c"
	{
		GRegex* reg = NULL;
		GRegex* _tmp0_;
		GMatchInfo* match = NULL;
		GtkLabel* _tmp2_;
		const gchar* _tmp3_;
		GMatchInfo* _tmp4_ = NULL;
		gboolean _tmp5_;
#line 107 "../src/Widgets/Note.vala"
		_tmp0_ = g_regex_new ("(?m)^.*, (?<day>\\d{2})/(?<month>\\d{2}) (?<hour>\\d{2})\342\210\266(?" \
"<minute>\\d{2})$", 0, 0, &_inner_error0_);
#line 107 "../src/Widgets/Note.vala"
		reg = _tmp0_;
#line 107 "../src/Widgets/Note.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 557 "Note.c"
			gboolean _tmp1_ = FALSE;
#line 107 "../src/Widgets/Note.vala"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 561 "Note.c"
				goto __catch0_g_regex_error;
			}
#line 107 "../src/Widgets/Note.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 107 "../src/Widgets/Note.vala"
			g_clear_error (&_inner_error0_);
#line 107 "../src/Widgets/Note.vala"
			return _tmp1_;
#line 570 "Note.c"
		}
#line 110 "../src/Widgets/Note.vala"
		_tmp2_ = _data5_->subtitlelabel;
#line 110 "../src/Widgets/Note.vala"
		_tmp3_ = gtk_label_get_text (_tmp2_);
#line 110 "../src/Widgets/Note.vala"
		_tmp5_ = g_regex_match (reg, _tmp3_, 0, &_tmp4_);
#line 110 "../src/Widgets/Note.vala"
		_g_match_info_unref0 (match);
#line 110 "../src/Widgets/Note.vala"
		match = _tmp4_;
#line 110 "../src/Widgets/Note.vala"
		if (_tmp5_) {
#line 584 "Note.c"
			GDateTime* e = NULL;
			GDateTime* _tmp6_;
			GDateTime* d = NULL;
			GDateTime* _tmp7_;
			GMatchInfo* _tmp8_;
			gchar* _tmp9_;
			gchar* _tmp10_;
			GMatchInfo* _tmp11_;
			gchar* _tmp12_;
			gchar* _tmp13_;
			GMatchInfo* _tmp14_;
			gchar* _tmp15_;
			gchar* _tmp16_;
			GMatchInfo* _tmp17_;
			gchar* _tmp18_;
			gchar* _tmp19_;
			GDateTime* _tmp20_;
			GDateTime* _tmp21_;
			GDateTime* _tmp22_;
			GtkLabel* _tmp23_;
			GDateTime* _tmp24_;
			gchar* _tmp25_;
			gchar* _tmp26_;
			gchar* _tmp27_;
			gchar* _tmp28_;
#line 111 "../src/Widgets/Note.vala"
			_tmp6_ = g_date_time_new_now_local ();
#line 111 "../src/Widgets/Note.vala"
			e = _tmp6_;
#line 112 "../src/Widgets/Note.vala"
			_tmp7_ = e;
#line 112 "../src/Widgets/Note.vala"
			_tmp8_ = match;
#line 112 "../src/Widgets/Note.vala"
			_tmp9_ = g_match_info_fetch_named (_tmp8_, "month");
#line 112 "../src/Widgets/Note.vala"
			_tmp10_ = _tmp9_;
#line 112 "../src/Widgets/Note.vala"
			_tmp11_ = match;
#line 112 "../src/Widgets/Note.vala"
			_tmp12_ = g_match_info_fetch_named (_tmp11_, "day");
#line 112 "../src/Widgets/Note.vala"
			_tmp13_ = _tmp12_;
#line 112 "../src/Widgets/Note.vala"
			_tmp14_ = match;
#line 112 "../src/Widgets/Note.vala"
			_tmp15_ = g_match_info_fetch_named (_tmp14_, "hour");
#line 112 "../src/Widgets/Note.vala"
			_tmp16_ = _tmp15_;
#line 112 "../src/Widgets/Note.vala"
			_tmp17_ = match;
#line 112 "../src/Widgets/Note.vala"
			_tmp18_ = g_match_info_fetch_named (_tmp17_, "minute");
#line 112 "../src/Widgets/Note.vala"
			_tmp19_ = _tmp18_;
#line 112 "../src/Widgets/Note.vala"
			_tmp20_ = e;
#line 112 "../src/Widgets/Note.vala"
			_tmp21_ = g_date_time_new_local (g_date_time_get_year (_tmp7_), atoi (_tmp10_), atoi (_tmp13_), atoi (_tmp16_), atoi (_tmp19_), (gdouble) g_date_time_get_second (_tmp20_));
#line 112 "../src/Widgets/Note.vala"
			_tmp22_ = _tmp21_;
#line 112 "../src/Widgets/Note.vala"
			_g_free0 (_tmp19_);
#line 112 "../src/Widgets/Note.vala"
			_g_free0 (_tmp16_);
#line 112 "../src/Widgets/Note.vala"
			_g_free0 (_tmp13_);
#line 112 "../src/Widgets/Note.vala"
			_g_free0 (_tmp10_);
#line 112 "../src/Widgets/Note.vala"
			d = _tmp22_;
#line 118 "../src/Widgets/Note.vala"
			_tmp23_ = _data5_->subtitlelabel;
#line 118 "../src/Widgets/Note.vala"
			_tmp24_ = d;
#line 118 "../src/Widgets/Note.vala"
			_tmp25_ = notejot_utils_get_relative_datetime (_tmp24_);
#line 118 "../src/Widgets/Note.vala"
			_tmp26_ = _tmp25_;
#line 118 "../src/Widgets/Note.vala"
			_tmp27_ = g_strdup_printf ("%s", _tmp26_);
#line 118 "../src/Widgets/Note.vala"
			_tmp28_ = _tmp27_;
#line 118 "../src/Widgets/Note.vala"
			gtk_label_set_text (_tmp23_, _tmp28_);
#line 118 "../src/Widgets/Note.vala"
			_g_free0 (_tmp28_);
#line 118 "../src/Widgets/Note.vala"
			_g_free0 (_tmp26_);
#line 110 "../src/Widgets/Note.vala"
			_g_date_time_unref0 (d);
#line 110 "../src/Widgets/Note.vala"
			_g_date_time_unref0 (e);
#line 678 "Note.c"
		}
#line 106 "../src/Widgets/Note.vala"
		_g_match_info_unref0 (match);
#line 106 "../src/Widgets/Note.vala"
		_g_regex_unref0 (reg);
#line 684 "Note.c"
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
		GError* re = NULL;
		GError* _tmp29_;
		const gchar* _tmp30_;
		gchar* _tmp31_;
		gchar* _tmp32_;
#line 106 "../src/Widgets/Note.vala"
		re = _inner_error0_;
#line 106 "../src/Widgets/Note.vala"
		_inner_error0_ = NULL;
#line 121 "../src/Widgets/Note.vala"
		_tmp29_ = re;
#line 121 "../src/Widgets/Note.vala"
		_tmp30_ = _tmp29_->message;
#line 121 "../src/Widgets/Note.vala"
		_tmp31_ = g_strdup_printf ("%s", _tmp30_);
#line 121 "../src/Widgets/Note.vala"
		_tmp32_ = _tmp31_;
#line 121 "../src/Widgets/Note.vala"
		g_warning ("Note.vala:121: %s", _tmp32_);
#line 121 "../src/Widgets/Note.vala"
		_g_free0 (_tmp32_);
#line 106 "../src/Widgets/Note.vala"
		_g_error_free0 (re);
#line 712 "Note.c"
	}
	__finally0:
#line 106 "../src/Widgets/Note.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 717 "Note.c"
		gboolean _tmp33_ = FALSE;
#line 106 "../src/Widgets/Note.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 106 "../src/Widgets/Note.vala"
		g_clear_error (&_inner_error0_);
#line 106 "../src/Widgets/Note.vala"
		return _tmp33_;
#line 725 "Note.c"
	}
#line 124 "../src/Widgets/Note.vala"
	_tmp34_ = _data5_->subtitlelabel;
#line 124 "../src/Widgets/Note.vala"
	_tmp35_ = gtk_label_get_text (_tmp34_);
#line 124 "../src/Widgets/Note.vala"
	_tmp36_ = g_strdup_printf ("Subtitle is now %s", _tmp35_);
#line 124 "../src/Widgets/Note.vala"
	_tmp37_ = _tmp36_;
#line 124 "../src/Widgets/Note.vala"
	g_warning ("Note.vala:124: %s", _tmp37_);
#line 124 "../src/Widgets/Note.vala"
	_g_free0 (_tmp37_);
#line 125 "../src/Widgets/Note.vala"
	result = TRUE;
#line 125 "../src/Widgets/Note.vala"
	return result;
#line 743 "Note.c"
}

static gboolean
___lambda45__gsource_func (gpointer self)
{
	gboolean result;
	result = __lambda45_ (self);
#line 105 "../src/Widgets/Note.vala"
	return result;
#line 753 "Note.c"
}

static void
__lambda46_ (Block5Data* _data5_)
{
	NotejotWidgetsNote* self;
	GtkLabel* _tmp0_;
	const gchar* _tmp1_;
	GtkLabel* _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	NotejotTaskManager* _tmp5_;
#line 128 "../src/Widgets/Note.vala"
	self = _data5_->self;
#line 129 "../src/Widgets/Note.vala"
	_tmp0_ = _data5_->subtitlelabel;
#line 129 "../src/Widgets/Note.vala"
	_tmp1_ = gtk_label_get_text (_tmp0_);
#line 129 "../src/Widgets/Note.vala"
	hdy_action_row_set_subtitle ((HdyActionRow*) self, _tmp1_);
#line 130 "../src/Widgets/Note.vala"
	_tmp2_ = _data5_->subtitlelabel;
#line 130 "../src/Widgets/Note.vala"
	_tmp3_ = gtk_label_get_text (_tmp2_);
#line 130 "../src/Widgets/Note.vala"
	_tmp4_ = g_strdup (_tmp3_);
#line 130 "../src/Widgets/Note.vala"
	_g_free0 (self->subtitle);
#line 130 "../src/Widgets/Note.vala"
	self->subtitle = _tmp4_;
#line 131 "../src/Widgets/Note.vala"
	_tmp5_ = _data5_->win->tm;
#line 131 "../src/Widgets/Note.vala"
	notejot_task_manager_save_notes (_tmp5_, NULL, NULL);
#line 788 "Note.c"
}

static void
___lambda46__g_object_notify (GObject* _sender,
                              GParamSpec* pspec,
                              gpointer self)
{
#line 128 "../src/Widgets/Note.vala"
	__lambda46_ (self);
#line 798 "Note.c"
}

static void
__lambda47_ (Block5Data* _data5_)
{
	NotejotWidgetsNote* self;
	GSettings* _tmp0_;
#line 150 "../src/Widgets/Note.vala"
	self = _data5_->self;
#line 151 "../src/Widgets/Note.vala"
	_tmp0_ = notejot_application_gsettings;
#line 151 "../src/Widgets/Note.vala"
	if (g_settings_get_boolean (_tmp0_, "dark-mode")) {
#line 812 "Note.c"
		GtkSettings* _tmp1_;
		NotejotWidgetsTextField* _tmp2_;
		GtkStyleContext* _tmp3_;
		gchar* _tmp4_;
		gchar* _tmp5_;
		GtkImage* _tmp6_;
		GtkStyleContext* _tmp7_;
		gchar* _tmp8_;
		gchar* _tmp9_;
		NotejotWidgetsEditableLabel* _tmp10_;
		GtkStyleContext* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
		GtkLabel* _tmp14_;
		GtkStyleContext* _tmp15_;
		gchar* _tmp16_;
		gchar* _tmp17_;
		GtkGrid* _tmp18_;
		GtkStyleContext* _tmp19_;
		gchar* _tmp20_;
		gchar* _tmp21_;
#line 152 "../src/Widgets/Note.vala"
		_tmp1_ = gtk_settings_get_default ();
#line 152 "../src/Widgets/Note.vala"
		g_object_set (_tmp1_, "gtk-application-prefer-dark-theme", TRUE, NULL);
#line 153 "../src/Widgets/Note.vala"
		_tmp2_ = self->textfield;
#line 153 "../src/Widgets/Note.vala"
		_tmp3_ = gtk_widget_get_style_context ((GtkWidget*) _tmp2_);
#line 153 "../src/Widgets/Note.vala"
		_tmp4_ = g_strdup_printf ("notejot-tview-dark-%d", self->uid);
#line 153 "../src/Widgets/Note.vala"
		_tmp5_ = _tmp4_;
#line 153 "../src/Widgets/Note.vala"
		gtk_style_context_add_class (_tmp3_, _tmp5_);
#line 153 "../src/Widgets/Note.vala"
		_g_free0 (_tmp5_);
#line 154 "../src/Widgets/Note.vala"
		_tmp6_ = _data5_->icon;
#line 154 "../src/Widgets/Note.vala"
		_tmp7_ = gtk_widget_get_style_context ((GtkWidget*) _tmp6_);
#line 154 "../src/Widgets/Note.vala"
		_tmp8_ = g_strdup_printf ("notejot-sidebar-dbg-dark-%d", self->uid);
#line 154 "../src/Widgets/Note.vala"
		_tmp9_ = _tmp8_;
#line 154 "../src/Widgets/Note.vala"
		gtk_style_context_add_class (_tmp7_, _tmp9_);
#line 154 "../src/Widgets/Note.vala"
		_g_free0 (_tmp9_);
#line 155 "../src/Widgets/Note.vala"
		_tmp10_ = self->titlelabel;
#line 155 "../src/Widgets/Note.vala"
		_tmp11_ = gtk_widget_get_style_context ((GtkWidget*) _tmp10_);
#line 155 "../src/Widgets/Note.vala"
		_tmp12_ = g_strdup_printf ("notejot-label-dark-%d", self->uid);
#line 155 "../src/Widgets/Note.vala"
		_tmp13_ = _tmp12_;
#line 155 "../src/Widgets/Note.vala"
		gtk_style_context_add_class (_tmp11_, _tmp13_);
#line 155 "../src/Widgets/Note.vala"
		_g_free0 (_tmp13_);
#line 156 "../src/Widgets/Note.vala"
		_tmp14_ = _data5_->subtitlelabel;
#line 156 "../src/Widgets/Note.vala"
		_tmp15_ = gtk_widget_get_style_context ((GtkWidget*) _tmp14_);
#line 156 "../src/Widgets/Note.vala"
		_tmp16_ = g_strdup_printf ("notejot-label-dark-%d", self->uid);
#line 156 "../src/Widgets/Note.vala"
		_tmp17_ = _tmp16_;
#line 156 "../src/Widgets/Note.vala"
		gtk_style_context_add_class (_tmp15_, _tmp17_);
#line 156 "../src/Widgets/Note.vala"
		_g_free0 (_tmp17_);
#line 157 "../src/Widgets/Note.vala"
		_tmp18_ = _data5_->note_grid;
#line 157 "../src/Widgets/Note.vala"
		_tmp19_ = gtk_widget_get_style_context ((GtkWidget*) _tmp18_);
#line 157 "../src/Widgets/Note.vala"
		_tmp20_ = g_strdup_printf ("notejot-stack-dark-%d", self->uid);
#line 157 "../src/Widgets/Note.vala"
		_tmp21_ = _tmp20_;
#line 157 "../src/Widgets/Note.vala"
		gtk_style_context_add_class (_tmp19_, _tmp21_);
#line 157 "../src/Widgets/Note.vala"
		_g_free0 (_tmp21_);
#line 898 "Note.c"
	} else {
		GtkSettings* _tmp22_;
		NotejotWidgetsTextField* _tmp23_;
		GtkStyleContext* _tmp24_;
		gchar* _tmp25_;
		gchar* _tmp26_;
		GtkImage* _tmp27_;
		GtkStyleContext* _tmp28_;
		gchar* _tmp29_;
		gchar* _tmp30_;
		NotejotWidgetsEditableLabel* _tmp31_;
		GtkStyleContext* _tmp32_;
		gchar* _tmp33_;
		gchar* _tmp34_;
		GtkLabel* _tmp35_;
		GtkStyleContext* _tmp36_;
		gchar* _tmp37_;
		gchar* _tmp38_;
		GtkGrid* _tmp39_;
		GtkStyleContext* _tmp40_;
		gchar* _tmp41_;
		gchar* _tmp42_;
#line 159 "../src/Widgets/Note.vala"
		_tmp22_ = gtk_settings_get_default ();
#line 159 "../src/Widgets/Note.vala"
		g_object_set (_tmp22_, "gtk-application-prefer-dark-theme", FALSE, NULL);
#line 160 "../src/Widgets/Note.vala"
		_tmp23_ = self->textfield;
#line 160 "../src/Widgets/Note.vala"
		_tmp24_ = gtk_widget_get_style_context ((GtkWidget*) _tmp23_);
#line 160 "../src/Widgets/Note.vala"
		_tmp25_ = g_strdup_printf ("notejot-tview-dark-%d", self->uid);
#line 160 "../src/Widgets/Note.vala"
		_tmp26_ = _tmp25_;
#line 160 "../src/Widgets/Note.vala"
		gtk_style_context_remove_class (_tmp24_, _tmp26_);
#line 160 "../src/Widgets/Note.vala"
		_g_free0 (_tmp26_);
#line 161 "../src/Widgets/Note.vala"
		_tmp27_ = _data5_->icon;
#line 161 "../src/Widgets/Note.vala"
		_tmp28_ = gtk_widget_get_style_context ((GtkWidget*) _tmp27_);
#line 161 "../src/Widgets/Note.vala"
		_tmp29_ = g_strdup_printf ("notejot-sidebar-dbg-dark-%d", self->uid);
#line 161 "../src/Widgets/Note.vala"
		_tmp30_ = _tmp29_;
#line 161 "../src/Widgets/Note.vala"
		gtk_style_context_remove_class (_tmp28_, _tmp30_);
#line 161 "../src/Widgets/Note.vala"
		_g_free0 (_tmp30_);
#line 162 "../src/Widgets/Note.vala"
		_tmp31_ = self->titlelabel;
#line 162 "../src/Widgets/Note.vala"
		_tmp32_ = gtk_widget_get_style_context ((GtkWidget*) _tmp31_);
#line 162 "../src/Widgets/Note.vala"
		_tmp33_ = g_strdup_printf ("notejot-label-dark-%d", self->uid);
#line 162 "../src/Widgets/Note.vala"
		_tmp34_ = _tmp33_;
#line 162 "../src/Widgets/Note.vala"
		gtk_style_context_remove_class (_tmp32_, _tmp34_);
#line 162 "../src/Widgets/Note.vala"
		_g_free0 (_tmp34_);
#line 163 "../src/Widgets/Note.vala"
		_tmp35_ = _data5_->subtitlelabel;
#line 163 "../src/Widgets/Note.vala"
		_tmp36_ = gtk_widget_get_style_context ((GtkWidget*) _tmp35_);
#line 163 "../src/Widgets/Note.vala"
		_tmp37_ = g_strdup_printf ("notejot-label-dark-%d", self->uid);
#line 163 "../src/Widgets/Note.vala"
		_tmp38_ = _tmp37_;
#line 163 "../src/Widgets/Note.vala"
		gtk_style_context_remove_class (_tmp36_, _tmp38_);
#line 163 "../src/Widgets/Note.vala"
		_g_free0 (_tmp38_);
#line 164 "../src/Widgets/Note.vala"
		_tmp39_ = _data5_->note_grid;
#line 164 "../src/Widgets/Note.vala"
		_tmp40_ = gtk_widget_get_style_context ((GtkWidget*) _tmp39_);
#line 164 "../src/Widgets/Note.vala"
		_tmp41_ = g_strdup_printf ("notejot-stack-dark-%d", self->uid);
#line 164 "../src/Widgets/Note.vala"
		_tmp42_ = _tmp41_;
#line 164 "../src/Widgets/Note.vala"
		gtk_style_context_remove_class (_tmp40_, _tmp42_);
#line 164 "../src/Widgets/Note.vala"
		_g_free0 (_tmp42_);
#line 985 "Note.c"
	}
}

static void
___lambda47__g_settings_changed (GSettings* _sender,
                                 const gchar* key,
                                 gpointer self)
{
#line 150 "../src/Widgets/Note.vala"
	__lambda47_ (self);
#line 996 "Note.c"
}

NotejotWidgetsNote*
notejot_widgets_note_construct (GType object_type,
                                NotejotMainWindow* win,
                                const gchar* title,
                                const gchar* subtitle,
                                const gchar* text,
                                const gchar* color)
{
	NotejotWidgetsNote * self = NULL;
	Block5Data* _data5_;
	NotejotMainWindow* _tmp0_;
	NotejotMainWindow* _tmp1_;
	gint _tmp2_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	GtkImage* _tmp9_;
	GtkImage* _tmp10_;
	GtkImage* _tmp11_;
	GtkImage* _tmp12_;
	GtkStyleContext* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	GtkImage* _tmp16_;
	const gchar* _tmp17_;
	const gchar* _tmp18_;
	GtkStyleContext* _tmp19_;
	NotejotWidgetsTextField* _tmp20_;
	GtkScrolledWindow* text_scroller = NULL;
	GtkScrolledWindow* _tmp21_;
	GtkScrolledWindow* _tmp22_;
	GtkScrolledWindow* _tmp23_;
	NotejotWidgetsTextField* _tmp24_;
	NotejotWidgetsTextField* _tmp25_;
	const gchar* _tmp26_;
	gchar* _tmp27_;
	NotejotWidgetsTextField* _tmp28_;
	NotejotWidgetsNote* _tmp29_;
	NotejotWidgetsTextField* _tmp30_;
	const gchar* _tmp31_;
	NotejotWidgetsEditableLabel* _tmp32_;
	NotejotWidgetsEditableLabel* _tmp33_;
	GtkStyleContext* _tmp34_;
	gchar* _tmp35_;
	gchar* _tmp36_;
	NotejotWidgetsEditableLabel* _tmp37_;
	NotejotWidgetsEditableLabel* _tmp38_;
	NotejotWidgetsEditableLabel* _tmp39_;
	GtkLabel* _tmp40_;
	GtkStyleContext* _tmp41_;
	const gchar* _tmp42_;
	GtkLabel* _tmp43_;
	GtkLabel* _tmp44_;
	GtkLabel* _tmp45_;
	GtkLabel* _tmp46_;
	GtkStyleContext* _tmp47_;
	gchar* _tmp48_;
	gchar* _tmp49_;
	GtkLabel* _tmp50_;
	GtkStyleContext* _tmp51_;
	GtkSeparator* sep = NULL;
	GtkSeparator* _tmp52_;
	GtkSeparator* _tmp53_;
	NotejotWidgetsFormatBar* formatbar = NULL;
	NotejotWidgetsFormatBar* _tmp54_;
	NotejotWidgetsFormatBar* _tmp55_;
	NotejotWidgetsTextField* _tmp56_;
	NotejotWidgetsTextField* _tmp57_;
	GtkGrid* _tmp58_;
	GtkGrid* _tmp59_;
	GtkGrid* _tmp60_;
	NotejotWidgetsEditableLabel* _tmp61_;
	GtkGrid* _tmp62_;
	GtkLabel* _tmp63_;
	GtkGrid* _tmp64_;
	GtkSeparator* _tmp65_;
	GtkGrid* _tmp66_;
	GtkScrolledWindow* _tmp67_;
	GtkGrid* _tmp68_;
	NotejotWidgetsFormatBar* _tmp69_;
	GtkGrid* _tmp70_;
	GtkStack* _tmp71_;
	GtkGrid* _tmp72_;
	gchar* _tmp73_;
	gchar* _tmp74_;
	GtkGrid* _tmp75_;
	GtkStyleContext* _tmp76_;
	gchar* _tmp77_;
	gchar* _tmp78_;
	NotejotWidgetsEditableLabel* _tmp79_;
	GtkLabel* _tmp80_;
	GSettings* _tmp81_;
	GSettings* _tmp124_;
#line 32 "../src/Widgets/Note.vala"
	g_return_val_if_fail (win != NULL, NULL);
#line 32 "../src/Widgets/Note.vala"
	g_return_val_if_fail (title != NULL, NULL);
#line 32 "../src/Widgets/Note.vala"
	g_return_val_if_fail (subtitle != NULL, NULL);
#line 32 "../src/Widgets/Note.vala"
	g_return_val_if_fail (text != NULL, NULL);
#line 32 "../src/Widgets/Note.vala"
	g_return_val_if_fail (color != NULL, NULL);
#line 32 "../src/Widgets/Note.vala"
	_data5_ = g_slice_new0 (Block5Data);
#line 32 "../src/Widgets/Note.vala"
	_data5_->_ref_count_ = 1;
#line 32 "../src/Widgets/Note.vala"
	_tmp0_ = _g_object_ref0 (win);
#line 32 "../src/Widgets/Note.vala"
	_g_object_unref0 (_data5_->win);
#line 32 "../src/Widgets/Note.vala"
	_data5_->win = _tmp0_;
#line 32 "../src/Widgets/Note.vala"
	self = (NotejotWidgetsNote*) g_object_new (object_type, NULL);
#line 32 "../src/Widgets/Note.vala"
	_data5_->self = g_object_ref (self);
#line 33 "../src/Widgets/Note.vala"
	_tmp1_ = _g_object_ref0 (_data5_->win);
#line 33 "../src/Widgets/Note.vala"
	_g_object_unref0 (self->priv->win);
#line 33 "../src/Widgets/Note.vala"
	self->priv->win = _tmp1_;
#line 34 "../src/Widgets/Note.vala"
	_tmp2_ = notejot_widgets_note_uid_counter;
#line 34 "../src/Widgets/Note.vala"
	notejot_widgets_note_uid_counter = _tmp2_ + 1;
#line 34 "../src/Widgets/Note.vala"
	self->uid = _tmp2_;
#line 36 "../src/Widgets/Note.vala"
	if (g_strcmp0 (title, "") == 0) {
#line 1129 "Note.c"
		gchar* _tmp3_;
		gchar* _tmp4_;
		gchar* _tmp5_;
#line 37 "../src/Widgets/Note.vala"
		_tmp3_ = g_strdup_printf ("%i", self->uid + 1);
#line 37 "../src/Widgets/Note.vala"
		_tmp4_ = _tmp3_;
#line 37 "../src/Widgets/Note.vala"
		_tmp5_ = g_strconcat ("New Note ", _tmp4_, NULL);
#line 37 "../src/Widgets/Note.vala"
		_g_free0 (self->title);
#line 37 "../src/Widgets/Note.vala"
		self->title = _tmp5_;
#line 37 "../src/Widgets/Note.vala"
		_g_free0 (_tmp4_);
#line 1145 "Note.c"
	} else {
		gchar* _tmp6_;
#line 39 "../src/Widgets/Note.vala"
		_tmp6_ = g_strdup (title);
#line 39 "../src/Widgets/Note.vala"
		_g_free0 (self->title);
#line 39 "../src/Widgets/Note.vala"
		self->title = _tmp6_;
#line 1154 "Note.c"
	}
#line 42 "../src/Widgets/Note.vala"
	_tmp7_ = g_strdup (subtitle);
#line 42 "../src/Widgets/Note.vala"
	_g_free0 (self->subtitle);
#line 42 "../src/Widgets/Note.vala"
	self->subtitle = _tmp7_;
#line 43 "../src/Widgets/Note.vala"
	_tmp8_ = g_strdup (text);
#line 43 "../src/Widgets/Note.vala"
	_g_free0 (self->text);
#line 43 "../src/Widgets/Note.vala"
	self->text = _tmp8_;
#line 46 "../src/Widgets/Note.vala"
	_tmp9_ = (GtkImage*) gtk_image_new_from_icon_name ("", (GtkIconSize) GTK_ICON_SIZE_SMALL_TOOLBAR);
#line 46 "../src/Widgets/Note.vala"
	g_object_ref_sink (_tmp9_);
#line 46 "../src/Widgets/Note.vala"
	_data5_->icon = _tmp9_;
#line 47 "../src/Widgets/Note.vala"
	_tmp10_ = _data5_->icon;
#line 47 "../src/Widgets/Note.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp10_, GTK_ALIGN_START);
#line 48 "../src/Widgets/Note.vala"
	_tmp11_ = _data5_->icon;
#line 48 "../src/Widgets/Note.vala"
	gtk_widget_set_valign ((GtkWidget*) _tmp11_, GTK_ALIGN_CENTER);
#line 49 "../src/Widgets/Note.vala"
	_tmp12_ = _data5_->icon;
#line 49 "../src/Widgets/Note.vala"
	_tmp13_ = gtk_widget_get_style_context ((GtkWidget*) _tmp12_);
#line 49 "../src/Widgets/Note.vala"
	_tmp14_ = g_strdup_printf ("notejot-sidebar-dbg-%d", self->uid);
#line 49 "../src/Widgets/Note.vala"
	_tmp15_ = _tmp14_;
#line 49 "../src/Widgets/Note.vala"
	gtk_style_context_add_class (_tmp13_, _tmp15_);
#line 49 "../src/Widgets/Note.vala"
	_g_free0 (_tmp15_);
#line 51 "../src/Widgets/Note.vala"
	_tmp16_ = _data5_->icon;
#line 51 "../src/Widgets/Note.vala"
	hdy_action_row_add_prefix ((HdyActionRow*) self, (GtkWidget*) _tmp16_);
#line 53 "../src/Widgets/Note.vala"
	_tmp17_ = self->title;
#line 53 "../src/Widgets/Note.vala"
	hdy_preferences_row_set_title ((HdyPreferencesRow*) self, _tmp17_);
#line 54 "../src/Widgets/Note.vala"
	_tmp18_ = self->subtitle;
#line 54 "../src/Widgets/Note.vala"
	hdy_action_row_set_subtitle ((HdyActionRow*) self, _tmp18_);
#line 56 "../src/Widgets/Note.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 57 "../src/Widgets/Note.vala"
	_tmp19_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 57 "../src/Widgets/Note.vala"
	gtk_style_context_add_class (_tmp19_, "notejot-sidebar-box");
#line 59 "../src/Widgets/Note.vala"
	notejot_widgets_note_update_theme (self, color);
#line 61 "../src/Widgets/Note.vala"
	_tmp20_ = notejot_widgets_text_field_new (_data5_->win);
#line 61 "../src/Widgets/Note.vala"
	g_object_ref_sink (_tmp20_);
#line 61 "../src/Widgets/Note.vala"
	_g_object_unref0 (self->textfield);
#line 61 "../src/Widgets/Note.vala"
	self->textfield = _tmp20_;
#line 62 "../src/Widgets/Note.vala"
	_tmp21_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 62 "../src/Widgets/Note.vala"
	g_object_ref_sink (_tmp21_);
#line 62 "../src/Widgets/Note.vala"
	text_scroller = _tmp21_;
#line 63 "../src/Widgets/Note.vala"
	_tmp22_ = text_scroller;
#line 63 "../src/Widgets/Note.vala"
	gtk_widget_set_vexpand ((GtkWidget*) _tmp22_, TRUE);
#line 64 "../src/Widgets/Note.vala"
	_tmp23_ = text_scroller;
#line 64 "../src/Widgets/Note.vala"
	_tmp24_ = self->textfield;
#line 64 "../src/Widgets/Note.vala"
	gtk_container_add ((GtkContainer*) _tmp23_, (GtkWidget*) _tmp24_);
#line 65 "../src/Widgets/Note.vala"
	_tmp25_ = self->textfield;
#line 65 "../src/Widgets/Note.vala"
	_tmp26_ = self->text;
#line 65 "../src/Widgets/Note.vala"
	_tmp27_ = g_strdup (_tmp26_);
#line 65 "../src/Widgets/Note.vala"
	_g_free0 (_tmp25_->text);
#line 65 "../src/Widgets/Note.vala"
	_tmp25_->text = _tmp27_;
#line 66 "../src/Widgets/Note.vala"
	_tmp28_ = self->textfield;
#line 66 "../src/Widgets/Note.vala"
	_tmp29_ = _g_object_ref0 (self);
#line 66 "../src/Widgets/Note.vala"
	_g_object_unref0 (_tmp28_->controller);
#line 66 "../src/Widgets/Note.vala"
	_tmp28_->controller = _tmp29_;
#line 67 "../src/Widgets/Note.vala"
	_tmp30_ = self->textfield;
#line 67 "../src/Widgets/Note.vala"
	notejot_widgets_text_field_update_html_view (_tmp30_, NULL, NULL);
#line 69 "../src/Widgets/Note.vala"
	_tmp31_ = self->title;
#line 69 "../src/Widgets/Note.vala"
	_tmp32_ = notejot_widgets_editable_label_new (_data5_->win, _tmp31_);
#line 69 "../src/Widgets/Note.vala"
	g_object_ref_sink (_tmp32_);
#line 69 "../src/Widgets/Note.vala"
	_g_object_unref0 (self->titlelabel);
#line 69 "../src/Widgets/Note.vala"
	self->titlelabel = _tmp32_;
#line 70 "../src/Widgets/Note.vala"
	_tmp33_ = self->titlelabel;
#line 70 "../src/Widgets/Note.vala"
	_tmp34_ = gtk_widget_get_style_context ((GtkWidget*) _tmp33_);
#line 70 "../src/Widgets/Note.vala"
	_tmp35_ = g_strdup_printf ("notejot-label-%d", self->uid);
#line 70 "../src/Widgets/Note.vala"
	_tmp36_ = _tmp35_;
#line 70 "../src/Widgets/Note.vala"
	gtk_style_context_add_class (_tmp34_, _tmp36_);
#line 70 "../src/Widgets/Note.vala"
	_g_free0 (_tmp36_);
#line 71 "../src/Widgets/Note.vala"
	_tmp37_ = self->titlelabel;
#line 71 "../src/Widgets/Note.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp37_, GTK_ALIGN_START);
#line 72 "../src/Widgets/Note.vala"
	_tmp38_ = self->titlelabel;
#line 72 "../src/Widgets/Note.vala"
	gtk_widget_set_margin_top ((GtkWidget*) _tmp38_, 20);
#line 73 "../src/Widgets/Note.vala"
	_tmp39_ = self->titlelabel;
#line 73 "../src/Widgets/Note.vala"
	_tmp40_ = _tmp39_->title;
#line 73 "../src/Widgets/Note.vala"
	_tmp41_ = gtk_widget_get_style_context ((GtkWidget*) _tmp40_);
#line 73 "../src/Widgets/Note.vala"
	gtk_style_context_add_class (_tmp41_, "title-1");
#line 75 "../src/Widgets/Note.vala"
	_tmp42_ = self->subtitle;
#line 75 "../src/Widgets/Note.vala"
	_tmp43_ = (GtkLabel*) gtk_label_new (_tmp42_);
#line 75 "../src/Widgets/Note.vala"
	g_object_ref_sink (_tmp43_);
#line 75 "../src/Widgets/Note.vala"
	_data5_->subtitlelabel = _tmp43_;
#line 76 "../src/Widgets/Note.vala"
	_tmp44_ = _data5_->subtitlelabel;
#line 76 "../src/Widgets/Note.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp44_, GTK_ALIGN_START);
#line 77 "../src/Widgets/Note.vala"
	_tmp45_ = _data5_->subtitlelabel;
#line 77 "../src/Widgets/Note.vala"
	gtk_widget_set_margin_start ((GtkWidget*) _tmp45_, 40);
#line 78 "../src/Widgets/Note.vala"
	_tmp46_ = _data5_->subtitlelabel;
#line 78 "../src/Widgets/Note.vala"
	_tmp47_ = gtk_widget_get_style_context ((GtkWidget*) _tmp46_);
#line 78 "../src/Widgets/Note.vala"
	_tmp48_ = g_strdup_printf ("notejot-label-%d", self->uid);
#line 78 "../src/Widgets/Note.vala"
	_tmp49_ = _tmp48_;
#line 78 "../src/Widgets/Note.vala"
	gtk_style_context_add_class (_tmp47_, _tmp49_);
#line 78 "../src/Widgets/Note.vala"
	_g_free0 (_tmp49_);
#line 79 "../src/Widgets/Note.vala"
	_tmp50_ = _data5_->subtitlelabel;
#line 79 "../src/Widgets/Note.vala"
	_tmp51_ = gtk_widget_get_style_context ((GtkWidget*) _tmp50_);
#line 79 "../src/Widgets/Note.vala"
	gtk_style_context_add_class (_tmp51_, "dim-label");
#line 81 "../src/Widgets/Note.vala"
	_tmp52_ = (GtkSeparator*) gtk_separator_new (GTK_ORIENTATION_HORIZONTAL);
#line 81 "../src/Widgets/Note.vala"
	g_object_ref_sink (_tmp52_);
#line 81 "../src/Widgets/Note.vala"
	sep = _tmp52_;
#line 82 "../src/Widgets/Note.vala"
	_tmp53_ = sep;
#line 82 "../src/Widgets/Note.vala"
	gtk_widget_set_margin_top ((GtkWidget*) _tmp53_, 12);
#line 84 "../src/Widgets/Note.vala"
	_tmp54_ = notejot_widgets_format_bar_new (_data5_->win);
#line 84 "../src/Widgets/Note.vala"
	g_object_ref_sink (_tmp54_);
#line 84 "../src/Widgets/Note.vala"
	formatbar = _tmp54_;
#line 85 "../src/Widgets/Note.vala"
	_tmp55_ = formatbar;
#line 85 "../src/Widgets/Note.vala"
	_tmp56_ = self->textfield;
#line 85 "../src/Widgets/Note.vala"
	_tmp57_ = _g_object_ref0 (_tmp56_);
#line 85 "../src/Widgets/Note.vala"
	_g_object_unref0 (_tmp55_->controller);
#line 85 "../src/Widgets/Note.vala"
	_tmp55_->controller = _tmp57_;
#line 87 "../src/Widgets/Note.vala"
	_tmp58_ = (GtkGrid*) gtk_grid_new ();
#line 87 "../src/Widgets/Note.vala"
	g_object_ref_sink (_tmp58_);
#line 87 "../src/Widgets/Note.vala"
	_data5_->note_grid = _tmp58_;
#line 88 "../src/Widgets/Note.vala"
	_tmp59_ = _data5_->note_grid;
#line 88 "../src/Widgets/Note.vala"
	gtk_grid_set_column_spacing (_tmp59_, 12);
#line 89 "../src/Widgets/Note.vala"
	_tmp60_ = _data5_->note_grid;
#line 89 "../src/Widgets/Note.vala"
	_tmp61_ = self->titlelabel;
#line 89 "../src/Widgets/Note.vala"
	gtk_grid_attach (_tmp60_, (GtkWidget*) _tmp61_, 0, 0, 1, 1);
#line 90 "../src/Widgets/Note.vala"
	_tmp62_ = _data5_->note_grid;
#line 90 "../src/Widgets/Note.vala"
	_tmp63_ = _data5_->subtitlelabel;
#line 90 "../src/Widgets/Note.vala"
	gtk_grid_attach (_tmp62_, (GtkWidget*) _tmp63_, 0, 1, 1, 1);
#line 91 "../src/Widgets/Note.vala"
	_tmp64_ = _data5_->note_grid;
#line 91 "../src/Widgets/Note.vala"
	_tmp65_ = sep;
#line 91 "../src/Widgets/Note.vala"
	gtk_grid_attach (_tmp64_, (GtkWidget*) _tmp65_, 0, 2, 1, 1);
#line 92 "../src/Widgets/Note.vala"
	_tmp66_ = _data5_->note_grid;
#line 92 "../src/Widgets/Note.vala"
	_tmp67_ = text_scroller;
#line 92 "../src/Widgets/Note.vala"
	gtk_grid_attach (_tmp66_, (GtkWidget*) _tmp67_, 0, 3, 1, 1);
#line 93 "../src/Widgets/Note.vala"
	_tmp68_ = _data5_->note_grid;
#line 93 "../src/Widgets/Note.vala"
	_tmp69_ = formatbar;
#line 93 "../src/Widgets/Note.vala"
	gtk_grid_attach (_tmp68_, (GtkWidget*) _tmp69_, 0, 4, 1, 1);
#line 94 "../src/Widgets/Note.vala"
	_tmp70_ = _data5_->note_grid;
#line 94 "../src/Widgets/Note.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp70_);
#line 96 "../src/Widgets/Note.vala"
	_tmp71_ = _data5_->win->main_stack;
#line 96 "../src/Widgets/Note.vala"
	_tmp72_ = _data5_->note_grid;
#line 96 "../src/Widgets/Note.vala"
	_tmp73_ = g_strdup_printf ("textfield-%d", self->uid);
#line 96 "../src/Widgets/Note.vala"
	_tmp74_ = _tmp73_;
#line 96 "../src/Widgets/Note.vala"
	gtk_stack_add_named (_tmp71_, (GtkWidget*) _tmp72_, _tmp74_);
#line 96 "../src/Widgets/Note.vala"
	_g_free0 (_tmp74_);
#line 97 "../src/Widgets/Note.vala"
	_tmp75_ = _data5_->note_grid;
#line 97 "../src/Widgets/Note.vala"
	_tmp76_ = gtk_widget_get_style_context ((GtkWidget*) _tmp75_);
#line 97 "../src/Widgets/Note.vala"
	_tmp77_ = g_strdup_printf ("notejot-stack-%d", self->uid);
#line 97 "../src/Widgets/Note.vala"
	_tmp78_ = _tmp77_;
#line 97 "../src/Widgets/Note.vala"
	gtk_style_context_add_class (_tmp76_, _tmp78_);
#line 97 "../src/Widgets/Note.vala"
	_g_free0 (_tmp78_);
#line 99 "../src/Widgets/Note.vala"
	_tmp79_ = self->titlelabel;
#line 99 "../src/Widgets/Note.vala"
	g_signal_connect_data (_tmp79_, "changed", (GCallback) ___lambda44__notejot_widgets_editable_label_changed, block5_data_ref (_data5_), (GClosureNotify) block5_data_unref, 0);
#line 105 "../src/Widgets/Note.vala"
	g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) 1, ___lambda45__gsource_func, block5_data_ref (_data5_), block5_data_unref);
#line 128 "../src/Widgets/Note.vala"
	_tmp80_ = _data5_->subtitlelabel;
#line 128 "../src/Widgets/Note.vala"
	g_signal_connect_data ((GObject*) _tmp80_, "notify::get-text", (GCallback) ___lambda46__g_object_notify, block5_data_ref (_data5_), (GClosureNotify) block5_data_unref, 0);
#line 134 "../src/Widgets/Note.vala"
	_tmp81_ = notejot_application_gsettings;
#line 134 "../src/Widgets/Note.vala"
	if (g_settings_get_boolean (_tmp81_, "dark-mode")) {
#line 1440 "Note.c"
		GtkSettings* _tmp82_;
		NotejotWidgetsTextField* _tmp83_;
		GtkStyleContext* _tmp84_;
		gchar* _tmp85_;
		gchar* _tmp86_;
		GtkImage* _tmp87_;
		GtkStyleContext* _tmp88_;
		gchar* _tmp89_;
		gchar* _tmp90_;
		NotejotWidgetsEditableLabel* _tmp91_;
		GtkStyleContext* _tmp92_;
		gchar* _tmp93_;
		gchar* _tmp94_;
		GtkLabel* _tmp95_;
		GtkStyleContext* _tmp96_;
		gchar* _tmp97_;
		gchar* _tmp98_;
		GtkGrid* _tmp99_;
		GtkStyleContext* _tmp100_;
		gchar* _tmp101_;
		gchar* _tmp102_;
#line 135 "../src/Widgets/Note.vala"
		_tmp82_ = gtk_settings_get_default ();
#line 135 "../src/Widgets/Note.vala"
		g_object_set (_tmp82_, "gtk-application-prefer-dark-theme", TRUE, NULL);
#line 136 "../src/Widgets/Note.vala"
		_tmp83_ = self->textfield;
#line 136 "../src/Widgets/Note.vala"
		_tmp84_ = gtk_widget_get_style_context ((GtkWidget*) _tmp83_);
#line 136 "../src/Widgets/Note.vala"
		_tmp85_ = g_strdup_printf ("notejot-tview-dark-%d", self->uid);
#line 136 "../src/Widgets/Note.vala"
		_tmp86_ = _tmp85_;
#line 136 "../src/Widgets/Note.vala"
		gtk_style_context_add_class (_tmp84_, _tmp86_);
#line 136 "../src/Widgets/Note.vala"
		_g_free0 (_tmp86_);
#line 137 "../src/Widgets/Note.vala"
		_tmp87_ = _data5_->icon;
#line 137 "../src/Widgets/Note.vala"
		_tmp88_ = gtk_widget_get_style_context ((GtkWidget*) _tmp87_);
#line 137 "../src/Widgets/Note.vala"
		_tmp89_ = g_strdup_printf ("notejot-sidebar-dbg-dark-%d", self->uid);
#line 137 "../src/Widgets/Note.vala"
		_tmp90_ = _tmp89_;
#line 137 "../src/Widgets/Note.vala"
		gtk_style_context_add_class (_tmp88_, _tmp90_);
#line 137 "../src/Widgets/Note.vala"
		_g_free0 (_tmp90_);
#line 138 "../src/Widgets/Note.vala"
		_tmp91_ = self->titlelabel;
#line 138 "../src/Widgets/Note.vala"
		_tmp92_ = gtk_widget_get_style_context ((GtkWidget*) _tmp91_);
#line 138 "../src/Widgets/Note.vala"
		_tmp93_ = g_strdup_printf ("notejot-label-dark-%d", self->uid);
#line 138 "../src/Widgets/Note.vala"
		_tmp94_ = _tmp93_;
#line 138 "../src/Widgets/Note.vala"
		gtk_style_context_add_class (_tmp92_, _tmp94_);
#line 138 "../src/Widgets/Note.vala"
		_g_free0 (_tmp94_);
#line 139 "../src/Widgets/Note.vala"
		_tmp95_ = _data5_->subtitlelabel;
#line 139 "../src/Widgets/Note.vala"
		_tmp96_ = gtk_widget_get_style_context ((GtkWidget*) _tmp95_);
#line 139 "../src/Widgets/Note.vala"
		_tmp97_ = g_strdup_printf ("notejot-label-dark-%d", self->uid);
#line 139 "../src/Widgets/Note.vala"
		_tmp98_ = _tmp97_;
#line 139 "../src/Widgets/Note.vala"
		gtk_style_context_add_class (_tmp96_, _tmp98_);
#line 139 "../src/Widgets/Note.vala"
		_g_free0 (_tmp98_);
#line 140 "../src/Widgets/Note.vala"
		_tmp99_ = _data5_->note_grid;
#line 140 "../src/Widgets/Note.vala"
		_tmp100_ = gtk_widget_get_style_context ((GtkWidget*) _tmp99_);
#line 140 "../src/Widgets/Note.vala"
		_tmp101_ = g_strdup_printf ("notejot-stack-dark-%d", self->uid);
#line 140 "../src/Widgets/Note.vala"
		_tmp102_ = _tmp101_;
#line 140 "../src/Widgets/Note.vala"
		gtk_style_context_add_class (_tmp100_, _tmp102_);
#line 140 "../src/Widgets/Note.vala"
		_g_free0 (_tmp102_);
#line 1526 "Note.c"
	} else {
		GtkSettings* _tmp103_;
		NotejotWidgetsTextField* _tmp104_;
		GtkStyleContext* _tmp105_;
		gchar* _tmp106_;
		gchar* _tmp107_;
		GtkImage* _tmp108_;
		GtkStyleContext* _tmp109_;
		gchar* _tmp110_;
		gchar* _tmp111_;
		NotejotWidgetsEditableLabel* _tmp112_;
		GtkStyleContext* _tmp113_;
		gchar* _tmp114_;
		gchar* _tmp115_;
		GtkLabel* _tmp116_;
		GtkStyleContext* _tmp117_;
		gchar* _tmp118_;
		gchar* _tmp119_;
		GtkGrid* _tmp120_;
		GtkStyleContext* _tmp121_;
		gchar* _tmp122_;
		gchar* _tmp123_;
#line 142 "../src/Widgets/Note.vala"
		_tmp103_ = gtk_settings_get_default ();
#line 142 "../src/Widgets/Note.vala"
		g_object_set (_tmp103_, "gtk-application-prefer-dark-theme", FALSE, NULL);
#line 143 "../src/Widgets/Note.vala"
		_tmp104_ = self->textfield;
#line 143 "../src/Widgets/Note.vala"
		_tmp105_ = gtk_widget_get_style_context ((GtkWidget*) _tmp104_);
#line 143 "../src/Widgets/Note.vala"
		_tmp106_ = g_strdup_printf ("notejot-tview-dark-%d", self->uid);
#line 143 "../src/Widgets/Note.vala"
		_tmp107_ = _tmp106_;
#line 143 "../src/Widgets/Note.vala"
		gtk_style_context_remove_class (_tmp105_, _tmp107_);
#line 143 "../src/Widgets/Note.vala"
		_g_free0 (_tmp107_);
#line 144 "../src/Widgets/Note.vala"
		_tmp108_ = _data5_->icon;
#line 144 "../src/Widgets/Note.vala"
		_tmp109_ = gtk_widget_get_style_context ((GtkWidget*) _tmp108_);
#line 144 "../src/Widgets/Note.vala"
		_tmp110_ = g_strdup_printf ("notejot-sidebar-dbg-dark-%d", self->uid);
#line 144 "../src/Widgets/Note.vala"
		_tmp111_ = _tmp110_;
#line 144 "../src/Widgets/Note.vala"
		gtk_style_context_remove_class (_tmp109_, _tmp111_);
#line 144 "../src/Widgets/Note.vala"
		_g_free0 (_tmp111_);
#line 145 "../src/Widgets/Note.vala"
		_tmp112_ = self->titlelabel;
#line 145 "../src/Widgets/Note.vala"
		_tmp113_ = gtk_widget_get_style_context ((GtkWidget*) _tmp112_);
#line 145 "../src/Widgets/Note.vala"
		_tmp114_ = g_strdup_printf ("notejot-label-dark-%d", self->uid);
#line 145 "../src/Widgets/Note.vala"
		_tmp115_ = _tmp114_;
#line 145 "../src/Widgets/Note.vala"
		gtk_style_context_remove_class (_tmp113_, _tmp115_);
#line 145 "../src/Widgets/Note.vala"
		_g_free0 (_tmp115_);
#line 146 "../src/Widgets/Note.vala"
		_tmp116_ = _data5_->subtitlelabel;
#line 146 "../src/Widgets/Note.vala"
		_tmp117_ = gtk_widget_get_style_context ((GtkWidget*) _tmp116_);
#line 146 "../src/Widgets/Note.vala"
		_tmp118_ = g_strdup_printf ("notejot-label-dark-%d", self->uid);
#line 146 "../src/Widgets/Note.vala"
		_tmp119_ = _tmp118_;
#line 146 "../src/Widgets/Note.vala"
		gtk_style_context_remove_class (_tmp117_, _tmp119_);
#line 146 "../src/Widgets/Note.vala"
		_g_free0 (_tmp119_);
#line 147 "../src/Widgets/Note.vala"
		_tmp120_ = _data5_->note_grid;
#line 147 "../src/Widgets/Note.vala"
		_tmp121_ = gtk_widget_get_style_context ((GtkWidget*) _tmp120_);
#line 147 "../src/Widgets/Note.vala"
		_tmp122_ = g_strdup_printf ("notejot-stack-dark-%d", self->uid);
#line 147 "../src/Widgets/Note.vala"
		_tmp123_ = _tmp122_;
#line 147 "../src/Widgets/Note.vala"
		gtk_style_context_remove_class (_tmp121_, _tmp123_);
#line 147 "../src/Widgets/Note.vala"
		_g_free0 (_tmp123_);
#line 1613 "Note.c"
	}
#line 150 "../src/Widgets/Note.vala"
	_tmp124_ = notejot_application_gsettings;
#line 150 "../src/Widgets/Note.vala"
	g_signal_connect_data (_tmp124_, "changed", (GCallback) ___lambda47__g_settings_changed, block5_data_ref (_data5_), (GClosureNotify) block5_data_unref, 0);
#line 32 "../src/Widgets/Note.vala"
	_g_object_unref0 (formatbar);
#line 32 "../src/Widgets/Note.vala"
	_g_object_unref0 (sep);
#line 32 "../src/Widgets/Note.vala"
	_g_object_unref0 (text_scroller);
#line 32 "../src/Widgets/Note.vala"
	block5_data_unref (_data5_);
#line 32 "../src/Widgets/Note.vala"
	_data5_ = NULL;
#line 32 "../src/Widgets/Note.vala"
	return self;
#line 1631 "Note.c"
}

NotejotWidgetsNote*
notejot_widgets_note_new (NotejotMainWindow* win,
                          const gchar* title,
                          const gchar* subtitle,
                          const gchar* text,
                          const gchar* color)
{
#line 32 "../src/Widgets/Note.vala"
	return notejot_widgets_note_construct (NOTEJOT_WIDGETS_TYPE_NOTE, win, title, subtitle, text, color);
#line 1643 "Note.c"
}

void
notejot_widgets_note_destroy_item (NotejotWidgetsNote* self)
{
	GtkCssProvider* _tmp0_;
#line 169 "../src/Widgets/Note.vala"
	g_return_if_fail (self != NULL);
#line 170 "../src/Widgets/Note.vala"
	g_object_run_dispose ((GObject*) self);
#line 171 "../src/Widgets/Note.vala"
	_tmp0_ = self->priv->css_provider;
#line 171 "../src/Widgets/Note.vala"
	g_object_run_dispose ((GObject*) _tmp0_);
#line 1658 "Note.c"
}

void
notejot_widgets_note_select_item (NotejotWidgetsNote* self)
{
	NotejotMainWindow* _tmp0_;
	GtkStack* _tmp1_;
#line 174 "../src/Widgets/Note.vala"
	g_return_if_fail (self != NULL);
#line 175 "../src/Widgets/Note.vala"
	_tmp0_ = self->priv->win;
#line 175 "../src/Widgets/Note.vala"
	_tmp1_ = _tmp0_->main_stack;
#line 175 "../src/Widgets/Note.vala"
	if (_tmp1_ != NULL) {
#line 1674 "Note.c"
		NotejotMainWindow* _tmp2_;
		GtkStack* _tmp3_;
		gchar* _tmp4_;
		gchar* _tmp5_;
#line 176 "../src/Widgets/Note.vala"
		_tmp2_ = self->priv->win;
#line 176 "../src/Widgets/Note.vala"
		_tmp3_ = _tmp2_->main_stack;
#line 176 "../src/Widgets/Note.vala"
		_tmp4_ = g_strdup_printf ("textfield-%d", self->uid);
#line 176 "../src/Widgets/Note.vala"
		_tmp5_ = _tmp4_;
#line 176 "../src/Widgets/Note.vala"
		gtk_stack_set_visible_child_name (_tmp3_, _tmp5_);
#line 176 "../src/Widgets/Note.vala"
		_g_free0 (_tmp5_);
#line 1691 "Note.c"
	}
}

void
notejot_widgets_note_update_theme (NotejotWidgetsNote* self,
                                   const gchar* color)
{
	GtkCssProvider* _tmp0_;
	gchar* style = NULL;
	gchar* _tmp1_;
	GdkScreen* _tmp6_;
	GtkCssProvider* _tmp7_;
	gchar* _tmp8_;
	NotejotMainWindow* _tmp9_;
	NotejotTaskManager* _tmp10_;
	GError* _inner_error0_ = NULL;
#line 180 "../src/Widgets/Note.vala"
	g_return_if_fail (self != NULL);
#line 181 "../src/Widgets/Note.vala"
	_tmp0_ = gtk_css_provider_new ();
#line 181 "../src/Widgets/Note.vala"
	_g_object_unref0 (self->priv->css_provider);
#line 181 "../src/Widgets/Note.vala"
	self->priv->css_provider = _tmp0_;
#line 182 "../src/Widgets/Note.vala"
	style = NULL;
#line 183 "../src/Widgets/Note.vala"
	_tmp1_ = g_strdup_printf (N_ ("\n" \
"            .notejot-sidebar-dbg-%d {\n" \
"                border: 1px solid alpha(black, 0.25);\n" \
"                background: %s;\n" \
"                border-radius: 50px;\n" \
"            }\n" \
"            .notejot-sidebar-dbg-dark-%d {\n" \
"                border: 1px solid alpha(black, 0.25);\n" \
"                background: shade(%s, 0.8);\n" \
"                border-radius: 50px;\n" \
"            }\n" \
"            .notejot-label-%d {\n" \
"                background: mix(%s, @theme_bg_color, 0.8);\n" \
"            }\n" \
"            .notejot-label-dark-%d {\n" \
"                background: mix(%s, @theme_bg_color, 0.8);\n" \
"            }\n" \
"            .notejot-stack-%d {\n" \
"                background: mix(%s, @theme_bg_color, 0.8);\n" \
"            }\n" \
"            .notejot-stack-dark-%d {\n" \
"                background: mix(%s, @theme_bg_color, 0.8);\n" \
"            }\n" \
"            "), self->uid, color, self->uid, color, self->uid, color, self->uid, color, self->uid, color, self->uid, color);
#line 183 "../src/Widgets/Note.vala"
	_g_free0 (style);
#line 183 "../src/Widgets/Note.vala"
	style = _tmp1_;
#line 1724 "Note.c"
	{
		GtkCssProvider* _tmp2_;
		const gchar* _tmp3_;
#line 209 "../src/Widgets/Note.vala"
		_tmp2_ = self->priv->css_provider;
#line 209 "../src/Widgets/Note.vala"
		_tmp3_ = style;
#line 209 "../src/Widgets/Note.vala"
		gtk_css_provider_load_from_data (_tmp2_, _tmp3_, (gssize) -1, &_inner_error0_);
#line 209 "../src/Widgets/Note.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1736 "Note.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp4_;
		const gchar* _tmp5_;
#line 208 "../src/Widgets/Note.vala"
		e = _inner_error0_;
#line 208 "../src/Widgets/Note.vala"
		_inner_error0_ = NULL;
#line 211 "../src/Widgets/Note.vala"
		_tmp4_ = e;
#line 211 "../src/Widgets/Note.vala"
		_tmp5_ = _tmp4_->message;
#line 211 "../src/Widgets/Note.vala"
		g_warning ("Note.vala:211: Failed to parse css style : %s", _tmp5_);
#line 208 "../src/Widgets/Note.vala"
		_g_error_free0 (e);
#line 1758 "Note.c"
	}
	__finally0:
#line 208 "../src/Widgets/Note.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 208 "../src/Widgets/Note.vala"
		_g_free0 (style);
#line 208 "../src/Widgets/Note.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 208 "../src/Widgets/Note.vala"
		g_clear_error (&_inner_error0_);
#line 208 "../src/Widgets/Note.vala"
		return;
#line 1771 "Note.c"
	}
#line 214 "../src/Widgets/Note.vala"
	_tmp6_ = gdk_screen_get_default ();
#line 214 "../src/Widgets/Note.vala"
	_tmp7_ = self->priv->css_provider;
#line 214 "../src/Widgets/Note.vala"
	gtk_style_context_add_provider_for_screen (_tmp6_, (GtkStyleProvider*) _tmp7_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
#line 220 "../src/Widgets/Note.vala"
	_tmp8_ = g_strdup (color);
#line 220 "../src/Widgets/Note.vala"
	_g_free0 (self->color);
#line 220 "../src/Widgets/Note.vala"
	self->color = _tmp8_;
#line 221 "../src/Widgets/Note.vala"
	_tmp9_ = self->priv->win;
#line 221 "../src/Widgets/Note.vala"
	_tmp10_ = _tmp9_->tm;
#line 221 "../src/Widgets/Note.vala"
	notejot_task_manager_save_notes (_tmp10_, NULL, NULL);
#line 180 "../src/Widgets/Note.vala"
	_g_free0 (style);
#line 1793 "Note.c"
}

static void
__lambda25_ (NotejotWidgetsNote* self)
{
	NotejotMainWindow* _tmp0_;
	NotejotViewsTrashView* _tmp1_;
	NotejotMainWindow* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	NotejotMainWindow* _tmp7_;
	GtkStack* _tmp8_;
	NotejotMainWindow* _tmp9_;
	GtkBox* _tmp10_;
	GtkWidget* row = NULL;
	NotejotMainWindow* _tmp11_;
	GtkStack* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	GtkWidget* _tmp15_;
	GtkWidget* _tmp16_;
	GtkWidget* _tmp17_;
	NotejotMainWindow* _tmp18_;
	GtkStack* _tmp19_;
	NotejotMainWindow* _tmp20_;
	NotejotTaskManager* _tmp21_;
	NotejotMainWindow* _tmp22_;
	NotejotWidgetsSettingMenu* _tmp23_;
#line 226 "../src/Widgets/Note.vala"
	_tmp0_ = self->priv->win;
#line 226 "../src/Widgets/Note.vala"
	_tmp1_ = _tmp0_->trashview;
#line 226 "../src/Widgets/Note.vala"
	_tmp2_ = self->priv->win;
#line 226 "../src/Widgets/Note.vala"
	_tmp3_ = self->title;
#line 226 "../src/Widgets/Note.vala"
	_tmp4_ = self->subtitle;
#line 226 "../src/Widgets/Note.vala"
	_tmp5_ = self->text;
#line 226 "../src/Widgets/Note.vala"
	_tmp6_ = self->color;
#line 226 "../src/Widgets/Note.vala"
	notejot_views_trash_view_new_taskbox (_tmp1_, _tmp2_, _tmp3_, _tmp4_, _tmp5_, _tmp6_, NULL, NULL);
#line 227 "../src/Widgets/Note.vala"
	_tmp7_ = self->priv->win;
#line 227 "../src/Widgets/Note.vala"
	_tmp8_ = _tmp7_->main_stack;
#line 227 "../src/Widgets/Note.vala"
	_tmp9_ = self->priv->win;
#line 227 "../src/Widgets/Note.vala"
	_tmp10_ = _tmp9_->empty_state;
#line 227 "../src/Widgets/Note.vala"
	gtk_stack_set_visible_child (_tmp8_, (GtkWidget*) _tmp10_);
#line 228 "../src/Widgets/Note.vala"
	_tmp11_ = self->priv->win;
#line 228 "../src/Widgets/Note.vala"
	_tmp12_ = _tmp11_->main_stack;
#line 228 "../src/Widgets/Note.vala"
	_tmp13_ = g_strdup_printf ("textfield-%d", self->uid);
#line 228 "../src/Widgets/Note.vala"
	_tmp14_ = _tmp13_;
#line 228 "../src/Widgets/Note.vala"
	_tmp15_ = gtk_stack_get_child_by_name (_tmp12_, _tmp14_);
#line 228 "../src/Widgets/Note.vala"
	_tmp16_ = _g_object_ref0 (_tmp15_);
#line 228 "../src/Widgets/Note.vala"
	_tmp17_ = _tmp16_;
#line 228 "../src/Widgets/Note.vala"
	_g_free0 (_tmp14_);
#line 228 "../src/Widgets/Note.vala"
	row = _tmp17_;
#line 229 "../src/Widgets/Note.vala"
	_tmp18_ = self->priv->win;
#line 229 "../src/Widgets/Note.vala"
	_tmp19_ = _tmp18_->main_stack;
#line 229 "../src/Widgets/Note.vala"
	gtk_container_remove ((GtkContainer*) _tmp19_, row);
#line 230 "../src/Widgets/Note.vala"
	notejot_widgets_note_destroy_item (self);
#line 231 "../src/Widgets/Note.vala"
	_tmp20_ = self->priv->win;
#line 231 "../src/Widgets/Note.vala"
	_tmp21_ = _tmp20_->tm;
#line 231 "../src/Widgets/Note.vala"
	notejot_task_manager_save_notes (_tmp21_, NULL, NULL);
#line 232 "../src/Widgets/Note.vala"
	_tmp22_ = self->priv->win;
#line 232 "../src/Widgets/Note.vala"
	_tmp23_ = _tmp22_->settingmenu;
#line 232 "../src/Widgets/Note.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp23_, FALSE);
#line 225 "../src/Widgets/Note.vala"
	_g_object_unref0 (row);
#line 1890 "Note.c"
}

static void
___lambda25__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 225 "../src/Widgets/Note.vala"
	__lambda25_ ((NotejotWidgetsNote*) self);
#line 1899 "Note.c"
}

static void
__lambda26_ (NotejotWidgetsNote* self)
{
#line 236 "../src/Widgets/Note.vala"
	notejot_widgets_note_update_theme (self, "#f66151");
#line 1907 "Note.c"
}

static void
___lambda26__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 235 "../src/Widgets/Note.vala"
	__lambda26_ ((NotejotWidgetsNote*) self);
#line 1916 "Note.c"
}

static void
__lambda27_ (NotejotWidgetsNote* self)
{
#line 240 "../src/Widgets/Note.vala"
	notejot_widgets_note_update_theme (self, "#ffbe6f");
#line 1924 "Note.c"
}

static void
___lambda27__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 239 "../src/Widgets/Note.vala"
	__lambda27_ ((NotejotWidgetsNote*) self);
#line 1933 "Note.c"
}

static void
__lambda28_ (NotejotWidgetsNote* self)
{
#line 244 "../src/Widgets/Note.vala"
	notejot_widgets_note_update_theme (self, "#f9f06b");
#line 1941 "Note.c"
}

static void
___lambda28__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 243 "../src/Widgets/Note.vala"
	__lambda28_ ((NotejotWidgetsNote*) self);
#line 1950 "Note.c"
}

static void
__lambda29_ (NotejotWidgetsNote* self)
{
#line 248 "../src/Widgets/Note.vala"
	notejot_widgets_note_update_theme (self, "#8ff0a4");
#line 1958 "Note.c"
}

static void
___lambda29__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 247 "../src/Widgets/Note.vala"
	__lambda29_ ((NotejotWidgetsNote*) self);
#line 1967 "Note.c"
}

static void
__lambda30_ (NotejotWidgetsNote* self)
{
#line 252 "../src/Widgets/Note.vala"
	notejot_widgets_note_update_theme (self, "#99c1f1");
#line 1975 "Note.c"
}

static void
___lambda30__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 251 "../src/Widgets/Note.vala"
	__lambda30_ ((NotejotWidgetsNote*) self);
#line 1984 "Note.c"
}

static void
__lambda31_ (NotejotWidgetsNote* self)
{
#line 256 "../src/Widgets/Note.vala"
	notejot_widgets_note_update_theme (self, "#dc8add");
#line 1992 "Note.c"
}

static void
___lambda31__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 255 "../src/Widgets/Note.vala"
	__lambda31_ ((NotejotWidgetsNote*) self);
#line 2001 "Note.c"
}

static void
__lambda32_ (NotejotWidgetsNote* self)
{
#line 260 "../src/Widgets/Note.vala"
	notejot_widgets_note_update_theme (self, "#cdab8f");
#line 2009 "Note.c"
}

static void
___lambda32__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 259 "../src/Widgets/Note.vala"
	__lambda32_ ((NotejotWidgetsNote*) self);
#line 2018 "Note.c"
}

static void
__lambda33_ (NotejotWidgetsNote* self)
{
#line 264 "../src/Widgets/Note.vala"
	notejot_widgets_note_update_theme (self, "#ffffff");
#line 2026 "Note.c"
}

static void
___lambda33__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 263 "../src/Widgets/Note.vala"
	__lambda33_ ((NotejotWidgetsNote*) self);
#line 2035 "Note.c"
}

void
notejot_widgets_note_popover_listener (NotejotWidgetsNote* self,
                                       NotejotWidgetsNoteMenuPopover* popover)
{
	GtkModelButton* _tmp0_;
	GtkRadioButton* _tmp1_;
	GtkRadioButton* _tmp2_;
	GtkRadioButton* _tmp3_;
	GtkRadioButton* _tmp4_;
	GtkRadioButton* _tmp5_;
	GtkRadioButton* _tmp6_;
	GtkRadioButton* _tmp7_;
	GtkRadioButton* _tmp8_;
#line 224 "../src/Widgets/Note.vala"
	g_return_if_fail (self != NULL);
#line 225 "../src/Widgets/Note.vala"
	_tmp0_ = popover->delete_note_button;
#line 225 "../src/Widgets/Note.vala"
	g_signal_connect_object ((GtkButton*) _tmp0_, "clicked", (GCallback) ___lambda25__gtk_button_clicked, self, 0);
#line 235 "../src/Widgets/Note.vala"
	_tmp1_ = popover->color_button_red;
#line 235 "../src/Widgets/Note.vala"
	g_signal_connect_object ((GtkButton*) _tmp1_, "clicked", (GCallback) ___lambda26__gtk_button_clicked, self, 0);
#line 239 "../src/Widgets/Note.vala"
	_tmp2_ = popover->color_button_orange;
#line 239 "../src/Widgets/Note.vala"
	g_signal_connect_object ((GtkButton*) _tmp2_, "clicked", (GCallback) ___lambda27__gtk_button_clicked, self, 0);
#line 243 "../src/Widgets/Note.vala"
	_tmp3_ = popover->color_button_yellow;
#line 243 "../src/Widgets/Note.vala"
	g_signal_connect_object ((GtkButton*) _tmp3_, "clicked", (GCallback) ___lambda28__gtk_button_clicked, self, 0);
#line 247 "../src/Widgets/Note.vala"
	_tmp4_ = popover->color_button_green;
#line 247 "../src/Widgets/Note.vala"
	g_signal_connect_object ((GtkButton*) _tmp4_, "clicked", (GCallback) ___lambda29__gtk_button_clicked, self, 0);
#line 251 "../src/Widgets/Note.vala"
	_tmp5_ = popover->color_button_blue;
#line 251 "../src/Widgets/Note.vala"
	g_signal_connect_object ((GtkButton*) _tmp5_, "clicked", (GCallback) ___lambda30__gtk_button_clicked, self, 0);
#line 255 "../src/Widgets/Note.vala"
	_tmp6_ = popover->color_button_purple;
#line 255 "../src/Widgets/Note.vala"
	g_signal_connect_object ((GtkButton*) _tmp6_, "clicked", (GCallback) ___lambda31__gtk_button_clicked, self, 0);
#line 259 "../src/Widgets/Note.vala"
	_tmp7_ = popover->color_button_brown;
#line 259 "../src/Widgets/Note.vala"
	g_signal_connect_object ((GtkButton*) _tmp7_, "clicked", (GCallback) ___lambda32__gtk_button_clicked, self, 0);
#line 263 "../src/Widgets/Note.vala"
	_tmp8_ = popover->color_button_reset;
#line 263 "../src/Widgets/Note.vala"
	g_signal_connect_object ((GtkButton*) _tmp8_, "clicked", (GCallback) ___lambda33__gtk_button_clicked, self, 0);
#line 2089 "Note.c"
}

static void
notejot_widgets_note_class_init (NotejotWidgetsNoteClass * klass,
                                 gpointer klass_data)
{
#line 20 "../src/Widgets/Note.vala"
	notejot_widgets_note_parent_class = g_type_class_peek_parent (klass);
#line 20 "../src/Widgets/Note.vala"
	g_type_class_adjust_private_offset (klass, &NotejotWidgetsNote_private_offset);
#line 20 "../src/Widgets/Note.vala"
	G_OBJECT_CLASS (klass)->finalize = notejot_widgets_note_finalize;
#line 2102 "Note.c"
}

static void
notejot_widgets_note_instance_init (NotejotWidgetsNote * self,
                                    gpointer klass)
{
#line 20 "../src/Widgets/Note.vala"
	self->priv = notejot_widgets_note_get_instance_private (self);
#line 2111 "Note.c"
}

static void
notejot_widgets_note_finalize (GObject * obj)
{
	NotejotWidgetsNote * self;
#line 20 "../src/Widgets/Note.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote);
#line 21 "../src/Widgets/Note.vala"
	_g_object_unref0 (self->priv->win);
#line 22 "../src/Widgets/Note.vala"
	_g_object_unref0 (self->textfield);
#line 23 "../src/Widgets/Note.vala"
	_g_object_unref0 (self->titlelabel);
#line 26 "../src/Widgets/Note.vala"
	_g_free0 (self->title);
#line 27 "../src/Widgets/Note.vala"
	_g_free0 (self->subtitle);
#line 28 "../src/Widgets/Note.vala"
	_g_free0 (self->text);
#line 29 "../src/Widgets/Note.vala"
	_g_free0 (self->color);
#line 30 "../src/Widgets/Note.vala"
	_g_object_unref0 (self->priv->css_provider);
#line 20 "../src/Widgets/Note.vala"
	G_OBJECT_CLASS (notejot_widgets_note_parent_class)->finalize (obj);
#line 2138 "Note.c"
}

static GType
notejot_widgets_note_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (NotejotWidgetsNoteClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) notejot_widgets_note_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NotejotWidgetsNote), 0, (GInstanceInitFunc) notejot_widgets_note_instance_init, NULL };
	GType notejot_widgets_note_type_id;
	notejot_widgets_note_type_id = g_type_register_static (hdy_action_row_get_type (), "NotejotWidgetsNote", &g_define_type_info, 0);
	NotejotWidgetsNote_private_offset = g_type_add_instance_private (notejot_widgets_note_type_id, sizeof (NotejotWidgetsNotePrivate));
	return notejot_widgets_note_type_id;
}

GType
notejot_widgets_note_get_type (void)
{
	static volatile gsize notejot_widgets_note_type_id__volatile = 0;
	if (g_once_init_enter (&notejot_widgets_note_type_id__volatile)) {
		GType notejot_widgets_note_type_id;
		notejot_widgets_note_type_id = notejot_widgets_note_get_type_once ();
		g_once_init_leave (&notejot_widgets_note_type_id__volatile, notejot_widgets_note_type_id);
	}
	return notejot_widgets_note_type_id__volatile;
}

