/* SettingMenu.c generated by valac 0.50.3, the Vala compiler
 * generated from SettingMenu.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <handy.h>
#include <glib.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <webkit2/webkit2.h>
#include <glib/gi18n-lib.h>

#define NOTEJOT_WIDGETS_TYPE_SETTING_MENU (notejot_widgets_setting_menu_get_type ())
#define NOTEJOT_WIDGETS_SETTING_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenu))
#define NOTEJOT_WIDGETS_SETTING_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenuClass))
#define NOTEJOT_WIDGETS_IS_SETTING_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU))
#define NOTEJOT_WIDGETS_IS_SETTING_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_SETTING_MENU))
#define NOTEJOT_WIDGETS_SETTING_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenuClass))

typedef struct _NotejotWidgetsSettingMenu NotejotWidgetsSettingMenu;
typedef struct _NotejotWidgetsSettingMenuClass NotejotWidgetsSettingMenuClass;
typedef struct _NotejotWidgetsSettingMenuPrivate NotejotWidgetsSettingMenuPrivate;

#define NOTEJOT_WIDGETS_TYPE_NOTE (notejot_widgets_note_get_type ())
#define NOTEJOT_WIDGETS_NOTE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote))
#define NOTEJOT_WIDGETS_NOTE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNoteClass))
#define NOTEJOT_WIDGETS_IS_NOTE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_NOTE))
#define NOTEJOT_WIDGETS_IS_NOTE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_NOTE))
#define NOTEJOT_WIDGETS_NOTE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNoteClass))

typedef struct _NotejotWidgetsNote NotejotWidgetsNote;
typedef struct _NotejotWidgetsNoteClass NotejotWidgetsNoteClass;

#define NOTEJOT_TYPE_MAIN_WINDOW (notejot_main_window_get_type ())
#define NOTEJOT_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindow))
#define NOTEJOT_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindowClass))
#define NOTEJOT_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_TYPE_MAIN_WINDOW))
#define NOTEJOT_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_TYPE_MAIN_WINDOW))
#define NOTEJOT_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindowClass))

typedef struct _NotejotMainWindow NotejotMainWindow;
typedef struct _NotejotMainWindowClass NotejotMainWindowClass;
enum  {
	NOTEJOT_WIDGETS_SETTING_MENU_0_PROPERTY,
	NOTEJOT_WIDGETS_SETTING_MENU_NUM_PROPERTIES
};
static GParamSpec* notejot_widgets_setting_menu_properties[NOTEJOT_WIDGETS_SETTING_MENU_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block4Data Block4Data;

#define NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER (notejot_widgets_note_menu_popover_get_type ())
#define NOTEJOT_WIDGETS_NOTE_MENU_POPOVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER, NotejotWidgetsNoteMenuPopover))
#define NOTEJOT_WIDGETS_NOTE_MENU_POPOVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER, NotejotWidgetsNoteMenuPopoverClass))
#define NOTEJOT_WIDGETS_IS_NOTE_MENU_POPOVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER))
#define NOTEJOT_WIDGETS_IS_NOTE_MENU_POPOVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER))
#define NOTEJOT_WIDGETS_NOTE_MENU_POPOVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER, NotejotWidgetsNoteMenuPopoverClass))

typedef struct _NotejotWidgetsNoteMenuPopover NotejotWidgetsNoteMenuPopover;
typedef struct _NotejotWidgetsNoteMenuPopoverClass NotejotWidgetsNoteMenuPopoverClass;
typedef struct _NotejotWidgetsNoteMenuPopoverPrivate NotejotWidgetsNoteMenuPopoverPrivate;
typedef struct _NotejotMainWindowPrivate NotejotMainWindowPrivate;

#define NOTEJOT_WIDGETS_TYPE_DIALOG (notejot_widgets_dialog_get_type ())
#define NOTEJOT_WIDGETS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialog))
#define NOTEJOT_WIDGETS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialogClass))
#define NOTEJOT_WIDGETS_IS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG))
#define NOTEJOT_WIDGETS_IS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_DIALOG))
#define NOTEJOT_WIDGETS_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialogClass))

typedef struct _NotejotWidgetsDialog NotejotWidgetsDialog;
typedef struct _NotejotWidgetsDialogClass NotejotWidgetsDialogClass;

#define NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON (notejot_widgets_header_bar_button_get_type ())
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButton))
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButtonClass))
#define NOTEJOT_WIDGETS_IS_HEADER_BAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON))
#define NOTEJOT_WIDGETS_IS_HEADER_BAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON))
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButtonClass))

typedef struct _NotejotWidgetsHeaderBarButton NotejotWidgetsHeaderBarButton;
typedef struct _NotejotWidgetsHeaderBarButtonClass NotejotWidgetsHeaderBarButtonClass;

#define NOTEJOT_VIEWS_TYPE_LIST_VIEW (notejot_views_list_view_get_type ())
#define NOTEJOT_VIEWS_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListView))
#define NOTEJOT_VIEWS_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListViewClass))
#define NOTEJOT_VIEWS_IS_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW))
#define NOTEJOT_VIEWS_IS_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_VIEWS_TYPE_LIST_VIEW))
#define NOTEJOT_VIEWS_LIST_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListViewClass))

typedef struct _NotejotViewsListView NotejotViewsListView;
typedef struct _NotejotViewsListViewClass NotejotViewsListViewClass;

#define NOTEJOT_VIEWS_TYPE_TRASH_VIEW (notejot_views_trash_view_get_type ())
#define NOTEJOT_VIEWS_TRASH_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashView))
#define NOTEJOT_VIEWS_TRASH_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashViewClass))
#define NOTEJOT_VIEWS_IS_TRASH_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW))
#define NOTEJOT_VIEWS_IS_TRASH_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_VIEWS_TYPE_TRASH_VIEW))
#define NOTEJOT_VIEWS_TRASH_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashViewClass))

typedef struct _NotejotViewsTrashView NotejotViewsTrashView;
typedef struct _NotejotViewsTrashViewClass NotejotViewsTrashViewClass;

#define NOTEJOT_TYPE_TASK_MANAGER (notejot_task_manager_get_type ())
#define NOTEJOT_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManager))
#define NOTEJOT_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManagerClass))
#define NOTEJOT_IS_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_TYPE_TASK_MANAGER))
#define NOTEJOT_IS_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_TYPE_TASK_MANAGER))
#define NOTEJOT_TASK_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManagerClass))

typedef struct _NotejotTaskManager NotejotTaskManager;
typedef struct _NotejotTaskManagerClass NotejotTaskManagerClass;
typedef struct _NotejotWidgetsNotePrivate NotejotWidgetsNotePrivate;

#define NOTEJOT_WIDGETS_TYPE_TEXT_FIELD (notejot_widgets_text_field_get_type ())
#define NOTEJOT_WIDGETS_TEXT_FIELD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD, NotejotWidgetsTextField))
#define NOTEJOT_WIDGETS_TEXT_FIELD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD, NotejotWidgetsTextFieldClass))
#define NOTEJOT_WIDGETS_IS_TEXT_FIELD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD))
#define NOTEJOT_WIDGETS_IS_TEXT_FIELD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD))
#define NOTEJOT_WIDGETS_TEXT_FIELD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD, NotejotWidgetsTextFieldClass))

typedef struct _NotejotWidgetsTextField NotejotWidgetsTextField;
typedef struct _NotejotWidgetsTextFieldClass NotejotWidgetsTextFieldClass;

#define NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL (notejot_widgets_editable_label_get_type ())
#define NOTEJOT_WIDGETS_EDITABLE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabel))
#define NOTEJOT_WIDGETS_EDITABLE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabelClass))
#define NOTEJOT_WIDGETS_IS_EDITABLE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL))
#define NOTEJOT_WIDGETS_IS_EDITABLE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL))
#define NOTEJOT_WIDGETS_EDITABLE_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabelClass))

typedef struct _NotejotWidgetsEditableLabel NotejotWidgetsEditableLabel;
typedef struct _NotejotWidgetsEditableLabelClass NotejotWidgetsEditableLabelClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _NotejotWidgetsSettingMenu {
	GtkMenuButton parent_instance;
	NotejotWidgetsSettingMenuPrivate * priv;
	NotejotWidgetsNote* controller;
};

struct _NotejotWidgetsSettingMenuClass {
	GtkMenuButtonClass parent_class;
};

struct _NotejotWidgetsSettingMenuPrivate {
	NotejotMainWindow* win;
};

struct _Block4Data {
	int _ref_count_;
	NotejotWidgetsSettingMenu* self;
	NotejotMainWindow* win;
};

struct _NotejotWidgetsNoteMenuPopover {
	GtkPopover parent_instance;
	NotejotWidgetsNoteMenuPopoverPrivate * priv;
	GtkModelButton* delete_note_button;
	GtkRadioButton* color_button_red;
	GtkRadioButton* color_button_orange;
	GtkRadioButton* color_button_yellow;
	GtkRadioButton* color_button_green;
	GtkRadioButton* color_button_blue;
	GtkRadioButton* color_button_purple;
	GtkRadioButton* color_button_brown;
	GtkRadioButton* color_button_reset;
};

struct _NotejotWidgetsNoteMenuPopoverClass {
	GtkPopoverClass parent_class;
};

struct _NotejotMainWindow {
	HdyApplicationWindow parent_instance;
	NotejotMainWindowPrivate * priv;
	GtkButton* new_button;
	GtkButton* back_button;
	GtkButton* welcome_new_button;
	GtkMenuButton* menu_button;
	GtkBox* grid;
	GtkBox* sgrid;
	GtkBox* welcome_view;
	GtkBox* empty_state;
	HdyLeaflet* leaflet;
	GtkStack* main_stack;
	GtkStack* sidebar_stack;
	GtkStack* titlebar_stack;
	HdyHeaderBar* titlebar;
	HdyHeaderBar* stitlebar;
	HdyHeaderBar* welcome_titlebar;
	HdyHeaderGroup* titlegroup;
	GtkScrolledWindow* trash_scroller;
	GtkScrolledWindow* list_scroller;
	NotejotWidgetsDialog* dialog;
	NotejotWidgetsSettingMenu* settingmenu;
	NotejotWidgetsHeaderBarButton* sidebar_title_button;
	NotejotViewsListView* listview;
	NotejotViewsTrashView* trashview;
	NotejotTaskManager* tm;
	gboolean pinned;
};

struct _NotejotMainWindowClass {
	HdyApplicationWindowClass parent_class;
};

struct _NotejotWidgetsNote {
	HdyActionRow parent_instance;
	NotejotWidgetsNotePrivate * priv;
	NotejotWidgetsTextField* textfield;
	NotejotWidgetsEditableLabel* titlelabel;
	gint uid;
	gchar* title;
	gchar* subtitle;
	gchar* text;
	gchar* color;
};

struct _NotejotWidgetsNoteClass {
	HdyActionRowClass parent_class;
};

static gint NotejotWidgetsSettingMenu_private_offset;
static gpointer notejot_widgets_setting_menu_parent_class = NULL;

GType notejot_widgets_setting_menu_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsSettingMenu, g_object_unref)
GType notejot_widgets_note_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsNote, g_object_unref)
GType notejot_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotMainWindow, g_object_unref)
NotejotWidgetsSettingMenu* notejot_widgets_setting_menu_new (NotejotMainWindow* win);
NotejotWidgetsSettingMenu* notejot_widgets_setting_menu_construct (GType object_type,
                                                                   NotejotMainWindow* win);
static Block4Data* block4_data_ref (Block4Data* _data4_);
static void block4_data_unref (void * _userdata_);
GType notejot_widgets_note_menu_popover_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsNoteMenuPopover, g_object_unref)
NotejotWidgetsNoteMenuPopover* notejot_widgets_note_menu_popover_new (void);
NotejotWidgetsNoteMenuPopover* notejot_widgets_note_menu_popover_construct (GType object_type);
static void __lambda8_ (Block4Data* _data4_);
GType notejot_widgets_dialog_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsDialog, g_object_unref)
GType notejot_widgets_header_bar_button_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsHeaderBarButton, g_object_unref)
GType notejot_views_list_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotViewsListView, g_object_unref)
GType notejot_views_trash_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotViewsTrashView, g_object_unref)
gpointer notejot_task_manager_ref (gpointer instance);
void notejot_task_manager_unref (gpointer instance);
GParamSpec* notejot_param_spec_task_manager (const gchar* name,
                                             const gchar* nick,
                                             const gchar* blurb,
                                             GType object_type,
                                             GParamFlags flags);
void notejot_value_set_task_manager (GValue* value,
                                     gpointer v_object);
void notejot_value_take_task_manager (GValue* value,
                                      gpointer v_object);
gpointer notejot_value_get_task_manager (const GValue* value);
GType notejot_task_manager_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotTaskManager, notejot_task_manager_unref)
void notejot_views_trash_view_new_taskbox (NotejotViewsTrashView* self,
                                           NotejotMainWindow* win,
                                           const gchar* title,
                                           const gchar* contents,
                                           const gchar* text,
                                           const gchar* color,
                                           GAsyncReadyCallback _callback_,
                                           gpointer _user_data_);
void notejot_views_trash_view_new_taskbox_finish (NotejotViewsTrashView* self,
                                                  GAsyncResult* _res_);
GType notejot_widgets_text_field_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsTextField, g_object_unref)
GType notejot_widgets_editable_label_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsEditableLabel, g_object_unref)
void notejot_task_manager_save_notes (NotejotTaskManager* self,
                                      GAsyncReadyCallback _callback_,
                                      gpointer _user_data_);
void notejot_task_manager_save_notes_finish (NotejotTaskManager* self,
                                             GAsyncResult* _res_);
static void ___lambda8__gtk_button_clicked (GtkButton* _sender,
                                     gpointer self);
static void __lambda16_ (NotejotWidgetsSettingMenu* self);
void notejot_widgets_note_update_theme (NotejotWidgetsNote* self,
                                        const gchar* color);
static void ___lambda16__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda17_ (NotejotWidgetsSettingMenu* self);
static void ___lambda17__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda18_ (NotejotWidgetsSettingMenu* self);
static void ___lambda18__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda19_ (NotejotWidgetsSettingMenu* self);
static void ___lambda19__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda20_ (NotejotWidgetsSettingMenu* self);
static void ___lambda20__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda21_ (NotejotWidgetsSettingMenu* self);
static void ___lambda21__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda22_ (NotejotWidgetsSettingMenu* self);
static void ___lambda22__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void __lambda23_ (NotejotWidgetsSettingMenu* self);
static void ___lambda23__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
static void notejot_widgets_setting_menu_finalize (GObject * obj);
static GType notejot_widgets_setting_menu_get_type_once (void);

static inline gpointer
notejot_widgets_setting_menu_get_instance_private (NotejotWidgetsSettingMenu* self)
{
	return G_STRUCT_MEMBER_P (self, NotejotWidgetsSettingMenu_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 6 "../src/Widgets/SettingMenu.vala"
	return self ? g_object_ref (self) : NULL;
#line 327 "SettingMenu.c"
}

static Block4Data*
block4_data_ref (Block4Data* _data4_)
{
#line 6 "../src/Widgets/SettingMenu.vala"
	g_atomic_int_inc (&_data4_->_ref_count_);
#line 6 "../src/Widgets/SettingMenu.vala"
	return _data4_;
#line 337 "SettingMenu.c"
}

static void
block4_data_unref (void * _userdata_)
{
	Block4Data* _data4_;
	_data4_ = (Block4Data*) _userdata_;
#line 6 "../src/Widgets/SettingMenu.vala"
	if (g_atomic_int_dec_and_test (&_data4_->_ref_count_)) {
#line 347 "SettingMenu.c"
		NotejotWidgetsSettingMenu* self;
#line 6 "../src/Widgets/SettingMenu.vala"
		self = _data4_->self;
#line 6 "../src/Widgets/SettingMenu.vala"
		_g_object_unref0 (_data4_->win);
#line 6 "../src/Widgets/SettingMenu.vala"
		_g_object_unref0 (self);
#line 6 "../src/Widgets/SettingMenu.vala"
		g_slice_free (Block4Data, _data4_);
#line 357 "SettingMenu.c"
	}
}

static void
__lambda8_ (Block4Data* _data4_)
{
	NotejotWidgetsSettingMenu* self;
	NotejotViewsTrashView* _tmp0_;
	NotejotWidgetsNote* _tmp1_;
	const gchar* _tmp2_;
	NotejotWidgetsNote* _tmp3_;
	const gchar* _tmp4_;
	NotejotWidgetsNote* _tmp5_;
	const gchar* _tmp6_;
	NotejotWidgetsNote* _tmp7_;
	const gchar* _tmp8_;
	GtkStack* _tmp9_;
	GtkBox* _tmp10_;
	GtkWidget* row = NULL;
	GtkStack* _tmp11_;
	NotejotWidgetsNote* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	GtkWidget* _tmp15_;
	GtkWidget* _tmp16_;
	GtkWidget* _tmp17_;
	GtkStack* _tmp18_;
	NotejotWidgetsNote* _tmp19_;
	NotejotTaskManager* _tmp20_;
	NotejotWidgetsSettingMenu* _tmp21_;
#line 10 "../src/Widgets/SettingMenu.vala"
	self = _data4_->self;
#line 11 "../src/Widgets/SettingMenu.vala"
	_tmp0_ = _data4_->win->trashview;
#line 11 "../src/Widgets/SettingMenu.vala"
	_tmp1_ = self->controller;
#line 11 "../src/Widgets/SettingMenu.vala"
	_tmp2_ = _tmp1_->title;
#line 11 "../src/Widgets/SettingMenu.vala"
	_tmp3_ = self->controller;
#line 11 "../src/Widgets/SettingMenu.vala"
	_tmp4_ = _tmp3_->subtitle;
#line 11 "../src/Widgets/SettingMenu.vala"
	_tmp5_ = self->controller;
#line 11 "../src/Widgets/SettingMenu.vala"
	_tmp6_ = _tmp5_->text;
#line 11 "../src/Widgets/SettingMenu.vala"
	_tmp7_ = self->controller;
#line 11 "../src/Widgets/SettingMenu.vala"
	_tmp8_ = _tmp7_->color;
#line 11 "../src/Widgets/SettingMenu.vala"
	notejot_views_trash_view_new_taskbox (_tmp0_, _data4_->win, _tmp2_, _tmp4_, _tmp6_, _tmp8_, NULL, NULL);
#line 12 "../src/Widgets/SettingMenu.vala"
	_tmp9_ = _data4_->win->main_stack;
#line 12 "../src/Widgets/SettingMenu.vala"
	_tmp10_ = _data4_->win->empty_state;
#line 12 "../src/Widgets/SettingMenu.vala"
	gtk_stack_set_visible_child (_tmp9_, (GtkWidget*) _tmp10_);
#line 13 "../src/Widgets/SettingMenu.vala"
	_tmp11_ = _data4_->win->main_stack;
#line 13 "../src/Widgets/SettingMenu.vala"
	_tmp12_ = self->controller;
#line 13 "../src/Widgets/SettingMenu.vala"
	_tmp13_ = g_strdup_printf ("textfield-%d", _tmp12_->uid);
#line 13 "../src/Widgets/SettingMenu.vala"
	_tmp14_ = _tmp13_;
#line 13 "../src/Widgets/SettingMenu.vala"
	_tmp15_ = gtk_stack_get_child_by_name (_tmp11_, _tmp14_);
#line 13 "../src/Widgets/SettingMenu.vala"
	_tmp16_ = _g_object_ref0 (_tmp15_);
#line 13 "../src/Widgets/SettingMenu.vala"
	_tmp17_ = _tmp16_;
#line 13 "../src/Widgets/SettingMenu.vala"
	_g_free0 (_tmp14_);
#line 13 "../src/Widgets/SettingMenu.vala"
	row = _tmp17_;
#line 14 "../src/Widgets/SettingMenu.vala"
	_tmp18_ = _data4_->win->main_stack;
#line 14 "../src/Widgets/SettingMenu.vala"
	gtk_container_remove ((GtkContainer*) _tmp18_, row);
#line 15 "../src/Widgets/SettingMenu.vala"
	_tmp19_ = self->controller;
#line 15 "../src/Widgets/SettingMenu.vala"
	gtk_widget_destroy ((GtkWidget*) _tmp19_);
#line 16 "../src/Widgets/SettingMenu.vala"
	_tmp20_ = _data4_->win->tm;
#line 16 "../src/Widgets/SettingMenu.vala"
	notejot_task_manager_save_notes (_tmp20_, NULL, NULL);
#line 17 "../src/Widgets/SettingMenu.vala"
	_tmp21_ = _data4_->win->settingmenu;
#line 17 "../src/Widgets/SettingMenu.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp21_, FALSE);
#line 10 "../src/Widgets/SettingMenu.vala"
	_g_object_unref0 (row);
#line 452 "SettingMenu.c"
}

static void
___lambda8__gtk_button_clicked (GtkButton* _sender,
                                gpointer self)
{
#line 10 "../src/Widgets/SettingMenu.vala"
	__lambda8_ (self);
#line 461 "SettingMenu.c"
}

static void
__lambda16_ (NotejotWidgetsSettingMenu* self)
{
	NotejotWidgetsNote* _tmp0_;
#line 21 "../src/Widgets/SettingMenu.vala"
	_tmp0_ = self->controller;
#line 21 "../src/Widgets/SettingMenu.vala"
	notejot_widgets_note_update_theme (_tmp0_, "#f66151");
#line 472 "SettingMenu.c"
}

static void
___lambda16__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 20 "../src/Widgets/SettingMenu.vala"
	__lambda16_ ((NotejotWidgetsSettingMenu*) self);
#line 481 "SettingMenu.c"
}

static void
__lambda17_ (NotejotWidgetsSettingMenu* self)
{
	NotejotWidgetsNote* _tmp0_;
#line 25 "../src/Widgets/SettingMenu.vala"
	_tmp0_ = self->controller;
#line 25 "../src/Widgets/SettingMenu.vala"
	notejot_widgets_note_update_theme (_tmp0_, "#ffbe6f");
#line 492 "SettingMenu.c"
}

static void
___lambda17__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 24 "../src/Widgets/SettingMenu.vala"
	__lambda17_ ((NotejotWidgetsSettingMenu*) self);
#line 501 "SettingMenu.c"
}

static void
__lambda18_ (NotejotWidgetsSettingMenu* self)
{
	NotejotWidgetsNote* _tmp0_;
#line 29 "../src/Widgets/SettingMenu.vala"
	_tmp0_ = self->controller;
#line 29 "../src/Widgets/SettingMenu.vala"
	notejot_widgets_note_update_theme (_tmp0_, "#f9f06b");
#line 512 "SettingMenu.c"
}

static void
___lambda18__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 28 "../src/Widgets/SettingMenu.vala"
	__lambda18_ ((NotejotWidgetsSettingMenu*) self);
#line 521 "SettingMenu.c"
}

static void
__lambda19_ (NotejotWidgetsSettingMenu* self)
{
	NotejotWidgetsNote* _tmp0_;
#line 33 "../src/Widgets/SettingMenu.vala"
	_tmp0_ = self->controller;
#line 33 "../src/Widgets/SettingMenu.vala"
	notejot_widgets_note_update_theme (_tmp0_, "#8ff0a4");
#line 532 "SettingMenu.c"
}

static void
___lambda19__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 32 "../src/Widgets/SettingMenu.vala"
	__lambda19_ ((NotejotWidgetsSettingMenu*) self);
#line 541 "SettingMenu.c"
}

static void
__lambda20_ (NotejotWidgetsSettingMenu* self)
{
	NotejotWidgetsNote* _tmp0_;
#line 37 "../src/Widgets/SettingMenu.vala"
	_tmp0_ = self->controller;
#line 37 "../src/Widgets/SettingMenu.vala"
	notejot_widgets_note_update_theme (_tmp0_, "#99c1f1");
#line 552 "SettingMenu.c"
}

static void
___lambda20__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 36 "../src/Widgets/SettingMenu.vala"
	__lambda20_ ((NotejotWidgetsSettingMenu*) self);
#line 561 "SettingMenu.c"
}

static void
__lambda21_ (NotejotWidgetsSettingMenu* self)
{
	NotejotWidgetsNote* _tmp0_;
#line 41 "../src/Widgets/SettingMenu.vala"
	_tmp0_ = self->controller;
#line 41 "../src/Widgets/SettingMenu.vala"
	notejot_widgets_note_update_theme (_tmp0_, "#dc8add");
#line 572 "SettingMenu.c"
}

static void
___lambda21__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 40 "../src/Widgets/SettingMenu.vala"
	__lambda21_ ((NotejotWidgetsSettingMenu*) self);
#line 581 "SettingMenu.c"
}

static void
__lambda22_ (NotejotWidgetsSettingMenu* self)
{
	NotejotWidgetsNote* _tmp0_;
#line 45 "../src/Widgets/SettingMenu.vala"
	_tmp0_ = self->controller;
#line 45 "../src/Widgets/SettingMenu.vala"
	notejot_widgets_note_update_theme (_tmp0_, "#cdab8f");
#line 592 "SettingMenu.c"
}

static void
___lambda22__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 44 "../src/Widgets/SettingMenu.vala"
	__lambda22_ ((NotejotWidgetsSettingMenu*) self);
#line 601 "SettingMenu.c"
}

static void
__lambda23_ (NotejotWidgetsSettingMenu* self)
{
	NotejotWidgetsNote* _tmp0_;
#line 49 "../src/Widgets/SettingMenu.vala"
	_tmp0_ = self->controller;
#line 49 "../src/Widgets/SettingMenu.vala"
	notejot_widgets_note_update_theme (_tmp0_, "#ffffff");
#line 612 "SettingMenu.c"
}

static void
___lambda23__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
#line 48 "../src/Widgets/SettingMenu.vala"
	__lambda23_ ((NotejotWidgetsSettingMenu*) self);
#line 621 "SettingMenu.c"
}

NotejotWidgetsSettingMenu*
notejot_widgets_setting_menu_construct (GType object_type,
                                        NotejotMainWindow* win)
{
	NotejotWidgetsSettingMenu * self = NULL;
	Block4Data* _data4_;
	NotejotMainWindow* _tmp0_;
	NotejotMainWindow* _tmp1_;
	NotejotWidgetsNoteMenuPopover* vpopover = NULL;
	NotejotWidgetsNoteMenuPopover* _tmp2_;
	GtkModelButton* _tmp3_;
	GtkRadioButton* _tmp4_;
	GtkRadioButton* _tmp5_;
	GtkRadioButton* _tmp6_;
	GtkRadioButton* _tmp7_;
	GtkRadioButton* _tmp8_;
	GtkRadioButton* _tmp9_;
	GtkRadioButton* _tmp10_;
	GtkRadioButton* _tmp11_;
	GtkImage* _tmp12_;
	GtkImage* _tmp13_;
#line 6 "../src/Widgets/SettingMenu.vala"
	g_return_val_if_fail (win != NULL, NULL);
#line 6 "../src/Widgets/SettingMenu.vala"
	_data4_ = g_slice_new0 (Block4Data);
#line 6 "../src/Widgets/SettingMenu.vala"
	_data4_->_ref_count_ = 1;
#line 6 "../src/Widgets/SettingMenu.vala"
	_tmp0_ = _g_object_ref0 (win);
#line 6 "../src/Widgets/SettingMenu.vala"
	_g_object_unref0 (_data4_->win);
#line 6 "../src/Widgets/SettingMenu.vala"
	_data4_->win = _tmp0_;
#line 6 "../src/Widgets/SettingMenu.vala"
	self = (NotejotWidgetsSettingMenu*) g_object_new (object_type, NULL);
#line 6 "../src/Widgets/SettingMenu.vala"
	_data4_->self = g_object_ref (self);
#line 7 "../src/Widgets/SettingMenu.vala"
	_tmp1_ = _g_object_ref0 (_data4_->win);
#line 7 "../src/Widgets/SettingMenu.vala"
	_g_object_unref0 (self->priv->win);
#line 7 "../src/Widgets/SettingMenu.vala"
	self->priv->win = _tmp1_;
#line 8 "../src/Widgets/SettingMenu.vala"
	_tmp2_ = notejot_widgets_note_menu_popover_new ();
#line 8 "../src/Widgets/SettingMenu.vala"
	g_object_ref_sink (_tmp2_);
#line 8 "../src/Widgets/SettingMenu.vala"
	vpopover = _tmp2_;
#line 10 "../src/Widgets/SettingMenu.vala"
	_tmp3_ = vpopover->delete_note_button;
#line 10 "../src/Widgets/SettingMenu.vala"
	g_signal_connect_data ((GtkButton*) _tmp3_, "clicked", (GCallback) ___lambda8__gtk_button_clicked, block4_data_ref (_data4_), (GClosureNotify) block4_data_unref, 0);
#line 20 "../src/Widgets/SettingMenu.vala"
	_tmp4_ = vpopover->color_button_red;
#line 20 "../src/Widgets/SettingMenu.vala"
	g_signal_connect_object ((GtkButton*) _tmp4_, "clicked", (GCallback) ___lambda16__gtk_button_clicked, self, 0);
#line 24 "../src/Widgets/SettingMenu.vala"
	_tmp5_ = vpopover->color_button_orange;
#line 24 "../src/Widgets/SettingMenu.vala"
	g_signal_connect_object ((GtkButton*) _tmp5_, "clicked", (GCallback) ___lambda17__gtk_button_clicked, self, 0);
#line 28 "../src/Widgets/SettingMenu.vala"
	_tmp6_ = vpopover->color_button_yellow;
#line 28 "../src/Widgets/SettingMenu.vala"
	g_signal_connect_object ((GtkButton*) _tmp6_, "clicked", (GCallback) ___lambda18__gtk_button_clicked, self, 0);
#line 32 "../src/Widgets/SettingMenu.vala"
	_tmp7_ = vpopover->color_button_green;
#line 32 "../src/Widgets/SettingMenu.vala"
	g_signal_connect_object ((GtkButton*) _tmp7_, "clicked", (GCallback) ___lambda19__gtk_button_clicked, self, 0);
#line 36 "../src/Widgets/SettingMenu.vala"
	_tmp8_ = vpopover->color_button_blue;
#line 36 "../src/Widgets/SettingMenu.vala"
	g_signal_connect_object ((GtkButton*) _tmp8_, "clicked", (GCallback) ___lambda20__gtk_button_clicked, self, 0);
#line 40 "../src/Widgets/SettingMenu.vala"
	_tmp9_ = vpopover->color_button_purple;
#line 40 "../src/Widgets/SettingMenu.vala"
	g_signal_connect_object ((GtkButton*) _tmp9_, "clicked", (GCallback) ___lambda21__gtk_button_clicked, self, 0);
#line 44 "../src/Widgets/SettingMenu.vala"
	_tmp10_ = vpopover->color_button_brown;
#line 44 "../src/Widgets/SettingMenu.vala"
	g_signal_connect_object ((GtkButton*) _tmp10_, "clicked", (GCallback) ___lambda22__gtk_button_clicked, self, 0);
#line 48 "../src/Widgets/SettingMenu.vala"
	_tmp11_ = vpopover->color_button_reset;
#line 48 "../src/Widgets/SettingMenu.vala"
	g_signal_connect_object ((GtkButton*) _tmp11_, "clicked", (GCallback) ___lambda23__gtk_button_clicked, self, 0);
#line 52 "../src/Widgets/SettingMenu.vala"
	gtk_widget_set_has_tooltip ((GtkWidget*) self, TRUE);
#line 53 "../src/Widgets/SettingMenu.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) self, _ ("Note Settings"));
#line 54 "../src/Widgets/SettingMenu.vala"
	_tmp12_ = (GtkImage*) gtk_image_new_from_icon_name ("view-more-symbolic", (GtkIconSize) GTK_ICON_SIZE_SMALL_TOOLBAR);
#line 54 "../src/Widgets/SettingMenu.vala"
	g_object_ref_sink (_tmp12_);
#line 54 "../src/Widgets/SettingMenu.vala"
	_tmp13_ = _tmp12_;
#line 54 "../src/Widgets/SettingMenu.vala"
	gtk_button_set_image ((GtkButton*) self, (GtkWidget*) _tmp13_);
#line 54 "../src/Widgets/SettingMenu.vala"
	_g_object_unref0 (_tmp13_);
#line 55 "../src/Widgets/SettingMenu.vala"
	gtk_menu_button_set_popover ((GtkMenuButton*) self, (GtkPopover*) vpopover);
#line 56 "../src/Widgets/SettingMenu.vala"
	gtk_widget_set_halign ((GtkWidget*) self, GTK_ALIGN_END);
#line 57 "../src/Widgets/SettingMenu.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 6 "../src/Widgets/SettingMenu.vala"
	_g_object_unref0 (vpopover);
#line 6 "../src/Widgets/SettingMenu.vala"
	block4_data_unref (_data4_);
#line 6 "../src/Widgets/SettingMenu.vala"
	_data4_ = NULL;
#line 6 "../src/Widgets/SettingMenu.vala"
	return self;
#line 737 "SettingMenu.c"
}

NotejotWidgetsSettingMenu*
notejot_widgets_setting_menu_new (NotejotMainWindow* win)
{
#line 6 "../src/Widgets/SettingMenu.vala"
	return notejot_widgets_setting_menu_construct (NOTEJOT_WIDGETS_TYPE_SETTING_MENU, win);
#line 745 "SettingMenu.c"
}

static void
notejot_widgets_setting_menu_class_init (NotejotWidgetsSettingMenuClass * klass,
                                         gpointer klass_data)
{
#line 2 "../src/Widgets/SettingMenu.vala"
	notejot_widgets_setting_menu_parent_class = g_type_class_peek_parent (klass);
#line 2 "../src/Widgets/SettingMenu.vala"
	g_type_class_adjust_private_offset (klass, &NotejotWidgetsSettingMenu_private_offset);
#line 2 "../src/Widgets/SettingMenu.vala"
	G_OBJECT_CLASS (klass)->finalize = notejot_widgets_setting_menu_finalize;
#line 758 "SettingMenu.c"
}

static void
notejot_widgets_setting_menu_instance_init (NotejotWidgetsSettingMenu * self,
                                            gpointer klass)
{
#line 2 "../src/Widgets/SettingMenu.vala"
	self->priv = notejot_widgets_setting_menu_get_instance_private (self);
#line 767 "SettingMenu.c"
}

static void
notejot_widgets_setting_menu_finalize (GObject * obj)
{
	NotejotWidgetsSettingMenu * self;
#line 2 "../src/Widgets/SettingMenu.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenu);
#line 3 "../src/Widgets/SettingMenu.vala"
	_g_object_unref0 (self->priv->win);
#line 4 "../src/Widgets/SettingMenu.vala"
	_g_object_unref0 (self->controller);
#line 2 "../src/Widgets/SettingMenu.vala"
	G_OBJECT_CLASS (notejot_widgets_setting_menu_parent_class)->finalize (obj);
#line 782 "SettingMenu.c"
}

static GType
notejot_widgets_setting_menu_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (NotejotWidgetsSettingMenuClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) notejot_widgets_setting_menu_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NotejotWidgetsSettingMenu), 0, (GInstanceInitFunc) notejot_widgets_setting_menu_instance_init, NULL };
	GType notejot_widgets_setting_menu_type_id;
	notejot_widgets_setting_menu_type_id = g_type_register_static (gtk_menu_button_get_type (), "NotejotWidgetsSettingMenu", &g_define_type_info, 0);
	NotejotWidgetsSettingMenu_private_offset = g_type_add_instance_private (notejot_widgets_setting_menu_type_id, sizeof (NotejotWidgetsSettingMenuPrivate));
	return notejot_widgets_setting_menu_type_id;
}

GType
notejot_widgets_setting_menu_get_type (void)
{
	static volatile gsize notejot_widgets_setting_menu_type_id__volatile = 0;
	if (g_once_init_enter (&notejot_widgets_setting_menu_type_id__volatile)) {
		GType notejot_widgets_setting_menu_type_id;
		notejot_widgets_setting_menu_type_id = notejot_widgets_setting_menu_get_type_once ();
		g_once_init_leave (&notejot_widgets_setting_menu_type_id__volatile, notejot_widgets_setting_menu_type_id);
	}
	return notejot_widgets_setting_menu_type_id__volatile;
}

