/* ListView.c generated by valac 0.50.3, the Vala compiler
 * generated from ListView.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <handy.h>
#include <glib.h>
#include <webkit2/webkit2.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <float.h>
#include <math.h>
#include <gio/gio.h>

#define NOTEJOT_VIEWS_TYPE_LIST_VIEW (notejot_views_list_view_get_type ())
#define NOTEJOT_VIEWS_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListView))
#define NOTEJOT_VIEWS_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListViewClass))
#define NOTEJOT_VIEWS_IS_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW))
#define NOTEJOT_VIEWS_IS_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_VIEWS_TYPE_LIST_VIEW))
#define NOTEJOT_VIEWS_LIST_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListViewClass))

typedef struct _NotejotViewsListView NotejotViewsListView;
typedef struct _NotejotViewsListViewClass NotejotViewsListViewClass;
typedef struct _NotejotViewsListViewPrivate NotejotViewsListViewPrivate;

#define NOTEJOT_TYPE_MAIN_WINDOW (notejot_main_window_get_type ())
#define NOTEJOT_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindow))
#define NOTEJOT_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindowClass))
#define NOTEJOT_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_TYPE_MAIN_WINDOW))
#define NOTEJOT_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_TYPE_MAIN_WINDOW))
#define NOTEJOT_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindowClass))

typedef struct _NotejotMainWindow NotejotMainWindow;
typedef struct _NotejotMainWindowClass NotejotMainWindowClass;
enum  {
	NOTEJOT_VIEWS_LIST_VIEW_0_PROPERTY,
	NOTEJOT_VIEWS_LIST_VIEW_IS_MODIFIED_PROPERTY,
	NOTEJOT_VIEWS_LIST_VIEW_NUM_PROPERTIES
};
static GParamSpec* notejot_views_list_view_properties[NOTEJOT_VIEWS_LIST_VIEW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block1Data Block1Data;
typedef struct _NotejotMainWindowPrivate NotejotMainWindowPrivate;

#define NOTEJOT_WIDGETS_TYPE_DIALOG (notejot_widgets_dialog_get_type ())
#define NOTEJOT_WIDGETS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialog))
#define NOTEJOT_WIDGETS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialogClass))
#define NOTEJOT_WIDGETS_IS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG))
#define NOTEJOT_WIDGETS_IS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_DIALOG))
#define NOTEJOT_WIDGETS_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialogClass))

typedef struct _NotejotWidgetsDialog NotejotWidgetsDialog;
typedef struct _NotejotWidgetsDialogClass NotejotWidgetsDialogClass;

#define NOTEJOT_WIDGETS_TYPE_SETTING_MENU (notejot_widgets_setting_menu_get_type ())
#define NOTEJOT_WIDGETS_SETTING_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenu))
#define NOTEJOT_WIDGETS_SETTING_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenuClass))
#define NOTEJOT_WIDGETS_IS_SETTING_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU))
#define NOTEJOT_WIDGETS_IS_SETTING_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_SETTING_MENU))
#define NOTEJOT_WIDGETS_SETTING_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenuClass))

typedef struct _NotejotWidgetsSettingMenu NotejotWidgetsSettingMenu;
typedef struct _NotejotWidgetsSettingMenuClass NotejotWidgetsSettingMenuClass;

#define NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON (notejot_widgets_header_bar_button_get_type ())
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButton))
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButtonClass))
#define NOTEJOT_WIDGETS_IS_HEADER_BAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON))
#define NOTEJOT_WIDGETS_IS_HEADER_BAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON))
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButtonClass))

typedef struct _NotejotWidgetsHeaderBarButton NotejotWidgetsHeaderBarButton;
typedef struct _NotejotWidgetsHeaderBarButtonClass NotejotWidgetsHeaderBarButtonClass;

#define NOTEJOT_VIEWS_TYPE_TRASH_VIEW (notejot_views_trash_view_get_type ())
#define NOTEJOT_VIEWS_TRASH_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashView))
#define NOTEJOT_VIEWS_TRASH_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashViewClass))
#define NOTEJOT_VIEWS_IS_TRASH_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW))
#define NOTEJOT_VIEWS_IS_TRASH_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_VIEWS_TYPE_TRASH_VIEW))
#define NOTEJOT_VIEWS_TRASH_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashViewClass))

typedef struct _NotejotViewsTrashView NotejotViewsTrashView;
typedef struct _NotejotViewsTrashViewClass NotejotViewsTrashViewClass;

#define NOTEJOT_TYPE_TASK_MANAGER (notejot_task_manager_get_type ())
#define NOTEJOT_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManager))
#define NOTEJOT_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManagerClass))
#define NOTEJOT_IS_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_TYPE_TASK_MANAGER))
#define NOTEJOT_IS_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_TYPE_TASK_MANAGER))
#define NOTEJOT_TASK_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManagerClass))

typedef struct _NotejotTaskManager NotejotTaskManager;
typedef struct _NotejotTaskManagerClass NotejotTaskManagerClass;

#define NOTEJOT_WIDGETS_TYPE_NOTE (notejot_widgets_note_get_type ())
#define NOTEJOT_WIDGETS_NOTE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote))
#define NOTEJOT_WIDGETS_NOTE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNoteClass))
#define NOTEJOT_WIDGETS_IS_NOTE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_NOTE))
#define NOTEJOT_WIDGETS_IS_NOTE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_NOTE))
#define NOTEJOT_WIDGETS_NOTE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNoteClass))

typedef struct _NotejotWidgetsNote NotejotWidgetsNote;
typedef struct _NotejotWidgetsNoteClass NotejotWidgetsNoteClass;
typedef struct _NotejotWidgetsNotePrivate NotejotWidgetsNotePrivate;

#define NOTEJOT_WIDGETS_TYPE_TEXT_FIELD (notejot_widgets_text_field_get_type ())
#define NOTEJOT_WIDGETS_TEXT_FIELD(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD, NotejotWidgetsTextField))
#define NOTEJOT_WIDGETS_TEXT_FIELD_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD, NotejotWidgetsTextFieldClass))
#define NOTEJOT_WIDGETS_IS_TEXT_FIELD(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD))
#define NOTEJOT_WIDGETS_IS_TEXT_FIELD_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD))
#define NOTEJOT_WIDGETS_TEXT_FIELD_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_TEXT_FIELD, NotejotWidgetsTextFieldClass))

typedef struct _NotejotWidgetsTextField NotejotWidgetsTextField;
typedef struct _NotejotWidgetsTextFieldClass NotejotWidgetsTextFieldClass;

#define NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL (notejot_widgets_editable_label_get_type ())
#define NOTEJOT_WIDGETS_EDITABLE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabel))
#define NOTEJOT_WIDGETS_EDITABLE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabelClass))
#define NOTEJOT_WIDGETS_IS_EDITABLE_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL))
#define NOTEJOT_WIDGETS_IS_EDITABLE_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL))
#define NOTEJOT_WIDGETS_EDITABLE_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_EDITABLE_LABEL, NotejotWidgetsEditableLabelClass))

typedef struct _NotejotWidgetsEditableLabel NotejotWidgetsEditableLabel;
typedef struct _NotejotWidgetsEditableLabelClass NotejotWidgetsEditableLabelClass;
typedef struct _NotejotWidgetsSettingMenuPrivate NotejotWidgetsSettingMenuPrivate;

#define NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER (notejot_widgets_note_menu_popover_get_type ())
#define NOTEJOT_WIDGETS_NOTE_MENU_POPOVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER, NotejotWidgetsNoteMenuPopover))
#define NOTEJOT_WIDGETS_NOTE_MENU_POPOVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER, NotejotWidgetsNoteMenuPopoverClass))
#define NOTEJOT_WIDGETS_IS_NOTE_MENU_POPOVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER))
#define NOTEJOT_WIDGETS_IS_NOTE_MENU_POPOVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER))
#define NOTEJOT_WIDGETS_NOTE_MENU_POPOVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_NOTE_MENU_POPOVER, NotejotWidgetsNoteMenuPopoverClass))

typedef struct _NotejotWidgetsNoteMenuPopover NotejotWidgetsNoteMenuPopover;
typedef struct _NotejotWidgetsNoteMenuPopoverClass NotejotWidgetsNoteMenuPopoverClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _NotejotViewsListViewNewTaskboxData NotejotViewsListViewNewTaskboxData;

struct _NotejotViewsListView {
	GtkListBox parent_instance;
	NotejotViewsListViewPrivate * priv;
};

struct _NotejotViewsListViewClass {
	GtkListBoxClass parent_class;
};

struct _NotejotViewsListViewPrivate {
	NotejotMainWindow* win;
	GtkGestureMultiPress* press;
	gboolean _is_modified;
};

struct _Block1Data {
	int _ref_count_;
	NotejotViewsListView* self;
	NotejotMainWindow* win;
};

struct _NotejotMainWindow {
	HdyApplicationWindow parent_instance;
	NotejotMainWindowPrivate * priv;
	GtkButton* new_button;
	GtkButton* back_button;
	GtkButton* welcome_new_button;
	GtkMenuButton* menu_button;
	GtkBox* grid;
	GtkBox* sgrid;
	GtkBox* welcome_view;
	GtkBox* empty_state;
	HdyLeaflet* leaflet;
	GtkStack* main_stack;
	GtkStack* sidebar_stack;
	GtkStack* titlebar_stack;
	HdyHeaderBar* titlebar;
	HdyHeaderBar* stitlebar;
	HdyHeaderBar* welcome_titlebar;
	HdyHeaderGroup* titlegroup;
	GtkScrolledWindow* trash_scroller;
	GtkScrolledWindow* list_scroller;
	NotejotWidgetsDialog* dialog;
	NotejotWidgetsSettingMenu* settingmenu;
	NotejotWidgetsHeaderBarButton* sidebar_title_button;
	NotejotViewsListView* listview;
	NotejotViewsTrashView* trashview;
	NotejotTaskManager* tm;
	gboolean pinned;
};

struct _NotejotMainWindowClass {
	HdyApplicationWindowClass parent_class;
};

struct _NotejotWidgetsNote {
	HdyActionRow parent_instance;
	NotejotWidgetsNotePrivate * priv;
	NotejotWidgetsTextField* textfield;
	NotejotWidgetsEditableLabel* titlelabel;
	gint uid;
	gchar* title;
	gchar* subtitle;
	gchar* text;
	gchar* color;
};

struct _NotejotWidgetsNoteClass {
	HdyActionRowClass parent_class;
};

struct _NotejotWidgetsSettingMenu {
	GtkMenuButton parent_instance;
	NotejotWidgetsSettingMenuPrivate * priv;
	NotejotWidgetsNote* controller;
};

struct _NotejotWidgetsSettingMenuClass {
	GtkMenuButtonClass parent_class;
};

struct _NotejotViewsListViewNewTaskboxData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	NotejotViewsListView* self;
	NotejotMainWindow* win;
	gchar* title;
	gchar* contents;
	gchar* text;
	gchar* color;
	NotejotWidgetsNote* taskbox;
	NotejotWidgetsNote* _tmp0_;
	NotejotTaskManager* _tmp1_;
};

static gint NotejotViewsListView_private_offset;
static gpointer notejot_views_list_view_parent_class = NULL;

GType notejot_views_list_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotViewsListView, g_object_unref)
GType notejot_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotMainWindow, g_object_unref)
NotejotViewsListView* notejot_views_list_view_new (NotejotMainWindow* win);
NotejotViewsListView* notejot_views_list_view_construct (GType object_type,
                                                         NotejotMainWindow* win);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
void notejot_views_list_view_set_is_modified (NotejotViewsListView* self,
                                              gboolean value);
gint notejot_views_list_view_list_sort (NotejotViewsListView* self,
                                        GtkListBoxRow* first_row,
                                        GtkListBoxRow* second_row);
static gint _notejot_views_list_view_list_sort_gtk_list_box_sort_func (GtkListBoxRow* row1,
                                                                GtkListBoxRow* row2,
                                                                gpointer self);
static void __lambda7_ (Block1Data* _data1_,
                 GtkListBoxRow* selected_row);
GType notejot_widgets_dialog_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsDialog, g_object_unref)
GType notejot_widgets_setting_menu_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsSettingMenu, g_object_unref)
GType notejot_widgets_header_bar_button_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsHeaderBarButton, g_object_unref)
GType notejot_views_trash_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotViewsTrashView, g_object_unref)
gpointer notejot_task_manager_ref (gpointer instance);
void notejot_task_manager_unref (gpointer instance);
GParamSpec* notejot_param_spec_task_manager (const gchar* name,
                                             const gchar* nick,
                                             const gchar* blurb,
                                             GType object_type,
                                             GParamFlags flags);
void notejot_value_set_task_manager (GValue* value,
                                     gpointer v_object);
void notejot_value_take_task_manager (GValue* value,
                                      gpointer v_object);
gpointer notejot_value_get_task_manager (const GValue* value);
GType notejot_task_manager_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotTaskManager, notejot_task_manager_unref)
GType notejot_widgets_note_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsNote, g_object_unref)
GType notejot_widgets_text_field_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsTextField, g_object_unref)
GType notejot_widgets_editable_label_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsEditableLabel, g_object_unref)
void notejot_widgets_note_select_item (NotejotWidgetsNote* self);
static void ___lambda7__gtk_list_box_row_selected (GtkListBox* _sender,
                                            GtkListBoxRow* row,
                                            gpointer self);
static void __lambda24_ (NotejotViewsListView* self,
                  GtkGestureMultiPress* gesture,
                  gint n_press,
                  gdouble x,
                  gdouble y);
GType notejot_widgets_note_menu_popover_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsNoteMenuPopover, g_object_unref)
NotejotWidgetsNoteMenuPopover* notejot_widgets_note_menu_popover_new (void);
NotejotWidgetsNoteMenuPopover* notejot_widgets_note_menu_popover_construct (GType object_type);
void notejot_widgets_note_popover_listener (NotejotWidgetsNote* self,
                                            NotejotWidgetsNoteMenuPopover* popover);
static void ___lambda24__gtk_gesture_multi_press_pressed (GtkGestureMultiPress* _sender,
                                                   gint n_press,
                                                   gdouble x,
                                                   gdouble y,
                                                   gpointer self);
GList* notejot_views_list_view_get_rows (NotejotViewsListView* self);
void notejot_views_list_view_clear_column (NotejotViewsListView* self);
void notejot_task_manager_save_notes (NotejotTaskManager* self,
                                      GAsyncReadyCallback _callback_,
                                      gpointer _user_data_);
void notejot_task_manager_save_notes_finish (NotejotTaskManager* self,
                                             GAsyncResult* _res_);
static void notejot_views_list_view_new_taskbox_data_free (gpointer _data);
void notejot_views_list_view_new_taskbox (NotejotViewsListView* self,
                                          NotejotMainWindow* win,
                                          const gchar* title,
                                          const gchar* contents,
                                          const gchar* text,
                                          const gchar* color,
                                          GAsyncReadyCallback _callback_,
                                          gpointer _user_data_);
void notejot_views_list_view_new_taskbox_finish (NotejotViewsListView* self,
                                                 GAsyncResult* _res_);
static gboolean notejot_views_list_view_new_taskbox_co (NotejotViewsListViewNewTaskboxData* _data_);
NotejotWidgetsNote* notejot_widgets_note_new (NotejotMainWindow* win,
                                              const gchar* title,
                                              const gchar* subtitle,
                                              const gchar* text,
                                              const gchar* color);
NotejotWidgetsNote* notejot_widgets_note_construct (GType object_type,
                                                    NotejotMainWindow* win,
                                                    const gchar* title,
                                                    const gchar* subtitle,
                                                    const gchar* text,
                                                    const gchar* color);
gboolean notejot_views_list_view_get_is_modified (NotejotViewsListView* self);
static void notejot_views_list_view_finalize (GObject * obj);
static GType notejot_views_list_view_get_type_once (void);
static void _vala_notejot_views_list_view_get_property (GObject * object,
                                                 guint property_id,
                                                 GValue * value,
                                                 GParamSpec * pspec);
static void _vala_notejot_views_list_view_set_property (GObject * object,
                                                 guint property_id,
                                                 const GValue * value,
                                                 GParamSpec * pspec);

static inline gpointer
notejot_views_list_view_get_instance_private (NotejotViewsListView* self)
{
	return G_STRUCT_MEMBER_P (self, NotejotViewsListView_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 7 "../src/Views/ListView.vala"
	return self ? g_object_ref (self) : NULL;
#line 361 "ListView.c"
}

static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
#line 7 "../src/Views/ListView.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 7 "../src/Views/ListView.vala"
	return _data1_;
#line 371 "ListView.c"
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 7 "../src/Views/ListView.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 381 "ListView.c"
		NotejotViewsListView* self;
#line 7 "../src/Views/ListView.vala"
		self = _data1_->self;
#line 7 "../src/Views/ListView.vala"
		_g_object_unref0 (_data1_->win);
#line 7 "../src/Views/ListView.vala"
		_g_object_unref0 (self);
#line 7 "../src/Views/ListView.vala"
		g_slice_free (Block1Data, _data1_);
#line 391 "ListView.c"
	}
}

static gint
_notejot_views_list_view_list_sort_gtk_list_box_sort_func (GtkListBoxRow* row1,
                                                           GtkListBoxRow* row2,
                                                           gpointer self)
{
	gint result;
	result = notejot_views_list_view_list_sort ((NotejotViewsListView*) self, row1, row2);
#line 11 "../src/Views/ListView.vala"
	return result;
#line 404 "ListView.c"
}

static void
__lambda7_ (Block1Data* _data1_,
            GtkListBoxRow* selected_row)
{
	NotejotViewsListView* self;
	HdyLeaflet* _tmp0_;
	GtkBox* _tmp1_;
	NotejotWidgetsSettingMenu* _tmp2_;
#line 16 "../src/Views/ListView.vala"
	self = _data1_->self;
#line 17 "../src/Views/ListView.vala"
	_tmp0_ = _data1_->win->leaflet;
#line 17 "../src/Views/ListView.vala"
	_tmp1_ = _data1_->win->grid;
#line 17 "../src/Views/ListView.vala"
	hdy_leaflet_set_visible_child (_tmp0_, (GtkWidget*) _tmp1_);
#line 18 "../src/Views/ListView.vala"
	_tmp2_ = _data1_->win->settingmenu;
#line 18 "../src/Views/ListView.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp2_, TRUE);
#line 20 "../src/Views/ListView.vala"
	if (G_TYPE_CHECK_INSTANCE_CAST (selected_row, NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote) != NULL) {
#line 429 "ListView.c"
		HdyHeaderBar* _tmp3_;
		NotejotWidgetsSettingMenu* _tmp4_;
		NotejotWidgetsTextField* _tmp5_;
		NotejotWidgetsSettingMenu* _tmp6_;
		NotejotWidgetsNote* _tmp7_;
#line 21 "../src/Views/ListView.vala"
		_tmp3_ = _data1_->win->titlebar;
#line 21 "../src/Views/ListView.vala"
		_tmp4_ = _data1_->win->settingmenu;
#line 21 "../src/Views/ListView.vala"
		hdy_header_bar_pack_end (_tmp3_, (GtkWidget*) _tmp4_);
#line 22 "../src/Views/ListView.vala"
		_tmp5_ = G_TYPE_CHECK_INSTANCE_CAST (selected_row, NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote)->textfield;
#line 22 "../src/Views/ListView.vala"
		gtk_widget_grab_focus ((GtkWidget*) _tmp5_);
#line 23 "../src/Views/ListView.vala"
		notejot_widgets_note_select_item (G_TYPE_CHECK_INSTANCE_CAST (selected_row, NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote));
#line 24 "../src/Views/ListView.vala"
		_tmp6_ = _data1_->win->settingmenu;
#line 24 "../src/Views/ListView.vala"
		_tmp7_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (selected_row, NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote));
#line 24 "../src/Views/ListView.vala"
		_g_object_unref0 (_tmp6_->controller);
#line 24 "../src/Views/ListView.vala"
		_tmp6_->controller = _tmp7_;
#line 455 "ListView.c"
	} else {
		HdyHeaderBar* _tmp8_;
		NotejotWidgetsSettingMenu* _tmp9_;
#line 26 "../src/Views/ListView.vala"
		_tmp8_ = _data1_->win->titlebar;
#line 26 "../src/Views/ListView.vala"
		_tmp9_ = _data1_->win->settingmenu;
#line 26 "../src/Views/ListView.vala"
		gtk_container_remove ((GtkContainer*) _tmp8_, (GtkWidget*) _tmp9_);
#line 465 "ListView.c"
	}
}

static void
___lambda7__gtk_list_box_row_selected (GtkListBox* _sender,
                                       GtkListBoxRow* row,
                                       gpointer self)
{
#line 16 "../src/Views/ListView.vala"
	__lambda7_ (self, row);
#line 476 "ListView.c"
}

static void
__lambda24_ (NotejotViewsListView* self,
             GtkGestureMultiPress* gesture,
             gint n_press,
             gdouble x,
             gdouble y)
{
	GtkListBoxRow* row = NULL;
	GtkListBoxRow* _tmp1_;
	GtkListBoxRow* _tmp2_;
	GtkListBoxRow* _tmp3_;
	NotejotWidgetsNoteMenuPopover* popover = NULL;
	NotejotWidgetsNoteMenuPopover* _tmp5_;
	GtkListBoxRow* _tmp6_;
	NotejotWidgetsNoteMenuPopover* _tmp7_;
	NotejotWidgetsNoteMenuPopover* _tmp8_;
	GtkListBoxRow* _tmp9_;
	NotejotWidgetsNoteMenuPopover* _tmp10_;
	GtkGestureMultiPress* _tmp11_;
#line 33 "../src/Views/ListView.vala"
	g_return_if_fail (gesture != NULL);
#line 34 "../src/Views/ListView.vala"
	if (n_press > 1) {
#line 502 "ListView.c"
		GtkGestureMultiPress* _tmp0_;
#line 35 "../src/Views/ListView.vala"
		_tmp0_ = self->priv->press;
#line 35 "../src/Views/ListView.vala"
		gtk_gesture_set_state ((GtkGesture*) _tmp0_, GTK_EVENT_SEQUENCE_DENIED);
#line 36 "../src/Views/ListView.vala"
		return;
#line 510 "ListView.c"
	}
#line 39 "../src/Views/ListView.vala"
	_tmp1_ = gtk_list_box_get_row_at_y ((GtkListBox*) self, (gint) y);
#line 39 "../src/Views/ListView.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 39 "../src/Views/ListView.vala"
	row = _tmp2_;
#line 41 "../src/Views/ListView.vala"
	_tmp3_ = row;
#line 41 "../src/Views/ListView.vala"
	if (_tmp3_ == NULL) {
#line 522 "ListView.c"
		GtkGestureMultiPress* _tmp4_;
#line 42 "../src/Views/ListView.vala"
		_tmp4_ = self->priv->press;
#line 42 "../src/Views/ListView.vala"
		gtk_gesture_set_state ((GtkGesture*) _tmp4_, GTK_EVENT_SEQUENCE_DENIED);
#line 43 "../src/Views/ListView.vala"
		_g_object_unref0 (row);
#line 43 "../src/Views/ListView.vala"
		return;
#line 532 "ListView.c"
	}
#line 46 "../src/Views/ListView.vala"
	_tmp5_ = notejot_widgets_note_menu_popover_new ();
#line 46 "../src/Views/ListView.vala"
	g_object_ref_sink (_tmp5_);
#line 46 "../src/Views/ListView.vala"
	popover = _tmp5_;
#line 47 "../src/Views/ListView.vala"
	_tmp6_ = row;
#line 47 "../src/Views/ListView.vala"
	_tmp7_ = popover;
#line 47 "../src/Views/ListView.vala"
	notejot_widgets_note_popover_listener (G_TYPE_CHECK_INSTANCE_CAST (_tmp6_, NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote), _tmp7_);
#line 49 "../src/Views/ListView.vala"
	_tmp8_ = popover;
#line 49 "../src/Views/ListView.vala"
	_tmp9_ = row;
#line 49 "../src/Views/ListView.vala"
	gtk_popover_set_relative_to ((GtkPopover*) _tmp8_, (GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (_tmp9_, NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote));
#line 50 "../src/Views/ListView.vala"
	_tmp10_ = popover;
#line 50 "../src/Views/ListView.vala"
	gtk_popover_popup ((GtkPopover*) _tmp10_);
#line 52 "../src/Views/ListView.vala"
	_tmp11_ = self->priv->press;
#line 52 "../src/Views/ListView.vala"
	gtk_gesture_set_state ((GtkGesture*) _tmp11_, GTK_EVENT_SEQUENCE_CLAIMED);
#line 33 "../src/Views/ListView.vala"
	_g_object_unref0 (popover);
#line 33 "../src/Views/ListView.vala"
	_g_object_unref0 (row);
#line 564 "ListView.c"
}

static void
___lambda24__gtk_gesture_multi_press_pressed (GtkGestureMultiPress* _sender,
                                              gint n_press,
                                              gdouble x,
                                              gdouble y,
                                              gpointer self)
{
#line 33 "../src/Views/ListView.vala"
	__lambda24_ ((NotejotViewsListView*) self, _sender, n_press, x, y);
#line 576 "ListView.c"
}

NotejotViewsListView*
notejot_views_list_view_construct (GType object_type,
                                   NotejotMainWindow* win)
{
	NotejotViewsListView * self = NULL;
	Block1Data* _data1_;
	NotejotMainWindow* _tmp0_;
	NotejotMainWindow* _tmp1_;
	GtkGestureMultiPress* _tmp2_;
	GtkGestureMultiPress* _tmp3_;
	GtkGestureMultiPress* _tmp4_;
#line 7 "../src/Views/ListView.vala"
	g_return_val_if_fail (win != NULL, NULL);
#line 7 "../src/Views/ListView.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 7 "../src/Views/ListView.vala"
	_data1_->_ref_count_ = 1;
#line 7 "../src/Views/ListView.vala"
	_tmp0_ = _g_object_ref0 (win);
#line 7 "../src/Views/ListView.vala"
	_g_object_unref0 (_data1_->win);
#line 7 "../src/Views/ListView.vala"
	_data1_->win = _tmp0_;
#line 7 "../src/Views/ListView.vala"
	self = (NotejotViewsListView*) g_object_new (object_type, NULL);
#line 7 "../src/Views/ListView.vala"
	_data1_->self = g_object_ref (self);
#line 8 "../src/Views/ListView.vala"
	_tmp1_ = _g_object_ref0 (_data1_->win);
#line 8 "../src/Views/ListView.vala"
	_g_object_unref0 (self->priv->win);
#line 8 "../src/Views/ListView.vala"
	self->priv->win = _tmp1_;
#line 9 "../src/Views/ListView.vala"
	gtk_widget_set_vexpand ((GtkWidget*) self, TRUE);
#line 10 "../src/Views/ListView.vala"
	notejot_views_list_view_set_is_modified (self, FALSE);
#line 11 "../src/Views/ListView.vala"
	gtk_list_box_set_sort_func ((GtkListBox*) self, _notejot_views_list_view_list_sort_gtk_list_box_sort_func, g_object_ref (self), g_object_unref);
#line 12 "../src/Views/ListView.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 13 "../src/Views/ListView.vala"
	gtk_list_box_set_selection_mode ((GtkListBox*) self, GTK_SELECTION_SINGLE);
#line 14 "../src/Views/ListView.vala"
	gtk_list_box_set_activate_on_single_click ((GtkListBox*) self, TRUE);
#line 16 "../src/Views/ListView.vala"
	g_signal_connect_data ((GtkListBox*) self, "row-selected", (GCallback) ___lambda7__gtk_list_box_row_selected, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 30 "../src/Views/ListView.vala"
	_tmp2_ = (GtkGestureMultiPress*) gtk_gesture_multi_press_new ((GtkWidget*) self);
#line 30 "../src/Views/ListView.vala"
	_g_object_unref0 (self->priv->press);
#line 30 "../src/Views/ListView.vala"
	self->priv->press = _tmp2_;
#line 31 "../src/Views/ListView.vala"
	_tmp3_ = self->priv->press;
#line 31 "../src/Views/ListView.vala"
	gtk_gesture_single_set_button ((GtkGestureSingle*) _tmp3_, (guint) GDK_BUTTON_SECONDARY);
#line 33 "../src/Views/ListView.vala"
	_tmp4_ = self->priv->press;
#line 33 "../src/Views/ListView.vala"
	g_signal_connect_object (_tmp4_, "pressed", (GCallback) ___lambda24__gtk_gesture_multi_press_pressed, self, 0);
#line 7 "../src/Views/ListView.vala"
	block1_data_unref (_data1_);
#line 7 "../src/Views/ListView.vala"
	_data1_ = NULL;
#line 7 "../src/Views/ListView.vala"
	return self;
#line 646 "ListView.c"
}

NotejotViewsListView*
notejot_views_list_view_new (NotejotMainWindow* win)
{
#line 7 "../src/Views/ListView.vala"
	return notejot_views_list_view_construct (NOTEJOT_VIEWS_TYPE_LIST_VIEW, win);
#line 654 "ListView.c"
}

GList*
notejot_views_list_view_get_rows (NotejotViewsListView* self)
{
	GList* _tmp0_;
	GList* result = NULL;
#line 56 "../src/Views/ListView.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 57 "../src/Views/ListView.vala"
	_tmp0_ = gtk_container_get_children ((GtkContainer*) self);
#line 57 "../src/Views/ListView.vala"
	result = (GList*) _tmp0_;
#line 57 "../src/Views/ListView.vala"
	return result;
#line 670 "ListView.c"
}

void
notejot_views_list_view_clear_column (NotejotViewsListView* self)
{
	GList* _tmp0_;
	NotejotMainWindow* _tmp3_;
	NotejotTaskManager* _tmp4_;
#line 60 "../src/Views/ListView.vala"
	g_return_if_fail (self != NULL);
#line 61 "../src/Views/ListView.vala"
	_tmp0_ = gtk_container_get_children ((GtkContainer*) self);
#line 683 "ListView.c"
	{
		GList* item_collection = NULL;
		GList* item_it = NULL;
#line 61 "../src/Views/ListView.vala"
		item_collection = _tmp0_;
#line 61 "../src/Views/ListView.vala"
		for (item_it = item_collection; item_it != NULL; item_it = item_it->next) {
#line 691 "ListView.c"
			GtkWidget* _tmp1_;
			GtkWidget* item = NULL;
#line 61 "../src/Views/ListView.vala"
			_tmp1_ = _g_object_ref0 ((GtkWidget*) item_it->data);
#line 61 "../src/Views/ListView.vala"
			item = _tmp1_;
#line 698 "ListView.c"
			{
				GtkWidget* _tmp2_;
#line 62 "../src/Views/ListView.vala"
				_tmp2_ = item;
#line 62 "../src/Views/ListView.vala"
				gtk_widget_destroy (_tmp2_);
#line 61 "../src/Views/ListView.vala"
				_g_object_unref0 (item);
#line 707 "ListView.c"
			}
		}
#line 61 "../src/Views/ListView.vala"
		(item_collection == NULL) ? NULL : (item_collection = (g_list_free (item_collection), NULL));
#line 712 "ListView.c"
	}
#line 64 "../src/Views/ListView.vala"
	_tmp3_ = self->priv->win;
#line 64 "../src/Views/ListView.vala"
	_tmp4_ = _tmp3_->tm;
#line 64 "../src/Views/ListView.vala"
	notejot_task_manager_save_notes (_tmp4_, NULL, NULL);
#line 720 "ListView.c"
}

static void
notejot_views_list_view_new_taskbox_data_free (gpointer _data)
{
	NotejotViewsListViewNewTaskboxData* _data_;
	_data_ = _data;
#line 2 "../src/Views/ListView.vala"
	_g_object_unref0 (_data_->win);
#line 2 "../src/Views/ListView.vala"
	_g_free0 (_data_->title);
#line 2 "../src/Views/ListView.vala"
	_g_free0 (_data_->contents);
#line 2 "../src/Views/ListView.vala"
	_g_free0 (_data_->text);
#line 2 "../src/Views/ListView.vala"
	_g_free0 (_data_->color);
#line 2 "../src/Views/ListView.vala"
	_g_object_unref0 (_data_->self);
#line 2 "../src/Views/ListView.vala"
	g_slice_free (NotejotViewsListViewNewTaskboxData, _data_);
#line 742 "ListView.c"
}

void
notejot_views_list_view_new_taskbox (NotejotViewsListView* self,
                                     NotejotMainWindow* win,
                                     const gchar* title,
                                     const gchar* contents,
                                     const gchar* text,
                                     const gchar* color,
                                     GAsyncReadyCallback _callback_,
                                     gpointer _user_data_)
{
	NotejotViewsListViewNewTaskboxData* _data_;
	NotejotViewsListView* _tmp0_;
	NotejotMainWindow* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
#line 2 "../src/Views/ListView.vala"
	g_return_if_fail (self != NULL);
#line 2 "../src/Views/ListView.vala"
	g_return_if_fail (win != NULL);
#line 2 "../src/Views/ListView.vala"
	g_return_if_fail (title != NULL);
#line 2 "../src/Views/ListView.vala"
	g_return_if_fail (contents != NULL);
#line 2 "../src/Views/ListView.vala"
	g_return_if_fail (text != NULL);
#line 2 "../src/Views/ListView.vala"
	g_return_if_fail (color != NULL);
#line 2 "../src/Views/ListView.vala"
	_data_ = g_slice_new0 (NotejotViewsListViewNewTaskboxData);
#line 2 "../src/Views/ListView.vala"
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
#line 2 "../src/Views/ListView.vala"
	g_task_set_task_data (_data_->_async_result, _data_, notejot_views_list_view_new_taskbox_data_free);
#line 2 "../src/Views/ListView.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 2 "../src/Views/ListView.vala"
	_data_->self = _tmp0_;
#line 2 "../src/Views/ListView.vala"
	_tmp1_ = _g_object_ref0 (win);
#line 2 "../src/Views/ListView.vala"
	_g_object_unref0 (_data_->win);
#line 2 "../src/Views/ListView.vala"
	_data_->win = _tmp1_;
#line 2 "../src/Views/ListView.vala"
	_tmp2_ = g_strdup (title);
#line 2 "../src/Views/ListView.vala"
	_g_free0 (_data_->title);
#line 2 "../src/Views/ListView.vala"
	_data_->title = _tmp2_;
#line 2 "../src/Views/ListView.vala"
	_tmp3_ = g_strdup (contents);
#line 2 "../src/Views/ListView.vala"
	_g_free0 (_data_->contents);
#line 2 "../src/Views/ListView.vala"
	_data_->contents = _tmp3_;
#line 2 "../src/Views/ListView.vala"
	_tmp4_ = g_strdup (text);
#line 2 "../src/Views/ListView.vala"
	_g_free0 (_data_->text);
#line 2 "../src/Views/ListView.vala"
	_data_->text = _tmp4_;
#line 2 "../src/Views/ListView.vala"
	_tmp5_ = g_strdup (color);
#line 2 "../src/Views/ListView.vala"
	_g_free0 (_data_->color);
#line 2 "../src/Views/ListView.vala"
	_data_->color = _tmp5_;
#line 2 "../src/Views/ListView.vala"
	notejot_views_list_view_new_taskbox_co (_data_);
#line 816 "ListView.c"
}

void
notejot_views_list_view_new_taskbox_finish (NotejotViewsListView* self,
                                            GAsyncResult* _res_)
{
	NotejotViewsListViewNewTaskboxData* _data_;
#line 2 "../src/Views/ListView.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 826 "ListView.c"
}

static gboolean
notejot_views_list_view_new_taskbox_co (NotejotViewsListViewNewTaskboxData* _data_)
{
#line 67 "../src/Views/ListView.vala"
	switch (_data_->_state_) {
#line 67 "../src/Views/ListView.vala"
		case 0:
#line 836 "ListView.c"
		goto _state_0;
		default:
#line 67 "../src/Views/ListView.vala"
		g_assert_not_reached ();
#line 841 "ListView.c"
	}
	_state_0:
#line 68 "../src/Views/ListView.vala"
	_data_->_tmp0_ = notejot_widgets_note_new (_data_->win, _data_->title, _data_->contents, _data_->text, _data_->color);
#line 68 "../src/Views/ListView.vala"
	g_object_ref_sink (_data_->_tmp0_);
#line 68 "../src/Views/ListView.vala"
	_data_->taskbox = _data_->_tmp0_;
#line 69 "../src/Views/ListView.vala"
	gtk_list_box_insert ((GtkListBox*) _data_->self, (GtkWidget*) _data_->taskbox, -1);
#line 70 "../src/Views/ListView.vala"
	_data_->_tmp1_ = _data_->win->tm;
#line 70 "../src/Views/ListView.vala"
	notejot_task_manager_save_notes (_data_->_tmp1_, NULL, NULL);
#line 71 "../src/Views/ListView.vala"
	notejot_views_list_view_set_is_modified (_data_->self, TRUE);
#line 67 "../src/Views/ListView.vala"
	_g_object_unref0 (_data_->taskbox);
#line 67 "../src/Views/ListView.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 67 "../src/Views/ListView.vala"
	if (_data_->_state_ != 0) {
#line 67 "../src/Views/ListView.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 67 "../src/Views/ListView.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 868 "ListView.c"
		}
	}
#line 67 "../src/Views/ListView.vala"
	g_object_unref (_data_->_async_result);
#line 67 "../src/Views/ListView.vala"
	return FALSE;
#line 875 "ListView.c"
}

gint
notejot_views_list_view_list_sort (NotejotViewsListView* self,
                                   GtkListBoxRow* first_row,
                                   GtkListBoxRow* second_row)
{
	GtkListBoxRow* row_1 = NULL;
	GtkListBoxRow* _tmp0_;
	GtkListBoxRow* row_2 = NULL;
	GtkListBoxRow* _tmp1_;
	gchar* name_1 = NULL;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* name_2 = NULL;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	gint result = 0;
#line 74 "../src/Views/ListView.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 74 "../src/Views/ListView.vala"
	g_return_val_if_fail (first_row != NULL, 0);
#line 74 "../src/Views/ListView.vala"
	g_return_val_if_fail (second_row != NULL, 0);
#line 75 "../src/Views/ListView.vala"
	_tmp0_ = _g_object_ref0 (first_row);
#line 75 "../src/Views/ListView.vala"
	row_1 = _tmp0_;
#line 76 "../src/Views/ListView.vala"
	_tmp1_ = _g_object_ref0 (second_row);
#line 76 "../src/Views/ListView.vala"
	row_2 = _tmp1_;
#line 78 "../src/Views/ListView.vala"
	_tmp2_ = G_TYPE_CHECK_INSTANCE_CAST (row_1, NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote)->title;
#line 78 "../src/Views/ListView.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 78 "../src/Views/ListView.vala"
	name_1 = _tmp3_;
#line 79 "../src/Views/ListView.vala"
	_tmp4_ = G_TYPE_CHECK_INSTANCE_CAST (row_2, NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote)->title;
#line 79 "../src/Views/ListView.vala"
	_tmp5_ = g_strdup (_tmp4_);
#line 79 "../src/Views/ListView.vala"
	name_2 = _tmp5_;
#line 81 "../src/Views/ListView.vala"
	result = g_utf8_collate (name_1, name_2);
#line 81 "../src/Views/ListView.vala"
	_g_free0 (name_2);
#line 81 "../src/Views/ListView.vala"
	_g_free0 (name_1);
#line 81 "../src/Views/ListView.vala"
	_g_object_unref0 (row_2);
#line 81 "../src/Views/ListView.vala"
	_g_object_unref0 (row_1);
#line 81 "../src/Views/ListView.vala"
	return result;
#line 932 "ListView.c"
}

gboolean
notejot_views_list_view_get_is_modified (NotejotViewsListView* self)
{
	gboolean result;
#line 5 "../src/Views/ListView.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 5 "../src/Views/ListView.vala"
	result = self->priv->_is_modified;
#line 5 "../src/Views/ListView.vala"
	return result;
#line 945 "ListView.c"
}

void
notejot_views_list_view_set_is_modified (NotejotViewsListView* self,
                                         gboolean value)
{
	gboolean old_value;
#line 5 "../src/Views/ListView.vala"
	g_return_if_fail (self != NULL);
#line 5 "../src/Views/ListView.vala"
	old_value = notejot_views_list_view_get_is_modified (self);
#line 5 "../src/Views/ListView.vala"
	if (old_value != value) {
#line 5 "../src/Views/ListView.vala"
		self->priv->_is_modified = value;
#line 5 "../src/Views/ListView.vala"
		g_object_notify_by_pspec ((GObject *) self, notejot_views_list_view_properties[NOTEJOT_VIEWS_LIST_VIEW_IS_MODIFIED_PROPERTY]);
#line 963 "ListView.c"
	}
}

static void
notejot_views_list_view_class_init (NotejotViewsListViewClass * klass,
                                    gpointer klass_data)
{
#line 2 "../src/Views/ListView.vala"
	notejot_views_list_view_parent_class = g_type_class_peek_parent (klass);
#line 2 "../src/Views/ListView.vala"
	g_type_class_adjust_private_offset (klass, &NotejotViewsListView_private_offset);
#line 2 "../src/Views/ListView.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_notejot_views_list_view_get_property;
#line 2 "../src/Views/ListView.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_notejot_views_list_view_set_property;
#line 2 "../src/Views/ListView.vala"
	G_OBJECT_CLASS (klass)->finalize = notejot_views_list_view_finalize;
#line 2 "../src/Views/ListView.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), NOTEJOT_VIEWS_LIST_VIEW_IS_MODIFIED_PROPERTY, notejot_views_list_view_properties[NOTEJOT_VIEWS_LIST_VIEW_IS_MODIFIED_PROPERTY] = g_param_spec_boolean ("is-modified", "is-modified", "is-modified", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 983 "ListView.c"
}

static void
notejot_views_list_view_instance_init (NotejotViewsListView * self,
                                       gpointer klass)
{
#line 2 "../src/Views/ListView.vala"
	self->priv = notejot_views_list_view_get_instance_private (self);
#line 5 "../src/Views/ListView.vala"
	self->priv->_is_modified = FALSE;
#line 994 "ListView.c"
}

static void
notejot_views_list_view_finalize (GObject * obj)
{
	NotejotViewsListView * self;
#line 2 "../src/Views/ListView.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListView);
#line 3 "../src/Views/ListView.vala"
	_g_object_unref0 (self->priv->win);
#line 4 "../src/Views/ListView.vala"
	_g_object_unref0 (self->priv->press);
#line 2 "../src/Views/ListView.vala"
	G_OBJECT_CLASS (notejot_views_list_view_parent_class)->finalize (obj);
#line 1009 "ListView.c"
}

static GType
notejot_views_list_view_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (NotejotViewsListViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) notejot_views_list_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NotejotViewsListView), 0, (GInstanceInitFunc) notejot_views_list_view_instance_init, NULL };
	GType notejot_views_list_view_type_id;
	notejot_views_list_view_type_id = g_type_register_static (gtk_list_box_get_type (), "NotejotViewsListView", &g_define_type_info, 0);
	NotejotViewsListView_private_offset = g_type_add_instance_private (notejot_views_list_view_type_id, sizeof (NotejotViewsListViewPrivate));
	return notejot_views_list_view_type_id;
}

GType
notejot_views_list_view_get_type (void)
{
	static volatile gsize notejot_views_list_view_type_id__volatile = 0;
	if (g_once_init_enter (&notejot_views_list_view_type_id__volatile)) {
		GType notejot_views_list_view_type_id;
		notejot_views_list_view_type_id = notejot_views_list_view_get_type_once ();
		g_once_init_leave (&notejot_views_list_view_type_id__volatile, notejot_views_list_view_type_id);
	}
	return notejot_views_list_view_type_id__volatile;
}

static void
_vala_notejot_views_list_view_get_property (GObject * object,
                                            guint property_id,
                                            GValue * value,
                                            GParamSpec * pspec)
{
	NotejotViewsListView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListView);
#line 2 "../src/Views/ListView.vala"
	switch (property_id) {
#line 2 "../src/Views/ListView.vala"
		case NOTEJOT_VIEWS_LIST_VIEW_IS_MODIFIED_PROPERTY:
#line 2 "../src/Views/ListView.vala"
		g_value_set_boolean (value, notejot_views_list_view_get_is_modified (self));
#line 2 "../src/Views/ListView.vala"
		break;
#line 1050 "ListView.c"
		default:
#line 2 "../src/Views/ListView.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 2 "../src/Views/ListView.vala"
		break;
#line 1056 "ListView.c"
	}
}

static void
_vala_notejot_views_list_view_set_property (GObject * object,
                                            guint property_id,
                                            const GValue * value,
                                            GParamSpec * pspec)
{
	NotejotViewsListView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListView);
#line 2 "../src/Views/ListView.vala"
	switch (property_id) {
#line 2 "../src/Views/ListView.vala"
		case NOTEJOT_VIEWS_LIST_VIEW_IS_MODIFIED_PROPERTY:
#line 2 "../src/Views/ListView.vala"
		notejot_views_list_view_set_is_modified (self, g_value_get_boolean (value));
#line 2 "../src/Views/ListView.vala"
		break;
#line 1076 "ListView.c"
		default:
#line 2 "../src/Views/ListView.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 2 "../src/Views/ListView.vala"
		break;
#line 1082 "ListView.c"
	}
}

