/* TrashView.c generated by valac 0.50.3, the Vala compiler
 * generated from TrashView.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <handy.h>
#include <glib.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>

#define NOTEJOT_VIEWS_TYPE_TRASH_VIEW (notejot_views_trash_view_get_type ())
#define NOTEJOT_VIEWS_TRASH_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashView))
#define NOTEJOT_VIEWS_TRASH_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashViewClass))
#define NOTEJOT_VIEWS_IS_TRASH_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW))
#define NOTEJOT_VIEWS_IS_TRASH_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_VIEWS_TYPE_TRASH_VIEW))
#define NOTEJOT_VIEWS_TRASH_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashViewClass))

typedef struct _NotejotViewsTrashView NotejotViewsTrashView;
typedef struct _NotejotViewsTrashViewClass NotejotViewsTrashViewClass;
typedef struct _NotejotViewsTrashViewPrivate NotejotViewsTrashViewPrivate;

#define NOTEJOT_TYPE_MAIN_WINDOW (notejot_main_window_get_type ())
#define NOTEJOT_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindow))
#define NOTEJOT_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindowClass))
#define NOTEJOT_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_TYPE_MAIN_WINDOW))
#define NOTEJOT_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_TYPE_MAIN_WINDOW))
#define NOTEJOT_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindowClass))

typedef struct _NotejotMainWindow NotejotMainWindow;
typedef struct _NotejotMainWindowClass NotejotMainWindowClass;
enum  {
	NOTEJOT_VIEWS_TRASH_VIEW_0_PROPERTY,
	NOTEJOT_VIEWS_TRASH_VIEW_IS_MODIFIED_PROPERTY,
	NOTEJOT_VIEWS_TRASH_VIEW_NUM_PROPERTIES
};
static GParamSpec* notejot_views_trash_view_properties[NOTEJOT_VIEWS_TRASH_VIEW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define NOTEJOT_WIDGETS_TYPE_NOTE (notejot_widgets_note_get_type ())
#define NOTEJOT_WIDGETS_NOTE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote))
#define NOTEJOT_WIDGETS_NOTE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNoteClass))
#define NOTEJOT_WIDGETS_IS_NOTE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_NOTE))
#define NOTEJOT_WIDGETS_IS_NOTE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_NOTE))
#define NOTEJOT_WIDGETS_NOTE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNoteClass))

typedef struct _NotejotWidgetsNote NotejotWidgetsNote;
typedef struct _NotejotWidgetsNoteClass NotejotWidgetsNoteClass;
typedef struct _NotejotMainWindowPrivate NotejotMainWindowPrivate;

#define NOTEJOT_WIDGETS_TYPE_DIALOG (notejot_widgets_dialog_get_type ())
#define NOTEJOT_WIDGETS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialog))
#define NOTEJOT_WIDGETS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialogClass))
#define NOTEJOT_WIDGETS_IS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG))
#define NOTEJOT_WIDGETS_IS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_DIALOG))
#define NOTEJOT_WIDGETS_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialogClass))

typedef struct _NotejotWidgetsDialog NotejotWidgetsDialog;
typedef struct _NotejotWidgetsDialogClass NotejotWidgetsDialogClass;

#define NOTEJOT_WIDGETS_TYPE_SETTING_MENU (notejot_widgets_setting_menu_get_type ())
#define NOTEJOT_WIDGETS_SETTING_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenu))
#define NOTEJOT_WIDGETS_SETTING_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenuClass))
#define NOTEJOT_WIDGETS_IS_SETTING_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU))
#define NOTEJOT_WIDGETS_IS_SETTING_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_SETTING_MENU))
#define NOTEJOT_WIDGETS_SETTING_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenuClass))

typedef struct _NotejotWidgetsSettingMenu NotejotWidgetsSettingMenu;
typedef struct _NotejotWidgetsSettingMenuClass NotejotWidgetsSettingMenuClass;

#define NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON (notejot_widgets_header_bar_button_get_type ())
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButton))
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButtonClass))
#define NOTEJOT_WIDGETS_IS_HEADER_BAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON))
#define NOTEJOT_WIDGETS_IS_HEADER_BAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON))
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButtonClass))

typedef struct _NotejotWidgetsHeaderBarButton NotejotWidgetsHeaderBarButton;
typedef struct _NotejotWidgetsHeaderBarButtonClass NotejotWidgetsHeaderBarButtonClass;

#define NOTEJOT_VIEWS_TYPE_LIST_VIEW (notejot_views_list_view_get_type ())
#define NOTEJOT_VIEWS_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListView))
#define NOTEJOT_VIEWS_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListViewClass))
#define NOTEJOT_VIEWS_IS_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW))
#define NOTEJOT_VIEWS_IS_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_VIEWS_TYPE_LIST_VIEW))
#define NOTEJOT_VIEWS_LIST_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListViewClass))

typedef struct _NotejotViewsListView NotejotViewsListView;
typedef struct _NotejotViewsListViewClass NotejotViewsListViewClass;

#define NOTEJOT_TYPE_TASK_MANAGER (notejot_task_manager_get_type ())
#define NOTEJOT_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManager))
#define NOTEJOT_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManagerClass))
#define NOTEJOT_IS_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_TYPE_TASK_MANAGER))
#define NOTEJOT_IS_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_TYPE_TASK_MANAGER))
#define NOTEJOT_TASK_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManagerClass))

typedef struct _NotejotTaskManager NotejotTaskManager;
typedef struct _NotejotTaskManagerClass NotejotTaskManagerClass;
#define _g_free0(var) (var = (g_free (var), NULL))

#define NOTEJOT_WIDGETS_TYPE_TRASHED_ITEM (notejot_widgets_trashed_item_get_type ())
#define NOTEJOT_WIDGETS_TRASHED_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_TRASHED_ITEM, NotejotWidgetsTrashedItem))
#define NOTEJOT_WIDGETS_TRASHED_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_TRASHED_ITEM, NotejotWidgetsTrashedItemClass))
#define NOTEJOT_WIDGETS_IS_TRASHED_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_TRASHED_ITEM))
#define NOTEJOT_WIDGETS_IS_TRASHED_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_TRASHED_ITEM))
#define NOTEJOT_WIDGETS_TRASHED_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_TRASHED_ITEM, NotejotWidgetsTrashedItemClass))

typedef struct _NotejotWidgetsTrashedItem NotejotWidgetsTrashedItem;
typedef struct _NotejotWidgetsTrashedItemClass NotejotWidgetsTrashedItemClass;
typedef struct _NotejotViewsTrashViewNewTaskboxData NotejotViewsTrashViewNewTaskboxData;

struct _NotejotViewsTrashView {
	GtkListBox parent_instance;
	NotejotViewsTrashViewPrivate * priv;
};

struct _NotejotViewsTrashViewClass {
	GtkListBoxClass parent_class;
};

struct _NotejotViewsTrashViewPrivate {
	NotejotMainWindow* win;
	gboolean _is_modified;
};

struct _NotejotMainWindow {
	HdyApplicationWindow parent_instance;
	NotejotMainWindowPrivate * priv;
	GtkButton* new_button;
	GtkButton* back_button;
	GtkButton* welcome_new_button;
	GtkMenuButton* menu_button;
	GtkBox* grid;
	GtkBox* sgrid;
	GtkBox* welcome_view;
	GtkBox* empty_state;
	HdyLeaflet* leaflet;
	GtkStack* main_stack;
	GtkStack* sidebar_stack;
	GtkStack* titlebar_stack;
	HdyHeaderBar* titlebar;
	HdyHeaderBar* stitlebar;
	HdyHeaderBar* welcome_titlebar;
	HdyHeaderGroup* titlegroup;
	GtkScrolledWindow* trash_scroller;
	GtkScrolledWindow* list_scroller;
	NotejotWidgetsDialog* dialog;
	NotejotWidgetsSettingMenu* settingmenu;
	NotejotWidgetsHeaderBarButton* sidebar_title_button;
	NotejotViewsListView* listview;
	NotejotViewsTrashView* trashview;
	NotejotTaskManager* tm;
	gboolean pinned;
};

struct _NotejotMainWindowClass {
	HdyApplicationWindowClass parent_class;
};

struct _NotejotViewsTrashViewNewTaskboxData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	NotejotViewsTrashView* self;
	NotejotMainWindow* win;
	gchar* title;
	gchar* contents;
	gchar* text;
	gchar* color;
	NotejotWidgetsTrashedItem* taskbox;
	NotejotWidgetsTrashedItem* _tmp0_;
	NotejotTaskManager* _tmp1_;
};

static gint NotejotViewsTrashView_private_offset;
static gpointer notejot_views_trash_view_parent_class = NULL;

GType notejot_views_trash_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotViewsTrashView, g_object_unref)
GType notejot_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotMainWindow, g_object_unref)
NotejotViewsTrashView* notejot_views_trash_view_new (NotejotMainWindow* win);
NotejotViewsTrashView* notejot_views_trash_view_construct (GType object_type,
                                                           NotejotMainWindow* win);
void notejot_views_trash_view_set_is_modified (NotejotViewsTrashView* self,
                                               gboolean value);
gint notejot_views_trash_view_list_sort (NotejotViewsTrashView* self,
                                         GtkListBoxRow* first_row,
                                         GtkListBoxRow* second_row);
static gint _notejot_views_trash_view_list_sort_gtk_list_box_sort_func (GtkListBoxRow* row1,
                                                                 GtkListBoxRow* row2,
                                                                 gpointer self);
GType notejot_widgets_note_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsNote, g_object_unref)
GList* notejot_views_trash_view_get_rows (NotejotViewsTrashView* self);
void notejot_views_trash_view_clear_column (NotejotViewsTrashView* self);
GType notejot_widgets_dialog_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsDialog, g_object_unref)
GType notejot_widgets_setting_menu_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsSettingMenu, g_object_unref)
GType notejot_widgets_header_bar_button_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsHeaderBarButton, g_object_unref)
GType notejot_views_list_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotViewsListView, g_object_unref)
gpointer notejot_task_manager_ref (gpointer instance);
void notejot_task_manager_unref (gpointer instance);
GParamSpec* notejot_param_spec_task_manager (const gchar* name,
                                             const gchar* nick,
                                             const gchar* blurb,
                                             GType object_type,
                                             GParamFlags flags);
void notejot_value_set_task_manager (GValue* value,
                                     gpointer v_object);
void notejot_value_take_task_manager (GValue* value,
                                      gpointer v_object);
gpointer notejot_value_get_task_manager (const GValue* value);
GType notejot_task_manager_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotTaskManager, notejot_task_manager_unref)
void notejot_task_manager_save_notes (NotejotTaskManager* self,
                                      GAsyncReadyCallback _callback_,
                                      gpointer _user_data_);
void notejot_task_manager_save_notes_finish (NotejotTaskManager* self,
                                             GAsyncResult* _res_);
static void notejot_views_trash_view_new_taskbox_data_free (gpointer _data);
void notejot_views_trash_view_new_taskbox (NotejotViewsTrashView* self,
                                           NotejotMainWindow* win,
                                           const gchar* title,
                                           const gchar* contents,
                                           const gchar* text,
                                           const gchar* color,
                                           GAsyncReadyCallback _callback_,
                                           gpointer _user_data_);
void notejot_views_trash_view_new_taskbox_finish (NotejotViewsTrashView* self,
                                                  GAsyncResult* _res_);
static gboolean notejot_views_trash_view_new_taskbox_co (NotejotViewsTrashViewNewTaskboxData* _data_);
GType notejot_widgets_trashed_item_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsTrashedItem, g_object_unref)
NotejotWidgetsTrashedItem* notejot_widgets_trashed_item_new (NotejotMainWindow* win,
                                                             const gchar* title,
                                                             const gchar* subtitle,
                                                             const gchar* text,
                                                             const gchar* color);
NotejotWidgetsTrashedItem* notejot_widgets_trashed_item_construct (GType object_type,
                                                                   NotejotMainWindow* win,
                                                                   const gchar* title,
                                                                   const gchar* subtitle,
                                                                   const gchar* text,
                                                                   const gchar* color);
gboolean notejot_views_trash_view_get_is_modified (NotejotViewsTrashView* self);
static void notejot_views_trash_view_finalize (GObject * obj);
static GType notejot_views_trash_view_get_type_once (void);
static void _vala_notejot_views_trash_view_get_property (GObject * object,
                                                  guint property_id,
                                                  GValue * value,
                                                  GParamSpec * pspec);
static void _vala_notejot_views_trash_view_set_property (GObject * object,
                                                  guint property_id,
                                                  const GValue * value,
                                                  GParamSpec * pspec);

static inline gpointer
notejot_views_trash_view_get_instance_private (NotejotViewsTrashView* self)
{
	return G_STRUCT_MEMBER_P (self, NotejotViewsTrashView_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 7 "../src/Views/TrashView.vala"
	return self ? g_object_ref (self) : NULL;
#line 275 "TrashView.c"
}

static gint
_notejot_views_trash_view_list_sort_gtk_list_box_sort_func (GtkListBoxRow* row1,
                                                            GtkListBoxRow* row2,
                                                            gpointer self)
{
	gint result;
	result = notejot_views_trash_view_list_sort ((NotejotViewsTrashView*) self, row1, row2);
#line 10 "../src/Views/TrashView.vala"
	return result;
#line 287 "TrashView.c"
}

NotejotViewsTrashView*
notejot_views_trash_view_construct (GType object_type,
                                    NotejotMainWindow* win)
{
	NotejotViewsTrashView * self = NULL;
	NotejotMainWindow* _tmp0_;
#line 6 "../src/Views/TrashView.vala"
	g_return_val_if_fail (win != NULL, NULL);
#line 6 "../src/Views/TrashView.vala"
	self = (NotejotViewsTrashView*) g_object_new (object_type, NULL);
#line 7 "../src/Views/TrashView.vala"
	_tmp0_ = _g_object_ref0 (win);
#line 7 "../src/Views/TrashView.vala"
	_g_object_unref0 (self->priv->win);
#line 7 "../src/Views/TrashView.vala"
	self->priv->win = _tmp0_;
#line 8 "../src/Views/TrashView.vala"
	gtk_widget_set_vexpand ((GtkWidget*) self, TRUE);
#line 9 "../src/Views/TrashView.vala"
	notejot_views_trash_view_set_is_modified (self, FALSE);
#line 10 "../src/Views/TrashView.vala"
	gtk_list_box_set_sort_func ((GtkListBox*) self, _notejot_views_trash_view_list_sort_gtk_list_box_sort_func, g_object_ref (self), g_object_unref);
#line 11 "../src/Views/TrashView.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 12 "../src/Views/TrashView.vala"
	gtk_list_box_set_selection_mode ((GtkListBox*) self, GTK_SELECTION_NONE);
#line 6 "../src/Views/TrashView.vala"
	return self;
#line 318 "TrashView.c"
}

NotejotViewsTrashView*
notejot_views_trash_view_new (NotejotMainWindow* win)
{
#line 6 "../src/Views/TrashView.vala"
	return notejot_views_trash_view_construct (NOTEJOT_VIEWS_TYPE_TRASH_VIEW, win);
#line 326 "TrashView.c"
}

GList*
notejot_views_trash_view_get_rows (NotejotViewsTrashView* self)
{
	GList* _tmp0_;
	GList* result = NULL;
#line 15 "../src/Views/TrashView.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 16 "../src/Views/TrashView.vala"
	_tmp0_ = gtk_container_get_children ((GtkContainer*) self);
#line 16 "../src/Views/TrashView.vala"
	result = (GList*) _tmp0_;
#line 16 "../src/Views/TrashView.vala"
	return result;
#line 342 "TrashView.c"
}

void
notejot_views_trash_view_clear_column (NotejotViewsTrashView* self)
{
	GList* _tmp0_;
	NotejotMainWindow* _tmp3_;
	NotejotTaskManager* _tmp4_;
#line 19 "../src/Views/TrashView.vala"
	g_return_if_fail (self != NULL);
#line 20 "../src/Views/TrashView.vala"
	_tmp0_ = gtk_container_get_children ((GtkContainer*) self);
#line 355 "TrashView.c"
	{
		GList* item_collection = NULL;
		GList* item_it = NULL;
#line 20 "../src/Views/TrashView.vala"
		item_collection = _tmp0_;
#line 20 "../src/Views/TrashView.vala"
		for (item_it = item_collection; item_it != NULL; item_it = item_it->next) {
#line 363 "TrashView.c"
			GtkWidget* _tmp1_;
			GtkWidget* item = NULL;
#line 20 "../src/Views/TrashView.vala"
			_tmp1_ = _g_object_ref0 ((GtkWidget*) item_it->data);
#line 20 "../src/Views/TrashView.vala"
			item = _tmp1_;
#line 370 "TrashView.c"
			{
				GtkWidget* _tmp2_;
#line 21 "../src/Views/TrashView.vala"
				_tmp2_ = item;
#line 21 "../src/Views/TrashView.vala"
				gtk_widget_destroy (_tmp2_);
#line 20 "../src/Views/TrashView.vala"
				_g_object_unref0 (item);
#line 379 "TrashView.c"
			}
		}
#line 20 "../src/Views/TrashView.vala"
		(item_collection == NULL) ? NULL : (item_collection = (g_list_free (item_collection), NULL));
#line 384 "TrashView.c"
	}
#line 23 "../src/Views/TrashView.vala"
	_tmp3_ = self->priv->win;
#line 23 "../src/Views/TrashView.vala"
	_tmp4_ = _tmp3_->tm;
#line 23 "../src/Views/TrashView.vala"
	notejot_task_manager_save_notes (_tmp4_, NULL, NULL);
#line 392 "TrashView.c"
}

static void
notejot_views_trash_view_new_taskbox_data_free (gpointer _data)
{
	NotejotViewsTrashViewNewTaskboxData* _data_;
	_data_ = _data;
#line 2 "../src/Views/TrashView.vala"
	_g_object_unref0 (_data_->win);
#line 2 "../src/Views/TrashView.vala"
	_g_free0 (_data_->title);
#line 2 "../src/Views/TrashView.vala"
	_g_free0 (_data_->contents);
#line 2 "../src/Views/TrashView.vala"
	_g_free0 (_data_->text);
#line 2 "../src/Views/TrashView.vala"
	_g_free0 (_data_->color);
#line 2 "../src/Views/TrashView.vala"
	_g_object_unref0 (_data_->self);
#line 2 "../src/Views/TrashView.vala"
	g_slice_free (NotejotViewsTrashViewNewTaskboxData, _data_);
#line 414 "TrashView.c"
}

void
notejot_views_trash_view_new_taskbox (NotejotViewsTrashView* self,
                                      NotejotMainWindow* win,
                                      const gchar* title,
                                      const gchar* contents,
                                      const gchar* text,
                                      const gchar* color,
                                      GAsyncReadyCallback _callback_,
                                      gpointer _user_data_)
{
	NotejotViewsTrashViewNewTaskboxData* _data_;
	NotejotViewsTrashView* _tmp0_;
	NotejotMainWindow* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
#line 2 "../src/Views/TrashView.vala"
	g_return_if_fail (self != NULL);
#line 2 "../src/Views/TrashView.vala"
	g_return_if_fail (win != NULL);
#line 2 "../src/Views/TrashView.vala"
	g_return_if_fail (title != NULL);
#line 2 "../src/Views/TrashView.vala"
	g_return_if_fail (contents != NULL);
#line 2 "../src/Views/TrashView.vala"
	g_return_if_fail (text != NULL);
#line 2 "../src/Views/TrashView.vala"
	g_return_if_fail (color != NULL);
#line 2 "../src/Views/TrashView.vala"
	_data_ = g_slice_new0 (NotejotViewsTrashViewNewTaskboxData);
#line 2 "../src/Views/TrashView.vala"
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
#line 2 "../src/Views/TrashView.vala"
	g_task_set_task_data (_data_->_async_result, _data_, notejot_views_trash_view_new_taskbox_data_free);
#line 2 "../src/Views/TrashView.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 2 "../src/Views/TrashView.vala"
	_data_->self = _tmp0_;
#line 2 "../src/Views/TrashView.vala"
	_tmp1_ = _g_object_ref0 (win);
#line 2 "../src/Views/TrashView.vala"
	_g_object_unref0 (_data_->win);
#line 2 "../src/Views/TrashView.vala"
	_data_->win = _tmp1_;
#line 2 "../src/Views/TrashView.vala"
	_tmp2_ = g_strdup (title);
#line 2 "../src/Views/TrashView.vala"
	_g_free0 (_data_->title);
#line 2 "../src/Views/TrashView.vala"
	_data_->title = _tmp2_;
#line 2 "../src/Views/TrashView.vala"
	_tmp3_ = g_strdup (contents);
#line 2 "../src/Views/TrashView.vala"
	_g_free0 (_data_->contents);
#line 2 "../src/Views/TrashView.vala"
	_data_->contents = _tmp3_;
#line 2 "../src/Views/TrashView.vala"
	_tmp4_ = g_strdup (text);
#line 2 "../src/Views/TrashView.vala"
	_g_free0 (_data_->text);
#line 2 "../src/Views/TrashView.vala"
	_data_->text = _tmp4_;
#line 2 "../src/Views/TrashView.vala"
	_tmp5_ = g_strdup (color);
#line 2 "../src/Views/TrashView.vala"
	_g_free0 (_data_->color);
#line 2 "../src/Views/TrashView.vala"
	_data_->color = _tmp5_;
#line 2 "../src/Views/TrashView.vala"
	notejot_views_trash_view_new_taskbox_co (_data_);
#line 488 "TrashView.c"
}

void
notejot_views_trash_view_new_taskbox_finish (NotejotViewsTrashView* self,
                                             GAsyncResult* _res_)
{
	NotejotViewsTrashViewNewTaskboxData* _data_;
#line 2 "../src/Views/TrashView.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 498 "TrashView.c"
}

static gboolean
notejot_views_trash_view_new_taskbox_co (NotejotViewsTrashViewNewTaskboxData* _data_)
{
#line 26 "../src/Views/TrashView.vala"
	switch (_data_->_state_) {
#line 26 "../src/Views/TrashView.vala"
		case 0:
#line 508 "TrashView.c"
		goto _state_0;
		default:
#line 26 "../src/Views/TrashView.vala"
		g_assert_not_reached ();
#line 513 "TrashView.c"
	}
	_state_0:
#line 27 "../src/Views/TrashView.vala"
	_data_->_tmp0_ = notejot_widgets_trashed_item_new (_data_->win, _data_->title, _data_->contents, _data_->text, _data_->color);
#line 27 "../src/Views/TrashView.vala"
	g_object_ref_sink (_data_->_tmp0_);
#line 27 "../src/Views/TrashView.vala"
	_data_->taskbox = _data_->_tmp0_;
#line 28 "../src/Views/TrashView.vala"
	gtk_list_box_insert ((GtkListBox*) _data_->self, (GtkWidget*) _data_->taskbox, -1);
#line 29 "../src/Views/TrashView.vala"
	_data_->_tmp1_ = _data_->win->tm;
#line 29 "../src/Views/TrashView.vala"
	notejot_task_manager_save_notes (_data_->_tmp1_, NULL, NULL);
#line 30 "../src/Views/TrashView.vala"
	notejot_views_trash_view_set_is_modified (_data_->self, TRUE);
#line 26 "../src/Views/TrashView.vala"
	_g_object_unref0 (_data_->taskbox);
#line 26 "../src/Views/TrashView.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 26 "../src/Views/TrashView.vala"
	if (_data_->_state_ != 0) {
#line 26 "../src/Views/TrashView.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 26 "../src/Views/TrashView.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 540 "TrashView.c"
		}
	}
#line 26 "../src/Views/TrashView.vala"
	g_object_unref (_data_->_async_result);
#line 26 "../src/Views/TrashView.vala"
	return FALSE;
#line 547 "TrashView.c"
}

gint
notejot_views_trash_view_list_sort (NotejotViewsTrashView* self,
                                    GtkListBoxRow* first_row,
                                    GtkListBoxRow* second_row)
{
	GtkListBoxRow* row_1 = NULL;
	GtkListBoxRow* _tmp0_;
	GtkListBoxRow* row_2 = NULL;
	GtkListBoxRow* _tmp1_;
	gchar* name_1 = NULL;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* name_2 = NULL;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	gint result = 0;
#line 33 "../src/Views/TrashView.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 33 "../src/Views/TrashView.vala"
	g_return_val_if_fail (first_row != NULL, 0);
#line 33 "../src/Views/TrashView.vala"
	g_return_val_if_fail (second_row != NULL, 0);
#line 34 "../src/Views/TrashView.vala"
	_tmp0_ = _g_object_ref0 (first_row);
#line 34 "../src/Views/TrashView.vala"
	row_1 = _tmp0_;
#line 35 "../src/Views/TrashView.vala"
	_tmp1_ = _g_object_ref0 (second_row);
#line 35 "../src/Views/TrashView.vala"
	row_2 = _tmp1_;
#line 37 "../src/Views/TrashView.vala"
	_tmp2_ = gtk_widget_get_name ((GtkWidget*) row_1);
#line 37 "../src/Views/TrashView.vala"
	_tmp3_ = _tmp2_;
#line 37 "../src/Views/TrashView.vala"
	_tmp4_ = g_strdup (_tmp3_);
#line 37 "../src/Views/TrashView.vala"
	name_1 = _tmp4_;
#line 38 "../src/Views/TrashView.vala"
	_tmp5_ = gtk_widget_get_name ((GtkWidget*) row_2);
#line 38 "../src/Views/TrashView.vala"
	_tmp6_ = _tmp5_;
#line 38 "../src/Views/TrashView.vala"
	_tmp7_ = g_strdup (_tmp6_);
#line 38 "../src/Views/TrashView.vala"
	name_2 = _tmp7_;
#line 40 "../src/Views/TrashView.vala"
	result = g_utf8_collate (name_1, name_2);
#line 40 "../src/Views/TrashView.vala"
	_g_free0 (name_2);
#line 40 "../src/Views/TrashView.vala"
	_g_free0 (name_1);
#line 40 "../src/Views/TrashView.vala"
	_g_object_unref0 (row_2);
#line 40 "../src/Views/TrashView.vala"
	_g_object_unref0 (row_1);
#line 40 "../src/Views/TrashView.vala"
	return result;
#line 610 "TrashView.c"
}

gboolean
notejot_views_trash_view_get_is_modified (NotejotViewsTrashView* self)
{
	gboolean result;
#line 4 "../src/Views/TrashView.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 4 "../src/Views/TrashView.vala"
	result = self->priv->_is_modified;
#line 4 "../src/Views/TrashView.vala"
	return result;
#line 623 "TrashView.c"
}

void
notejot_views_trash_view_set_is_modified (NotejotViewsTrashView* self,
                                          gboolean value)
{
	gboolean old_value;
#line 4 "../src/Views/TrashView.vala"
	g_return_if_fail (self != NULL);
#line 4 "../src/Views/TrashView.vala"
	old_value = notejot_views_trash_view_get_is_modified (self);
#line 4 "../src/Views/TrashView.vala"
	if (old_value != value) {
#line 4 "../src/Views/TrashView.vala"
		self->priv->_is_modified = value;
#line 4 "../src/Views/TrashView.vala"
		g_object_notify_by_pspec ((GObject *) self, notejot_views_trash_view_properties[NOTEJOT_VIEWS_TRASH_VIEW_IS_MODIFIED_PROPERTY]);
#line 641 "TrashView.c"
	}
}

static void
notejot_views_trash_view_class_init (NotejotViewsTrashViewClass * klass,
                                     gpointer klass_data)
{
#line 2 "../src/Views/TrashView.vala"
	notejot_views_trash_view_parent_class = g_type_class_peek_parent (klass);
#line 2 "../src/Views/TrashView.vala"
	g_type_class_adjust_private_offset (klass, &NotejotViewsTrashView_private_offset);
#line 2 "../src/Views/TrashView.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_notejot_views_trash_view_get_property;
#line 2 "../src/Views/TrashView.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_notejot_views_trash_view_set_property;
#line 2 "../src/Views/TrashView.vala"
	G_OBJECT_CLASS (klass)->finalize = notejot_views_trash_view_finalize;
#line 2 "../src/Views/TrashView.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), NOTEJOT_VIEWS_TRASH_VIEW_IS_MODIFIED_PROPERTY, notejot_views_trash_view_properties[NOTEJOT_VIEWS_TRASH_VIEW_IS_MODIFIED_PROPERTY] = g_param_spec_boolean ("is-modified", "is-modified", "is-modified", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 661 "TrashView.c"
}

static void
notejot_views_trash_view_instance_init (NotejotViewsTrashView * self,
                                        gpointer klass)
{
#line 2 "../src/Views/TrashView.vala"
	self->priv = notejot_views_trash_view_get_instance_private (self);
#line 4 "../src/Views/TrashView.vala"
	self->priv->_is_modified = FALSE;
#line 672 "TrashView.c"
}

static void
notejot_views_trash_view_finalize (GObject * obj)
{
	NotejotViewsTrashView * self;
#line 2 "../src/Views/TrashView.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashView);
#line 3 "../src/Views/TrashView.vala"
	_g_object_unref0 (self->priv->win);
#line 2 "../src/Views/TrashView.vala"
	G_OBJECT_CLASS (notejot_views_trash_view_parent_class)->finalize (obj);
#line 685 "TrashView.c"
}

static GType
notejot_views_trash_view_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (NotejotViewsTrashViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) notejot_views_trash_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NotejotViewsTrashView), 0, (GInstanceInitFunc) notejot_views_trash_view_instance_init, NULL };
	GType notejot_views_trash_view_type_id;
	notejot_views_trash_view_type_id = g_type_register_static (gtk_list_box_get_type (), "NotejotViewsTrashView", &g_define_type_info, 0);
	NotejotViewsTrashView_private_offset = g_type_add_instance_private (notejot_views_trash_view_type_id, sizeof (NotejotViewsTrashViewPrivate));
	return notejot_views_trash_view_type_id;
}

GType
notejot_views_trash_view_get_type (void)
{
	static volatile gsize notejot_views_trash_view_type_id__volatile = 0;
	if (g_once_init_enter (&notejot_views_trash_view_type_id__volatile)) {
		GType notejot_views_trash_view_type_id;
		notejot_views_trash_view_type_id = notejot_views_trash_view_get_type_once ();
		g_once_init_leave (&notejot_views_trash_view_type_id__volatile, notejot_views_trash_view_type_id);
	}
	return notejot_views_trash_view_type_id__volatile;
}

static void
_vala_notejot_views_trash_view_get_property (GObject * object,
                                             guint property_id,
                                             GValue * value,
                                             GParamSpec * pspec)
{
	NotejotViewsTrashView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashView);
#line 2 "../src/Views/TrashView.vala"
	switch (property_id) {
#line 2 "../src/Views/TrashView.vala"
		case NOTEJOT_VIEWS_TRASH_VIEW_IS_MODIFIED_PROPERTY:
#line 2 "../src/Views/TrashView.vala"
		g_value_set_boolean (value, notejot_views_trash_view_get_is_modified (self));
#line 2 "../src/Views/TrashView.vala"
		break;
#line 726 "TrashView.c"
		default:
#line 2 "../src/Views/TrashView.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 2 "../src/Views/TrashView.vala"
		break;
#line 732 "TrashView.c"
	}
}

static void
_vala_notejot_views_trash_view_set_property (GObject * object,
                                             guint property_id,
                                             const GValue * value,
                                             GParamSpec * pspec)
{
	NotejotViewsTrashView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashView);
#line 2 "../src/Views/TrashView.vala"
	switch (property_id) {
#line 2 "../src/Views/TrashView.vala"
		case NOTEJOT_VIEWS_TRASH_VIEW_IS_MODIFIED_PROPERTY:
#line 2 "../src/Views/TrashView.vala"
		notejot_views_trash_view_set_is_modified (self, g_value_get_boolean (value));
#line 2 "../src/Views/TrashView.vala"
		break;
#line 752 "TrashView.c"
		default:
#line 2 "../src/Views/TrashView.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 2 "../src/Views/TrashView.vala"
		break;
#line 758 "TrashView.c"
	}
}

