/* dark.c generated by valac 0.50.3, the Vala compiler
 * generated from dark.vala, do not modify */

/*
* Copyright (C) 2017-2021 Lains
*
* This program is free software; you can redistribute it &&/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 3 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*/

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gobject/gvaluecollector.h>

#define NOTEJOT_STYLES_TYPE_DARK (notejot_styles_dark_get_type ())
#define NOTEJOT_STYLES_DARK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_STYLES_TYPE_DARK, NotejotStylesdark))
#define NOTEJOT_STYLES_DARK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_STYLES_TYPE_DARK, NotejotStylesdarkClass))
#define NOTEJOT_STYLES_IS_DARK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_STYLES_TYPE_DARK))
#define NOTEJOT_STYLES_IS_DARK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_STYLES_TYPE_DARK))
#define NOTEJOT_STYLES_DARK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_STYLES_TYPE_DARK, NotejotStylesdarkClass))

typedef struct _NotejotStylesdark NotejotStylesdark;
typedef struct _NotejotStylesdarkClass NotejotStylesdarkClass;
typedef struct _NotejotStylesdarkPrivate NotejotStylesdarkPrivate;
typedef struct _NotejotStylesParamSpecdark NotejotStylesParamSpecdark;

struct _NotejotStylesdark {
	GTypeInstance parent_instance;
	volatile int ref_count;
	NotejotStylesdarkPrivate * priv;
};

struct _NotejotStylesdarkClass {
	GTypeClass parent_class;
	void (*finalize) (NotejotStylesdark *self);
};

struct _NotejotStylesParamSpecdark {
	GParamSpec parent_instance;
};

static gpointer notejot_styles_dark_parent_class = NULL;

gpointer notejot_styles_dark_ref (gpointer instance);
void notejot_styles_dark_unref (gpointer instance);
GParamSpec* notejot_styles_param_spec_dark (const gchar* name,
                                            const gchar* nick,
                                            const gchar* blurb,
                                            GType object_type,
                                            GParamFlags flags);
void notejot_styles_value_set_dark (GValue* value,
                                    gpointer v_object);
void notejot_styles_value_take_dark (GValue* value,
                                     gpointer v_object);
gpointer notejot_styles_value_get_dark (const GValue* value);
GType notejot_styles_dark_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotStylesdark, notejot_styles_dark_unref)
#define NOTEJOT_STYLES_DARK_css "\n" \
"    html {\n" \
"      width: 100%;\n" \
"      margin: 0 auto;\n" \
"    }\n" \
"\n" \
"    body {\n" \
"      color: #FAFAFA;\n" \
"      background-color: #222;\n" \
"      font-family: \"Cantarell\", Arial, Helvetica, sans-serif;\n" \
"      font-weight: 400;\n" \
"      font-size: 1.1rem;\n" \
"      letter-spacing: 0.2;\n" \
"      line-height: 1.45rem;\n" \
"      text-align: left;\n" \
"      margin-left: 40px;\n" \
"      margin-right: 40px;\n" \
"      margin-top: 20px;\n" \
"      overflow-x: hidden;\n" \
"    }\n" \
"  "
NotejotStylesdark* notejot_styles_dark_new (void);
NotejotStylesdark* notejot_styles_dark_construct (GType object_type);
static void notejot_styles_dark_finalize (NotejotStylesdark * obj);
static GType notejot_styles_dark_get_type_once (void);

NotejotStylesdark*
notejot_styles_dark_construct (GType object_type)
{
	NotejotStylesdark* self = NULL;
#line 19 "../src/Styles/dark.vala"
	self = (NotejotStylesdark*) g_type_create_instance (object_type);
#line 19 "../src/Styles/dark.vala"
	return self;
#line 87 "dark.c"
}

NotejotStylesdark*
notejot_styles_dark_new (void)
{
#line 19 "../src/Styles/dark.vala"
	return notejot_styles_dark_construct (NOTEJOT_STYLES_TYPE_DARK);
#line 95 "dark.c"
}

static void
notejot_styles_value_dark_init (GValue* value)
{
#line 19 "../src/Styles/dark.vala"
	value->data[0].v_pointer = NULL;
#line 103 "dark.c"
}

static void
notejot_styles_value_dark_free_value (GValue* value)
{
#line 19 "../src/Styles/dark.vala"
	if (value->data[0].v_pointer) {
#line 19 "../src/Styles/dark.vala"
		notejot_styles_dark_unref (value->data[0].v_pointer);
#line 113 "dark.c"
	}
}

static void
notejot_styles_value_dark_copy_value (const GValue* src_value,
                                      GValue* dest_value)
{
#line 19 "../src/Styles/dark.vala"
	if (src_value->data[0].v_pointer) {
#line 19 "../src/Styles/dark.vala"
		dest_value->data[0].v_pointer = notejot_styles_dark_ref (src_value->data[0].v_pointer);
#line 125 "dark.c"
	} else {
#line 19 "../src/Styles/dark.vala"
		dest_value->data[0].v_pointer = NULL;
#line 129 "dark.c"
	}
}

static gpointer
notejot_styles_value_dark_peek_pointer (const GValue* value)
{
#line 19 "../src/Styles/dark.vala"
	return value->data[0].v_pointer;
#line 138 "dark.c"
}

static gchar*
notejot_styles_value_dark_collect_value (GValue* value,
                                         guint n_collect_values,
                                         GTypeCValue* collect_values,
                                         guint collect_flags)
{
#line 19 "../src/Styles/dark.vala"
	if (collect_values[0].v_pointer) {
#line 149 "dark.c"
		NotejotStylesdark * object;
		object = collect_values[0].v_pointer;
#line 19 "../src/Styles/dark.vala"
		if (object->parent_instance.g_class == NULL) {
#line 19 "../src/Styles/dark.vala"
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 156 "dark.c"
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
#line 19 "../src/Styles/dark.vala"
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
#line 160 "dark.c"
		}
#line 19 "../src/Styles/dark.vala"
		value->data[0].v_pointer = notejot_styles_dark_ref (object);
#line 164 "dark.c"
	} else {
#line 19 "../src/Styles/dark.vala"
		value->data[0].v_pointer = NULL;
#line 168 "dark.c"
	}
#line 19 "../src/Styles/dark.vala"
	return NULL;
#line 172 "dark.c"
}

static gchar*
notejot_styles_value_dark_lcopy_value (const GValue* value,
                                       guint n_collect_values,
                                       GTypeCValue* collect_values,
                                       guint collect_flags)
{
	NotejotStylesdark ** object_p;
	object_p = collect_values[0].v_pointer;
#line 19 "../src/Styles/dark.vala"
	if (!object_p) {
#line 19 "../src/Styles/dark.vala"
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
#line 187 "dark.c"
	}
#line 19 "../src/Styles/dark.vala"
	if (!value->data[0].v_pointer) {
#line 19 "../src/Styles/dark.vala"
		*object_p = NULL;
#line 193 "dark.c"
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
#line 19 "../src/Styles/dark.vala"
		*object_p = value->data[0].v_pointer;
#line 197 "dark.c"
	} else {
#line 19 "../src/Styles/dark.vala"
		*object_p = notejot_styles_dark_ref (value->data[0].v_pointer);
#line 201 "dark.c"
	}
#line 19 "../src/Styles/dark.vala"
	return NULL;
#line 205 "dark.c"
}

GParamSpec*
notejot_styles_param_spec_dark (const gchar* name,
                                const gchar* nick,
                                const gchar* blurb,
                                GType object_type,
                                GParamFlags flags)
{
	NotejotStylesParamSpecdark* spec;
#line 19 "../src/Styles/dark.vala"
	g_return_val_if_fail (g_type_is_a (object_type, NOTEJOT_STYLES_TYPE_DARK), NULL);
#line 19 "../src/Styles/dark.vala"
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
#line 19 "../src/Styles/dark.vala"
	G_PARAM_SPEC (spec)->value_type = object_type;
#line 19 "../src/Styles/dark.vala"
	return G_PARAM_SPEC (spec);
#line 224 "dark.c"
}

gpointer
notejot_styles_value_get_dark (const GValue* value)
{
#line 19 "../src/Styles/dark.vala"
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, NOTEJOT_STYLES_TYPE_DARK), NULL);
#line 19 "../src/Styles/dark.vala"
	return value->data[0].v_pointer;
#line 234 "dark.c"
}

void
notejot_styles_value_set_dark (GValue* value,
                               gpointer v_object)
{
	NotejotStylesdark * old;
#line 19 "../src/Styles/dark.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, NOTEJOT_STYLES_TYPE_DARK));
#line 19 "../src/Styles/dark.vala"
	old = value->data[0].v_pointer;
#line 19 "../src/Styles/dark.vala"
	if (v_object) {
#line 19 "../src/Styles/dark.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, NOTEJOT_STYLES_TYPE_DARK));
#line 19 "../src/Styles/dark.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 19 "../src/Styles/dark.vala"
		value->data[0].v_pointer = v_object;
#line 19 "../src/Styles/dark.vala"
		notejot_styles_dark_ref (value->data[0].v_pointer);
#line 256 "dark.c"
	} else {
#line 19 "../src/Styles/dark.vala"
		value->data[0].v_pointer = NULL;
#line 260 "dark.c"
	}
#line 19 "../src/Styles/dark.vala"
	if (old) {
#line 19 "../src/Styles/dark.vala"
		notejot_styles_dark_unref (old);
#line 266 "dark.c"
	}
}

void
notejot_styles_value_take_dark (GValue* value,
                                gpointer v_object)
{
	NotejotStylesdark * old;
#line 19 "../src/Styles/dark.vala"
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, NOTEJOT_STYLES_TYPE_DARK));
#line 19 "../src/Styles/dark.vala"
	old = value->data[0].v_pointer;
#line 19 "../src/Styles/dark.vala"
	if (v_object) {
#line 19 "../src/Styles/dark.vala"
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, NOTEJOT_STYLES_TYPE_DARK));
#line 19 "../src/Styles/dark.vala"
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
#line 19 "../src/Styles/dark.vala"
		value->data[0].v_pointer = v_object;
#line 287 "dark.c"
	} else {
#line 19 "../src/Styles/dark.vala"
		value->data[0].v_pointer = NULL;
#line 291 "dark.c"
	}
#line 19 "../src/Styles/dark.vala"
	if (old) {
#line 19 "../src/Styles/dark.vala"
		notejot_styles_dark_unref (old);
#line 297 "dark.c"
	}
}

static void
notejot_styles_dark_class_init (NotejotStylesdarkClass * klass,
                                gpointer klass_data)
{
#line 19 "../src/Styles/dark.vala"
	notejot_styles_dark_parent_class = g_type_class_peek_parent (klass);
#line 19 "../src/Styles/dark.vala"
	((NotejotStylesdarkClass *) klass)->finalize = notejot_styles_dark_finalize;
#line 309 "dark.c"
}

static void
notejot_styles_dark_instance_init (NotejotStylesdark * self,
                                   gpointer klass)
{
#line 19 "../src/Styles/dark.vala"
	self->ref_count = 1;
#line 318 "dark.c"
}

static void
notejot_styles_dark_finalize (NotejotStylesdark * obj)
{
	NotejotStylesdark * self;
#line 19 "../src/Styles/dark.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, NOTEJOT_STYLES_TYPE_DARK, NotejotStylesdark);
#line 19 "../src/Styles/dark.vala"
	g_signal_handlers_destroy (self);
#line 329 "dark.c"
}

static GType
notejot_styles_dark_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { notejot_styles_value_dark_init, notejot_styles_value_dark_free_value, notejot_styles_value_dark_copy_value, notejot_styles_value_dark_peek_pointer, "p", notejot_styles_value_dark_collect_value, "p", notejot_styles_value_dark_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (NotejotStylesdarkClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) notejot_styles_dark_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NotejotStylesdark), 0, (GInstanceInitFunc) notejot_styles_dark_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType notejot_styles_dark_type_id;
	notejot_styles_dark_type_id = g_type_register_fundamental (g_type_fundamental_next (), "NotejotStylesdark", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return notejot_styles_dark_type_id;
}

GType
notejot_styles_dark_get_type (void)
{
	static volatile gsize notejot_styles_dark_type_id__volatile = 0;
	if (g_once_init_enter (&notejot_styles_dark_type_id__volatile)) {
		GType notejot_styles_dark_type_id;
		notejot_styles_dark_type_id = notejot_styles_dark_get_type_once ();
		g_once_init_leave (&notejot_styles_dark_type_id__volatile, notejot_styles_dark_type_id);
	}
	return notejot_styles_dark_type_id__volatile;
}

gpointer
notejot_styles_dark_ref (gpointer instance)
{
	NotejotStylesdark * self;
	self = instance;
#line 19 "../src/Styles/dark.vala"
	g_atomic_int_inc (&self->ref_count);
#line 19 "../src/Styles/dark.vala"
	return instance;
#line 364 "dark.c"
}

void
notejot_styles_dark_unref (gpointer instance)
{
	NotejotStylesdark * self;
	self = instance;
#line 19 "../src/Styles/dark.vala"
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
#line 19 "../src/Styles/dark.vala"
		NOTEJOT_STYLES_DARK_GET_CLASS (self)->finalize (self);
#line 19 "../src/Styles/dark.vala"
		g_type_free_instance ((GTypeInstance *) self);
#line 378 "dark.c"
	}
}

