/* MainWindow.c generated by valac 0.50.3, the Vala compiler
 * generated from MainWindow.vala, do not modify */

/*
* Copyright (c) 2017-2021 Lains
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 3 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*/

#include <handy.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib.h>
#include <gio/gio.h>
#include <gdk/gdk.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include "config.h"
#include <glib/gi18n-lib.h>

#define NOTEJOT_TYPE_MAIN_WINDOW (notejot_main_window_get_type ())
#define NOTEJOT_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindow))
#define NOTEJOT_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindowClass))
#define NOTEJOT_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_TYPE_MAIN_WINDOW))
#define NOTEJOT_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_TYPE_MAIN_WINDOW))
#define NOTEJOT_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindowClass))

typedef struct _NotejotMainWindow NotejotMainWindow;
typedef struct _NotejotMainWindowClass NotejotMainWindowClass;
typedef struct _NotejotMainWindowPrivate NotejotMainWindowPrivate;

#define NOTEJOT_WIDGETS_TYPE_DIALOG (notejot_widgets_dialog_get_type ())
#define NOTEJOT_WIDGETS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialog))
#define NOTEJOT_WIDGETS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialogClass))
#define NOTEJOT_WIDGETS_IS_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG))
#define NOTEJOT_WIDGETS_IS_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_DIALOG))
#define NOTEJOT_WIDGETS_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_DIALOG, NotejotWidgetsDialogClass))

typedef struct _NotejotWidgetsDialog NotejotWidgetsDialog;
typedef struct _NotejotWidgetsDialogClass NotejotWidgetsDialogClass;

#define NOTEJOT_WIDGETS_TYPE_SETTING_MENU (notejot_widgets_setting_menu_get_type ())
#define NOTEJOT_WIDGETS_SETTING_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenu))
#define NOTEJOT_WIDGETS_SETTING_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenuClass))
#define NOTEJOT_WIDGETS_IS_SETTING_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU))
#define NOTEJOT_WIDGETS_IS_SETTING_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_SETTING_MENU))
#define NOTEJOT_WIDGETS_SETTING_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_SETTING_MENU, NotejotWidgetsSettingMenuClass))

typedef struct _NotejotWidgetsSettingMenu NotejotWidgetsSettingMenu;
typedef struct _NotejotWidgetsSettingMenuClass NotejotWidgetsSettingMenuClass;

#define NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON (notejot_widgets_header_bar_button_get_type ())
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButton))
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButtonClass))
#define NOTEJOT_WIDGETS_IS_HEADER_BAR_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON))
#define NOTEJOT_WIDGETS_IS_HEADER_BAR_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON))
#define NOTEJOT_WIDGETS_HEADER_BAR_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_HEADER_BAR_BUTTON, NotejotWidgetsHeaderBarButtonClass))

typedef struct _NotejotWidgetsHeaderBarButton NotejotWidgetsHeaderBarButton;
typedef struct _NotejotWidgetsHeaderBarButtonClass NotejotWidgetsHeaderBarButtonClass;

#define NOTEJOT_VIEWS_TYPE_LIST_VIEW (notejot_views_list_view_get_type ())
#define NOTEJOT_VIEWS_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListView))
#define NOTEJOT_VIEWS_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListViewClass))
#define NOTEJOT_VIEWS_IS_LIST_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW))
#define NOTEJOT_VIEWS_IS_LIST_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_VIEWS_TYPE_LIST_VIEW))
#define NOTEJOT_VIEWS_LIST_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_VIEWS_TYPE_LIST_VIEW, NotejotViewsListViewClass))

typedef struct _NotejotViewsListView NotejotViewsListView;
typedef struct _NotejotViewsListViewClass NotejotViewsListViewClass;

#define NOTEJOT_VIEWS_TYPE_TRASH_VIEW (notejot_views_trash_view_get_type ())
#define NOTEJOT_VIEWS_TRASH_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashView))
#define NOTEJOT_VIEWS_TRASH_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashViewClass))
#define NOTEJOT_VIEWS_IS_TRASH_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW))
#define NOTEJOT_VIEWS_IS_TRASH_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_VIEWS_TYPE_TRASH_VIEW))
#define NOTEJOT_VIEWS_TRASH_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_VIEWS_TYPE_TRASH_VIEW, NotejotViewsTrashViewClass))

typedef struct _NotejotViewsTrashView NotejotViewsTrashView;
typedef struct _NotejotViewsTrashViewClass NotejotViewsTrashViewClass;

#define NOTEJOT_TYPE_TASK_MANAGER (notejot_task_manager_get_type ())
#define NOTEJOT_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManager))
#define NOTEJOT_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManagerClass))
#define NOTEJOT_IS_TASK_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_TYPE_TASK_MANAGER))
#define NOTEJOT_IS_TASK_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_TYPE_TASK_MANAGER))
#define NOTEJOT_TASK_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_TYPE_TASK_MANAGER, NotejotTaskManagerClass))

typedef struct _NotejotTaskManager NotejotTaskManager;
typedef struct _NotejotTaskManagerClass NotejotTaskManagerClass;
enum  {
	NOTEJOT_MAIN_WINDOW_0_PROPERTY,
	NOTEJOT_MAIN_WINDOW_ACTIONS_PROPERTY,
	NOTEJOT_MAIN_WINDOW_APP_PROPERTY,
	NOTEJOT_MAIN_WINDOW_NUM_PROPERTIES
};
static GParamSpec* notejot_main_window_properties[NOTEJOT_MAIN_WINDOW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _notejot_task_manager_unref0(var) ((var == NULL) ? NULL : (var = (notejot_task_manager_unref (var), NULL)))

#define NOTEJOT_WIDGETS_TYPE_NOTE (notejot_widgets_note_get_type ())
#define NOTEJOT_WIDGETS_NOTE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNote))
#define NOTEJOT_WIDGETS_NOTE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNoteClass))
#define NOTEJOT_WIDGETS_IS_NOTE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), NOTEJOT_WIDGETS_TYPE_NOTE))
#define NOTEJOT_WIDGETS_IS_NOTE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), NOTEJOT_WIDGETS_TYPE_NOTE))
#define NOTEJOT_WIDGETS_NOTE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), NOTEJOT_WIDGETS_TYPE_NOTE, NotejotWidgetsNoteClass))

typedef struct _NotejotWidgetsNote NotejotWidgetsNote;
typedef struct _NotejotWidgetsNoteClass NotejotWidgetsNoteClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
typedef struct _NotejotMainWindowOnCreateNewData NotejotMainWindowOnCreateNewData;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
typedef void (*NotejotMainWindowHookFunc) (gpointer user_data);
typedef struct _NotejotWidgetsHeaderBarButtonPrivate NotejotWidgetsHeaderBarButtonPrivate;

struct _NotejotMainWindow {
	HdyApplicationWindow parent_instance;
	NotejotMainWindowPrivate * priv;
	GtkButton* new_button;
	GtkButton* back_button;
	GtkButton* welcome_new_button;
	GtkMenuButton* menu_button;
	GtkBox* grid;
	GtkBox* sgrid;
	GtkBox* welcome_view;
	GtkBox* empty_state;
	HdyLeaflet* leaflet;
	GtkStack* main_stack;
	GtkStack* sidebar_stack;
	GtkStack* titlebar_stack;
	HdyHeaderBar* titlebar;
	HdyHeaderBar* stitlebar;
	HdyHeaderBar* welcome_titlebar;
	HdyHeaderGroup* titlegroup;
	GtkScrolledWindow* trash_scroller;
	GtkScrolledWindow* list_scroller;
	NotejotWidgetsDialog* dialog;
	NotejotWidgetsSettingMenu* settingmenu;
	NotejotWidgetsHeaderBarButton* sidebar_title_button;
	NotejotViewsListView* listview;
	NotejotViewsTrashView* trashview;
	NotejotTaskManager* tm;
	gboolean pinned;
};

struct _NotejotMainWindowClass {
	HdyApplicationWindowClass parent_class;
};

struct _NotejotMainWindowPrivate {
	GSimpleActionGroup* _actions;
	GtkApplication* _app;
};

struct _NotejotMainWindowOnCreateNewData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	NotejotMainWindow* self;
	GDateTime* dt;
	GDateTime* _tmp0_;
	NotejotWidgetsNote* sidebaritem;
	GDateTime* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	NotejotWidgetsNote* _tmp6_;
	NotejotWidgetsNote* _tmp7_;
	NotejotViewsListView* _tmp8_;
	NotejotWidgetsNote* _tmp9_;
	NotejotViewsListView* _tmp10_;
	NotejotViewsListView* _tmp11_;
	NotejotWidgetsNote* _tmp12_;
	NotejotViewsListView* _tmp13_;
	GtkListBoxRow* _tmp14_;
	GtkStack* _tmp15_;
	GtkBox* _tmp16_;
	GtkStack* _tmp17_;
	HdyHeaderBar* _tmp18_;
	GtkBox* _tmp19_;
	GtkBox* _tmp20_;
	GtkBox* _tmp21_;
	NotejotWidgetsSettingMenu* _tmp22_;
};

struct _NotejotWidgetsHeaderBarButton {
	GtkBin parent_instance;
	NotejotWidgetsHeaderBarButtonPrivate * priv;
	GtkMenuButton* menu;
};

struct _NotejotWidgetsHeaderBarButtonClass {
	GtkBinClass parent_class;
};

static gint NotejotMainWindow_private_offset;
static gpointer notejot_main_window_parent_class = NULL;
extern GeeMultiMap* notejot_main_window_action_accelerators;
GeeMultiMap* notejot_main_window_action_accelerators = NULL;
extern GSettings* notejot_application_gsettings;

GType notejot_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotMainWindow, g_object_unref)
GType notejot_widgets_dialog_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsDialog, g_object_unref)
GType notejot_widgets_setting_menu_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsSettingMenu, g_object_unref)
GType notejot_widgets_header_bar_button_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsHeaderBarButton, g_object_unref)
GType notejot_views_list_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotViewsListView, g_object_unref)
GType notejot_views_trash_view_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotViewsTrashView, g_object_unref)
gpointer notejot_task_manager_ref (gpointer instance);
void notejot_task_manager_unref (gpointer instance);
GParamSpec* notejot_param_spec_task_manager (const gchar* name,
                                             const gchar* nick,
                                             const gchar* blurb,
                                             GType object_type,
                                             GParamFlags flags);
void notejot_value_set_task_manager (GValue* value,
                                     gpointer v_object);
void notejot_value_take_task_manager (GValue* value,
                                      gpointer v_object);
gpointer notejot_value_get_task_manager (const GValue* value);
GType notejot_task_manager_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotTaskManager, notejot_task_manager_unref)
#define NOTEJOT_MAIN_WINDOW_ACTION_PREFIX "win."
#define NOTEJOT_MAIN_WINDOW_ACTION_ABOUT "action_about"
#define NOTEJOT_MAIN_WINDOW_ACTION_ALL_NOTES "action_all_notes"
#define NOTEJOT_MAIN_WINDOW_ACTION_TRASH "action_trash"
#define NOTEJOT_MAIN_WINDOW_ACTION_KEYS "action_keys"
#define NOTEJOT_MAIN_WINDOW_ACTION_TRASH_NOTES "action_trash_notes"
#define NOTEJOT_MAIN_WINDOW_ACTION_DARK_MODE "action_dark_mode"
void notejot_main_window_action_about (NotejotMainWindow* self);
static void _notejot_main_window_action_about_gsimple_action_activate_callback (GSimpleAction* action,
                                                                         GVariant* parameter,
                                                                         gpointer self);
void notejot_main_window_action_all_notes (NotejotMainWindow* self);
static void _notejot_main_window_action_all_notes_gsimple_action_activate_callback (GSimpleAction* action,
                                                                             GVariant* parameter,
                                                                             gpointer self);
void notejot_main_window_action_trash (NotejotMainWindow* self);
static void _notejot_main_window_action_trash_gsimple_action_activate_callback (GSimpleAction* action,
                                                                         GVariant* parameter,
                                                                         gpointer self);
void notejot_main_window_action_keys (NotejotMainWindow* self);
static void _notejot_main_window_action_keys_gsimple_action_activate_callback (GSimpleAction* action,
                                                                        GVariant* parameter,
                                                                        gpointer self);
void notejot_main_window_action_trash_notes (NotejotMainWindow* self);
static void _notejot_main_window_action_trash_notes_gsimple_action_activate_callback (GSimpleAction* action,
                                                                               GVariant* parameter,
                                                                               gpointer self);
void notejot_main_window_action_dark_mode (NotejotMainWindow* self,
                                           GSimpleAction* action,
                                           GVariant* parameter);
static void _notejot_main_window_action_dark_mode_gsimple_action_activate_callback (GSimpleAction* action,
                                                                             GVariant* parameter,
                                                                             gpointer self);
NotejotMainWindow* notejot_main_window_new (GtkApplication* application);
NotejotMainWindow* notejot_main_window_construct (GType object_type,
                                                  GtkApplication* application);
static gboolean __lambda48_ (NotejotMainWindow* self,
                      GdkEventKey* e);
gboolean notejot_main_window_match_keycode (NotejotMainWindow* self,
                                            guint keyval,
                                            guint code);
void notejot_main_window_on_create_new (NotejotMainWindow* self,
                                        GAsyncReadyCallback _callback_,
                                        gpointer _user_data_);
void notejot_main_window_on_create_new_finish (NotejotMainWindow* self,
                                               GAsyncResult* _res_);
static gboolean ___lambda48__gtk_widget_key_press_event (GtkWidget* _sender,
                                                  GdkEventKey* event,
                                                  gpointer self);
static void notejot_main_window_update (NotejotMainWindow* self);
static gboolean notejot_main_window_real_delete_event (GtkWidget* base,
                                                GdkEventAny* event);
static void notejot_main_window_on_create_new_data_free (gpointer _data);
static gboolean notejot_main_window_on_create_new_co (NotejotMainWindowOnCreateNewData* _data_);
GType notejot_widgets_note_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (NotejotWidgetsNote, g_object_unref)
NotejotWidgetsNote* notejot_widgets_note_new (NotejotMainWindow* win,
                                              const gchar* title,
                                              const gchar* subtitle,
                                              const gchar* text,
                                              const gchar* color);
NotejotWidgetsNote* notejot_widgets_note_construct (GType object_type,
                                                    NotejotMainWindow* win,
                                                    const gchar* title,
                                                    const gchar* subtitle,
                                                    const gchar* text,
                                                    const gchar* color);
void notejot_views_list_view_set_is_modified (NotejotViewsListView* self,
                                              gboolean value);
void notejot_widgets_header_bar_button_set_title (NotejotWidgetsHeaderBarButton* self,
                                                  const gchar* value);
NotejotWidgetsDialog* notejot_widgets_dialog_new (NotejotMainWindow* win,
                                                  const gchar* ltitle,
                                                  const gchar* subtitle,
                                                  const gchar* cancel_label,
                                                  const gchar* ok_label);
NotejotWidgetsDialog* notejot_widgets_dialog_construct (GType object_type,
                                                        NotejotMainWindow* win,
                                                        const gchar* ltitle,
                                                        const gchar* subtitle,
                                                        const gchar* cancel_label,
                                                        const gchar* ok_label);
GSimpleActionGroup* notejot_main_window_get_actions (NotejotMainWindow* self);
static void notejot_main_window_set_actions (NotejotMainWindow* self,
                                      GSimpleActionGroup* value);
GtkApplication* notejot_main_window_get_app (NotejotMainWindow* self);
static void notejot_main_window_set_app (NotejotMainWindow* self,
                                  GtkApplication* value);
static GObject * notejot_main_window_constructor (GType type,
                                           guint n_construct_properties,
                                           GObjectConstructParam * construct_properties);
NotejotTaskManager* notejot_task_manager_new (NotejotMainWindow* win);
NotejotTaskManager* notejot_task_manager_construct (GType object_type,
                                                    NotejotMainWindow* win);
static void _vala_array_add1 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
NotejotWidgetsSettingMenu* notejot_widgets_setting_menu_new (NotejotMainWindow* win);
NotejotWidgetsSettingMenu* notejot_widgets_setting_menu_construct (GType object_type,
                                                                   NotejotMainWindow* win);
static void _notejot_main_window___lambda49_ (NotejotMainWindow* self);
static void __notejot_main_window___lambda49__gtk_button_clicked (GtkButton* _sender,
                                                           gpointer self);
static void _notejot_main_window___lambda50_ (NotejotMainWindow* self);
static void __notejot_main_window___lambda50__gtk_button_clicked (GtkButton* _sender,
                                                           gpointer self);
NotejotViewsListView* notejot_views_list_view_new (NotejotMainWindow* win);
NotejotViewsListView* notejot_views_list_view_construct (GType object_type,
                                                         NotejotMainWindow* win);
NotejotViewsTrashView* notejot_views_trash_view_new (NotejotMainWindow* win);
NotejotViewsTrashView* notejot_views_trash_view_construct (GType object_type,
                                                           NotejotMainWindow* win);
NotejotWidgetsHeaderBarButton* notejot_widgets_header_bar_button_new (void);
NotejotWidgetsHeaderBarButton* notejot_widgets_header_bar_button_construct (GType object_type);
static void _notejot_main_window___lambda51_ (NotejotMainWindow* self);
static void __notejot_main_window___lambda51__gtk_button_clicked (GtkButton* _sender,
                                                           gpointer self);
static void _notejot_main_window___lambda52_ (NotejotMainWindow* self);
static void __notejot_main_window___lambda52__g_object_notify (GObject* _sender,
                                                        GParamSpec* pspec,
                                                        gpointer self);
void notejot_task_manager_load_from_file (NotejotTaskManager* self,
                                          GAsyncReadyCallback _callback_,
                                          gpointer _user_data_);
void notejot_task_manager_load_from_file_finish (NotejotTaskManager* self,
                                                 GAsyncResult* _res_);
gboolean notejot_views_list_view_get_is_modified (NotejotViewsListView* self);
static void notejot_main_window_finalize (GObject * obj);
static GType notejot_main_window_get_type_once (void);
static void _vala_notejot_main_window_get_property (GObject * object,
                                             guint property_id,
                                             GValue * value,
                                             GParamSpec * pspec);
static void _vala_notejot_main_window_set_property (GObject * object,
                                             guint property_id,
                                             const GValue * value,
                                             GParamSpec * pspec);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);

static const GActionEntry NOTEJOT_MAIN_WINDOW_ACTION_ENTRIES[6] = {{NOTEJOT_MAIN_WINDOW_ACTION_ABOUT, _notejot_main_window_action_about_gsimple_action_activate_callback}, {NOTEJOT_MAIN_WINDOW_ACTION_ALL_NOTES, _notejot_main_window_action_all_notes_gsimple_action_activate_callback}, {NOTEJOT_MAIN_WINDOW_ACTION_TRASH, _notejot_main_window_action_trash_gsimple_action_activate_callback}, {NOTEJOT_MAIN_WINDOW_ACTION_KEYS, _notejot_main_window_action_keys_gsimple_action_activate_callback}, {NOTEJOT_MAIN_WINDOW_ACTION_TRASH_NOTES, _notejot_main_window_action_trash_notes_gsimple_action_activate_callback}, {NOTEJOT_MAIN_WINDOW_ACTION_DARK_MODE, _notejot_main_window_action_dark_mode_gsimple_action_activate_callback, NULL, "false", NULL}};

static inline gpointer
notejot_main_window_get_instance_private (NotejotMainWindow* self)
{
	return G_STRUCT_MEMBER_P (self, NotejotMainWindow_private_offset);
}

static void
_notejot_main_window_action_about_gsimple_action_activate_callback (GSimpleAction* action,
                                                                    GVariant* parameter,
                                                                    gpointer self)
{
#line 82 "../src/MainWindow.vala"
	notejot_main_window_action_about ((NotejotMainWindow*) self);
#line 407 "MainWindow.c"
}

static void
_notejot_main_window_action_all_notes_gsimple_action_activate_callback (GSimpleAction* action,
                                                                        GVariant* parameter,
                                                                        gpointer self)
{
#line 82 "../src/MainWindow.vala"
	notejot_main_window_action_all_notes ((NotejotMainWindow*) self);
#line 417 "MainWindow.c"
}

static void
_notejot_main_window_action_trash_gsimple_action_activate_callback (GSimpleAction* action,
                                                                    GVariant* parameter,
                                                                    gpointer self)
{
#line 82 "../src/MainWindow.vala"
	notejot_main_window_action_trash ((NotejotMainWindow*) self);
#line 427 "MainWindow.c"
}

static void
_notejot_main_window_action_keys_gsimple_action_activate_callback (GSimpleAction* action,
                                                                   GVariant* parameter,
                                                                   gpointer self)
{
#line 82 "../src/MainWindow.vala"
	notejot_main_window_action_keys ((NotejotMainWindow*) self);
#line 437 "MainWindow.c"
}

static void
_notejot_main_window_action_trash_notes_gsimple_action_activate_callback (GSimpleAction* action,
                                                                          GVariant* parameter,
                                                                          gpointer self)
{
#line 82 "../src/MainWindow.vala"
	notejot_main_window_action_trash_notes ((NotejotMainWindow*) self);
#line 447 "MainWindow.c"
}

static void
_notejot_main_window_action_dark_mode_gsimple_action_activate_callback (GSimpleAction* action,
                                                                        GVariant* parameter,
                                                                        gpointer self)
{
#line 82 "../src/MainWindow.vala"
	notejot_main_window_action_dark_mode ((NotejotMainWindow*) self, action, parameter);
#line 457 "MainWindow.c"
}

static gboolean
__lambda48_ (NotejotMainWindow* self,
             GdkEventKey* e)
{
	guint keycode = 0U;
	GdkModifierType _tmp0_;
	GdkModifierType _tmp1_;
	gboolean result = FALSE;
#line 100 "../src/MainWindow.vala"
	g_return_val_if_fail (e != NULL, FALSE);
#line 101 "../src/MainWindow.vala"
	keycode = (guint) e->hardware_keycode;
#line 102 "../src/MainWindow.vala"
	_tmp0_ = e->state;
#line 102 "../src/MainWindow.vala"
	if ((_tmp0_ & GDK_CONTROL_MASK) != 0) {
#line 103 "../src/MainWindow.vala"
		if (notejot_main_window_match_keycode (self, GDK_KEY_q, keycode)) {
#line 104 "../src/MainWindow.vala"
			gtk_widget_destroy ((GtkWidget*) self);
#line 480 "MainWindow.c"
		}
	}
#line 107 "../src/MainWindow.vala"
	_tmp1_ = e->state;
#line 107 "../src/MainWindow.vala"
	if ((_tmp1_ & GDK_CONTROL_MASK) != 0) {
#line 108 "../src/MainWindow.vala"
		if (notejot_main_window_match_keycode (self, GDK_KEY_n, keycode)) {
#line 109 "../src/MainWindow.vala"
			notejot_main_window_on_create_new (self, NULL, NULL);
#line 491 "MainWindow.c"
		}
	}
#line 112 "../src/MainWindow.vala"
	result = FALSE;
#line 112 "../src/MainWindow.vala"
	return result;
#line 498 "MainWindow.c"
}

static gboolean
___lambda48__gtk_widget_key_press_event (GtkWidget* _sender,
                                         GdkEventKey* event,
                                         gpointer self)
{
	gboolean result;
	result = __lambda48_ ((NotejotMainWindow*) self, event);
#line 100 "../src/MainWindow.vala"
	return result;
#line 510 "MainWindow.c"
}

NotejotMainWindow*
notejot_main_window_construct (GType object_type,
                               GtkApplication* application)
{
	NotejotMainWindow * self = NULL;
#line 92 "../src/MainWindow.vala"
	g_return_val_if_fail (application != NULL, NULL);
#line 93 "../src/MainWindow.vala"
	self = (NotejotMainWindow*) g_object_new (object_type, "application", application, "app", application, "icon-name", APP_ID, "title", _ ("Notejot"), NULL);
#line 100 "../src/MainWindow.vala"
	g_signal_connect_object ((GtkWidget*) self, "key-press-event", (GCallback) ___lambda48__gtk_widget_key_press_event, self, 0);
#line 92 "../src/MainWindow.vala"
	return self;
#line 526 "MainWindow.c"
}

NotejotMainWindow*
notejot_main_window_new (GtkApplication* application)
{
#line 92 "../src/MainWindow.vala"
	return notejot_main_window_construct (NOTEJOT_TYPE_MAIN_WINDOW, application);
#line 534 "MainWindow.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 240 "../src/MainWindow.vala"
	return self ? g_object_ref (self) : NULL;
#line 542 "MainWindow.c"
}

gboolean
notejot_main_window_match_keycode (NotejotMainWindow* self,
                                   guint keyval,
                                   guint code)
{
	GdkKeymapKey* keys = NULL;
	gint keys_length1 = 0;
	gint _keys_size_ = 0;
	GdkKeymap* keymap = NULL;
	GdkDisplay* _tmp0_;
	GdkKeymap* _tmp1_;
	GdkKeymap* _tmp2_;
	GdkKeymap* _tmp3_;
	GdkKeymapKey* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gboolean _tmp6_;
	gboolean result = FALSE;
#line 235 "../src/MainWindow.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 240 "../src/MainWindow.vala"
	_tmp0_ = gdk_display_get_default ();
#line 240 "../src/MainWindow.vala"
	_tmp1_ = gdk_keymap_get_for_display (_tmp0_);
#line 240 "../src/MainWindow.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 240 "../src/MainWindow.vala"
	keymap = _tmp2_;
#line 241 "../src/MainWindow.vala"
	_tmp3_ = keymap;
#line 241 "../src/MainWindow.vala"
	_tmp6_ = gdk_keymap_get_entries_for_keyval (_tmp3_, keyval, &_tmp4_, &_tmp5_);
#line 241 "../src/MainWindow.vala"
	keys = (g_free (keys), NULL);
#line 241 "../src/MainWindow.vala"
	keys = _tmp4_;
#line 241 "../src/MainWindow.vala"
	keys_length1 = _tmp5_;
#line 241 "../src/MainWindow.vala"
	_keys_size_ = keys_length1;
#line 241 "../src/MainWindow.vala"
	if (_tmp6_) {
#line 586 "MainWindow.c"
		GdkKeymapKey* _tmp7_;
		gint _tmp7__length1;
#line 242 "../src/MainWindow.vala"
		_tmp7_ = keys;
#line 242 "../src/MainWindow.vala"
		_tmp7__length1 = keys_length1;
#line 593 "MainWindow.c"
		{
			GdkKeymapKey* key_collection = NULL;
			gint key_collection_length1 = 0;
			gint _key_collection_size_ = 0;
			gint key_it = 0;
#line 242 "../src/MainWindow.vala"
			key_collection = _tmp7_;
#line 242 "../src/MainWindow.vala"
			key_collection_length1 = _tmp7__length1;
#line 242 "../src/MainWindow.vala"
			for (key_it = 0; key_it < key_collection_length1; key_it = key_it + 1) {
#line 605 "MainWindow.c"
				GdkKeymapKey key = {0};
#line 242 "../src/MainWindow.vala"
				key = key_collection[key_it];
#line 609 "MainWindow.c"
				{
					GdkKeymapKey _tmp8_;
#line 243 "../src/MainWindow.vala"
					_tmp8_ = key;
#line 243 "../src/MainWindow.vala"
					if (code == _tmp8_.keycode) {
#line 244 "../src/MainWindow.vala"
						result = TRUE;
#line 244 "../src/MainWindow.vala"
						_g_object_unref0 (keymap);
#line 244 "../src/MainWindow.vala"
						keys = (g_free (keys), NULL);
#line 244 "../src/MainWindow.vala"
						return result;
#line 624 "MainWindow.c"
					}
				}
			}
		}
	}
#line 247 "../src/MainWindow.vala"
	result = FALSE;
#line 247 "../src/MainWindow.vala"
	_g_object_unref0 (keymap);
#line 247 "../src/MainWindow.vala"
	keys = (g_free (keys), NULL);
#line 247 "../src/MainWindow.vala"
	return result;
#line 638 "MainWindow.c"
}

static void
notejot_main_window_update (NotejotMainWindow* self)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	HdyLeaflet* _tmp2_;
#line 250 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 251 "../src/MainWindow.vala"
	_tmp2_ = self->leaflet;
#line 251 "../src/MainWindow.vala"
	if (_tmp2_ != NULL) {
#line 653 "MainWindow.c"
		HdyHeaderGroup* _tmp3_;
#line 251 "../src/MainWindow.vala"
		_tmp3_ = self->titlegroup;
#line 251 "../src/MainWindow.vala"
		_tmp1_ = _tmp3_ != NULL;
#line 659 "MainWindow.c"
	} else {
#line 251 "../src/MainWindow.vala"
		_tmp1_ = FALSE;
#line 663 "MainWindow.c"
	}
#line 251 "../src/MainWindow.vala"
	if (_tmp1_) {
#line 667 "MainWindow.c"
		HdyLeaflet* _tmp4_;
#line 251 "../src/MainWindow.vala"
		_tmp4_ = self->leaflet;
#line 251 "../src/MainWindow.vala"
		_tmp0_ = hdy_leaflet_get_folded (_tmp4_);
#line 673 "MainWindow.c"
	} else {
#line 251 "../src/MainWindow.vala"
		_tmp0_ = FALSE;
#line 677 "MainWindow.c"
	}
#line 251 "../src/MainWindow.vala"
	if (_tmp0_) {
#line 681 "MainWindow.c"
		GtkButton* _tmp5_;
		GtkButton* _tmp6_;
		HdyHeaderGroup* _tmp7_;
#line 252 "../src/MainWindow.vala"
		_tmp5_ = self->back_button;
#line 252 "../src/MainWindow.vala"
		gtk_widget_set_visible ((GtkWidget*) _tmp5_, TRUE);
#line 253 "../src/MainWindow.vala"
		_tmp6_ = self->back_button;
#line 253 "../src/MainWindow.vala"
		gtk_widget_set_no_show_all ((GtkWidget*) _tmp6_, FALSE);
#line 254 "../src/MainWindow.vala"
		_tmp7_ = self->titlegroup;
#line 254 "../src/MainWindow.vala"
		hdy_header_group_set_decorate_all (_tmp7_, TRUE);
#line 697 "MainWindow.c"
	} else {
		GtkButton* _tmp8_;
		GtkButton* _tmp9_;
		HdyHeaderGroup* _tmp10_;
#line 256 "../src/MainWindow.vala"
		_tmp8_ = self->back_button;
#line 256 "../src/MainWindow.vala"
		gtk_widget_set_visible ((GtkWidget*) _tmp8_, FALSE);
#line 257 "../src/MainWindow.vala"
		_tmp9_ = self->back_button;
#line 257 "../src/MainWindow.vala"
		gtk_widget_set_no_show_all ((GtkWidget*) _tmp9_, TRUE);
#line 258 "../src/MainWindow.vala"
		_tmp10_ = self->titlegroup;
#line 258 "../src/MainWindow.vala"
		hdy_header_group_set_decorate_all (_tmp10_, FALSE);
#line 714 "MainWindow.c"
	}
}

static gboolean
notejot_main_window_real_delete_event (GtkWidget* base,
                                       GdkEventAny* event)
{
	NotejotMainWindow * self;
	gint x = 0;
	gint y = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint w = 0;
	gint h = 0;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	GSettings* _tmp4_;
	GSettings* _tmp5_;
	GSettings* _tmp6_;
	GSettings* _tmp7_;
	gboolean result = FALSE;
#line 262 "../src/MainWindow.vala"
	self = (NotejotMainWindow*) base;
#line 262 "../src/MainWindow.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 264 "../src/MainWindow.vala"
	gtk_window_get_position ((GtkWindow*) self, &_tmp0_, &_tmp1_);
#line 264 "../src/MainWindow.vala"
	x = _tmp0_;
#line 264 "../src/MainWindow.vala"
	y = _tmp1_;
#line 266 "../src/MainWindow.vala"
	gtk_window_get_size ((GtkWindow*) self, &_tmp2_, &_tmp3_);
#line 266 "../src/MainWindow.vala"
	w = _tmp2_;
#line 266 "../src/MainWindow.vala"
	h = _tmp3_;
#line 267 "../src/MainWindow.vala"
	_tmp4_ = notejot_application_gsettings;
#line 267 "../src/MainWindow.vala"
	g_settings_set_int (_tmp4_, "window-w", w);
#line 268 "../src/MainWindow.vala"
	_tmp5_ = notejot_application_gsettings;
#line 268 "../src/MainWindow.vala"
	g_settings_set_int (_tmp5_, "window-h", h);
#line 269 "../src/MainWindow.vala"
	_tmp6_ = notejot_application_gsettings;
#line 269 "../src/MainWindow.vala"
	g_settings_set_int (_tmp6_, "window-x", x);
#line 270 "../src/MainWindow.vala"
	_tmp7_ = notejot_application_gsettings;
#line 270 "../src/MainWindow.vala"
	g_settings_set_int (_tmp7_, "window-y", y);
#line 271 "../src/MainWindow.vala"
	result = FALSE;
#line 271 "../src/MainWindow.vala"
	return result;
#line 772 "MainWindow.c"
}

static void
notejot_main_window_on_create_new_data_free (gpointer _data)
{
	NotejotMainWindowOnCreateNewData* _data_;
	_data_ = _data;
#line 21 "../src/MainWindow.vala"
	_g_object_unref0 (_data_->self);
#line 21 "../src/MainWindow.vala"
	g_slice_free (NotejotMainWindowOnCreateNewData, _data_);
#line 784 "MainWindow.c"
}

void
notejot_main_window_on_create_new (NotejotMainWindow* self,
                                   GAsyncReadyCallback _callback_,
                                   gpointer _user_data_)
{
	NotejotMainWindowOnCreateNewData* _data_;
	NotejotMainWindow* _tmp0_;
#line 21 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 21 "../src/MainWindow.vala"
	_data_ = g_slice_new0 (NotejotMainWindowOnCreateNewData);
#line 21 "../src/MainWindow.vala"
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
#line 21 "../src/MainWindow.vala"
	g_task_set_task_data (_data_->_async_result, _data_, notejot_main_window_on_create_new_data_free);
#line 21 "../src/MainWindow.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 21 "../src/MainWindow.vala"
	_data_->self = _tmp0_;
#line 21 "../src/MainWindow.vala"
	notejot_main_window_on_create_new_co (_data_);
#line 808 "MainWindow.c"
}

void
notejot_main_window_on_create_new_finish (NotejotMainWindow* self,
                                          GAsyncResult* _res_)
{
	NotejotMainWindowOnCreateNewData* _data_;
#line 21 "../src/MainWindow.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 818 "MainWindow.c"
}

static gboolean
notejot_main_window_on_create_new_co (NotejotMainWindowOnCreateNewData* _data_)
{
#line 275 "../src/MainWindow.vala"
	switch (_data_->_state_) {
#line 275 "../src/MainWindow.vala"
		case 0:
#line 828 "MainWindow.c"
		goto _state_0;
		default:
#line 275 "../src/MainWindow.vala"
		g_assert_not_reached ();
#line 833 "MainWindow.c"
	}
	_state_0:
#line 276 "../src/MainWindow.vala"
	_data_->_tmp0_ = g_date_time_new_now_local ();
#line 276 "../src/MainWindow.vala"
	_data_->dt = _data_->_tmp0_;
#line 277 "../src/MainWindow.vala"
	_data_->_tmp1_ = _data_->dt;
#line 277 "../src/MainWindow.vala"
	_data_->_tmp2_ = g_date_time_format (_data_->_tmp1_, "%A, %d/%m %H∶%M");
#line 277 "../src/MainWindow.vala"
	_data_->_tmp3_ = _data_->_tmp2_;
#line 277 "../src/MainWindow.vala"
	_data_->_tmp4_ = g_strdup_printf ("%s", _data_->_tmp3_);
#line 277 "../src/MainWindow.vala"
	_data_->_tmp5_ = _data_->_tmp4_;
#line 277 "../src/MainWindow.vala"
	_data_->_tmp6_ = notejot_widgets_note_new (_data_->self, "", _data_->_tmp5_, "This is a text example.", "#f6f5f4");
#line 277 "../src/MainWindow.vala"
	g_object_ref_sink (_data_->_tmp6_);
#line 277 "../src/MainWindow.vala"
	_data_->_tmp7_ = _data_->_tmp6_;
#line 277 "../src/MainWindow.vala"
	_g_free0 (_data_->_tmp5_);
#line 277 "../src/MainWindow.vala"
	_g_free0 (_data_->_tmp3_);
#line 277 "../src/MainWindow.vala"
	_data_->sidebaritem = _data_->_tmp7_;
#line 278 "../src/MainWindow.vala"
	_data_->_tmp8_ = _data_->self->listview;
#line 278 "../src/MainWindow.vala"
	_data_->_tmp9_ = _data_->sidebaritem;
#line 278 "../src/MainWindow.vala"
	gtk_container_add ((GtkContainer*) _data_->_tmp8_, (GtkWidget*) _data_->_tmp9_);
#line 279 "../src/MainWindow.vala"
	_data_->_tmp10_ = _data_->self->listview;
#line 279 "../src/MainWindow.vala"
	notejot_views_list_view_set_is_modified (_data_->_tmp10_, TRUE);
#line 280 "../src/MainWindow.vala"
	_data_->_tmp11_ = _data_->self->listview;
#line 280 "../src/MainWindow.vala"
	_data_->_tmp12_ = _data_->sidebaritem;
#line 280 "../src/MainWindow.vala"
	gtk_list_box_select_row ((GtkListBox*) _data_->_tmp11_, (GtkListBoxRow*) _data_->_tmp12_);
#line 282 "../src/MainWindow.vala"
	_data_->_tmp13_ = _data_->self->listview;
#line 282 "../src/MainWindow.vala"
	_data_->_tmp14_ = gtk_list_box_get_selected_row ((GtkListBox*) _data_->_tmp13_);
#line 282 "../src/MainWindow.vala"
	if (_data_->_tmp14_ == NULL) {
#line 283 "../src/MainWindow.vala"
		_data_->_tmp15_ = _data_->self->main_stack;
#line 283 "../src/MainWindow.vala"
		_data_->_tmp16_ = _data_->self->empty_state;
#line 283 "../src/MainWindow.vala"
		gtk_stack_set_visible_child (_data_->_tmp15_, (GtkWidget*) _data_->_tmp16_);
#line 890 "MainWindow.c"
	}
#line 285 "../src/MainWindow.vala"
	_data_->_tmp17_ = _data_->self->titlebar_stack;
#line 285 "../src/MainWindow.vala"
	_data_->_tmp18_ = _data_->self->titlebar;
#line 285 "../src/MainWindow.vala"
	gtk_stack_set_visible_child (_data_->_tmp17_, (GtkWidget*) _data_->_tmp18_);
#line 286 "../src/MainWindow.vala"
	_data_->_tmp19_ = _data_->self->sgrid;
#line 286 "../src/MainWindow.vala"
	gtk_widget_set_no_show_all ((GtkWidget*) _data_->_tmp19_, FALSE);
#line 287 "../src/MainWindow.vala"
	_data_->_tmp20_ = _data_->self->sgrid;
#line 287 "../src/MainWindow.vala"
	gtk_widget_set_visible ((GtkWidget*) _data_->_tmp20_, TRUE);
#line 288 "../src/MainWindow.vala"
	_data_->_tmp21_ = _data_->self->sgrid;
#line 288 "../src/MainWindow.vala"
	gtk_widget_show_all ((GtkWidget*) _data_->_tmp21_);
#line 289 "../src/MainWindow.vala"
	_data_->_tmp22_ = _data_->self->settingmenu;
#line 289 "../src/MainWindow.vala"
	gtk_widget_set_visible ((GtkWidget*) _data_->_tmp22_, TRUE);
#line 275 "../src/MainWindow.vala"
	_g_object_unref0 (_data_->sidebaritem);
#line 275 "../src/MainWindow.vala"
	_g_date_time_unref0 (_data_->dt);
#line 275 "../src/MainWindow.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 275 "../src/MainWindow.vala"
	if (_data_->_state_ != 0) {
#line 275 "../src/MainWindow.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 275 "../src/MainWindow.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 926 "MainWindow.c"
		}
	}
#line 275 "../src/MainWindow.vala"
	g_object_unref (_data_->_async_result);
#line 275 "../src/MainWindow.vala"
	return FALSE;
#line 933 "MainWindow.c"
}

void
notejot_main_window_action_about (NotejotMainWindow* self)
{
#line 293 "../src/MainWindow.vala"
	static const char COPYRIGHT[] = "Copyright \xc2\xa9 2017-2021 Paulo \"Lains\" Galardi\n";
#line 295 "../src/MainWindow.vala"
	static const gchar* AUTHORS[2] = {"Paulo \"Lains\" Galardi", NULL};
#line 943 "MainWindow.c"
	gchar* program_name = NULL;
	gchar* _tmp0_;
#line 292 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 300 "../src/MainWindow.vala"
	_tmp0_ = g_strconcat (NAME_PREFIX, _ ("Notejot"), NULL);
#line 300 "../src/MainWindow.vala"
	program_name = _tmp0_;
#line 301 "../src/MainWindow.vala"
	gtk_show_about_dialog ((GtkWindow*) self, "program-name", program_name, "logo-icon-name", APP_ID, "version", VERSION, "comments", _ ("Jot your ideas."), "copyright", COPYRIGHT, "authors", AUTHORS, "artists", NULL, "license-type", GTK_LICENSE_GPL_3_0, "wrap-license", FALSE, "translator-credits", _ ("translator-credits"), NULL, NULL);
#line 292 "../src/MainWindow.vala"
	_g_free0 (program_name);
#line 956 "MainWindow.c"
}

void
notejot_main_window_action_all_notes (NotejotMainWindow* self)
{
	GtkStack* _tmp0_;
	GtkScrolledWindow* _tmp1_;
	GSettings* _tmp2_;
	NotejotWidgetsHeaderBarButton* _tmp3_;
	GtkStack* _tmp4_;
	GtkBox* _tmp5_;
	NotejotViewsListView* _tmp6_;
	GtkListBoxRow* _tmp7_;
	NotejotWidgetsSettingMenu* _tmp11_;
	HdyHeaderBar* _tmp12_;
#line 315 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 316 "../src/MainWindow.vala"
	_tmp0_ = self->sidebar_stack;
#line 316 "../src/MainWindow.vala"
	_tmp1_ = self->list_scroller;
#line 316 "../src/MainWindow.vala"
	gtk_stack_set_visible_child (_tmp0_, (GtkWidget*) _tmp1_);
#line 317 "../src/MainWindow.vala"
	_tmp2_ = notejot_application_gsettings;
#line 317 "../src/MainWindow.vala"
	g_settings_set_string (_tmp2_, "last-view", "list");
#line 318 "../src/MainWindow.vala"
	_tmp3_ = self->sidebar_title_button;
#line 318 "../src/MainWindow.vala"
	notejot_widgets_header_bar_button_set_title (_tmp3_, _ ("All Notes"));
#line 319 "../src/MainWindow.vala"
	_tmp4_ = self->main_stack;
#line 319 "../src/MainWindow.vala"
	_tmp5_ = self->empty_state;
#line 319 "../src/MainWindow.vala"
	gtk_stack_set_visible_child (_tmp4_, (GtkWidget*) _tmp5_);
#line 320 "../src/MainWindow.vala"
	_tmp6_ = self->listview;
#line 320 "../src/MainWindow.vala"
	_tmp7_ = gtk_list_box_get_selected_row ((GtkListBox*) _tmp6_);
#line 320 "../src/MainWindow.vala"
	if (_tmp7_ != NULL) {
#line 1000 "MainWindow.c"
		NotejotViewsListView* _tmp8_;
		NotejotViewsListView* _tmp9_;
		GtkListBoxRow* _tmp10_;
#line 321 "../src/MainWindow.vala"
		_tmp8_ = self->listview;
#line 321 "../src/MainWindow.vala"
		_tmp9_ = self->listview;
#line 321 "../src/MainWindow.vala"
		_tmp10_ = gtk_list_box_get_selected_row ((GtkListBox*) _tmp9_);
#line 321 "../src/MainWindow.vala"
		gtk_list_box_unselect_row ((GtkListBox*) _tmp8_, _tmp10_);
#line 1012 "MainWindow.c"
	}
#line 323 "../src/MainWindow.vala"
	_tmp11_ = self->settingmenu;
#line 323 "../src/MainWindow.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp11_, FALSE);
#line 324 "../src/MainWindow.vala"
	_tmp12_ = self->titlebar;
#line 324 "../src/MainWindow.vala"
	hdy_header_bar_set_title (_tmp12_, "");
#line 1022 "MainWindow.c"
}

void
notejot_main_window_action_trash (NotejotMainWindow* self)
{
	GtkStack* _tmp0_;
	GtkScrolledWindow* _tmp1_;
	GSettings* _tmp2_;
	NotejotWidgetsHeaderBarButton* _tmp3_;
	GtkStack* _tmp4_;
	GtkBox* _tmp5_;
	NotejotViewsTrashView* _tmp6_;
	GtkListBoxRow* _tmp7_;
	NotejotWidgetsSettingMenu* _tmp11_;
	HdyHeaderBar* _tmp12_;
#line 327 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 328 "../src/MainWindow.vala"
	_tmp0_ = self->sidebar_stack;
#line 328 "../src/MainWindow.vala"
	_tmp1_ = self->trash_scroller;
#line 328 "../src/MainWindow.vala"
	gtk_stack_set_visible_child (_tmp0_, (GtkWidget*) _tmp1_);
#line 329 "../src/MainWindow.vala"
	_tmp2_ = notejot_application_gsettings;
#line 329 "../src/MainWindow.vala"
	g_settings_set_string (_tmp2_, "last-view", "trash");
#line 330 "../src/MainWindow.vala"
	_tmp3_ = self->sidebar_title_button;
#line 330 "../src/MainWindow.vala"
	notejot_widgets_header_bar_button_set_title (_tmp3_, _ ("Trash"));
#line 331 "../src/MainWindow.vala"
	_tmp4_ = self->main_stack;
#line 331 "../src/MainWindow.vala"
	_tmp5_ = self->empty_state;
#line 331 "../src/MainWindow.vala"
	gtk_stack_set_visible_child (_tmp4_, (GtkWidget*) _tmp5_);
#line 332 "../src/MainWindow.vala"
	_tmp6_ = self->trashview;
#line 332 "../src/MainWindow.vala"
	_tmp7_ = gtk_list_box_get_selected_row ((GtkListBox*) _tmp6_);
#line 332 "../src/MainWindow.vala"
	if (_tmp7_ != NULL) {
#line 1066 "MainWindow.c"
		NotejotViewsTrashView* _tmp8_;
		NotejotViewsTrashView* _tmp9_;
		GtkListBoxRow* _tmp10_;
#line 333 "../src/MainWindow.vala"
		_tmp8_ = self->trashview;
#line 333 "../src/MainWindow.vala"
		_tmp9_ = self->trashview;
#line 333 "../src/MainWindow.vala"
		_tmp10_ = gtk_list_box_get_selected_row ((GtkListBox*) _tmp9_);
#line 333 "../src/MainWindow.vala"
		gtk_list_box_unselect_row ((GtkListBox*) _tmp8_, _tmp10_);
#line 1078 "MainWindow.c"
	}
#line 335 "../src/MainWindow.vala"
	_tmp11_ = self->settingmenu;
#line 335 "../src/MainWindow.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp11_, FALSE);
#line 336 "../src/MainWindow.vala"
	_tmp12_ = self->titlebar;
#line 336 "../src/MainWindow.vala"
	hdy_header_bar_set_title (_tmp12_, "");
#line 1088 "MainWindow.c"
}

void
notejot_main_window_action_trash_notes (NotejotMainWindow* self)
{
	NotejotWidgetsDialog* _tmp0_;
	NotejotWidgetsDialog* _tmp1_;
#line 339 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 340 "../src/MainWindow.vala"
	_tmp0_ = notejot_widgets_dialog_new (self, _ ("Empty the Trashed Notes?"), _ ("Emptying the trash means all the notes in it will be permanently lost " \
"with no recovery."), _ ("Cancel"), _ ("Empty Trash"));
#line 340 "../src/MainWindow.vala"
	g_object_ref_sink (_tmp0_);
#line 340 "../src/MainWindow.vala"
	_g_object_unref0 (self->dialog);
#line 340 "../src/MainWindow.vala"
	self->dialog = _tmp0_;
#line 345 "../src/MainWindow.vala"
	_tmp1_ = self->dialog;
#line 345 "../src/MainWindow.vala"
	if (_tmp1_ != NULL) {
#line 1110 "MainWindow.c"
		NotejotWidgetsDialog* _tmp2_;
#line 346 "../src/MainWindow.vala"
		_tmp2_ = self->dialog;
#line 346 "../src/MainWindow.vala"
		gtk_window_present ((GtkWindow*) _tmp2_);
#line 347 "../src/MainWindow.vala"
		return;
#line 1118 "MainWindow.c"
	} else {
		NotejotWidgetsDialog* _tmp3_;
#line 349 "../src/MainWindow.vala"
		_tmp3_ = self->dialog;
#line 349 "../src/MainWindow.vala"
		gtk_dialog_run ((GtkDialog*) _tmp3_);
#line 1125 "MainWindow.c"
	}
}

void
notejot_main_window_action_keys (NotejotMainWindow* self)
{
	GError* _inner_error0_ = NULL;
#line 353 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 1135 "MainWindow.c"
	{
		GtkBuilder* build = NULL;
		GtkBuilder* _tmp0_;
		GtkApplicationWindow* window = NULL;
		GObject* _tmp1_;
		GtkApplicationWindow* _tmp2_;
		GtkApplicationWindow* _tmp3_;
		GtkApplicationWindow* _tmp4_;
#line 355 "../src/MainWindow.vala"
		_tmp0_ = gtk_builder_new ();
#line 355 "../src/MainWindow.vala"
		build = _tmp0_;
#line 356 "../src/MainWindow.vala"
		gtk_builder_add_from_resource (build, "/io/github/lainsce/Notejot/shortcuts.ui", &_inner_error0_);
#line 356 "../src/MainWindow.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 356 "../src/MainWindow.vala"
			_g_object_unref0 (build);
#line 1154 "MainWindow.c"
			goto __catch0_g_error;
		}
#line 357 "../src/MainWindow.vala"
		_tmp1_ = gtk_builder_get_object (build, "shortcuts-notejot");
#line 357 "../src/MainWindow.vala"
		_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, gtk_application_window_get_type (), GtkApplicationWindow));
#line 357 "../src/MainWindow.vala"
		window = _tmp2_;
#line 358 "../src/MainWindow.vala"
		_tmp3_ = window;
#line 358 "../src/MainWindow.vala"
		gtk_window_set_transient_for ((GtkWindow*) _tmp3_, (GtkWindow*) self);
#line 359 "../src/MainWindow.vala"
		_tmp4_ = window;
#line 359 "../src/MainWindow.vala"
		gtk_widget_show_all ((GtkWidget*) _tmp4_);
#line 354 "../src/MainWindow.vala"
		_g_object_unref0 (window);
#line 354 "../src/MainWindow.vala"
		_g_object_unref0 (build);
#line 1175 "MainWindow.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp5_;
		const gchar* _tmp6_;
#line 354 "../src/MainWindow.vala"
		e = _inner_error0_;
#line 354 "../src/MainWindow.vala"
		_inner_error0_ = NULL;
#line 361 "../src/MainWindow.vala"
		_tmp5_ = e;
#line 361 "../src/MainWindow.vala"
		_tmp6_ = _tmp5_->message;
#line 361 "../src/MainWindow.vala"
		g_warning ("MainWindow.vala:361: Failed to open shortcuts window: %s\n", _tmp6_);
#line 354 "../src/MainWindow.vala"
		_g_error_free0 (e);
#line 1195 "MainWindow.c"
	}
	__finally0:
#line 354 "../src/MainWindow.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 354 "../src/MainWindow.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 354 "../src/MainWindow.vala"
		g_clear_error (&_inner_error0_);
#line 354 "../src/MainWindow.vala"
		return;
#line 1206 "MainWindow.c"
	}
}

void
notejot_main_window_action_dark_mode (NotejotMainWindow* self,
                                      GSimpleAction* action,
                                      GVariant* parameter)
{
	gboolean state = FALSE;
	GVariant* _tmp0_;
	GVariant* _tmp1_;
	gboolean _tmp2_;
	GVariant* _tmp3_;
	GVariant* _tmp4_;
	GSettings* _tmp5_;
#line 365 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 365 "../src/MainWindow.vala"
	g_return_if_fail (action != NULL);
#line 366 "../src/MainWindow.vala"
	_tmp0_ = g_action_get_state ((GAction*) action);
#line 366 "../src/MainWindow.vala"
	_tmp1_ = (GVariant*) _tmp0_;
#line 366 "../src/MainWindow.vala"
	_tmp2_ = g_variant_get_boolean (_tmp1_);
#line 366 "../src/MainWindow.vala"
	_g_variant_unref0 (_tmp1_);
#line 366 "../src/MainWindow.vala"
	state = _tmp2_;
#line 367 "../src/MainWindow.vala"
	_tmp3_ = g_variant_new_boolean (!state);
#line 367 "../src/MainWindow.vala"
	g_variant_ref_sink (_tmp3_);
#line 367 "../src/MainWindow.vala"
	_tmp4_ = _tmp3_;
#line 367 "../src/MainWindow.vala"
	g_simple_action_set_state (action, _tmp4_);
#line 367 "../src/MainWindow.vala"
	_g_variant_unref0 (_tmp4_);
#line 368 "../src/MainWindow.vala"
	_tmp5_ = notejot_application_gsettings;
#line 368 "../src/MainWindow.vala"
	g_settings_set_boolean (_tmp5_, "dark-mode", !state);
#line 1250 "MainWindow.c"
}

GSimpleActionGroup*
notejot_main_window_get_actions (NotejotMainWindow* self)
{
	GSimpleActionGroup* result;
	GSimpleActionGroup* _tmp0_;
#line 72 "../src/MainWindow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 72 "../src/MainWindow.vala"
	_tmp0_ = self->priv->_actions;
#line 72 "../src/MainWindow.vala"
	result = _tmp0_;
#line 72 "../src/MainWindow.vala"
	return result;
#line 1266 "MainWindow.c"
}

static void
notejot_main_window_set_actions (NotejotMainWindow* self,
                                 GSimpleActionGroup* value)
{
	GSimpleActionGroup* old_value;
#line 72 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 72 "../src/MainWindow.vala"
	old_value = notejot_main_window_get_actions (self);
#line 72 "../src/MainWindow.vala"
	if (old_value != value) {
#line 1280 "MainWindow.c"
		GSimpleActionGroup* _tmp0_;
#line 72 "../src/MainWindow.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 72 "../src/MainWindow.vala"
		_g_object_unref0 (self->priv->_actions);
#line 72 "../src/MainWindow.vala"
		self->priv->_actions = _tmp0_;
#line 72 "../src/MainWindow.vala"
		g_object_notify_by_pspec ((GObject *) self, notejot_main_window_properties[NOTEJOT_MAIN_WINDOW_ACTIONS_PROPERTY]);
#line 1290 "MainWindow.c"
	}
}

GtkApplication*
notejot_main_window_get_app (NotejotMainWindow* self)
{
	GtkApplication* result;
	GtkApplication* _tmp0_;
#line 91 "../src/MainWindow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 91 "../src/MainWindow.vala"
	_tmp0_ = self->priv->_app;
#line 91 "../src/MainWindow.vala"
	result = _tmp0_;
#line 91 "../src/MainWindow.vala"
	return result;
#line 1307 "MainWindow.c"
}

static void
notejot_main_window_set_app (NotejotMainWindow* self,
                             GtkApplication* value)
{
	GtkApplication* old_value;
#line 91 "../src/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 91 "../src/MainWindow.vala"
	old_value = notejot_main_window_get_app (self);
#line 91 "../src/MainWindow.vala"
	if (old_value != value) {
#line 1321 "MainWindow.c"
		GtkApplication* _tmp0_;
#line 91 "../src/MainWindow.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 91 "../src/MainWindow.vala"
		_g_object_unref0 (self->priv->_app);
#line 91 "../src/MainWindow.vala"
		self->priv->_app = _tmp0_;
#line 91 "../src/MainWindow.vala"
		g_object_notify_by_pspec ((GObject *) self, notejot_main_window_properties[NOTEJOT_MAIN_WINDOW_APP_PROPERTY]);
#line 1331 "MainWindow.c"
	}
}

static void
_vala_array_add1 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
#line 145 "../src/MainWindow.vala"
	if ((*length) == (*size)) {
#line 145 "../src/MainWindow.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 145 "../src/MainWindow.vala"
		*array = g_renew (gchar*, *array, (*size) + 1);
#line 1347 "MainWindow.c"
	}
#line 145 "../src/MainWindow.vala"
	(*array)[(*length)++] = value;
#line 145 "../src/MainWindow.vala"
	(*array)[*length] = NULL;
#line 1353 "MainWindow.c"
}

static void
_notejot_main_window___lambda49_ (NotejotMainWindow* self)
{
	HdyLeaflet* _tmp0_;
	GtkBox* _tmp1_;
#line 156 "../src/MainWindow.vala"
	_tmp0_ = self->leaflet;
#line 156 "../src/MainWindow.vala"
	_tmp1_ = self->sgrid;
#line 156 "../src/MainWindow.vala"
	hdy_leaflet_set_visible_child (_tmp0_, (GtkWidget*) _tmp1_);
#line 1367 "MainWindow.c"
}

static void
__notejot_main_window___lambda49__gtk_button_clicked (GtkButton* _sender,
                                                      gpointer self)
{
#line 155 "../src/MainWindow.vala"
	_notejot_main_window___lambda49_ ((NotejotMainWindow*) self);
#line 1376 "MainWindow.c"
}

static void
_notejot_main_window___lambda50_ (NotejotMainWindow* self)
{
#line 162 "../src/MainWindow.vala"
	notejot_main_window_on_create_new (self, NULL, NULL);
#line 1384 "MainWindow.c"
}

static void
__notejot_main_window___lambda50__gtk_button_clicked (GtkButton* _sender,
                                                      gpointer self)
{
#line 161 "../src/MainWindow.vala"
	_notejot_main_window___lambda50_ ((NotejotMainWindow*) self);
#line 1393 "MainWindow.c"
}

static void
_notejot_main_window___lambda51_ (NotejotMainWindow* self)
{
#line 200 "../src/MainWindow.vala"
	notejot_main_window_on_create_new (self, NULL, NULL);
#line 1401 "MainWindow.c"
}

static void
__notejot_main_window___lambda51__gtk_button_clicked (GtkButton* _sender,
                                                      gpointer self)
{
#line 199 "../src/MainWindow.vala"
	_notejot_main_window___lambda51_ ((NotejotMainWindow*) self);
#line 1410 "MainWindow.c"
}

static void
_notejot_main_window___lambda52_ (NotejotMainWindow* self)
{
#line 209 "../src/MainWindow.vala"
	notejot_main_window_update (self);
#line 1418 "MainWindow.c"
}

static void
__notejot_main_window___lambda52__g_object_notify (GObject* _sender,
                                                   GParamSpec* pspec,
                                                   gpointer self)
{
#line 208 "../src/MainWindow.vala"
	_notejot_main_window___lambda52_ ((NotejotMainWindow*) self);
#line 1428 "MainWindow.c"
}

static GObject *
notejot_main_window_constructor (GType type,
                                 guint n_construct_properties,
                                 GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	NotejotMainWindow * self;
	GtkCssProvider* provider = NULL;
	GtkCssProvider* _tmp0_;
	GtkCssProvider* _tmp1_;
	GdkScreen* _tmp2_;
	GtkCssProvider* _tmp3_;
	GtkStyleContext* style = NULL;
	GtkStyleContext* _tmp4_;
	GtkStyleContext* _tmp5_;
	GtkStyleContext* _tmp7_;
	gint x = 0;
	GSettings* _tmp8_;
	gint y = 0;
	GSettings* _tmp9_;
	gint w = 0;
	GSettings* _tmp10_;
	gint h = 0;
	GSettings* _tmp11_;
	gboolean _tmp12_ = FALSE;
	NotejotTaskManager* _tmp13_;
	GSimpleActionGroup* _tmp14_;
	GSimpleActionGroup* _tmp15_;
	GSimpleActionGroup* _tmp16_;
	GSimpleActionGroup* _tmp17_;
	NotejotWidgetsSettingMenu* _tmp38_;
	NotejotWidgetsSettingMenu* _tmp39_;
	GtkButton* _tmp40_;
	GtkButton* _tmp41_;
	GtkButton* _tmp42_;
	GtkButton* _tmp43_;
	GtkBuilder* builder = NULL;
	GtkBuilder* _tmp44_;
	GtkMenuButton* _tmp45_;
	GtkBuilder* _tmp46_;
	GObject* _tmp47_;
	NotejotViewsListView* _tmp48_;
	GtkScrolledWindow* _tmp49_;
	GtkScrolledWindow* _tmp50_;
	GtkScrolledWindow* _tmp51_;
	NotejotViewsListView* _tmp52_;
	GtkScrolledWindow* _tmp53_;
	NotejotViewsTrashView* _tmp54_;
	GtkScrolledWindow* _tmp55_;
	GtkScrolledWindow* _tmp56_;
	GtkScrolledWindow* _tmp57_;
	NotejotViewsTrashView* _tmp58_;
	GtkStack* _tmp59_;
	GtkScrolledWindow* _tmp60_;
	GtkStack* _tmp61_;
	GtkScrolledWindow* _tmp62_;
	GtkBuilder* tbuilder = NULL;
	GtkBuilder* _tmp63_;
	NotejotWidgetsHeaderBarButton* _tmp64_;
	NotejotWidgetsHeaderBarButton* _tmp65_;
	NotejotWidgetsHeaderBarButton* _tmp66_;
	NotejotWidgetsHeaderBarButton* _tmp67_;
	GtkMenuButton* _tmp68_;
	GtkBuilder* _tmp69_;
	GObject* _tmp70_;
	NotejotWidgetsHeaderBarButton* _tmp71_;
	NotejotWidgetsHeaderBarButton* _tmp72_;
	GtkStyleContext* _tmp73_;
	NotejotWidgetsHeaderBarButton* _tmp74_;
	GtkStyleContext* _tmp75_;
	HdyHeaderBar* _tmp76_;
	NotejotWidgetsHeaderBarButton* _tmp77_;
	GtkButton* _tmp78_;
	HdyLeaflet* _tmp79_;
	HdyLeaflet* _tmp80_;
	NotejotTaskManager* _tmp81_;
	NotejotViewsListView* _tmp82_;
	gboolean _tmp83_;
	gboolean _tmp84_;
#line 116 "../src/MainWindow.vala"
	parent_class = G_OBJECT_CLASS (notejot_main_window_parent_class);
#line 116 "../src/MainWindow.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 116 "../src/MainWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindow);
#line 117 "../src/MainWindow.vala"
	hdy_init ();
#line 119 "../src/MainWindow.vala"
	_tmp0_ = gtk_css_provider_new ();
#line 119 "../src/MainWindow.vala"
	provider = _tmp0_;
#line 120 "../src/MainWindow.vala"
	_tmp1_ = provider;
#line 120 "../src/MainWindow.vala"
	gtk_css_provider_load_from_resource (_tmp1_, "/io/github/lainsce/Notejot/app.css");
#line 121 "../src/MainWindow.vala"
	_tmp2_ = gdk_screen_get_default ();
#line 121 "../src/MainWindow.vala"
	_tmp3_ = provider;
#line 121 "../src/MainWindow.vala"
	gtk_style_context_add_provider_for_screen (_tmp2_, (GtkStyleProvider*) _tmp3_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
#line 123 "../src/MainWindow.vala"
	_tmp4_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 123 "../src/MainWindow.vala"
	_tmp5_ = _g_object_ref0 (_tmp4_);
#line 123 "../src/MainWindow.vala"
	style = _tmp5_;
#line 124 "../src/MainWindow.vala"
	if (g_strcmp0 (PROFILE, "Devel") == 0) {
#line 1541 "MainWindow.c"
		GtkStyleContext* _tmp6_;
#line 125 "../src/MainWindow.vala"
		_tmp6_ = style;
#line 125 "../src/MainWindow.vala"
		gtk_style_context_add_class (_tmp6_, "devel");
#line 1547 "MainWindow.c"
	}
#line 128 "../src/MainWindow.vala"
	_tmp7_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 128 "../src/MainWindow.vala"
	gtk_style_context_add_class (_tmp7_, "notejot-view");
#line 129 "../src/MainWindow.vala"
	_tmp8_ = notejot_application_gsettings;
#line 129 "../src/MainWindow.vala"
	x = g_settings_get_int (_tmp8_, "window-x");
#line 130 "../src/MainWindow.vala"
	_tmp9_ = notejot_application_gsettings;
#line 130 "../src/MainWindow.vala"
	y = g_settings_get_int (_tmp9_, "window-y");
#line 131 "../src/MainWindow.vala"
	_tmp10_ = notejot_application_gsettings;
#line 131 "../src/MainWindow.vala"
	w = g_settings_get_int (_tmp10_, "window-w");
#line 132 "../src/MainWindow.vala"
	_tmp11_ = notejot_application_gsettings;
#line 132 "../src/MainWindow.vala"
	h = g_settings_get_int (_tmp11_, "window-h");
#line 133 "../src/MainWindow.vala"
	if (x != -1) {
#line 133 "../src/MainWindow.vala"
		_tmp12_ = y != -1;
#line 1573 "MainWindow.c"
	} else {
#line 133 "../src/MainWindow.vala"
		_tmp12_ = FALSE;
#line 1577 "MainWindow.c"
	}
#line 133 "../src/MainWindow.vala"
	if (_tmp12_) {
#line 134 "../src/MainWindow.vala"
		gtk_window_move ((GtkWindow*) self, x, y);
#line 1583 "MainWindow.c"
	}
#line 136 "../src/MainWindow.vala"
	gtk_window_resize ((GtkWindow*) self, w, h);
#line 137 "../src/MainWindow.vala"
	_tmp13_ = notejot_task_manager_new (self);
#line 137 "../src/MainWindow.vala"
	_notejot_task_manager_unref0 (self->tm);
#line 137 "../src/MainWindow.vala"
	self->tm = _tmp13_;
#line 139 "../src/MainWindow.vala"
	_tmp14_ = g_simple_action_group_new ();
#line 139 "../src/MainWindow.vala"
	_tmp15_ = _tmp14_;
#line 139 "../src/MainWindow.vala"
	notejot_main_window_set_actions (self, _tmp15_);
#line 139 "../src/MainWindow.vala"
	_g_object_unref0 (_tmp15_);
#line 140 "../src/MainWindow.vala"
	_tmp16_ = self->priv->_actions;
#line 140 "../src/MainWindow.vala"
	g_action_map_add_action_entries ((GActionMap*) _tmp16_, NOTEJOT_MAIN_WINDOW_ACTION_ENTRIES, (gint) G_N_ELEMENTS (NOTEJOT_MAIN_WINDOW_ACTION_ENTRIES), self);
#line 141 "../src/MainWindow.vala"
	_tmp17_ = self->priv->_actions;
#line 141 "../src/MainWindow.vala"
	gtk_widget_insert_action_group ((GtkWidget*) self, "win", (GActionGroup*) _tmp17_);
#line 1609 "MainWindow.c"
	{
		GeeIterator* _action_it = NULL;
		GeeMultiMap* _tmp18_;
		GeeSet* _tmp19_;
		GeeSet* _tmp20_;
		GeeIterator* _tmp21_;
		GeeIterator* _tmp22_;
#line 143 "../src/MainWindow.vala"
		_tmp18_ = notejot_main_window_action_accelerators;
#line 143 "../src/MainWindow.vala"
		_tmp19_ = gee_multi_map_get_keys (_tmp18_);
#line 143 "../src/MainWindow.vala"
		_tmp20_ = _tmp19_;
#line 143 "../src/MainWindow.vala"
		_tmp21_ = gee_iterable_iterator ((GeeIterable*) _tmp20_);
#line 143 "../src/MainWindow.vala"
		_tmp22_ = _tmp21_;
#line 143 "../src/MainWindow.vala"
		_g_object_unref0 (_tmp20_);
#line 143 "../src/MainWindow.vala"
		_action_it = _tmp22_;
#line 143 "../src/MainWindow.vala"
		while (TRUE) {
#line 1633 "MainWindow.c"
			GeeIterator* _tmp23_;
			gchar* action = NULL;
			GeeIterator* _tmp24_;
			gpointer _tmp25_;
			gchar** accels_array = NULL;
			GeeMultiMap* _tmp26_;
			const gchar* _tmp27_;
			GeeCollection* _tmp28_;
			GeeCollection* _tmp29_;
			gint _tmp30_ = 0;
			gpointer* _tmp31_;
			gchar** _tmp32_;
			gint _tmp32__length1;
			gint accels_array_length1;
			gint _accels_array_size_;
			GtkApplication* _tmp33_;
			const gchar* _tmp34_;
			gchar* _tmp35_;
			gchar* _tmp36_;
			gchar** _tmp37_;
			gint _tmp37__length1;
#line 143 "../src/MainWindow.vala"
			_tmp23_ = _action_it;
#line 143 "../src/MainWindow.vala"
			if (!gee_iterator_next (_tmp23_)) {
#line 143 "../src/MainWindow.vala"
				break;
#line 1661 "MainWindow.c"
			}
#line 143 "../src/MainWindow.vala"
			_tmp24_ = _action_it;
#line 143 "../src/MainWindow.vala"
			_tmp25_ = gee_iterator_get (_tmp24_);
#line 143 "../src/MainWindow.vala"
			action = (gchar*) _tmp25_;
#line 144 "../src/MainWindow.vala"
			_tmp26_ = notejot_main_window_action_accelerators;
#line 144 "../src/MainWindow.vala"
			_tmp27_ = action;
#line 144 "../src/MainWindow.vala"
			_tmp28_ = gee_multi_map_get (_tmp26_, _tmp27_);
#line 144 "../src/MainWindow.vala"
			_tmp29_ = _tmp28_;
#line 144 "../src/MainWindow.vala"
			_tmp31_ = gee_collection_to_array (_tmp29_, &_tmp30_);
#line 144 "../src/MainWindow.vala"
			_tmp32_ = _tmp31_;
#line 144 "../src/MainWindow.vala"
			_tmp32__length1 = _tmp30_;
#line 144 "../src/MainWindow.vala"
			_g_object_unref0 (_tmp29_);
#line 144 "../src/MainWindow.vala"
			accels_array = _tmp32_;
#line 144 "../src/MainWindow.vala"
			accels_array_length1 = _tmp32__length1;
#line 144 "../src/MainWindow.vala"
			_accels_array_size_ = accels_array_length1;
#line 145 "../src/MainWindow.vala"
			_vala_array_add1 (&accels_array, &accels_array_length1, &_accels_array_size_, NULL);
#line 147 "../src/MainWindow.vala"
			_tmp33_ = self->priv->_app;
#line 147 "../src/MainWindow.vala"
			_tmp34_ = action;
#line 147 "../src/MainWindow.vala"
			_tmp35_ = g_strconcat (NOTEJOT_MAIN_WINDOW_ACTION_PREFIX, _tmp34_, NULL);
#line 147 "../src/MainWindow.vala"
			_tmp36_ = _tmp35_;
#line 147 "../src/MainWindow.vala"
			_tmp37_ = accels_array;
#line 147 "../src/MainWindow.vala"
			_tmp37__length1 = accels_array_length1;
#line 147 "../src/MainWindow.vala"
			gtk_application_set_accels_for_action (_tmp33_, _tmp36_, _tmp37_);
#line 147 "../src/MainWindow.vala"
			_g_free0 (_tmp36_);
#line 143 "../src/MainWindow.vala"
			accels_array = (_vala_array_free (accels_array, accels_array_length1, (GDestroyNotify) g_free), NULL);
#line 143 "../src/MainWindow.vala"
			_g_free0 (action);
#line 1713 "MainWindow.c"
		}
#line 143 "../src/MainWindow.vala"
		_g_object_unref0 (_action_it);
#line 1717 "MainWindow.c"
	}
#line 151 "../src/MainWindow.vala"
	_tmp38_ = notejot_widgets_setting_menu_new (self);
#line 151 "../src/MainWindow.vala"
	g_object_ref_sink (_tmp38_);
#line 151 "../src/MainWindow.vala"
	_g_object_unref0 (self->settingmenu);
#line 151 "../src/MainWindow.vala"
	self->settingmenu = _tmp38_;
#line 152 "../src/MainWindow.vala"
	_tmp39_ = self->settingmenu;
#line 152 "../src/MainWindow.vala"
	gtk_widget_set_visible ((GtkWidget*) _tmp39_, FALSE);
#line 154 "../src/MainWindow.vala"
	_tmp40_ = self->back_button;
#line 154 "../src/MainWindow.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp40_);
#line 155 "../src/MainWindow.vala"
	_tmp41_ = self->back_button;
#line 155 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp41_, "clicked", (GCallback) __notejot_main_window___lambda49__gtk_button_clicked, self, 0);
#line 158 "../src/MainWindow.vala"
	_tmp42_ = self->back_button;
#line 158 "../src/MainWindow.vala"
	gtk_widget_set_no_show_all ((GtkWidget*) _tmp42_, TRUE);
#line 161 "../src/MainWindow.vala"
	_tmp43_ = self->new_button;
#line 161 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp43_, "clicked", (GCallback) __notejot_main_window___lambda50__gtk_button_clicked, self, 0);
#line 165 "../src/MainWindow.vala"
	_tmp44_ = gtk_builder_new_from_resource ("/io/github/lainsce/Notejot/menu.ui");
#line 165 "../src/MainWindow.vala"
	builder = _tmp44_;
#line 166 "../src/MainWindow.vala"
	_tmp45_ = self->menu_button;
#line 166 "../src/MainWindow.vala"
	_tmp46_ = builder;
#line 166 "../src/MainWindow.vala"
	_tmp47_ = gtk_builder_get_object (_tmp46_, "menu");
#line 166 "../src/MainWindow.vala"
	gtk_menu_button_set_menu_model (_tmp45_, G_TYPE_CHECK_INSTANCE_CAST (_tmp47_, g_menu_model_get_type (), GMenuModel));
#line 169 "../src/MainWindow.vala"
	_tmp48_ = notejot_views_list_view_new (self);
#line 169 "../src/MainWindow.vala"
	g_object_ref_sink (_tmp48_);
#line 169 "../src/MainWindow.vala"
	_g_object_unref0 (self->listview);
#line 169 "../src/MainWindow.vala"
	self->listview = _tmp48_;
#line 171 "../src/MainWindow.vala"
	_tmp49_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 171 "../src/MainWindow.vala"
	g_object_ref_sink (_tmp49_);
#line 171 "../src/MainWindow.vala"
	_g_object_unref0 (self->list_scroller);
#line 171 "../src/MainWindow.vala"
	self->list_scroller = _tmp49_;
#line 172 "../src/MainWindow.vala"
	_tmp50_ = self->list_scroller;
#line 172 "../src/MainWindow.vala"
	gtk_widget_set_vexpand ((GtkWidget*) _tmp50_, TRUE);
#line 173 "../src/MainWindow.vala"
	_tmp51_ = self->list_scroller;
#line 173 "../src/MainWindow.vala"
	_tmp52_ = self->listview;
#line 173 "../src/MainWindow.vala"
	gtk_container_add ((GtkContainer*) _tmp51_, (GtkWidget*) _tmp52_);
#line 174 "../src/MainWindow.vala"
	_tmp53_ = self->list_scroller;
#line 174 "../src/MainWindow.vala"
	gtk_widget_set_size_request ((GtkWidget*) _tmp53_, 250, -1);
#line 177 "../src/MainWindow.vala"
	_tmp54_ = notejot_views_trash_view_new (self);
#line 177 "../src/MainWindow.vala"
	g_object_ref_sink (_tmp54_);
#line 177 "../src/MainWindow.vala"
	_g_object_unref0 (self->trashview);
#line 177 "../src/MainWindow.vala"
	self->trashview = _tmp54_;
#line 179 "../src/MainWindow.vala"
	_tmp55_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 179 "../src/MainWindow.vala"
	g_object_ref_sink (_tmp55_);
#line 179 "../src/MainWindow.vala"
	_g_object_unref0 (self->trash_scroller);
#line 179 "../src/MainWindow.vala"
	self->trash_scroller = _tmp55_;
#line 180 "../src/MainWindow.vala"
	_tmp56_ = self->trash_scroller;
#line 180 "../src/MainWindow.vala"
	gtk_widget_set_vexpand ((GtkWidget*) _tmp56_, TRUE);
#line 181 "../src/MainWindow.vala"
	_tmp57_ = self->trash_scroller;
#line 181 "../src/MainWindow.vala"
	_tmp58_ = self->trashview;
#line 181 "../src/MainWindow.vala"
	gtk_container_add ((GtkContainer*) _tmp57_, (GtkWidget*) _tmp58_);
#line 183 "../src/MainWindow.vala"
	_tmp59_ = self->sidebar_stack;
#line 183 "../src/MainWindow.vala"
	_tmp60_ = self->list_scroller;
#line 183 "../src/MainWindow.vala"
	gtk_stack_add_named (_tmp59_, (GtkWidget*) _tmp60_, "list");
#line 184 "../src/MainWindow.vala"
	_tmp61_ = self->sidebar_stack;
#line 184 "../src/MainWindow.vala"
	_tmp62_ = self->trash_scroller;
#line 184 "../src/MainWindow.vala"
	gtk_stack_add_named (_tmp61_, (GtkWidget*) _tmp62_, "trash");
#line 186 "../src/MainWindow.vala"
	_tmp63_ = gtk_builder_new_from_resource ("/io/github/lainsce/Notejot/title_menu.ui");
#line 186 "../src/MainWindow.vala"
	tbuilder = _tmp63_;
#line 188 "../src/MainWindow.vala"
	_tmp64_ = notejot_widgets_header_bar_button_new ();
#line 188 "../src/MainWindow.vala"
	g_object_ref_sink (_tmp64_);
#line 188 "../src/MainWindow.vala"
	_g_object_unref0 (self->sidebar_title_button);
#line 188 "../src/MainWindow.vala"
	self->sidebar_title_button = _tmp64_;
#line 189 "../src/MainWindow.vala"
	_tmp65_ = self->sidebar_title_button;
#line 189 "../src/MainWindow.vala"
	gtk_widget_set_has_tooltip ((GtkWidget*) _tmp65_, TRUE);
#line 190 "../src/MainWindow.vala"
	_tmp66_ = self->sidebar_title_button;
#line 190 "../src/MainWindow.vala"
	notejot_widgets_header_bar_button_set_title (_tmp66_, _ ("All Notes"));
#line 191 "../src/MainWindow.vala"
	_tmp67_ = self->sidebar_title_button;
#line 191 "../src/MainWindow.vala"
	_tmp68_ = _tmp67_->menu;
#line 191 "../src/MainWindow.vala"
	_tmp69_ = tbuilder;
#line 191 "../src/MainWindow.vala"
	_tmp70_ = gtk_builder_get_object (_tmp69_, "menu");
#line 191 "../src/MainWindow.vala"
	gtk_menu_button_set_menu_model (_tmp68_, G_TYPE_CHECK_INSTANCE_CAST (_tmp70_, g_menu_model_get_type (), GMenuModel));
#line 192 "../src/MainWindow.vala"
	_tmp71_ = self->sidebar_title_button;
#line 192 "../src/MainWindow.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp71_);
#line 193 "../src/MainWindow.vala"
	_tmp72_ = self->sidebar_title_button;
#line 193 "../src/MainWindow.vala"
	_tmp73_ = gtk_widget_get_style_context ((GtkWidget*) _tmp72_);
#line 193 "../src/MainWindow.vala"
	gtk_style_context_add_class (_tmp73_, "rename-button");
#line 194 "../src/MainWindow.vala"
	_tmp74_ = self->sidebar_title_button;
#line 194 "../src/MainWindow.vala"
	_tmp75_ = gtk_widget_get_style_context ((GtkWidget*) _tmp74_);
#line 194 "../src/MainWindow.vala"
	gtk_style_context_add_class (_tmp75_, "flat");
#line 196 "../src/MainWindow.vala"
	_tmp76_ = self->stitlebar;
#line 196 "../src/MainWindow.vala"
	_tmp77_ = self->sidebar_title_button;
#line 196 "../src/MainWindow.vala"
	hdy_header_bar_set_custom_title (_tmp76_, (GtkWidget*) _tmp77_);
#line 199 "../src/MainWindow.vala"
	_tmp78_ = self->welcome_new_button;
#line 199 "../src/MainWindow.vala"
	g_signal_connect_object (_tmp78_, "clicked", (GCallback) __notejot_main_window___lambda51__gtk_button_clicked, self, 0);
#line 204 "../src/MainWindow.vala"
	_tmp79_ = self->leaflet;
#line 204 "../src/MainWindow.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp79_);
#line 206 "../src/MainWindow.vala"
	notejot_main_window_update (self);
#line 208 "../src/MainWindow.vala"
	_tmp80_ = self->leaflet;
#line 208 "../src/MainWindow.vala"
	g_signal_connect_object ((GObject*) _tmp80_, "notify::folded", (GCallback) __notejot_main_window___lambda52__g_object_notify, self, 0);
#line 212 "../src/MainWindow.vala"
	_tmp81_ = self->tm;
#line 212 "../src/MainWindow.vala"
	notejot_task_manager_load_from_file (_tmp81_, NULL, NULL);
#line 214 "../src/MainWindow.vala"
	_tmp82_ = self->listview;
#line 214 "../src/MainWindow.vala"
	_tmp83_ = notejot_views_list_view_get_is_modified (_tmp82_);
#line 214 "../src/MainWindow.vala"
	_tmp84_ = _tmp83_;
#line 214 "../src/MainWindow.vala"
	if (_tmp84_ == FALSE) {
#line 1905 "MainWindow.c"
		GtkStack* _tmp85_;
		GtkBox* _tmp86_;
		GtkStack* _tmp87_;
		HdyHeaderBar* _tmp88_;
		GtkBox* _tmp89_;
		GtkBox* _tmp90_;
		GtkMenuButton* _tmp91_;
		NotejotWidgetsSettingMenu* _tmp92_;
#line 215 "../src/MainWindow.vala"
		_tmp85_ = self->main_stack;
#line 215 "../src/MainWindow.vala"
		_tmp86_ = self->welcome_view;
#line 215 "../src/MainWindow.vala"
		gtk_stack_set_visible_child (_tmp85_, (GtkWidget*) _tmp86_);
#line 216 "../src/MainWindow.vala"
		_tmp87_ = self->titlebar_stack;
#line 216 "../src/MainWindow.vala"
		_tmp88_ = self->welcome_titlebar;
#line 216 "../src/MainWindow.vala"
		gtk_stack_set_visible_child (_tmp87_, (GtkWidget*) _tmp88_);
#line 217 "../src/MainWindow.vala"
		_tmp89_ = self->sgrid;
#line 217 "../src/MainWindow.vala"
		gtk_widget_set_no_show_all ((GtkWidget*) _tmp89_, TRUE);
#line 218 "../src/MainWindow.vala"
		_tmp90_ = self->sgrid;
#line 218 "../src/MainWindow.vala"
		gtk_widget_set_visible ((GtkWidget*) _tmp90_, FALSE);
#line 219 "../src/MainWindow.vala"
		_tmp91_ = self->menu_button;
#line 219 "../src/MainWindow.vala"
		gtk_widget_set_visible ((GtkWidget*) _tmp91_, TRUE);
#line 220 "../src/MainWindow.vala"
		_tmp92_ = self->settingmenu;
#line 220 "../src/MainWindow.vala"
		gtk_widget_set_visible ((GtkWidget*) _tmp92_, FALSE);
#line 1942 "MainWindow.c"
	} else {
		GtkStack* _tmp93_;
		GtkBox* _tmp94_;
		GtkStack* _tmp95_;
		HdyHeaderBar* _tmp96_;
		GtkBox* _tmp97_;
		GtkBox* _tmp98_;
		GtkMenuButton* _tmp99_;
		NotejotWidgetsSettingMenu* _tmp100_;
#line 222 "../src/MainWindow.vala"
		_tmp93_ = self->main_stack;
#line 222 "../src/MainWindow.vala"
		_tmp94_ = self->empty_state;
#line 222 "../src/MainWindow.vala"
		gtk_stack_set_visible_child (_tmp93_, (GtkWidget*) _tmp94_);
#line 223 "../src/MainWindow.vala"
		_tmp95_ = self->titlebar_stack;
#line 223 "../src/MainWindow.vala"
		_tmp96_ = self->titlebar;
#line 223 "../src/MainWindow.vala"
		gtk_stack_set_visible_child (_tmp95_, (GtkWidget*) _tmp96_);
#line 224 "../src/MainWindow.vala"
		_tmp97_ = self->sgrid;
#line 224 "../src/MainWindow.vala"
		gtk_widget_set_no_show_all ((GtkWidget*) _tmp97_, FALSE);
#line 225 "../src/MainWindow.vala"
		_tmp98_ = self->sgrid;
#line 225 "../src/MainWindow.vala"
		gtk_widget_set_visible ((GtkWidget*) _tmp98_, TRUE);
#line 226 "../src/MainWindow.vala"
		_tmp99_ = self->menu_button;
#line 226 "../src/MainWindow.vala"
		gtk_widget_set_visible ((GtkWidget*) _tmp99_, TRUE);
#line 227 "../src/MainWindow.vala"
		_tmp100_ = self->settingmenu;
#line 227 "../src/MainWindow.vala"
		gtk_widget_set_visible ((GtkWidget*) _tmp100_, FALSE);
#line 1980 "MainWindow.c"
	}
#line 230 "../src/MainWindow.vala"
	gtk_widget_set_size_request ((GtkWidget*) self, 375, 280);
#line 231 "../src/MainWindow.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 116 "../src/MainWindow.vala"
	_g_object_unref0 (tbuilder);
#line 116 "../src/MainWindow.vala"
	_g_object_unref0 (builder);
#line 116 "../src/MainWindow.vala"
	_g_object_unref0 (style);
#line 116 "../src/MainWindow.vala"
	_g_object_unref0 (provider);
#line 116 "../src/MainWindow.vala"
	return obj;
#line 1996 "MainWindow.c"
}

static void
notejot_main_window_class_init (NotejotMainWindowClass * klass,
                                gpointer klass_data)
{
	GeeHashMultiMap* _tmp0_;
#line 21 "../src/MainWindow.vala"
	notejot_main_window_parent_class = g_type_class_peek_parent (klass);
#line 21 "../src/MainWindow.vala"
	g_type_class_adjust_private_offset (klass, &NotejotMainWindow_private_offset);
#line 21 "../src/MainWindow.vala"
	((GtkWidgetClass *) klass)->delete_event = (gboolean (*) (GtkWidget*, GdkEventAny*)) notejot_main_window_real_delete_event;
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_notejot_main_window_get_property;
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_notejot_main_window_set_property;
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (klass)->constructor = notejot_main_window_constructor;
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (klass)->finalize = notejot_main_window_finalize;
#line 21 "../src/MainWindow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), NOTEJOT_MAIN_WINDOW_ACTIONS_PROPERTY, notejot_main_window_properties[NOTEJOT_MAIN_WINDOW_ACTIONS_PROPERTY] = g_param_spec_object ("actions", "actions", "actions", g_simple_action_group_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 21 "../src/MainWindow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), NOTEJOT_MAIN_WINDOW_APP_PROPERTY, notejot_main_window_properties[NOTEJOT_MAIN_WINDOW_APP_PROPERTY] = g_param_spec_object ("app", "app", "app", gtk_application_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/io/github/lainsce/Notejot/main_window.ui");
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "new_button", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, new_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "back_button", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, back_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "welcome_new_button", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, welcome_new_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "menu_button", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, menu_button));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "grid", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, grid));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "sgrid", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, sgrid));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "welcome_view", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, welcome_view));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "empty_state", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, empty_state));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "leaflet", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, leaflet));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "main_stack", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, main_stack));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "sidebar_stack", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, sidebar_stack));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "titlebar_stack", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, titlebar_stack));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "titlebar", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, titlebar));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "stitlebar", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, stitlebar));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "welcome_titlebar", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, welcome_titlebar));
#line 21 "../src/MainWindow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "titlegroup", FALSE, G_STRUCT_OFFSET (NotejotMainWindow, titlegroup));
#line 80 "../src/MainWindow.vala"
	_tmp0_ = gee_hash_multi_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 80 "../src/MainWindow.vala"
	notejot_main_window_action_accelerators = (GeeMultiMap*) _tmp0_;
#line 2060 "MainWindow.c"
}

static void
notejot_main_window_instance_init (NotejotMainWindow * self,
                                   gpointer klass)
{
#line 21 "../src/MainWindow.vala"
	self->priv = notejot_main_window_get_instance_private (self);
#line 62 "../src/MainWindow.vala"
	self->dialog = NULL;
#line 70 "../src/MainWindow.vala"
	self->pinned = FALSE;
#line 21 "../src/MainWindow.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 2075 "MainWindow.c"
}

static void
notejot_main_window_finalize (GObject * obj)
{
	NotejotMainWindow * self;
#line 21 "../src/MainWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindow);
#line 25 "../src/MainWindow.vala"
	_g_object_unref0 (self->new_button);
#line 27 "../src/MainWindow.vala"
	_g_object_unref0 (self->back_button);
#line 29 "../src/MainWindow.vala"
	_g_object_unref0 (self->welcome_new_button);
#line 31 "../src/MainWindow.vala"
	_g_object_unref0 (self->menu_button);
#line 34 "../src/MainWindow.vala"
	_g_object_unref0 (self->grid);
#line 36 "../src/MainWindow.vala"
	_g_object_unref0 (self->sgrid);
#line 38 "../src/MainWindow.vala"
	_g_object_unref0 (self->welcome_view);
#line 40 "../src/MainWindow.vala"
	_g_object_unref0 (self->empty_state);
#line 42 "../src/MainWindow.vala"
	_g_object_unref0 (self->leaflet);
#line 45 "../src/MainWindow.vala"
	_g_object_unref0 (self->main_stack);
#line 47 "../src/MainWindow.vala"
	_g_object_unref0 (self->sidebar_stack);
#line 49 "../src/MainWindow.vala"
	_g_object_unref0 (self->titlebar_stack);
#line 51 "../src/MainWindow.vala"
	_g_object_unref0 (self->titlebar);
#line 53 "../src/MainWindow.vala"
	_g_object_unref0 (self->stitlebar);
#line 55 "../src/MainWindow.vala"
	_g_object_unref0 (self->welcome_titlebar);
#line 57 "../src/MainWindow.vala"
	_g_object_unref0 (self->titlegroup);
#line 60 "../src/MainWindow.vala"
	_g_object_unref0 (self->trash_scroller);
#line 61 "../src/MainWindow.vala"
	_g_object_unref0 (self->list_scroller);
#line 62 "../src/MainWindow.vala"
	_g_object_unref0 (self->dialog);
#line 63 "../src/MainWindow.vala"
	_g_object_unref0 (self->settingmenu);
#line 64 "../src/MainWindow.vala"
	_g_object_unref0 (self->sidebar_title_button);
#line 65 "../src/MainWindow.vala"
	_g_object_unref0 (self->listview);
#line 66 "../src/MainWindow.vala"
	_g_object_unref0 (self->trashview);
#line 67 "../src/MainWindow.vala"
	_notejot_task_manager_unref0 (self->tm);
#line 72 "../src/MainWindow.vala"
	_g_object_unref0 (self->priv->_actions);
#line 91 "../src/MainWindow.vala"
	_g_object_unref0 (self->priv->_app);
#line 21 "../src/MainWindow.vala"
	G_OBJECT_CLASS (notejot_main_window_parent_class)->finalize (obj);
#line 2138 "MainWindow.c"
}

static GType
notejot_main_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (NotejotMainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) notejot_main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (NotejotMainWindow), 0, (GInstanceInitFunc) notejot_main_window_instance_init, NULL };
	GType notejot_main_window_type_id;
	notejot_main_window_type_id = g_type_register_static (hdy_application_window_get_type (), "NotejotMainWindow", &g_define_type_info, 0);
	NotejotMainWindow_private_offset = g_type_add_instance_private (notejot_main_window_type_id, sizeof (NotejotMainWindowPrivate));
	return notejot_main_window_type_id;
}

GType
notejot_main_window_get_type (void)
{
	static volatile gsize notejot_main_window_type_id__volatile = 0;
	if (g_once_init_enter (&notejot_main_window_type_id__volatile)) {
		GType notejot_main_window_type_id;
		notejot_main_window_type_id = notejot_main_window_get_type_once ();
		g_once_init_leave (&notejot_main_window_type_id__volatile, notejot_main_window_type_id);
	}
	return notejot_main_window_type_id__volatile;
}

static void
_vala_notejot_main_window_get_property (GObject * object,
                                        guint property_id,
                                        GValue * value,
                                        GParamSpec * pspec)
{
	NotejotMainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindow);
#line 21 "../src/MainWindow.vala"
	switch (property_id) {
#line 21 "../src/MainWindow.vala"
		case NOTEJOT_MAIN_WINDOW_ACTIONS_PROPERTY:
#line 21 "../src/MainWindow.vala"
		g_value_set_object (value, notejot_main_window_get_actions (self));
#line 21 "../src/MainWindow.vala"
		break;
#line 21 "../src/MainWindow.vala"
		case NOTEJOT_MAIN_WINDOW_APP_PROPERTY:
#line 21 "../src/MainWindow.vala"
		g_value_set_object (value, notejot_main_window_get_app (self));
#line 21 "../src/MainWindow.vala"
		break;
#line 2185 "MainWindow.c"
		default:
#line 21 "../src/MainWindow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 21 "../src/MainWindow.vala"
		break;
#line 2191 "MainWindow.c"
	}
}

static void
_vala_notejot_main_window_set_property (GObject * object,
                                        guint property_id,
                                        const GValue * value,
                                        GParamSpec * pspec)
{
	NotejotMainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, NOTEJOT_TYPE_MAIN_WINDOW, NotejotMainWindow);
#line 21 "../src/MainWindow.vala"
	switch (property_id) {
#line 21 "../src/MainWindow.vala"
		case NOTEJOT_MAIN_WINDOW_ACTIONS_PROPERTY:
#line 21 "../src/MainWindow.vala"
		notejot_main_window_set_actions (self, g_value_get_object (value));
#line 21 "../src/MainWindow.vala"
		break;
#line 21 "../src/MainWindow.vala"
		case NOTEJOT_MAIN_WINDOW_APP_PROPERTY:
#line 21 "../src/MainWindow.vala"
		notejot_main_window_set_app (self, g_value_get_object (value));
#line 21 "../src/MainWindow.vala"
		break;
#line 2217 "MainWindow.c"
		default:
#line 21 "../src/MainWindow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 21 "../src/MainWindow.vala"
		break;
#line 2223 "MainWindow.c"
	}
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gint i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

